### ISSUE TITLE
Can't proceed beyond level 8 in bow & arrow 16bit windows game

### ISSUE THREAD

**Issue by arnabanimesh** [otya128/winevdm#1006]
Try the latest version first.
Go [here](https://ci.appveyor.com/project/otya128/winevdm) and click `Environment: THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1`-> `Artifacts 1`-> `zip` to download the latest version.

**Describe the bug**
Can't go beyond level 8 in bow & arrow game. It just stays there.
Screen recording:

https://user-images.githubusercontent.com/6032584/126048343-99372ecb-ea51-4878-8059-441cc8ad44ec.mp4

**Expected behavior**
Start level 9 after passing level 8

Check this video: https://youtu.be/dcv-XKmUPjo?t=449

**Screenshots**
Recording already provided

**Environment (please complete the following information):**
 - OS: Windows 10 21H1
 - Version 19043

**Additional context**

It is very helpful to provide a trace file if possible.
Please note that this file contains detailed information about the program.
**Procedure**
1. Run the command prompt.
2. Set the environment variable:
```cmd
set WINEDEBUG=+all,-snoop,-ldt,-fixup,-module,-global,-local,-disasm,-syslevel,-thunk
```
3.
```cmd
*old-executable-file* 2> trace.txt
```
4. Upload trace.txt here.
[trace.txt](https://github.com/otya128/winevdm/files/6835251/trace.txt)

**Comment by cracyc** [comment]
This is a program bug as it also occurs in ntvdm.  It happens when the screen is wider than about 1400 px.

**Comment by arnabanimesh** [comment]
I ran it in 640x480 compatibility mode, and it ran fine.
