### ISSUE TITLE
Next release when?

### ISSUE THREAD

**Issue by coldacid** [otya128/winevdm#1007]
Are there any plans for a proper release in the near future? It's been over two years since v0.7.0 was released.

**Comment by cracyc** [comment]
Usually you can just download the last artifact but seems except for my last PR, they've all been removed since they are older than one month.

**Comment by coldacid** [comment]
@cracyc the automatic removal is one of the reasons I won't use the "nightlies" for the Chocolatey packages, but not the only one. We need properly versioned releases.
