### ISSUE TITLE
DIB.DRV error on "たまごっちペイントCD-ROM スタンプdeおたすけっち"

### ISSUE THREAD

**Issue by KuromeSan** [otya128/winevdm#1019]
**Describe the bug**
When starting the game (in compatibility mode settings to set 256 bit color mode on OTVDM.exe) 

in japanese it shows an error saying like "DIB.DRV IS MISSING CURRUPT" 
despite it being on the CD right there,

ISO: https://archive.org/details/tamago-cd

error: ![image](https://user-images.githubusercontent.com/39113159/133953437-565053bc-2fd1-44fe-aca6-6239aa994013.png)

![image](https://user-images.githubusercontent.com/39113159/133953428-b3581b50-af9d-4a5e-ac10-28c410764ce5.png)

[trace.log](https://github.com/otya128/winevdm/files/7193426/trace.log)

**Comment by cracyc** [comment]
https://github.com/otya128/winevdm/pull/1020 fixes this and the program is usable but the ui flickers a lot for unknown reasons.

**Comment by KuromeSan** [comment]
yes. that seems to work
