### ISSUE TITLE
The Brush shapes toolbar is empty in PC Paintbrush

### ISSUE THREAD

**Issue by Anix-x** [otya128/winevdm#1031]
![image](https://user-images.githubusercontent.com/92230793/137409844-e1ce832c-9795-48e8-83d2-fd3c73993814.png)
http://toastytech.com/guis/PC%20Paintbrush%20for%20Windows%201.05%20(3.5).zip

**Comment by cracyc** [comment]
Works for me.
![Capture](https://user-images.githubusercontent.com/9255333/137592395-2811ff90-e98e-401b-a716-2906125b7627.PNG)

**Comment by cracyc** [comment]
Need a trace for this too.

**Comment by Anixx** [comment]
Yes, DisableAero key causes this problem.
