### ISSUE TITLE
Both new stable version 0.8.0 and unstable build 2157 completely breaks Hyper-V

### ISSUE THREAD

**Issue by ArguaBILL** [otya128/winevdm#1047]
I installed the new update as I would any other update and now Hyper-V support (which I require for adequate near-native performance of the various Win16 programs I use) is completely gone with the simple error message "Failed to load WinHvPlatform.dll"

**Comment by ArguaBILL** [comment]
ok i slept off my depression and found something really weird that works to my befit but is something you should really look into

by using the old set of dll files from [this source](https://github.com/otya128/winevdm/issues/699#issuecomment-646020250_) i can get Hyper-V to work on the new stable version 0.8.0

**Comment by otya128** [comment]
I seem to have accidentally released an old DLL.
Replaced with a new DLL.
https://github.com/otya128/WinHvPlatform32/releases/tag/1.0
