### ISSUE TITLE
Collins English Dictionary 16bit Error When Running Please Help !!!

### ISSUE THREAD

**Issue by alienfxfiend** [otya128/winevdm#1048]
[COLLINS.zip](https://github.com/otya128/winevdm/files/7532942/COLLINS.zip)
Please I need to use this Dictionary App urgently: "Collins English Dictionary", it errors out with a error message when running it with OTVDM under Windows 10. Even with the 0.8 update. Please fix this as it would help me in my field of work tremendously !!! Thank you ! ♥

**Comment by ArguaBILL** [comment]
i can get the application to work on windows 11 but pressing either the "Dictionary" or "Thesaurus" buttons causes a segfault

**Comment by alienfxfiend** [comment]
Thank you for the fix, I hope I can use this app ! ♥

**Comment by alienfxfiend** [comment]
Wowee ! I've waited two years for this ! Awesomesauce ! ♥

**Comment by ArguaBILL** [comment]
rad
