### ISSUE TITLE
WinPlay3 segfaults after showing blank error window

### ISSUE THREAD

**Issue by ArguaBILL** [otya128/winevdm#1054]
I personally use WinPlay3 v1.4 as a "benchmark" of sorts to make damn sure the hypervisor is working (the MAME 386 emulation core is too slow to playback a high quality MP3 file at full output quality, so if an MP3 can play without stuttering to Hell and back and subsequently crashing the program then the hypervisor is indeed working)

[Here is a link](https://www.rarewares.org/rrw/winplay3.php) to the software and the following is a valid serial number to activate it with.
- UserName=ISO FreeWare
             RegistrationCode=222221-025226-0002

![image](https://user-images.githubusercontent.com/93482203/142286140-dd9a1933-baaa-43ed-b48b-122a8b732ac0.png)

![image](https://user-images.githubusercontent.com/93482203/142286166-010edd39-c62a-41d0-b790-f52d442e5e47.png)

[trace.txt](https://github.com/otya128/winevdm/files/7558126/trace.txt) (The trace was performed with Hyper-V enabled, but I had to use the MAME 386 emulation core to get the error windows to display.)

**Comment by cracyc** [comment]
https://github.com/otya128/winevdm/pull/1053 fixes this for me but according to your trace that change is included in the build you are using.  Also the crash isn't in that trace, I need one that shows it.

**Comment by ArguaBILL** [comment]
[This trace](https://github.com/otya128/winevdm/files/7559104/trace.txt) was performed with the MAME 386 emulation core.

**Comment by otya128** [comment]
It's caused by DisableAero = 0, which is probably a regression of 55ba5968438f161fa297ea720e1df8d655df674c.

**Comment by ArguaBILL** [comment]
This fixed it!

![image](https://user-images.githubusercontent.com/93482203/142355987-432e8a87-c873-402c-b0cd-a4660c1be6de.png)
