### ISSUE TITLE
Feature request: Command line option to hide the console Window

### ISSUE THREAD

**Issue by JoachimHenze** [otya128/winevdm#1055]
This is a request for a adding the new feature to hide the second Window that displays the debug output of WineVDM.
Something like
-noconsole

Reason: We - The ReactOS team - are planning to offer out-of-box-integration of WineVDM.
See https://jira.reactos.org/browse/CORE-17852
Thank you.

**Comment by HBelusca** [comment]
Note what is written in the `install.inf` file:
```
;If you want to hide the console window, change otvdm.exe to otvdmw.exe
MappedExeName=otvdm.exe
```

**Comment by JoachimHenze** [comment]
Thank you. We missed that. I guess that will do the job. Thank you. Closed and resolved.
