### ISSUE TITLE
XyWrite segfaults upon opening no matter what settings are enabled or disabled

### ISSUE THREAD

**Issue by ArguaBILL** [otya128/winevdm#1056]
[trace.txt](https://github.com/otya128/winevdm/files/7574563/trace.txt)
[ XyWrite installation program](http://www.columbia.edu/~em36/xywin.html)

**Comment by cracyc** [comment]
https://github.com/otya128/winevdm/pull/1057 fixes the crash but the XPS printer driver still won't work because extdevicemode fails with that driver.  The Microsoft PDF driver seems to work fine though.

**Comment by ArguaBILL** [comment]
It still crashes in the exact same way for me

**Comment by emendelson** [comment]
Works perfectly here, using the installer that you linked to. The important thing for me is to set  `EnumFontLimitation=1` in otvdm.ini, which the installer offers to do for you.

**Comment by cracyc** [comment]
Well, seems my xps writer driver is broken which is why I had a similar appearing but apparently different problem.  I guess you should reopen this or make a new issue if you can't, my bad.

**Comment by ArguaBILL** [comment]
The application cannot even start; this screenshot was taken while running with Hyper-V acceleration enabled, but with the MAME 386 emulation core it produces a segmentation fault window instead.

And yes, I do have limited font parsing enabled

![image](https://user-images.githubusercontent.com/93482203/142748278-cac37c5f-82c1-4cdc-a8ee-2c4a48da0295.png)

**Comment by ArguaBILL** [comment]
ok with the latest round of patches xywrite works for me again 🤗
