### ISSUE TITLE
Star Wars Chess Runs But /w Glitches In-Game !!

### ISSUE THREAD

**Issue by alienfxfiend** [otya128/winevdm#1062]
[STARWARS.zip](https://github.com/otya128/winevdm/files/7602575/STARWARS.zip)

The in-game Sound Effects when moving doesn't play, also, the in-game Battle Cutscenes when capturing pieces doesn't play. This is a Win 3.11 game —tons of fun ! Please, if you could please fix this as it's imperative that I get this game to work on Windows 10. P.S:: Run it with XCHESS.exe. It was working (with aforementioned issues) before, now it doesn't even run, I don't know why (Oh I had to click Continue on the error for some reason.) BTW I've tested it on Win 3.11 running on DOSBox & it works perfectly.

**Comment by cracyc** [comment]
I tried what you posted and didn't have the animations but when I tried the original cdrom which has a bunch more files, they work fine.  You have to set ForceSingleProcessor=1 in otvdm.ini to avoid the errors at start.

**Comment by alienfxfiend** [comment]
Oh wow, I installed from the original CD-ROM version & the animations do work when I installed them to the Hard Disk, thank you so much for trouble you've taken !

**Comment by alienfxfiend** [comment]
Oh wow, I installed from the original CD-ROM version & the animations do work when I installed them to the Hard Disk, thank you so much for trouble you've taken ! ♥
