### ISSUE TITLE
Unable to running Resource Workshop 4.5

### ISSUE THREAD

**Issue by thefirefox12537** [otya128/winevdm#1065]
I already have the name of program: Resource Workshop 4.5 (a resource hacker from 16-bit Windows), while i running this program show Explorer force close window all of time and cannot be run. How can be run Resource Workshop in WineVDM/OTVDM?

**Comment by cracyc** [comment]
This is a bug in Windows ntvdm64.dll.  You have to run otvdm with brw.exe on the command line or otvdmw and select it in the open file dialog.

**Comment by thefirefox12537** [comment]
> This is a bug in Windows ntvdm64.dll. You have to run otvdm with workshop.exe on the command line or otvdmw and select it in the open file dialog.
So i open otvdm.exe and otvdmw.exe first not workshop.exe quickly?

**Comment by cracyc** [comment]
Yes
