### ISSUE TITLE
101 Dalmatians Print Studio. Can't Run, trows memory allocation error.

### ISSUE THREAD

**Issue by Skynet19972029** [otya128/winevdm#1068]
I've tried 0.8.1 and latest otvdm-master-2199

**Describe the bug**
Application can not allocate (X) ammount of memory

**Expected behavior**
The program to start.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/72090667/145680541-52392210-f6c4-485d-b28d-ab3fe735b48c.png)

**Environment (please complete the following information):**
 - OS: Windows 21H2
 - Version 19044.1387

**It is very helpful to provide a trace file if possible.**

[trace.txt](https://github.com/otya128/winevdm/files/7697221/trace.txt)

**Comment by cracyc** [comment]
The pr fixes it but it's still slow to start.  Whpx makes things quite faster.

**Comment by Skynet19972029** [comment]
Works perfect now.
Took like 10 seconds to start, not a big deal at all.

Thank you very much.
