### ISSUE TITLE
can not japanese civlization2

### ISSUE THREAD

**Issue by pikumo** [otya128/winevdm#1073]
version: 2201
Limit check at 0x03f07554 failed. Segment 2d67, limit 000000bf, offset 000000c0
=====dump all modules=====
Module Flags Name Flag
 2d0f   8309    ICONLIB     SINGLEDATA | FRAMEBUF | CONSOLE | GUI | LIBMODULE
 19f7   8021    WING        SINGLEDATA | BUILTIN | LIBMODULE
 1957   8309    ICONLIB     SINGLEDATA | FRAMEBUF | CONSOLE | GUI | LIBMODULE
 18ef   8021    WIN87EM     SINGLEDATA | BUILTIN | LIBMODULE
 18d7   8021    TOOLHELP    SINGLEDATA | BUILTIN | LIBMODULE
 18bf   8021    COMMDLG     SINGLEDATA | BUILTIN | LIBMODULE
 188f   8309    SMEDSNET    SINGLEDATA | FRAMEBUF | CONSOLE | GUI | LIBMODULE
 1877   8021    AVIFILE     SINGLEDATA | BUILTIN | LIBMODULE
 1857   8021    MSVIDEO     SINGLEDATA | BUILTIN | LIBMODULE
 11af   030a    CIV2        MULTIPLEDATA | FRAMEBUF | CONSOLE | GUI
 1197   8021    SOUND       SINGLEDATA | BUILTIN | LIBMODULE
 117f   8021    MMSYSTEM    SINGLEDATA | BUILTIN | LIBMODULE
 1167   8021    MOUSE       SINGLEDATA | BUILTIN | LIBMODULE
 114f   8021    KEYBOARD    SINGLEDATA | BUILTIN | LIBMODULE
 1137   8021    DISPLAY     SINGLEDATA | BUILTIN | LIBMODULE
 1117   8021    USER        SINGLEDATA | BUILTIN | LIBMODULE
 10f7   8021    GDI         SINGLEDATA | BUILTIN | LIBMODULE
 10cf   8021    TIMER       SINGLEDATA | BUILTIN | LIBMODULE
 10b7   8021    COMM        SINGLEDATA | BUILTIN | LIBMODULE
 109f   8021    SYSTEM      SINGLEDATA | BUILTIN | LIBMODULE
 1007   8021    KERNEL      SINGLEDATA | BUILTIN | LIBMODULE
=====dump all modules=====
00C00000-00C09000 otvdm.exe
77660000-77803000 ntdll.dll
76710000-76800000 KERNEL32.DLL
76B40000-76D54000 KERNELBASE.dll
75730000-75850000 ucrtbase.dll
74890000-748A4000 VCRUNTIME140.dll
63E00000-63E3A000 libwine.dll
63D80000-63DFB000 krnl386.exe16
76070000-760EA000 ADVAPI32.dll
765F0000-766AF000 msvcrt.dll
75620000-75695000 sechost.dll
651D0000-6524F000 DSOUND.dll
76F40000-76FFF000 RPCRT4.dll
76800000-76A81000 combase.dll
76450000-765F0000 USER32.dll
73D90000-73DD4000 powrprof.dll
755A0000-755B8000 win32u.dll
756E0000-75704000 GDI32.dll
76E60000-76F3C000 gdi32full.dll
75520000-7559B000 msvcp_win.dll
654A0000-654BD000 winmmbase.dll
75AA0000-76053000 SHELL32.dll
75A30000-75A75000 SHLWAPI.dll
73D00000-73D72000 WINSPOOL.DRV
729F0000-729FD000 UMPDC.dll
762E0000-76305000 IMM32.DLL
6FD20000-6FD49000 ntmarta.dll
63D70000-63D78000 system.drv16
63D60000-63D68000 comm.drv16
63D50000-63D58000 timer.drv16
63CC0000-63D47000 vm86.dll
75710000-75729000 imagehlp.dll
63C90000-63CB2000 gdi.exe16
63AE0000-63C8F000 user.exe16
73DE0000-73DE8000 VERSION.dll
73C20000-73C39000 MPR.dll
73A30000-73AA4000 UxTheme.dll
76370000-76443000 MSCTF.dll
76A90000-76B26000 OLEAUT32.dll
760F0000-761D3000 ole32.dll
73980000-7398F000 kernel.appcore.dll
755C0000-7561F000 bcryptPrimitives.dll
63AD0000-63AD9000 display.drv16
63AC0000-63AC8000 keyboard.drv16
63AB0000-63AB8000 mouse.drv16
72BB0000-731B8000 windows.storage.dll
72AB0000-72AD5000 Wldp.dll
6FC50000-6FD12000 PROPSYS.dll
63A90000-63AAA000 mmsystem.dll16
74400000-74428000 WINMM.dll
63A80000-63A89000 sound.drv16
63A70000-63A7D000 msvideo.dll16
63FB0000-63FD2000 MSVFW32.dll
673D0000-6745D000 COMCTL32.dll
63A60000-63A6A000 avifile.dll16
63F80000-63F9B000 AVIFIL32.dll
65260000-65279000 MSACM32.dll
63A40000-63A5B000 commdlg.dll16
77160000-7720F000 COMDLG32.dll
761E0000-76267000 shcore.dll
63A30000-63A39000 toolhelp.dll16
63A20000-63A28000 win87em.dll16
6E520000-6E6A8000 dbghelp.dll
63F20000-63F35000 mcicda.dll
65430000-6549B000 MMDevAPI.DLL
749C0000-749EB000 DEVOBJ.dll
756A0000-756DB000 cfgmgr32.dll
653F0000-6542A000 wdmaud.drv
653D0000-653D7000 ksuser.dll
653E0000-653E8000 AVRT.dll
65290000-653C6000 AUDIOSES.DLL
65280000-6528A000 msacm32.drv
65250000-65258000 midimap.dll
77090000-7710E000 clbcatq.dll
63A10000-63A18000 wing.dll16
67980000-67A14000 TextShaping.dll
697F0000-698A9000 textinputframework.dll
6AB40000-6ADBE000 CoreUIComponents.dll
6D1A0000-6D23B000 CoreMessaging.dll
75850000-758B3000 WS2_32.dll
6B7D0000-6B8AB000 wintypes.dll
20: vm86.dll!load_x87function+0x7141 - 0x63d0bb40 0x63d12c81 (null):0
19: ntdll.dll!LdrSetDllManifestProber+0xf8 - 0x776cccd0 0x776ccdc8 (null):0
18: ntdll.dll!RtlUnwind+0x1cb - 0x776c8e80 0x776c904b (null):0
17: ntdll.dll!KiUserExceptionDispatcher+0x26 - 0x776d4ec0 0x776d4ee6 (null):0

16: vm86.dll!disassemble_debug+0x48e - 0x63d135e0 0x63d13a6e (null):0
15: vm86.dll!disassemble_debug+0xd54 - 0x63d135e0 0x63d14334 (null):0
14: vm86.dll!wine_call_to_16_regs_vm86+0x53 - 0x63d132d0 0x63d13323 (null):0
13: krnl386.exe16!K32WOWCallback16Ex+0x454 - 0x63dcd590 0x63dcd9e4 (null):0
12: user.exe16!dialog_template16_to_template32+0x30d2 - 0x63aed5e0 0x63af06b2 (null):0
11: user.exe16!dialog_template16_to_template32+0x8e4b - 0x63aed5e0 0x63af642b (null):0
10: user.exe16!_wine_call_wndproc+0xa19 - 0x63af6440 0x63af6e59 (null):0
9: krnl386.exe16!RegFlushKey16+0x743 - 0x63db8de0 0x63db9523 (null):0
8: krnl386.exe16!vm_debug_get_entry_point+0x7fc - 0x63db9580 0x63db9d7c (null):0
7: vm86.dll!disassemble_debug+0x1195 - 0x63d135e0 0x63d14775 (null):0
6: vm86.dll!wine_call_to_16_regs_vm86+0x53 - 0x63d132d0 0x63d13323 (null):0
5: krnl386.exe16!K32WOWCallback16Ex+0x454 - 0x63dcd590 0x63dcd9e4 (null):0
4: krnl386.exe16!LoadModule16+0x7b8 - 0x63db3b30 0x63db42e8 (null):0
3: krnl386.exe16!RestoreThunkLock+0xe7b - 0x63dbf800 0x63dc067b (null):0
2: KERNEL32.DLL!BaseThreadInitThunk+0x19 - 0x7672fa10 0x7672fa29 (null):0
1: ntdll.dll!RtlGetAppContainerNamedObjectPath+0x11e - 0x776c7980 0x776c7a9e (null):0
0: ntdll.dll!RtlGetAppContainerNamedObjectPath+0xee - 0x776c7980 0x776c7a6e (null):0
cs:ip=13f7:1e44 bp=ac98                 args(1427,0020,2c7f,0000,2d67,1000,1802,0002,0026,0020)
cs:ip=1427:84ea bp=acc5(call 13f7:1e19) args(0000,2d67,0020,2c7f,2000,0000,0026,0026,0000,0000)
cs:ip=1427:7ba2 bp=ad01                 args(002a,0000,2c7f,0000,0026,0000,0000,0000,0000,0000)
cs:ip=1417:71bb bp=ad7d(call 1427:794d) args(0000,2c7f,002a,03bd,0026,e150,03ec,0000,0000,000c)
(callback)cs:ip=102f:0458 bp=adb7
cs:ip=1427:12af bp=add3(call 111f:5286) args(aebd,4c44,1407,0001,0000,0000,1c87,ce90,0000,3bfa)
cs:ip=1427:12c9 bp=add9                 args(0001,0000,0000,1c87,ce90,0000,3bfa,184f,0000,0000)
cs:ip=1407:4c44 bp=aebd(call 1427:12bf) args(490e,171f,3bfa,184f,000a,00c0,0004,1797,0001,0000)
cs:ip=13bf:1d15 bp=aee1(call 1407:47e6) args(afe0,2753,144f,1e14,13bf,aee6,0006,184f,0000,0000)
cs:ip=13bf:1fb9 bp=afcb                 args(184f,b593,45aa,1237,0060,71c6,0100,0001,ffff,2753)
cs:ip=1237:4316 bp=afd3(call 13bf:1e22) args(0060,71c6,0100,0001,ffff,2753,144f,4370,1237,afd8)
cs:ip=1237:45aa bp=b593                 args(184f,b5a3,13b1,123f,184f,b5af,003f,1247,727a,71c6)
cs:ip=1237:4961 bp=b59b                 args(184f,b5af,003f,1247,727a,71c6,184f,0001,00b6,120f)
cs:ip=123f:13b1 bp=b5a3(call 1237:4949) args(727a,71c6,184f,0001,00b6,120f,0001,0080,11f7,0000)
cs:ip=1247:003f bp=b5af(call 123f:13a2) args(0001,0080,11f7,0000,184e,0000,0458,102f,0000,0000)
cs:ip=120f:00b6 bp=0001(call 1247:0000) args(b5f0,0000,7656,b41e,b5c0,030a,0000,ae12,678a,184f)
cs:ip=120f:0000 bp=0000                 args(0000,b5f0,0000,7656,b41e,b5c0,030a,0000,ae12,678a)

address=76C6B502
access address=63D1BBAC
VM context
EAX:187F,ECX:0FA0,EDX:00C0,EBX:0202
ESP:AC8A,EBP:AC98,ESI:00C0,EDI:00E0
ES:2C7F,CS:13F7,SS:184F,DS:2D67,FS:0000,GS:0000
IP:1E44, address:63D2AC2D
EFLAGS:00003202

Interrupt 0D #GP (13F7:1E43) flags 3202 err 0000
lodsb

**Comment by cracyc** [comment]
I don't have the japanese version of civ2 so unless you can reproduce it in the english version I'll need a trace.

**Comment by pikumo** [comment]
english version 2.11
