### ISSUE TITLE
Possible to run Borlands Win16 Turbo Debugger (tdw.exe) with winedvm?

### ISSUE THREAD

**Issue by LegacyFreak** [otya128/winevdm#1082]
Hello,
is ist possible to get Borlands tdw to work under winevdm? I tried it in text mode. It starts in the text console and freezes immediately.
See screenshot an trace.
![TDW](https://user-images.githubusercontent.com/68747203/147745150-22d9338f-9e25-4a0c-aba0-cf2bde171e42.jpg)
[Trace_TDW.zip](https://github.com/otya128/winevdm/files/7792569/Trace_TDW.zip)

**Comment by cracyc** [comment]
TDW 5 added ntvdm support so try instead.  4.x only supported win31 and 95 and probably can't be reasonably made to work in nt.

**Comment by LegacyFreak** [comment]
Ok, thanks for the reply.
Best regards.
