### ISSUE TITLE
Permissions for upstream wine?

### ISSUE THREAD

**Issue by DarkShadow44** [otya128/winevdm#1084]
Hello, I noticed that the license of this project is GPL - this would make it impossible to merge back changes into Wine which is LGPL. Could we get a written statement from the top contributors on whether we could port back changes into Wine?

I understand if you don't want to deal with Wine as upstream yourself and opt for a fork, but it would be useful if Wine could benefit from your work as well. :smiley:

**Comment by cracyc** [comment]
The files that come from wine have LGPL headers in them and I, at least, am fine with that.  The only part that is GPL AFAICT is the bits from the msdos player (except the parts from MAME which are BSD licensed).

**Comment by DarkShadow44** [comment]
Thanks, since the repo itself is marked as GPL I had to ask. Still hoping for a reply from otya128 though, just to be sure.

**Comment by DarkShadow44** [comment]
@otya128 Would you mind giving a statement on this? :)

**Comment by otya128** [comment]
The header of the existing wine code has the LGPL-2.0 notation, which is ambiguous but at least I agree that my changes and newly added files will be licensed to LGPL-2.0.
