### ISSUE TITLE
whpxvm.dll causes programs to hang soon after launching

### ISSUE THREAD

**Issue by JamesDubbeleu** [otya128/winevdm#1085]
Try the latest version first.
Go [here](https://ci.appveyor.com/project/otya128/winevdm) and click `Environment: THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1`-> `Artiracts 1`-> `zip` to download the latest version.

**Describe the bug**
otvdm.exe hangs forever when run using whpxvm.dll on my computer. After some experimentation I figured out that WHvRunVirtualProcessor (whpxvm.c: 1074) is constantly returning with ExitReason WHvRunVpExitReasonMemoryAccess, which leads me to suspect that the hypervisor isn't able to access memory allocated by otvdm (to store executables, dlls, etc.).

**Expected behavior**
otvdm shouldn't hang forever when using the Windows Hypervisor Platform.

**Screenshots**
No applicable screenshots

**Environment (please complete the following information):**
 - OS: Windows 10 21H2
 - Version 19044.4145

**Additional context**
My computer uses an AMD A10-8700P processor - I don't know if this bug is AMD-specific or if Intel processors are affected too.
I used WinHvPlatform32 1.1 - https://github.com/otya128/WinHvPlatform32/releases/tag/1.1

It is very helpful to provide a trace file if possible.
Please note that this file contains detailed information about the program.
**Procedure**
1. Run the command prompt.
2. Set the environment variable:
```cmd
set WINEDEBUG=+all,-snoop,-ldt,-fixup,-module,-global,-local,-disasm,-syslevel,-thunk
```
3.
```cmd
*old-executable-file* 2> trace.txt
```
4. Upload trace.txt here.
NOTE: whpxvm.dll does not produce trace file output using the above procedure.

**Comment by cracyc** [comment]
Try a trace with +disasm to see if it's running any instructions at all.  I know it works with Intel cpus because mine is and it works for me.

**Comment by JamesDubbeleu** [comment]
[trace.txt](https://github.com/otya128/winevdm/files/7804158/trace.txt)
[trace2.txt](https://github.com/otya128/winevdm/files/7804159/trace2.txt)
[trace3.txt](https://github.com/otya128/winevdm/files/7804160/trace3.txt)

Interesting, it does seem to be running some instructions. I've tested several programs, and attached a few traces; they all seem to call in to a function at 1017h:4218h which ends up hanging after several instructions.

**Comment by cracyc** [comment]
It's likely to be calling InitTask.  WHvRunVpExitReasonMemoryAccess is expected because it exits the vm to call the win32 native function.  It should then return to the caller past the exiting call.  I can't say why it wouldn't.

**Comment by JamesDubbeleu** [comment]
I figured that it was probably calling InitTask. My guess is that the 16-bit<->32-bit relay function isn't being called. I will have another look at the code that handles WHvRunVpExitReasonMemoryAccess to see if I can figure out why that is,

**Comment by JamesDubbeleu** [comment]
After doing some further testing, I figured out that, on my computer, every time the hypervisor exits with WHvRunVpExitReasonMemoryAccess, exit.MemoryAccess.Gva is always set to 0, while exit.VpContext.Rip is set to a non-zero value. This appears to cause whpxvm.dll to skip over the relay function and hang forever.

**Comment by otya128** [comment]
Will this fix it?
```diff
         case WHvRunVpExitReasonMemoryAccess:
             if (exit.MemoryAccess.AccessInfo.GpaUnmapped)
             {
-                if (exit.MemoryAccess.Gva == exit.VpContext.Rip && exit.VpContext.Cs.Selector == seg_cs)
+                if (exit.VpContext.Cs.Selector == seg_cs)
                 {
                     BOOL is_reg = ptr == from16_reg;
                     if (is_reg || ptr == __wine_call_from_16)
```

**Comment by JamesDubbeleu** [comment]
After more testing on my end, that change worked for me in a private build. I'm not sure if removing that part of the check breaks anything else though

**Comment by JamesDubbeleu** [comment]
@otya128 Removing that check definitely fixes the issue for me, and doesn't seem to cause any regressions

**Comment by ArguaBILL** [comment]
> @otya128 That change definitely fixes the issue for me, and doesn't seem to cause any regressions

Can you provide this private build? I'd like to test it on my own Threadripper system.

**Comment by JamesDubbeleu** [comment]
[whpxvm.zip](https://github.com/otya128/winevdm/files/7824479/whpxvm.zip)
Compiled from the latest master with the change indicated in [this comment](https://github.com/otya128/winevdm/issues/1085#issuecomment-1004679428).

**Comment by otya128** [comment]
For reference, what values are in exit.MemoryAccess?

In my environment it is filled with the following values.
```
MemoryAccess.AccessInfo.AccessType = WHvMemoryAccessExecute
MemoryAccess.AccessInfo.GvaValid = 1
MemoryAccess.AccessInfo.GvaUnmapped = 1
MemoryAccess.Gva = MemoryAccess.Gpa = VpContext.Rip
```

**Comment by ArguaBILL** [comment]
> [whpxvm.zip](https://github.com/otya128/winevdm/files/7824479/whpxvm.zip) Compiled from the latest master with the change indicated in [this comment](https://github.com/otya128/winevdm/issues/1085#issuecomment-1004679428).

THIS GOT HARDWARE-ACCELERATED OTVDM WORKING ON MY THREADRIPPER
I AM NO LONGER CONCIDERING UPGRADING TO ALDER LAKE AT THIS TIME BECAUSE OF THIS
THANK YOU

**Comment by JamesDubbeleu** [comment]
I'm glad to hear it worked for you! Hopefully that might help #975 too. Still need to grab that reference environment though @otya128

**Comment by dcharlespyle** [comment]
I'd love to try it out, but I get this when I try to extract the file to the proper location:
![image](https://user-images.githubusercontent.com/5110398/148492502-4bd73266-24c1-4218-8e98-4c50754aa08a.png)

**Comment by JamesDubbeleu** [comment]
Probably a mistake on my end, but try the latest master build, that supersedes the zip file

**Comment by dcharlespyle** [comment]
How do I get to the location? Everywhere I have checked so far has been uncompiled code.

**Comment by JamesDubbeleu** [comment]
Go [here](https://ci.appveyor.com/project/otya128/winevdm) and click Environment: THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1-> Artiracts 1-> zip

**Comment by dcharlespyle** [comment]
Thank you. Unfortunately, no joy.  Now get this:
![image](https://user-images.githubusercontent.com/5110398/148493640-da2ce3b5-d74e-44ba-9a96-7cf1761652c0.png)

**Comment by JamesDubbeleu** [comment]
Make sure you're running [version 1.1 of WinHvPlatform32](https://github.com/otya128/WinHvPlatform32/releases/tag/1.1), I used to have that issue on older versions.

**Comment by dcharlespyle** [comment]
Well, no more error messages.  But otvdm runs for a few moments and then disappears from Task Manager.  Bummer.

**Comment by JamesDubbeleu** [comment]
@dcharlespyle I suggest you open a new issue for that.
@otya128, if it still matters, this is the values in exit.MemoryAccess I get:
```
MemoryAccess.AccessInfo.AccessType = WHvMemoryAccessExecute
MemoryAccess.AccessInfo.GvaValid = 0
MemoryAccess.AccessInfo.GpaUnmapped = 1
MemoryAccess.Gva = 0
MemoryAccess.Gpa != VpContext.Rip
MemeoryAccess.Gpa != 0
VpContext.Rip != 0
```

**Comment by dcharlespyle** [comment]
Don't know if the below traces will help, but here they are (first is with +disasm and second with -disasm):
[trace.txt](https://github.com/otya128/winevdm/files/7830870/trace.txt)
[trace2.txt](https://github.com/otya128/winevdm/files/7830876/trace2.txt)
