### ISSUE TITLE
Regression: XyWrite for Windows crashes

### ISSUE THREAD

**Issue by emendelson** [otya128/winevdm#1094]
Tested with current code as of 11 January 2022

XyWrite for Windows crashes when run. It ran perfectly in versions dating from mid-2021, though I'm not certain when the problem began. See screen shot below for error message.

![Capture](https://user-images.githubusercontent.com/5208505/149045613-b4805ecc-4823-49c7-befa-d954278d39ff.PNG)

**Environment (please complete the following information):**
 - OS: Windows 10.0.19044.1415

**Additional context**
You can download a XyWrite for Windows installer here:

http://www.columbia.edu/~em36/xywin.html

**And here is trace.txt:**
[trace.txt](https://github.com/otya128/winevdm/files/7850846/trace.txt)

**Comment by ArguaBILL** [comment]
it works fine here; could it be that Hyper-V accelerated OTVDM has become more stable than standard 386 MAME core OTVDM

**Comment by cracyc** [comment]
Try https://github.com/otya128/winevdm/pull/1098

**Comment by emendelson** [comment]
Fixed! Thank you. That was fast...
