### ISSUE TITLE
MS Encarta 96 Setup Error When Installing (Works /w Win3.11 Though)

### ISSUE THREAD

**Issue by alienfxfiend** [otya128/winevdm#1100]
https://winworldpc.com/product/encarta/1996 First link: "Microsoft Encarta 96 (ISO)" (514,900 KB .7z)
I was interested in getting this Encyclopedia (3x \ 95) to work /w OTVDM —I installed it via Windows 3.11 using DOSBox Games Launcher (frontend) & it works fine /w that (even mounted the ISO via the DOSBox Games Launcher built-in feature.) The Setup errors out, I mounted the ISO on Win10 using PowerISO Free. Also, It says missing DLLs which were in the SYSTEM folder of the ISO (when running the Win3.11 installed executable.)

**Comment by cracyc** [comment]
The dosbox windows/system dir and the winevdm windows/system dir are likely different so winevdm isn't going to to be able to find the installed dlls.  The installer on windows nt is going to try to install the 32bit version so you need to copy the dlls and the ini file to the winevdm system dir or the encarta installed path if you aren't running it from the cd.    Setting IAmNotNt=1 in your otvdm.ini and running the installer may also work but that might think it's on windows 95 instead.

**Comment by alienfxfiend** [comment]
Oh I see, thanks !

**Comment by alienfxfiend** [comment]
I don't think it's possible to get this to work #1 When I first ran Setup it said some .LST file could not be read #2 I used IsNotNT & then the Setup stalled indefinitely saying Searching For Components #3 I tried running the Win3.11 + DOSBox Games Launcher preinstalled executable & it flat out said it cannot Run Please Restart Windows. Also there are many dependencies [multimedia] apps required so I give up.
