### ISSUE TITLE
Messenger of the Gods double mouse cursor; window incorrectly captured

### ISSUE THREAD

**Issue by emxd** [otya128/winevdm#1104]
**Describe the bug**
Messenger of the Gods is an old czech point and click adventure game. The game starts and technically *works*, but instead of running at 640x480 full screen it runs in a window in the middle of the screen with wrong dimensions (not 640x480) and also it has 2 mouse cursors. One mouse cursor is the classic Windows mouse cursor that is captured in a 640x480 box in the upper left corner of the screen. The other mouse cursor is the game cursor that works inside the game window. The game mouse cursor copies the movements of the Windows cursor. Some graphical deformations are also created because of the wrong window size. The game was originally a DOS game that was wrapped as a Windows game at the last minute.

**Expected behavior**
To be able to run the game full screen at 640x480 resolution. This would hopefully also fix the double mouse cursor problem.

**Video**
https://icedrive.net/s/TayQx8GiWY4GR69NRawhBzu92TNk

**Environment (please complete the following information):**
 - otvdm 2252 
 - Win10 20H2

**Additional context**
link to the game -> https://www.old-games.ru/game/download/get.php?fileid=13824&modal=1
Tried running the game with the 640x480 compatibility set, but it made no difference. The game was still captured in a window with the 2 mouse cursors.

**Trace**
set WINEDEBUG=+all,-snoop,-ldt,-fixup,-module,-global,-local,-disasm,-syslevel,-thunk
https://icedrive.net/s/uRaWuGG67A2Xx5SAwAWh8kWAxwwA

**Comment by cracyc** [comment]
This program uses dispdib so it's difficult enough to make it work at all, note that it doesn't work in ntvdm.  https://github.com/otya128/winevdm/pull/1105 is really the best that I can do right now.  The program grabs the cursor into the upper left, if you use the windows key to break it then you can maximize the window and the windows pointer is hidden.  The main issue then is you can't point to the very top.

**Comment by emxd** [comment]
Thank you, this is still very useful. I used autohotkey to turn it into a borderless window and now it's basically identical to full screen 640x480.

https://i.ibb.co/GWpWBnJ/1.png

The only exception being the white aspect ratio bars on the side instead of the usual black bars. Come to think of it, would it be possible to make the background surface not white, but black? To have the usual black bars. I could technically change the desktop resolution to 4:3 and get black bars that way, but this would be nicer.

**Comment by cracyc** [comment]
It's possible to make it borderless by default but that will make it harder to use other programs that use dispdib like Out of this world.  Another problematic one is Burncycle which takes over the pointer when it has focus which makes it impossible to move or resize the window, wonder if autohotkey would help with that.

**Comment by emxd** [comment]
@cracyc 
One more thing. If I go to the main menu -> settings -> back the game crashes with a 005 error. I checked and 005 is a file access error. I did try some basic things like removing read only flags with 

attrib -r \*.\* /s /d 

and moving the game directory to a place with an 8.3 filename but none of that helped. If you've got the time could you take a look? Thank you

here's a video https://icedrive.net/s/bhBiWQ496RwPCVPz1f3WXiBAjvZN
