### ISSUE TITLE
P3 Primavera Scheduling - Interrupt 0D on load

### ISSUE THREAD

**Issue by danielgatley** [otya128/winevdm#1119]
**Describe the bug**
Attempting to execute P3.EXE from Primavera Scheduling application (main application exe), gives Interrupt 0D error before loading any visible interface.

**Expected behavior**
Application loads before splash screen would normally be displayed.  Application is working as expected on Windows 10 x32.

**Screenshots**
![image](https://user-images.githubusercontent.com/140229/153774878-f4002837-9c9e-4d8f-b5db-2f26a7df8f53.png)

**Environment (please complete the following information):**
Windows 10 21H2 (19044.1526)
version: 2261

**Additional context**
[p3.log](https://github.com/otya128/winevdm/files/8056651/p3.log)

**Comment by cracyc** [comment]
The log doesn't contain enough info to solve the problem (and what is in there is odd).  Is there a demo of it somewhere?

**Comment by danielgatley** [comment]
Thank you for the quick response.

Hopefully the lack of log information and it'd oddness aren't anything I've missed/done wrong.  For slightly more context the installer wouldn't run, it complained about a missing dependency (Btrieve).  As I just wanted to establish the application could run I performed a monitored install on a Win 10 x32 install (which with with NTVDM seemed to run fine) and copied out the created and modified files.  I then reset this machine and copied the files back to confirm it would work with just a file copy, again this worked with NTVDM.  Attempting to use winevdm to run the same application (P3.exe) resulted in the reported error.

I have noticed when running under NTVDM that while the P3.exe is 16bit it seems to be executing other applications which are 32bit (in particular BCHECK.EXE which seems related to Btrieve and as such could explain why installer was failing to detect it).

I have linked a copy of the application files exactly as I have been trying to execute them (paths in INI files dictate the P3 folder should be in the root of C:).  To avoid confusion i've also included a "JustAppFiles" folder which contains just the files created/modified by the installer).

https://we.tl/t-jgB7BodMLW (Pass: swiftfrog26)

Hopefully this is enough.

**Comment by cracyc** [comment]
>Hopefully the lack of log information and it'd oddness aren't anything I've missed/done wrong

Not your fault.  The log is fine just the problem is one that can't really be logged and the oddness is something the program is doing.

**Comment by cracyc** [comment]
https://github.com/otya128/winevdm/pull/1121 fixes this problem.  I couldn't get any further because it requires 32bit btrieve.

> (in particular BCHECK.EXE which seems related to Btrieve and as such could explain why installer was failing to detect it).
The program won't be able to find the real windows directory because winevdm by default redirects it so installers don't require privilege elevation.
