### ISSUE TITLE
"The Thinking Man's Thesaurus" Error When Launching Works When Ignoring (Recently Cropped-Up)

### ISSUE THREAD

**Issue by alienfxfiend** [otya128/winevdm#1124]
[ththes13.zip](https://github.com/otya128/winevdm/files/8076118/ththes13.zip)

I get an 'Interrupt' error recently when opening "The Thinking Man's Thesaurus" —it was working perfectly before yesterday when I got some Cumulative Windows 10 update & a .NET 5 update (maybe that's the 'cause ?) […] I don't understand —can it be fixed please ?! When I click continue it loads normally (I noticed the cipboard gets auto-pasted maybe it corrupts the app ?), also it only occurs /w the taskbar-pinned shortcut (/w a custom icon) not when I run THES.EXE via a Launcher app ("Everything" by voidtools), I'm thinking maybe it's a prob /w my .ini file ? I opened it & Use Single Processor was disabled, I had it use only one Processor before to avoid errors. It was working w/o a hitch a few days ago, I had enabled HIPS (Host Intrusion Protection System) on Comodo Internet Security Premium but now I have it disabled, so it couldn't be that —I get the latest version from AppVeyor.

P.S: It's a tiny app /w no setup runs directly /w THES.EXE.

**Comment by alienfxfiend** [comment]
Nevermind "ForceSingleProcessor=1" somehow got disabled again, I will test again & see if it's resolved. Sorry for taking your time.

**Comment by alienfxfiend** [comment]
The new OTVDM Heap corruption in OLE certainly improves loadtimes as that of Win 3.11 under DOSBox but sometimes I get an interrupt error (the app automatically enters clipboard text on loading) & sometimes it causes problems —please try to fix the issue, I get a block symbol in the apps input field, & sometimes this causes an error as of the latest commit (OLE Heap corruption) ! Collins Dictionary works perfectly though, only not this Thinking Man's Thesaurus !

**Comment by cracyc** [comment]
Need more detail.  What is on the clipboard when it crashes?  Did this start after the recent commits?  Also a trace could help.

**Comment by alienfxfiend** [comment]
Bingo ! I found out what clipboard text was crashing the app (the aforementioned Interrupt crash.) It was an EmDash "—" (without quotes) !

**Comment by cracyc** [comment]
Not fixable because it's a bug in the program as emdash is ascii 0x97 and it sign extends it to 0xff97 which causes a pointer underflow.  Also reproducible in ntvdm.  You can try this spell.dll replacement which might fix it
[SPELL.zip](https://github.com/otya128/winevdm/files/8209726/SPELL.zip)
.

**Comment by alienfxfiend** [comment]
Thank you for clarifying —I will check it out pronto !
