### ISSUE TITLE
たまごっちペイントCD-ROM スタンプdeおたすけっち Crashes now ..

### ISSUE THREAD

**Issue by KuromeSan** [otya128/winevdm#1132]
when run:
![image](https://user-images.githubusercontent.com/39113159/157570453-9e3a2fa4-b52c-40b8-8155-e4b0d1e2ef88.png)
version 
![image](https://user-images.githubusercontent.com/39113159/157570545-94f65b6f-937e-47cd-a7b3-89fa2675aeed.png)

game: https://archive.org/details/tamago-cd

**Comment by cracyc** [comment]
Can't reproduce this.  The address it's crashing at is very strange.  A trace might help but it's possible it won't show anything.

**Comment by KuromeSan** [comment]
how to get a trace?

**Comment by KuromeSan** [comment]
nvm figured it out dumped app incorrectly. bin/cue dump has currupt TAMAGO.EXE.
