### ISSUE TITLE
Ai Shimai for windows 3.1 won't start properly

### ISSUE THREAD

**Issue by mochicchi** [otya128/winevdm#1137]
Hello, when I try to start this game, I get a popup error after the intro plays (see the screenshot). When I click "retry" the same message appears and when i click "ignore" the game shows a blank screen. It's supposed to go to the main menu after the intro.
![aisimai error](https://user-images.githubusercontent.com/90536620/159619968-9be44a08-b71b-4785-8aa4-a3d3df244807.png)
The error message says:
"Failed to read FLAG5 file.
It is recommended that you reload the game to resolve this error.
If this message appears again after reloading, the necessary file might be corrupted.
In that case, please reinstall the game."

Enivironment: Windows 10 x64 19042
Version: otvdm version 2281

[trace.zip](https://github.com/otya128/winevdm/files/8329526/trace.zip)

**Comment by cracyc** [comment]
```
3b64:Call KERNEL.88: LSTRCPY(12173738,1217244c ".") ret=120f:55e3 ds=1217
3b64:Ret  KERNEL.88: LSTRCPY() retval=12173738 ret=120f:55e3 ds=1217
3b64:Call KERNEL.89: LSTRCAT(1217:3738 ".",1217081c "FLAG5") ret=120f:55f9 ds=1217
3b64:Ret  KERNEL.89: LSTRCAT() retval=12173738 ret=120f:55f9 ds=1217
3b64:Call KERNEL.85: _LOPEN(12173738 ".FLAG5",0000) ret=120f:5606 ds=1217
3b64:Ret  KERNEL.85: _LOPEN() retval=ffffffff ret=120f:5606 ds=1217
3b64:Call KERNEL.84: _LLSEEK(ffff,00000020,0000) ret=120f:5613 ds=1217
3b64:Ret  KERNEL.84: _LLSEEK() retval=ffffffff ret=120f:5613 ds=1217
3b64:Call KERNEL.82: _LREAD(ffff,772fe020,0236) ret=120f:5625 ds=1217
30c8:3b64:trace:file:WIN16_hread 65535 772fe020 566
3b64:Ret  KERNEL.82: _LREAD() retval=ffffffff ret=120f:5625 ds=1217
```

You need to look in silwin.ini and fix any relative paths.

**Comment by mochicchi** [comment]
![silwin](https://user-images.githubusercontent.com/90536620/159807832-0f84c47e-0c0d-4bdb-9779-a28c7162a6c0.png)
This is what's inside silwin.ini. What should I change?

**Comment by mochicchi** [comment]
![silwin](https://user-images.githubusercontent.com/90536620/159808357-30042a7f-27a7-47ac-acf6-1f608bfdc227.png)
This is all I could find inside silwin.ini. What should I change?

**Comment by cracyc** [comment]
```
3b64:Call KERNEL.128: GETPRIVATEPROFILESTRING(12170078 "Config",1217007f "SaveDirectory",1217008d ".",1217:244c,0104,12173a00 "./SILWIN.INI") ret=120f:0292 ds=1217
30c8:3b64:trace:file:GetPrivateProfileString16 ./SILWIN.INI Config SaveDirectory
30c8:3b64:trace:file:GetPrivateProfileString16 ("Config", "SaveDirectory", ".", 02B90444, 260, "C:\\OTVDM-~1\\OTVDM-~1\\WINDOWS\\./SILWIN.INI")
3b64:Ret  KERNEL.128: GETPRIVATEPROFILESTRING() retval=00000001 ret=120f:0292 ds=1217
```
SaveDirectory sets the default to "." which is the same as the bad one used above.  If that doesn't fix it then I can't tell what it's doing without working on it directly.

**Comment by mochicchi** [comment]
It didn't seem to work :( Here's the game--
https://ia801409.us.archive.org/view_archive.php?archive=/9/items/eroge94-02/%5B951117%5D%5BSilkys%5D%20%E6%84%9B%E5%A7%89%E5%A6%B9%20%EF%BD%9E%E4%BA%8C%E4%BA%BA%E3%81%AE%E6%9E%9C%E5%AE%9F%EF%BD%9E%20for%20Windows31.rar

**Comment by cracyc** [comment]
Fixed in https://github.com/otya128/winevdm/pull/1138 which also fixes the graphical output.  My testing showed it didn't work in xp/ntvdm or win98 in qemu either.

**Comment by mochicchi** [comment]
It works now! Thank you so much!
