### ISSUE TITLE
Win ISO V3.0 not working.

### ISSUE THREAD

**Issue by xmjacky** [otya128/winevdm#1144]
**Describe the bug**
When you start the application, you will be prompted with an error "Application (.TST) file not found...". As shown in the screenshot.

**Expected behavior**
The software can be started normally.

**Screenshots**
![20220419225114](https://user-images.githubusercontent.com/104000003/164032797-509d15c3-2de7-4e41-ab6c-60199c0a3522.png)

**Environment (please complete the following information):**
 - OS: Windows 10 21H1   64 bit
 - Version: 19043.1586

 I will package the software installation package and the files after installation in the attachment.

[trace.txt](https://github.com/otya128/winevdm/files/8514033/trace.txt)

[PC Software Win ISO V3.0.zip](https://github.com/otya128/winevdm/files/8514100/PC.Software.Win.ISO.V3.0.zip)

**Comment by cracyc** [comment]
There's a serious bug in the installer
```
1cdc:Call KERNEL.51: MAKEPROCINSTANCE(120f00ee,1217) ret=120f:08bb ds=1217
1cdc:Ret  KERNEL.51: MAKEPROCINSTANCE() retval=11ff00c2 ret=120f:08bb ds=1217
1cdc:Call USER.89: CREATEDIALOG(1217,121701bc "REGISTER",0000,11ff00ba) ret=120f:08d7 ds=1217
...
1cdc:Call KERNEL.52: FREEPROCINSTANCE(11ff00ba) ret=120f:09ef ds=1217
1cdc:Ret  KERNEL.52: FREEPROCINSTANCE() retval=00000018 ret=120f:09ef ds=1217
...
1cdc:Call USER.53: DESTROYWINDOW(003d) ret=120f:0a15 ds=1217
1cdc:trace:msg:WINPROC_CallProc32ATo16 (7421CF80, 00D20162, (null)(0090), 00000000, 00000000)
1cdc:CallTo16(func=11ff:00ba,ds=1217,003d,0090,0000,0000,0000) ss:sp=1217:ec1e ax=1217 bx=0006 cx=0000 dx=0000 si=003d di=0000 bp=ec48 es=1217 fs=0053
Limit check at 0x02e7edaa failed. Segment 1217, limit 0000fd1f, offset 0000ff8b
```
It sets the wrong dlgproc in createdialog which just happens to kind of work because the following procinstance is the correct one.  I'm disinclined to try and fix it and you can press continue in the error dialog ~3 times to skip it.  This doesn't fix the problem mentioned though.

**Comment by cracyc** [comment]
The program needs to be run with winiso5k.tst on the command line.  https://github.com/otya128/winevdm/pull/1145 fixes the start menu icons so it can be run properly from there like the message box says.  Also the program crashes when run and the pr also fixes that.  The program appears to support com ports which may work without the driver.  I don't have the hardware and so can't find out but if it requires the driver then you'll have to find a 64bit one.

**Comment by xmjacky** [comment]
Thank you very much.

There is a problem with visual studio on my computer. Can you compile it and send it to me?

**Comment by otya128** [comment]
CI build artifact is available.
https://ci.appveyor.com/project/otya128/winevdm/builds/43283657/job/pckaaa0326yi9gmi/artifacts

**Comment by xmjacky** [comment]
The software works normally. 
Thank you very much.
