### ISSUE TITLE
QuickTime v2.1.1 installs itself in the WineVDM Windows folders and Win32 application thus can't access QuickTime

### ISSUE THREAD

**Issue by BEENNath58** [otya128/winevdm#1146]
I am trying to play a game Oregon Trail 2. The game uses QuickTime movies, and in order to install QuickTime, I require WineVDM, since the setup is 16-bit. It installs itself in the WineVDM's Windows folders. 

**Expected behavior**

QuickTime was supposed to install in C:\Windows directory. Following that, when I run the Win32 game, it should load the QuickTime video, which it doesn't because it doesn't install in C:\ drive. I tried copying the selected installed files from WineVDM directories to C:\Windows directories but that doesn't help because WineVDM redirects back them to WineVDM's Windows directories.

**Screenshots**

A black window appears. It seems I can't take a screenshot of it, but take it as a generic black window.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Version 21H@ (Build 22000.613)

**Trace**

I have never done a track.txt file generation. Since it was on a CD, I copied the QT installer files to my HDD and executed it from there. The file is attached:
[trace.txt](https://github.com/otya128/winevdm/files/8552531/trace.txt)

**Comment by cracyc** [comment]
You can edit otvdm.ini to set the windows directory but IMO this is a bad idea.  Instead https://archive.org/details/applequicktime32 has a win32 installer for quicktime 2.1.1.

**Comment by BEENNath58** [comment]
> You can edit otvdm.ini to set the windows directory but IMO this is a bad idea. Instead https://archive.org/details/applequicktime32 has a win32 installer for quicktime 2.1.1.

Probably you are right. Editing again and again is messy, and this installer worked so I will go with it. Thankls
