### ISSUE TITLE
Access 2.0 - wrong find dialog

### ISSUE THREAD

**Issue by LegacyFreak** [otya128/winevdm#1147]
Hello,
Access 2.0 calls the wrong find dialog. With otvdm the standard API find dialog is shown not the customized one from Access.
See screenshots and trace.

Screenshot otvdm:
![otvdm](https://user-images.githubusercontent.com/68747203/165590406-f7015ea8-8464-42f3-8b96-f6c5ed6b12d5.jpg)

Screenshot Windows 2000:
![Win2k](https://user-images.githubusercontent.com/68747203/165590514-31572c92-770b-4bb7-9432-61a846fc97f0.jpg)
[Trace.zip](https://github.com/otya128/winevdm/files/8575345/Trace.zip)

**Comment by LegacyFreak** [comment]
Hallo,
thanks for the fix, but threre is another problem according to the find dialog. Every time I used the find dialog, the application crashes on exit. See screenshot and trace.

![Error](https://user-images.githubusercontent.com/68747203/166142610-089d3f81-b473-4d7b-bd8a-1c3024d34d56.jpg)
[Trace.zip](https://github.com/otya128/winevdm/files/8598733/Trace.zip)

**Comment by cracyc** [comment]
I can't repo this.  Is there some specific options you use in the find dialog that causes it or anything?

**Comment by LegacyFreak** [comment]
Hallo,
I tried several options, but the crash always happens when I close the application. I use the search dialog with the tables in the Northwind database. To make it clear: The crash haben when I exit the application, not the find dialog. The crash only happens when I used the find dialog in this session. Maybe it only occurs in the german version of Access 2.0. Maybe it only happens with specific ini settings.
My otvdm.ini:
[otvdm.ini.zip](https://github.com/otya128/winevdm/files/8599469/otvdm.ini.zip)

**Comment by LegacyFreak** [comment]
Hallo,
I tried several options, but the crash always happens when I close the application. I use the search dialog with the tables in the Northwind database. To make it clear: The crash haben when I exit the application, not the find dialog. The crash only happens when I used the find dialog in this session. Maybe it only occurs in the german version of Access 2.0. Maybe it only happens with specific ini settings.
My otvdm.ini:
[otvdm.ini.zip](https://github.com/otya128/winevdm/files/8599469/otvdm.ini.zip)

**Comment by cracyc** [comment]
I think the problem is caused by the program receiving an unexpected message just before exiting.  On my computer it gets WM_QUIT then exits without problems.  If you can rerun the trace adding +msg in the WINEDEBUG env var it might help.

**Comment by otya128** [comment]
This happens even without #1151 and not when dispatching 0x0060 with PeekMessage32_16 to remove it.

```
00ec:Call USER.6: POSTQUITMESSAGE(0000) ret=122f:0ca4 ds=1917
00ec:Ret  USER.6: POSTQUITMESSAGE() retval=00000001 ret=122f:0ca4 ds=1917
00ec:Call USER.445: DEFFRAMEPROC(0023,0031,0002,0000,00000000) ret=122f:1484 ds=1917
00ec:trace:msg:WINPROC_CallProc16To32A (74D9D96E, 0023, WM_DESTROY(0002), 0000, 00000000)
00ec:Ret  USER.445: DEFFRAMEPROC() retval=00000000 ret=122f:1484 ds=1917
00ec:RetFrom16() ss:sp=1917:dc0c  ax=0000 bx=0026 cx=1e6f dx=0000 bp=dc36 sp=dc0c
00ec:trace:msg:WINPROC_CallProc32ATo16 (74D9D45F, 000707B4, WM_NCDESTROY(0082), 00000000, 00000000)
00ec:CallTo16(func=122f:0a98,ds=1917,0023,0082,0000,0000,0000) ss:sp=1917:dc0c ax=1917 bx=0006 cx=0000 dx=0000 si=0023 di=0000 bp=dc36 es=1917 fs=0053
00ec:Call USER.445: DEFFRAMEPROC(0023,0000,0082,0000,00000000) ret=122f:1484 ds=1917
00ec:trace:msg:WINPROC_CallProc16To32A (74D9D96E, 0023, WM_NCDESTROY(0082), 0000, 00000000)
00ec:Ret  USER.445: DEFFRAMEPROC() retval=00000000 ret=122f:1484 ds=1917
00ec:RetFrom16() ss:sp=1917:dc0c  ax=0000 bx=0006 cx=0000 dx=0000 bp=dc36 sp=dc0c
00ec:Ret  USER.53: DESTROYWINDOW() retval=00000001 ret=122f:144f ds=1917
00ec:RetFrom16() ss:sp=1917:dc7c  ax=0000 bx=dbea cx=0028 dx=0000 bp=dca6 sp=dc7c
00ec:trace:message:SendMessage16 (0x0023) [0010] wp=0000 lp=00000000 returned 00000000
00ec:Ret  USER.111: SENDMESSAGE() retval=00000000 ret=1407:0156 ds=1917
00ec:RetFrom16() ss:sp=1917:ddf6  ax=0000 bx=dd9e cx=0000 dx=0000 bp=de20 sp=ddf6
00ec:trace:message:DispatchMessage16 (0x0023) [0112] wp=f060 lp=00000000 returned 00000000
00ec:Ret  USER.114: DISPATCHMESSAGE() retval=00000000 ret=122f:05e5 ds=1917
00ec:Call USER.109: PEEKMESSAGE(1917:de32,0000,0000,0000,0001) ret=122f:01b7 ds=1917
00ec:trace:msg:WINPROC_CallProc32ATo16 (74D9DA81, 000707C6, (null)(0060), 80000006, 00000000)
00ec:Ret  USER.109: PEEKMESSAGE() retval=00000001 ret=122f:01b7 ds=1917
00ec:Call USER.236: GETCAPTURE() ret=122f:03af ds=1917
00ec:Ret  USER.236: GETCAPTURE() retval=00000000 ret=122f:03af ds=1917
```

**Comment by otya128** [comment]
UserAdapterWindowClass may have been changed to SystemUserAdapterWindowClass in Windows 11. (#114)

**Comment by LegacyFreak** [comment]
Hallo, 
with build 2299 the standard API find dialog appears again. I run otvdm on Windows 11.

**Comment by cracyc** [comment]
2299 doesn't include the find dialog template support so that's expected.  Does it crash at exit now?

**Comment by LegacyFreak** [comment]
No it doesn't crash at exit now.
