### ISSUE TITLE
can anyone help with this?

### ISSUE THREAD

**Issue by TheProob** [otya128/winevdm#1148]
![image](https://user-images.githubusercontent.com/104532918/165634688-4bfe50f4-e1ca-4a4e-93e4-d76d072fefb2.png)

im trying to download an old puzzle game from 2000 the setup ran perfectly fine with otvdm but the game executable itself won't run and gives me this message, any help would be appreciated

**Comment by cracyc** [comment]
Need more info like a trace and link to program if available.

**Comment by TheProob** [comment]
here's a link to the program,
https://archive.org/details/Apuzz210

also mind if i ask what a trace is? im kinda new to this :P

> Need more info like a trace and link to program if available.

**Comment by cracyc** [comment]
https://github.com/otya128/winevdm/issues/226#issuecomment-779702542 but https://github.com/otya128/winevdm/pull/1150 fixes it so a trace isn't needed.

**Comment by TheProob** [comment]
> [#226 (comment)](https://github.com/otya128/winevdm/issues/226#issuecomment-779702542) but #1150 fixes it so a trace isn't needed.

sorry, but how exactly do i do that?

**Comment by TheProob** [comment]
the program thankfully worked, i appreciate the support, thanks
