### ISSUE TITLE
Aero borders (7/Vista) are too slim

### ISSUE THREAD

**Issue by MiraakThuri** [otya128/winevdm#1160]
Hey, 
Running on W7 x64 aero theme with DisableAero=0, my 16bits apps have a border looking smaller than it should be, making it abit weird in comparaison to regular 32 or 64bits apps.

16bit:
![16bit](https://user-images.githubusercontent.com/69920875/170720876-cdd0a048-728b-4aef-9e1c-f874e98cfb2e.PNG)

32/64bit:
![regular](https://user-images.githubusercontent.com/69920875/170720935-ed03b76c-025d-40b2-b218-afd0a5e814a3.PNG)

**Comment by otya128** [comment]
This is intended for compatibility.
See https://github.com/otya128/winevdm/issues/341#issuecomment-495863960.
