### ISSUE TITLE
0xc00007b on launching otvdm.exe

### ISSUE THREAD

**Issue by sanrobin** [otya128/winevdm#1161]
Try the latest version first.
Go [here](https://ci.appveyor.com/project/otya128/winevdm) and click `Environment: THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1`-> `Artifacts 1`-> `zip` to download the latest version.

**Describe the bug**
Whenever I open a 16 bit application, it dosent open at all!

**Screenshots**
[Screenshot](https://drive.google.com/file/d/1AGqrJmKbn6IW7as0xJ9EywRbmo0Iow1J/view?usp=sharing)

**Environment (please complete the following information):**
 - OS: Windows 7 Ultimate
 - Version 6.1 (Build 7601 Service Pack 1)

**Additional context**
I cannot tell but all it does that it says "The application was unable to start correctly (0xc00007b). Click OK to close the application.

It is very helpful to provide a trace file if possible.
Please note that this file contains detailed information about the program.
**Procedure**
1. Run the command prompt.
2. Set the environment variable:
```cmd
set WINEDEBUG=+all,-snoop,-ldt,-fixup,-module,-global,-local,-disasm,-syslevel,-thunk
```
3.
```cmd
*old-executable-file* 2> trace.txt
```
4. Upload trace.txt here.

I'm extremely sorry but the trace file is empty. I tried so many times but to no avail. This is the information that I have - Crashing upon startup.

**Comment by cracyc** [comment]
Can you try the "not recommended" gcc build too?

**Comment by WindClan** [comment]
Just had this happen

**Comment by WindClan** [comment]
Its VC++

I forgot to install it on my laptop and installing it fixed it
