### ISSUE TITLE
Super Solvers: Midnight Rescue! (1995) sound compatibility

### ISSUE THREAD

**Issue by flyingninjaowl** [otya128/winevdm#1165]
I'm trying to run the 1995 version of "Super Solvers: Midnight Rescue!" (from The Learning Company) and after installing the game won't run because of a sound compatibility error. It claims that the MIDI driver could not be found on the sound card.

This is the first thing I see when I run SETUP.EXE:
<img width="284" alt="first" src="https://user-images.githubusercontent.com/107602080/173992691-211e9903-e6f0-4f65-9b34-52e9cd7abe9c.png">

Further details upon clicking:
<img width="311" alt="further" src="https://user-images.githubusercontent.com/107602080/173992711-d1e6441c-849e-4852-a6a7-4e1359c57c24.png">

When trying to run SSRWINCD.EXE:
<img width="287" alt="run" src="https://user-images.githubusercontent.com/107602080/173992789-ae5e9f6f-4985-4df6-b0c8-782b99dcdc1c.png">

- OS: Windows 10 Education
- OS build: 19044.1706
- Version: 21H2

I've tried running it with Windows 95 Compatibility mode, 8-bit 256 reduced color mode, and running in 640x480 screen resolution but I still can't run the game.

[trace.txt](https://github.com/otya128/winevdm/files/8915753/trace.txt)

**Comment by flyingninjaowl** [comment]
That worked, thank you so much!

**Comment by roshkins** [comment]
When I run the setup for Gizmos and Gadgets it detects the dummy MIDI file, but when I run the program I get the same error: 
![image](https://user-images.githubusercontent.com/593949/184522721-cb33aa59-b9c8-47f6-8403-36011caaaece.png)
Any other tips?

**Comment by cracyc** [comment]
The setup is probably a win32 programs.  If so then there's nothing winevdm can do about that.
