### ISSUE TITLE
Microsoft Multimedia Schubert - Unable to find font Millicent 10, 12, 14, 16. Please run setup again

### ISSUE THREAD

**Issue by CSmeds99** [otya128/winevdm#1169]
When launching Microsoft Multimedia Schubert, I get an error message saying that the font Millicent 10, 12, 14, 16 is unable to be found. The previous bug report that I had posted for Multimedia Mozart with a similar issue was resolved with that program and it runs as expected. But the Millicent font issue still persists in Schubert, in which I thought it would resolve the same issue.

![schubert](https://user-images.githubusercontent.com/99499673/177569065-c6365e3e-c998-41ba-b5fa-9e54b2d95e7a.png)

Windows 11 Pro 21H2
WineVDM  build 2312

[trace.txt](https://github.com/otya128/winevdm/files/9055434/trace.txt)

**Comment by otya128** [comment]
```
3044:21f0:trace:int21:DOSVM_Int21Handler AX=4e5a BX=02fa CX=0000 DX=0e38 SI=069e DI=0e55 DS=1217 ES=1217 EFL=00003206
3044:21f0:trace:int21:DOSVM_Int21Handler FINDFIRST mask 0x0000 spec C:\OTVDM\WINDOWS\SYSTEM\FOUND
3044:21f0:trace:int21:DOSVM_Int21Handler FINDNEXT
3044:21f0:trace:int21:DOSVM_Int21Handler failed, error 18
3044:21f0:trace:int21:DOSVM_Int21Handler returning: AX=0012 BX=02fa CX=0000 DX=0e38 SI=069e DI=0e55 DS=1217 ES=1217 EFL=00003207
21f0:Ret  KERNEL.102: DOS3CALL() retval=none ret=1487:1d8b ds=1217
```
If this program only checks for the existence of the font file, it can be avoided by creating an empty file `C:\OTVDM\WINDOWS\SYSTEM\FOUND`.

**Comment by CSmeds99** [comment]
After creating the empty FOUND file under C:\OTVDM\WINDOWS\SYSTEM the program loaded correctly with no error message. Thanks for your help.
