### ISSUE TITLE
Jorou Gumo for windows 95 not starting 

### ISSUE THREAD

**Issue by mochicchi** [otya128/winevdm#1184]
Hello, this time Jorou Gumo for windows 95 won't start. The game installs fine, but when I start it, these errors appear after the opening animation plays:
![Screenshot (183)](https://user-images.githubusercontent.com/90536620/183302906-a55db8ff-6918-42c9-83b3-bbe9a15d2ebe.png)
(text says "file open error")
![Screenshot (184)](https://user-images.githubusercontent.com/90536620/183302912-176e678d-451b-4910-9818-1edd4646a3f3.png)

The game then crashes. (I've experienced similar errors in the games pilcaSEX and Cherry Jam, which are by the same developer and appear to use a similar system. The intro plays, "file open error" appears and i get a message about a bmp file, then the game crashes.)

OS: Windows 10 19044
otvdm version: 2327

Here is the game itself
https://mega.nz/folder/5pkxSJiJ#IfZcOTcHUEfiZjIJ1i1m0g
(joro.exe contains two patch files, neither of which fix the error when applied)

Thank you! Let me know if a trace file is necessary.

**Comment by cracyc** [comment]
Because the installer is win32, the jyorowin.ini file needs to be moved from your real windows dir to your winevdm windows dir.

**Comment by mochicchi** [comment]
Ok, it works now! Thank you!
