### ISSUE TITLE
Window frame displays incorrectly with BasicThemer2 or "disable composition" compatibility option enabled

### ISSUE THREAD

**Issue by OrthodoxWindows** [otya128/winevdm#1190]
Window frame displays incorrectly with BasicThemer2 or "disable composition" compatibility option enabled.
Specifically, the window displays in a white frame, with a tear when moved. I posted the problem in BaiscThemer2, and the developer (@Ingan121), replied that the problem was with Winevdm. Here is the detail of the problem : https://github.com/Ingan121/BasicThemer2/issues/19
However, the dialog boxes are displayed correctly.

Here are some screenshots of the issue (with Aerolite visual style):

![otvdmw_PZT6PRy4Ys](https://user-images.githubusercontent.com/100134023/186995887-5a9d8f10-ccda-4bfe-acef-1b933b1cf43b.png)
![178160700-87522082-ef22-4ccf-bbf1-99ba7722f4d6](https://user-images.githubusercontent.com/100134023/186996139-b31a5e44-635a-4b09-a0ce-56f417a3be41.png)
![178160713-49dbcba2-e5fb-4b33-89a6-038ae4396a75](https://user-images.githubusercontent.com/100134023/186996145-952e37f4-28cb-4a3a-b3cf-073a1691c8a1.png)

 - OS: [e.g. Windows 10 21H2]
This appears including in the latest version of Winevdm.

**Comment by otya128** [comment]
If you have changed EnableVisualStyle or DisableAero in otvdm.ini, please change them back.

**Comment by OrthodoxWindows** [comment]
Thank you for the correction !

Sorry for the lack of clarity, but English is not my native language. I will try to be clearer in the future.

Otherwise, I'm not asking for perfect compatibility with visual styles, I'm aware of the impossibility of the task ; only, this problem affected all applications.

So can I close the issue ?

**Comment by cracyc** [comment]
If the change fixes your issue then close it.
