### ISSUE TITLE
Meccano Inventory

### ISSUE THREAD

**Issue by cnfcomps** [otya128/winevdm#1198]
Hi,
I am trying to run a 16-Bit piece of software called 'Meccano Inventory 9.0' on 64-Bit Windows 10. Although I am able to get the program installed, a message 'MeccInv already running from C:\MECCINV' appears whenever it is run. I have confirmed the program works on 32-Bit Windows 10 through a VM where it starts up without error.

I have attached the trace log file hoping this might make sense to somebody.

If anyone could take a look I would really appreciate it.

Thank you,

Matt.

[trace.txt](https://github.com/otya128/winevdm/files/9543473/trace.txt)

**Comment by cracyc** [comment]
It looks like the problem is
```
1b9c:Call KERNEL.102: DOS3CALL() ret=14f7:1d8b ds=1217
     AX=4eff BX=6462 CX=0000 DX=0e38 SI=6470 DI=0e4e ES=1217 EFL=00003202
47ec:1b9c:trace:int21:DOSVM_Int21Handler AX=4eff BX=6462 CX=0000 DX=0e38 SI=6470 DI=0e4e DS=1217 ES=1217 EFL=00003202
47ec:1b9c:trace:int21:DOSVM_Int21Handler FINDFIRST mask 0x0000 spec C:\MECCINV\PURGEINVPOS
47ec:1b9c:trace:int21:DOSVM_Int21Handler failed, error 2
47ec:1b9c:trace:int21:DOSVM_Int21Handler returning: AX=0002 BX=6462 CX=0000 DX=0e38 SI=6470 DI=0e4e DS=1217 ES=1217 EFL=00003203
```
This doesn't work in ntvdm or in win95, possibly it's supposed to be purgeinv.pos, but they return error 12 instead of 2.  Try https://ci.appveyor.com/project/otya128/winevdm/builds/44755503/job/ylohqyxhnewphtk7/artifacts.

**Comment by cnfcomps** [comment]
It worked! Thank you so much for responding and resolving my query!
