### ISSUE TITLE
What version of GAS should I be using?

### ISSUE THREAD

**Issue by neozeed** [otya128/winevdm#12]
I've been able to build WineVDM up until today.  Now I'm getting this error:

krnl386.exe16.asm: Assembler messages:
krnl386.exe16.asm:5: Error: junk at end of line, first unrecognized character is `"'
krnl386.exe16.asm:72: Error: junk at end of line, first unrecognized character is `"'

In prior versions of WineVDM the assembly looked like this:

`/* File generated automatically from krnl386.exe16.spec; do not edit! */
/* This file can be copied, modified and distributed without restriction. */

        .section .init,"ax"
        jmp 1f
__wine_spec_pe_header:
        .skip 69632
1:
`

And the newer ones is giving me this ASM

`/* File generated automatically from krnl386.exe16.spec; do not edit! */
/* This file can be copied, modified and distributed without restriction. */

        .section ".init","ax"
        jmp 1f
__wine_spec_pe_header:
        .skip 69632
1:
`

I know that "GNU assembler 2.17.50 20060824" is no doubt too old but what should I be using?

Thanks!

**Comment by AndrewNile** [comment]
Hi neozeed, 

I was originally using 2.23.2 but that too doesn't work. I replaced it with 2.28 from mingw's binutils package and that is happy with ".init" as quoted.

This change happened in fcdf02d spec32.c:441/442.

**Comment by neozeed** [comment]
Ok that is the other version I have and it built fine
