### ISSUE TITLE
Civilization I installer creates shortcut without an icon

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#120]
The shortcut appears with the default icon.

**Comment by cracyc** [comment]
This can't work in 64-bit windows due to explorer not being able to read win16 program icon resources.

**Comment by Anixx** [comment]
I think, under Win 3.1 the icon in the program manager dioes not extract the icon from the executable. I think the installer puts an .ico file somewhere, but it is not used when the group is converted to the start menu folder.
