### ISSUE TITLE
Old 16 bit application runs well but it crashed, when I try to open a file 

### ISSUE THREAD

**Issue by IBIS628** [otya128/winevdm#1206]
**Describe the bug**

The application is for reading out/ to open driving files. It works fine, but if I try to open a file, it crashes:

![Interrupt](https://user-images.githubusercontent.com/78220951/194773735-ef0d4262-a0eb-488b-860c-360ad5122ab6.png)

**Environment 
 - OS:  Win 10 21H2
 - Version 19044.2006

I tried to create a trace, but it doesn't work, so here's the content of the cmd window, after it crashed: 
[Log.txt](https://github.com/otya128/winevdm/files/9742338/Log.txt)

**Comment by cracyc** [comment]
Please make a trace with the instructions from https://github.com/otya128/winevdm/issues/226#issuecomment-779702542

**Comment by IBIS628** [comment]
ok, now I got it
[trace.txt](https://github.com/otya128/winevdm/files/9742611/trace.txt)

**Comment by cracyc** [comment]
Can you do that again with "set WINEDEBUG=+all,-snoop,-ldt,-fixup,-module,-local,-disasm,-syslevel,-thunk" (-global removed).

**Comment by IBIS628** [comment]
Okay, here is the new trace:  [trace.txt](https://github.com/otya128/winevdm/files/9743555/trace.txt)

**Comment by cracyc** [comment]
Try https://ci.appveyor.com/project/otya128/winevdm/builds/45066409/job/iqilrqvol1o89mw5/artifacts

**Comment by IBIS628** [comment]
It works, thanks! But it takes up to 30sec to open a little file (34kB) / up to 3min for a larger file (1MB).  Sometimes there will be a Runtime Error 401 "Can't show non-modal form when modal form is displayed"
If you want to try it yourself:
[Setup.zip](https://github.com/otya128/winevdm/files/9783419/Setup.zip)

**Comment by cracyc** [comment]
Enabling whpx makes the program more usable but window repainting is still quite slow.  I'm not sure how to get the runtime error to happen.

**Comment by IBIS628** [comment]
Now it's much faster and works good,. Thanks a lot! :D

**Comment by cracyc** [comment]
The slow window painting is an issue with dwm.  With dwm disabled it's as fast as ntvdm is.

**Comment by IBIS628** [comment]
Thank you for continuing to work on my problem. With the new version 2370 and activated whpx it now works almost as well as with an older 32-bit operating system
