### ISSUE TITLE
El traje nuevo del emperador: Trying playing music or recording audio triggers an error

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [otya128/winevdm#1208]
**Describe the bug**
This storyboard creator shows a error message when you go to the music menu (which previews midi music), softlocking you there. No music is played.
The same happens in the microphone menu, although you can get out from there.

**Expected behavior**
It let you play music and record sounds without showing error messages.

**Screenshots**
![error midi el traje nuevo del emperador](https://user-images.githubusercontent.com/16591467/195211707-79c52a85-2ce4-4220-a899-cf5c3bf0f732.jpg)
![error microfono el traje nuevo del emperador](https://user-images.githubusercontent.com/16591467/195211711-3c2b24c3-7c60-40bd-890f-ea2d5ce56646.jpg)

**Environment (please complete the following information):**
 Windows 10 Pro 64-bit (10.0, Build 19044) (19041.vb_release.191206-1406)

**Additional context**
It's a Macromedia Director v5.0.0.134 app.
![imagen](https://user-images.githubusercontent.com/16591467/195211898-f7671e26-37f9-4848-9cab-21d12b61acf4.png)

```2544:err:winevdm:set_peb_compatible_flag user32.dll has already been loaded. (Anti-virus software may be the cause.)
2544:err:winevdm:set_peb_compatible_flag Some compatibility flags can not be applied.
version: 2355
2544:err:winevdm:main Spawn a child process to apply compatible flags.
2544:err:winevdm:fix_compatible child pid = 13132
2a58:err:winevdm:set_peb_compatible_flag user32.dll has already been loaded. (Anti-virus software may be the cause.)
2a58:err:winevdm:set_peb_compatible_flag Some compatibility flags can not be applied.
version: 2355
2a58:err:winevdm:main parent pid = 8500
30f4:err:local:LOCAL_GetBlock not enough space in local heap 1ed7 for 124 bytes
30f4:err:local:LOCAL_GetBlock not enough space in local heap 1fcf for 2332 bytes
30f4:err:local:LOCAL_GetBlock not enough space in local heap 1ed7 for 2332 bytes
30f4:err:local:LOCAL_GetBlock not enough space in local heap 1fcf for 3500 bytes
30f4:err:local:LOCAL_GetBlock not enough space in local heap 20c7 for 3328 bytes
30f4:err:local:LOCAL_GetBlock not enough space in local heap 1fcf for 3328 bytes
30f4:err:local:LOCAL_GetBlock not enough space in local heap 1ed7 for 3328 bytes
```

**Comment by cracyc** [comment]
Need a trace like https://github.com/otya128/winevdm/issues/226#issuecomment-779702542.  A link to the software would help too.

**Comment by RafaelTrepaUnCarballo** [comment]
Of course:
[trace.zip](https://github.com/otya128/winevdm/files/9762991/trace.zip)

I can rip the disk and send you the link. It would be acceptable to post it right here?

**Comment by cracyc** [comment]
Try https://github.com/otya128/winevdm/pull/1209

**Comment by RafaelTrepaUnCarballo** [comment]
Yes, the new build fixes the error messages and the audio playback.
Thanks.
