### ISSUE TITLE
language.dll

### ISSUE THREAD

**Issue by TurboBlaise** [otya128/winevdm#1215]
First of all, thanks for your excellent work!
I have a question though: how can I define the language.dll (sort order) used by the system?
In win 3 it was set in the [boot] section of the system.ini and in NTVDM it could be set by the following registry key:

> [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\WOW\boot]
> "language.dll"="langger.dll"

I need this to get access to Paradox-Tables from within Borland's ObjectVision which otherwise seems to run just fine and for me still is (30 years after EOD) one of the easiest and quickest RAD tools.

**Comment by cracyc** [comment]
What locale is your machine set to?  I'd expect that sort order would follow the system locale for your computer.  Is the program looking in win.ini for that entry?  Can you provide a trace?

**Comment by TurboBlaise** [comment]
I have to privide the DLL in the system directory.

**Comment by cracyc** [comment]
My testing doesn't show it even tries to load the dll, it just reads the value from system.ini and uses that to set the sort order in the database.  Try https://ci.appveyor.com/project/otya128/winevdm/builds/45156875/job/lpqdtojcwqbhr9bs/artifacts .
