### ISSUE TITLE
Wrong version set by installer

### ISSUE THREAD

**Issue by KRosUser2** [otya128/winevdm#1221]
Using WineVDM 0.8.1. Installer sets "1.0" in registry.

![image](https://user-images.githubusercontent.com/114949464/201544603-7cc9d02b-c578-4089-9096-042993c83bef.png)

Discovered using ReactOS : https://jira.reactos.org/browse/CORE-18641

**Comment by cracyc** [comment]
That installer isn't from here.  The link shown in the picture in the ros bug report shows https://github.com/peterooch/winevdm_installer .
