### ISSUE TITLE
Pkunzip.exe and Itf.exe  won't run Main Program exe starts up fine in 64bit

### ISSUE THREAD

**Issue by Rexsley** [otya128/winevdm#1224]
My 2.6a Foxpro program  starts up fine but when I call for the Pkunzip.exe  to unzip a file  it can't unzip the file anymore and Itf.exe which sorts the database  can't get its file. 
These two files are in the same folder as the  Main.exe file.  Is there some registry entries I can make or use a .bat file to get 
Otvdm to work on these files.

**Comment by cracyc** [comment]
Use dosemu= in otvdm.ini to select a different dos emulator.  If dosbox doesn't work because of drive mappings try msdos-player.

**Comment by Rexsley** [comment]
Ok I did change the line in otvdm.ini  to  dosemu=command.com  so the actual window comes up  now  I have two files to deal with  unzip.exe   which runs first   the  ift.exe  runs   both are 16 bit   I get the following screen shots



![one (1)](https://user-images.githubusercontent.com/47876740/203187525-bfa054d7-0cf5-4cbc-a887-90ba545bcd89.png)
![one (2)](https://u
![one (3)](https://user-images.githubusercontent.com/47876740/203187542-c189420a-0e2c-45a3-8e91-5d0c15d58359.png)
ser-images.githubusercontent.com/47876740/203187533-b8429f0a-58ad-4d01-be7b-c25e43778835.png)

**Comment by cracyc** [comment]
Nope, command.com is not a dos emulator.  Try dosbox (https://www.dosbox.com/), msdos-player (http://takeda-toshiya.my.coocan.jp/msdos/) or dosbox-x (https://dosbox-x.com/).  One of these should work for both dos programs.

**Comment by Rexsley** [comment]
this an actual software program it runs perfectly in 32bit  it was written in Foxpro 2.6a . I can you msi installation file if you wish

**Comment by Rexsley** [comment]
first unzip.exe  unzips the  zip file  one program is then  disected by  the itf.exe program  and put into about 6 files that the program uses as a data base

**Comment by cracyc** [comment]
> this an actual software program it runs perfectly in 32bit it was written in Foxpro 2.6a . I can you msi installation file if you wish

Okay

**Comment by Rexsley** [comment]
Heres a link  download the  HRH_AQH Quarter  Horse software   use this key 145-469-637-341 
https://horseracing-handicapper.com/?page_id=113

**Comment by Rexsley** [comment]
I just install otvdm  and run install no console  and this soft ware runs  its on the Import Button where the snag is  bringing in a zip file and dissecting it to the right files

**Comment by cracyc** [comment]
Put dosemu=msdos.exe in your otvdm.ini file and put the program in this zip into your program installer dir.
[msdos.zip](https://github.com/otya128/winevdm/files/10063450/msdos.zip)

**Comment by Rexsley** [comment]
I can't seem to download that  msdos.zip

**Comment by Rexsley** [comment]
can you just email me that zip  my email on my site.  I am getting all kinds of errors trying to open it

**Comment by cracyc** [comment]
If your antivirus is rejecting that file I don't think emailing it will make a difference.  You can also get it from http://takeda-toshiya.my.coocan.jp/msdos/msdos.7z .  The one in binary/v30/msdos.exe appears to be the fastest with your program.

**Comment by Rexsley** [comment]
thanks very much for your help I got all my programs working now in Windows 11 64 bit
