### ISSUE TITLE
InstallShield installer doesn't detect OS

### ISSUE THREAD

**Issue by PlayNeth** [otya128/winevdm#1226]
**Describe the bug**
Game's Installshield installer doesn't detect Windows version and refuses to install the game

**Expected behavior**
Detect the OS and install normally

**Screenshots**
![image](https://user-images.githubusercontent.com/82559127/206310327-0aa27029-06ef-4df5-8aaa-c62e924e5a82.png)

**Environment (please complete the following information):**
 - OS: Windows 10 22h2

**Additional context**
I've tried everything in .ini configuration file, like setting winver=4.0 (Windows 95) but I still can't get installshield to proceed whatsoever, it just gives me that w95/98 error message and nothing else.

**Comment by emendelson** [comment]
Have you tried this instead:

https://www.nfsplanet.com/en/nfs3/files/

**Comment by PlayNeth** [comment]
> Have you tried this instead:
> 
> https://www.nfsplanet.com/en/nfs3/files/

That did the trick, thanks a lot!

**Comment by cracyc** [comment]
It might also work to set iamnotnt=1 in otvdm.ini for other installers that have similar issues.  In this case the alternative installer is a better solution.
