### ISSUE TITLE
Virus warning for otvdm-for-old-windows-v0.8.1 

### ISSUE THREAD

**Issue by Torinde** [otya128/winevdm#1230]
When downloading [otvdm-for-old-windows-v0.8.1.zip](https://github.com/otya128/winevdm/releases/download/v0.8.0/otvdm-for-old-windows-v0.8.1.zip) Windows Defender gives warning about "AndroidOS/Multiverze - Settings Modifier - potentially unwanted behavior"
![image](https://user-images.githubusercontent.com/97228894/206891483-dba6c181-b16c-432d-b0e3-469bbb203488.png)

The regular [otvdm-v0.8.1.zip](https://github.com/otya128/winevdm/releases/download/v0.8.0/otvdm-v0.8.1.zip) downloads OK.

**Comment by cracyc** [comment]
Lots of virus scanners have flagged it with generic or absurd detections.  https://www.virustotal.com/gui/file/a33f3ed9043c5bdedfbaf56de98c2349b8bbb9f355a08536831fbb499fda0dc0  Anyone having a problem with it should report it as a false positive if they can.

**Comment by Torinde** [comment]
FYI - after allowing the AndroidOS/Multiverze, then a second one was found:
![image](https://user-images.githubusercontent.com/97228894/206923810-f6ce73fe-5539-4261-9d89-28d837955ae3.png)
