### ISSUE TITLE
Windows 1.04 D5 Apps not working

### ISSUE THREAD

**Issue by Torinde** [otya128/winevdm#1231]
Of the applications from Windows 1.04 Disk 5 - only CALC.EXE works. The rest give a blue Windows message about incompatible version.
![image](https://user-images.githubusercontent.com/97228894/206909213-e4d6c9ea-9f36-4f5a-b7ed-3d26bfe7155d.png)

I assume that's due to the apps requiring the CPU's real mode. Can OTVDM be extended to somehow utilize for those an emulated CPU from QEMU or DOSbox?

**Comment by cracyc** [comment]
These can't be run directly, they need to be run as "otvdm <file.exe>".  Windows ntvdm64.dll detects them as OS/2 16bit binaries and rejects them.

**Comment by Torinde** [comment]
Great, it works!
Per the [Wine Wikipedia page](https://en.wikipedia.org/wiki/Wine_(software)#Functionality) Wine itself doesn't support those, so maybe you can improve Wine by adding this functionality there as well (so that Linux systems also can run those apps)?

**Comment by cracyc** [comment]
They're free to backport whatever they need, https://github.com/otya128/winevdm/issues/1084.  Winevdm (this one not theirs) can also be run in wine.
