### ISSUE TITLE
Mario Teaches Typing 2: Game locks after any confirmation dialog is displayed

### ISSUE THREAD

**Issue by teconmoon** [otya128/winevdm#1232]
**Describe the bug**
When a confirmation dialog or notification box is displayed, such as when saving an edited lesson file or when pressing ESC and being asked if you want to exit the game, after the dialog has cleared (in the latter example, assuming you said no, you don't want to exit), you are unable to interact with the game.

**Expected behavior**
After confirmation or notification boxes are displayed, the game should continue as expected.

**Screenshots**
[Short video demonstrating behavior](https://drive.google.com/file/d/1-K84PytwJGcewf3i_Mmg7c47xolva5Gs/view)

**Environment (please complete the following information):**
 - OS: Windows 11 Pro
 - Version 22H2 (OS Build 22621.963)

**Additional context**
[trace.txt](https://github.com/otya128/winevdm/files/10238800/trace.txt)

**Comment by cracyc** [comment]
I think this is a focus issue rather than a dialog one.  If you click on any other window then back to the mario one does it do the same?

**Comment by teconmoon** [comment]
Hi there, sorry I forgot to reply and thanks for the fix! This seems to partially help, as the game no longer loses focus when saving language files as described above. However, using the Recover button to restore the language file to the original file still causes the game to lose focus, as does pressing Esc to exit and selecting No (i.e. you didn't mean to hit Esc). In these instances, it seems like Alt-Tabbing away from the game and then Alt-Tabbing back to it helps regain focus.

Let me know if it would help to have a separate trace or video showing this.

**Comment by cracyc** [comment]
This problem occurs in ntvdm on windows xp too when run in anything other than 8bit color mode so it's really an issue with windows not winevdm.  MTT2 relies on the precise windows behavior with how it sends wm_querynewpalette messages and in >8bpp modes windows only sends that message when a program starts while in 8bpp it's sent whenever the window gains focus.  It might be possible to tweak but I don't think it'll ever be perfect.

**Comment by teconmoon** [comment]
Thanks for the explanation. I am running the app using the 640x480 and 8-bit (256) color compatibility mode flags, but sounds like that may not be sufficient to avoid this issue. In this scenario you describe, does the actual display mode have to be 8bit color, or should the compatibility mode flag be sufficient? iirc the game complains if it's not running in 8-bit color mode.

**Comment by cracyc** [comment]
Try https://github.com/otya128/winevdm/pull/1240

**Comment by teconmoon** [comment]
> Try #1240 and see if it works better.

That did the trick! #1234 definitely helped with some aspects but the game no longer loses focus with #1240. I tested with many dialog options such as restoring lesson files, escaping back to the main menu, deleting student files, and it didn't lose focus once.

Thanks again for your willingness to look into this.
