### ISSUE TITLE
AutoSketch v2.1 crashes when opening text settings

### ISSUE THREAD

**Issue by mluizescu** [otya128/winevdm#1243]
using otvdm-master-2382

**Describe the bug**
When opening text properties, it errors out. If using WHPX, the program crashes, without WHPX, there is a SEGV error, if i click "continue" or "try again", i can carry on changing the text properties, if i click cancel, the program crashes. Under 32-bit Windows, the error is not present.

**Expected behavior**
There should be no error when changing text properties.

**Screenshots**

![Error](https://user-images.githubusercontent.com/57252786/210788286-055cb441-08ff-457e-8824-2ea8c2f24a06.JPG)

**Environment (please complete the following information):**
 - OS: Windows 10 22H2
 - Version 19045.2364

**Trace files**

[trace_files.zip](https://github.com/otya128/winevdm/files/10352468/trace_files.zip)

**Comment by cracyc** [comment]
This program also might need "EnumFontLimitation=1" in otvdm.ini at least had to set it for it to work.

**Comment by mluizescu** [comment]
Hi @cracyc, thank you for your help! With your commit, the error is gone. "EnumFontLimitation=1" speeds up the loading of the text properties window. For me, it also works without it, but the window takes longer to load.
Closing the issue as solved. Thanks again for your quick response!
