### ISSUE TITLE
Wrong com port settings

### ISSUE THREAD

**Issue by hagsted** [otya128/winevdm#1254]
**Describe the bug**
When opening a com port (serial RS232) the port settings are wrong. the settings in windows 10/11 is set to:

- Baud rate: 9600
- Data bit: 8
- Parity: None
- Stop bit: 1

But the trace reports

- Baud rate: 9600
- Data bit: 7
- Parity: Even
- Stop bit: 2

```
22b0:Call USER.200: OPENCOMM(12d7ab00 "COM1",0fa0,00c8) ret=1227:865f ds=12d7
1abc:22b0:trace:comm:OpenComm16 COM1, 4000, 200
1abc:22b0:trace:comm:GetCommState16 cid 0, ptr 7467ECDC
22b0:Ret  USER.200: OPENCOMM() retval=00000000 ret=1227:865f ds=12d7
22b0:Call USER.213: BUILDCOMMDCB(12d7:abca,12d7:ac94) ret=1227:8883 ds=12d7
1abc:22b0:trace:comm:BuildCommDCB16 (COM1:9600,e,7,2), ptr 02F8E83C
```

This results in no communication between attached device and the program.

**Expected behavior**
The win16 program should open and start communicating with the device. It is a machine control device, from last century.

**Environment (please complete the following information):**
 - OS: Windows 11 22h2 and windows 10 22h2
 - Version 2391

```
4. Upload trace.txt here.
[trace.txt](https://github.com/otya128/winevdm/files/10498082/trace.txt)

**Comment by hagsted** [comment]
You are completely right. And some testing with win31dosbox gives me the same com port settings. However when running the program in win31dosbox passing through the serial port, it connects as expected. Running the same program through otvdm, does connect to the serial port and sends data but it does not seem to connect correctly.

I use a virtual serial port with null modem connected to an emulated device. 

I have tried to attach a trace with [WINEDEBUG=+relay,+int21](https://github.com/otya128/winevdm/files/10509738/trace-relay.txt) and one with [WINEDEBUG=+all,-snoop,-ldt,-fixup,-module,-global,-local,-disasm,-syslevel,-thunk](https://github.com/otya128/winevdm/files/10509735/trace-all.txt)

Best regards Kristian

**Comment by cracyc** [comment]
I've verified that 7e2 settings work correctly with a terminal program.  I think I'd have to examine the program directly even if I can't run it.  It might be expecting something from the comm apis that we don't currently implement.

**Comment by hagsted** [comment]
I will be happy to send you the program, and the emulator that it can communicate with. The emulator is a dos program and at the moment I have only got it to run in dosbox. I connect them by a virtual serial port. When running emulator in doxbox and ex.exe in win31dosbox everything works fine, moving ex.exe to otvdm, and it will not connect.

The file that needs to run is the ex.exe, and its ex.ini file needs to be in the otvdm windows dir.

For the emulator, it is the file llc3.exe that needs to be called.

I do appreciate your help
[EXE.zip](https://github.com/otya128/winevdm/files/10517818/EXE.zip)

**Comment by hagsted** [comment]
Thank you. So far all looks good. I must admit that I am impressed and pleased with the fast and competence response.
