### ISSUE TITLE
Otvdmw 256 Color Mode

### ISSUE THREAD

**Issue by samikhan75** [otya128/winevdm#1256]
Hi...
I have a graphic designing sofware which is running in 256 color mode. Its working good in 32 bit OS with ntvdm.
Now i want to use this software in 64 bit OS with otvdm... Tried with compatibility 8 bit mode,,, 
Otvdmw not showing borders of my graph. Its cutting 2 lines of pixel from right side and 2 lines from down.... Any Solution plz ???
Sorry 4 my poor Eng....

**Comment by cracyc** [comment]
Need more information like a trace and what the program is.

**Comment by samikhan75** [comment]
![IMG_20230131_162809](https://user-images.githubusercontent.com/122938487/215748208-38362ba1-2d5b-45be-b725-c62f93cb8cba.jpg)
![IMG_20230131_162744](https://user-images.githubusercontent.com/122938487/215748219-7f0cbd58-d373-4870-aa1e-f771deddc318.jpg)


See the difference.

**Comment by samikhan75** [comment]
![IMG20230120211654](https://user-images.githubusercontent.com/122938487/215752170-9e9ee83c-2444-4f02-b241-7f87de99a1b9.jpg)


Program interface with 32 bit ntvdm.

**Comment by otya128** [comment]
It looks like NoPaddedBorder is not working.
Try setting compatibility mode (e.g. Windows 8) to otvdm.exe/otvdmw.exe.

**Comment by samikhan75** [comment]
Otvdmw.exe 256 color mode i m telling about.

**Comment by samikhan75** [comment]
Ok... Nw i will try with windows 8 com... Mode

**Comment by samikhan75** [comment]
I just tried with 8 bit mod.

**Comment by samikhan75** [comment]
Thank You Bro...  I dont belv this that its running on 64 bit...
Once again... Shukria. Problem solved.

**Comment by cracyc** [comment]
Was it windows 8 compatibility mode which fixed it?

**Comment by samikhan75** [comment]
Yes Bro...

**Comment by otya128** [comment]
If you are using otvdm-for-old-windows-v0.8.1.zip on Windows 7 or later, use https://ci.appveyor.com/project/otya128/winevdm/builds/46074706/job/g0m6i9neg2irxxsr/artifacts or otvdm-v0.8.1.zip.
