### ISSUE TITLE
Low CPU Usage

### ISSUE THREAD

**Issue by samikhan75** [otya128/winevdm#1258]
Hello

**Comment by cracyc** [comment]
What software? Did you try whpx?

**Comment by samikhan75** [comment]
Bitmap converter. 256 color mod.
Cracys bro you solved the problem
Of nopedded window..
But now there is  speed issue in some
Scenario... 
For load big size bitmap its not respond
For a while.
In cpu usage its using just 28%...
How to max speed for stable use
of my software. We use this sofware for
Textile machines. To convert bitmap file.

**Comment by samikhan75** [comment]
Added line to otvdm.ini
vm=whpxvm.dll
Windows hypervisor platform enabled.

Is this enough ???

**Comment by cracyc** [comment]
Get the package from https://github.com/otya128/WinHvPlatform32/releases/tag/1.1 and unzip it into your winevdm directory.

**Comment by samikhan75** [comment]
Whpx... didnt feel difference.

**Comment by samikhan75** [comment]
Can we go for haxmvm.dll
I have intel cpu.

**Comment by cracyc** [comment]
> In cpu usage its using just 28%...

If you have a 4 core cpu winevdm running a single task will only use ~25% because all win16 programs are single threaded.

>Can we go for haxmvm.dll

You can try it but I wouldn't expect any difference than whpx.

**Comment by samikhan75** [comment]
Does whpx work on win 7 ???

**Comment by cracyc** [comment]
No, you need windows 10 or 11.  Haxm does though.

**Comment by samikhan75** [comment]
Ok thanks... Bro.
Happy to uze otvdm.
