### ISSUE TITLE
Feature request: Windows 95 as windows version

### ISSUE THREAD

**Issue by BEENNath58** [otya128/winevdm#1259]
Till date, my main usage of WineVDM was to **install** old games that used 16-bit installers. There were "a lot of games" that needed to check the system is Windows 95. It was quite simple: Put Windows 95 compatibility mode on a **Win32 program** that launched the 16-bit installer (such as Autorun program). Compatibility modes were shared across child processes while combability fixes weren't (that's what I discovered).

However the method is no longer feasible since Windows 11 22H2. As EmulateHeap, a compatibility fix included in Windows 95 compatibility mode, no longer works correctly in this version of Windows, **most** of the installer programs crash due to improper handling of heap.

So my request is simple: I (and a lot more people) would be happy to have the 16-bit programs see Windows version as Windows 95.

Thank you

**Comment by cracyc** [comment]
Winevdm can return different versions of windows to 16 bit programs but that doesn't affect win32 programs run from it.  You can set Windows 95 compatbility to otvdm.exe itself, maybe that will work. Or you can try setting the compatibility mode to the shim, https://github.com/otya128/winevdm/pull/1253, I added to try and fix installshield sendmessagea hangs.

**Comment by BEENNath58** [comment]
>You can set Windows 95 compatbility to otvdm.exe itself, maybe that will work.

It doesn't. However Win95VersionLie compatibility **fix** works and fixes many non-IS installers, a positive sight.

> Or you can try setting the compatibility mode to the shim, #1253, I added to try and fix installshield sendmessagea hangs.

I didn't understand what to do with the file, I think tweaking with it necessary for Win9x IS to work. Can you elaborate?

**Comment by cracyc** [comment]
>I didn't understand what to do with the file, I think tweaking with it necessary for Win9x IS to work. Can you elaborate?

Put it in your winevdm dir and set the otvdm.ini setting then set the win9x compatibility mode on it.  Since it is run elevated then runs the win32 installer hopefully the compatibility fix will be inherited.

**Comment by BEENNath58** [comment]
I wasn't sure if I should put the folder of isfix, or just put the 2 files. What I ended up doing is put the 2 files across all the subdirectorires as well as the root of winevdm folder with the otvdmw.exe and putting:

`ElevationShim=isfixload.exe`  

in otvdm.exe

Now where do I put the Win9x compatibility mode? On otvdmw.exe? On the Installshied setup.exe file or isfix.exe file? I put it in otvdmw.exe and as always it fails to execute. I put it in isfix.exe and setup.exe of the game and there is no betterment, it still can't see Windows 95.

**Comment by cracyc** [comment]
On isfixload.exe.

**Comment by BEENNath58** [comment]
> On isfixload.exe. What is an example of a program affected by this?
> 
> I tested setting windows 95 compatbility to isfixload.exe and it does work at least with Hardcore 4x4. The elevationshim setting requires the full path to isfixload.exe.

There are many games (the CDs are offsite),  but the one where I learnt about this technique and I currently have is MechWarrior 2 Pentium Edition or MechWarrior 2 Titanium Edition

**Comment by cracyc** [comment]
Setting windows 95 compatbility to isfixload.exe also works for me with MechWarrior 2 Pentium Edition.  This is on win10 so I don't know whether the win11 problem you mentioned occurs.

**Comment by BEENNath58** [comment]
> Setting windows 95 compatbility to isfixload.exe also works for me with MechWarrior 2 Pentium Edition. This is on win10 so I don't know whether the win11 problem you mentioned occurs.

Which version of Windows 10? I have Windows 10 21H2 as well and setting `ElevationShim=isfixload.exe` and putting Win95 compat mode on isfixload.exe. It doesn't work on Win11 either
![mech2winnterrorwin10](https://user-images.githubusercontent.com/64649734/219482345-a0ff4d02-5a7c-4f6d-afb8-24d01926da09.png)
![mech2winnterrorwin11](https://user-images.githubusercontent.com/64649734/219482347-606a160c-b4e7-464e-b5ec-556c063bfca1.png)

`

**Comment by cracyc** [comment]
Windows 10 21H2.  When the elevation prompt shows up does it say isfixload.exe or _ins0432._mp.  If it's the latter then the shim isn't loading.

**Comment by BEENNath58** [comment]
> When the elevation prompt shows up does it say isfixload.exe or _ins0432._mp. If it's the latter then the shim isn't loading.

It says _ins0432._mp in elevation propt.

**Comment by cracyc** [comment]
Then the ElevationShim setting in otvdm.ini isn't active.  Did you put the file in the wrong place or did you not remove the semicolon in front of ElevationShim?

**Comment by BEENNath58** [comment]
Here's my otvdm.ini if there's something else to be changed:

`;The leading semicolon represents a comment. If you want to edit the settings, delete the leading semicolon.
[otvdm]

; Enable visual style. (default: 0)
; Setting this to 1 will significantly affect compatibility.
;EnableVisualStyle=0

; Disable window theme. (defualt: 1)
; Setting this to 0 will affect compatibility a bit.
;DisableAero=1

; The path to redirected Windows directory. (default: .\WINDOWS)
;WINDIR=WINDOWS

; DOS version (default: 8.0)
;VDMDOSVER=x.x

; Windows version (default: 3.95)
;WINVER=3.1

; Don't report running under Windows NT. (default: 0, report running under Windows NT)
;IAmNotNT=1

; Separate taskbar icons among programs. (default: 2)
; 0: Don't separate
; 1: Separate for each otvdm.exe process
; 2: Separate
;SeparateTaskbar=2

; SeparateWOWVDM (default: 1)
;SeparateWOWVDM=1

; VM dll (default: vm86.dll software x86 emulator)
; vm86.dll: The slowest, most compatible, and most stable.

; haxmvm.dll: VM using a hypervisor
;  You must install intel HAXM driver.
;  https://software.intel.com/en-us/articles/intel-hardware-accelerated-execution-manager-intel-haxm
;  It is 100 times faster (in some cases) than the software CPU emulator.

; gvm.dll: KVM ported to Windows
; You must install https://github.com/google/android-emulator-hypervisor-driver-for-amd-processors/releases
; Works with both AMD and Intel.

; whpxvm.dll: VM using Windows Hypervisor Platform
;  HAXM, GVM cannot be installed if you are using WSL2, Hyper-V.
;  Windows Hypervisor Platform should be enabled.
;  Since whpxvm.dll is implemented by forcibly loading a 64-bit DLL into a 32-bit process,
;  it may not work depending on the version of Windows.
;  You must download the DLL from the following URL and place it in the dll directory.
;  https://github.com/otya128/WinHvPlatform32/releases/tag/1.1

; whpxvm.dll is the most stable of the hypervisors.

;vm=haxmvm.dll

; Fix the size of the screen to the value considering taskbar. (default: 0)
;FixScreenSize=1

; Enable registry redirection (default: 0)
; All registry operations are redirected to:
; HKEY_CURRENT_USER\Software\otvdm\HKEY_CLASSES_ROOT
; HKEY_CURRENT_USER\Software\otvdm\HKEY_CURRENT_USER
; HKEY_CURRENT_USER\Software\otvdm\HKEY_LOCAL_MACHINE
; If necessary, combine SETUP.REG on windows setup disk with 16-bit REGEDIT.
;EnableRegistryRedirection=1

; Limit the number of fonts. (some old programs can not process many fonts)
; (default: 0)
;EnumFontLimitation=1

; Tweak rendering of TrueType fonts.
; Forced font quality values: (default: -1)
;  -1: No forced quality        3: Non-antialiased
;   0: Default                  4: Antialiased
;   1: Draft                    5: ClearType
;   2: Proof
;ForceFontQuality=-1

; Enable font antialias (default: 0)
; If EnableFontAntialias is 1, it is equivalent to ForceFontQuality=3.
;EnableFontAntialias=0

; Improve XOR composition. (default: 0)
;DWMDesktopDCFix=1

;DWMDesktopDCFixBackgroundColorR=254
;DWMDesktopDCFixBackgroundColorG=254
;DWMDesktopDCFixBackgroundColorB=254

; Set application to launch MSDOS programs with
; Works with msdos player, dosbox requires a config file to mount virtual drives
; (default: otvdm.exe)
;dosemu=msdos.exe

; Limit environment variable strings. (default: 1)
;EnvironmentVariableLimitation=1

; Force otvdm onto a single processor, programs that require tight sync
; between two processes can be more reliable (default: 0)
;ForceSingleProcessor=1

; Sleep for extra time in PeekMessage for programs that poll the message queue
; in a tight loop using all the available cpu time, wait time in milliseconds (default: 0)
;PeekMessageSleep=5

; If EnumFontLimitation=1, this section declare the font to be enumerated.
;[EnumFontLimitation]
;font name=1(enumerated)/0(not enumerated)
;MS Serif=1
;Webdings=0
;

; Run a compatibility shim for elevated processes
; isfixload will shim installshield which calls sendmessagea(HWND_BROADCAST) which can hang if there
; is a process not servicing it's message queue
ElevationShim=isfixload.exe
`

**Comment by cracyc** [comment]
21-09-2022?  ElevationShim was added last month.  You need to download a newer build.

**Comment by BEENNath58** [comment]
> 21-09-2022? ElevationShim was added last month. You need to download a newer build.

Could you link me to/ build the latest one for me? I have VC22 and it's incompatible with it. I never used the git commands either.

**Comment by otya128** [comment]
https://ci.appveyor.com/project/otya128/winevdm/build/job/2r4j31iqy374novi/artifacts

**Comment by BEENNath58** [comment]
> https://ci.appveyor.com/project/otya128/winevdm/build/job/2r4j31iqy374novi/artifacts

Thanks, I got some steps ahead. But now it complaints about not finding isfixload.exe. I have it in the root folder of OTVDM just as shown 2 posts earlier.

**Comment by cracyc** [comment]
ElevationShim needs to have to the full path to the file.

**Comment by BEENNath58** [comment]
> ElevationShim needs to have to the full path to the file.

How do I do that? Does it imply ripping the CD and running it then?

**Comment by BEENNath58** [comment]
I tested putting full path today. It now loads isfixload.exe properly. But the situation isn't improved. It still says I am running Windows NT.

**Comment by cracyc** [comment]
So it says isfixload.exe in the elevation prompt and you have isfixload set for Windows 95 compatibility?  This works for me so I don't know what to suggest for further debugging.

**Comment by BEENNath58** [comment]
Finally got it!

I needed to restart Windows and the isfixload.exe works perfectly. It also works fine when being run as a son process from a Win32 application!

Thanks!
