### ISSUE TITLE
Can't open Caswin program

### ISSUE THREAD

**Issue by DarkameMaster** [otya128/winevdm#1265]
**Describe the bug**

So basically I get this error:

address=749A2850
access address=00C674AD
VM context
EAX:FFFF,ECX:3C97,EDX:FFFF,EBX:0008
ESP:C3F0,EBP:C420,ESI:0000,EDI:0000
ES:3C97,CS:12CF,SS:12B7,DS:3C8F,FS:0000,GS:0000
IP:1431, address:02F94241
EFLAGS:00003296

SEGV

**Environment (please complete the following information):**
 - OS: Windows 10 21H2

**Additional context**
The program requires another one called jobman in order to cut/print the designs (jobman can be opened), also it needs a dongle in order to work but my father purchased a cracked version that shoul work by itself. I don't know if that can be the problem. 

[trace.txt](https://github.com/otya128/winevdm/files/10751679/trace.txt)

**Comment by cracyc** [comment]
Does this work in windows xp?  If so try setting vdmdosver in otvdm.ini to 5.50.

**Comment by DarkameMaster** [comment]
> Does this work in windows xp? If so try setting vdmdosver in otvdm.ini to 5.50.

Yes, it works in Windows XP. I just changed the vdmdosver to 5.50 but it still doesn't work

**Comment by cracyc** [comment]
Does it do anything different?  The trace shows it's trying to load a win31 or win95 vxd which won't work on nt/xp/10 so it's not detecting that it's running on nt but the trace doesn't show why.  https://github.com/leecher1337/haspnt64 suggests that the hasp dongle ntvdm driver expects dos ver to be 5.50.

**Comment by DarkameMaster** [comment]
Now I get this 
[trace.txt](https://github.com/otya128/winevdm/files/10759831/trace.txt)

Should I install the hasp dongle driver?

**Comment by cracyc** [comment]
```
22ac:21ac:trace:int21:DOSVM_Int21Handler AX=3306 BX=afc8 CX=2710 DX=0000 SI=0000 DI=12b7 DS=3c8f ES=11e7 EFL=00003246
22ac:21ac:trace:int21:DOSVM_Int21Handler GET TRUE VERSION NUMBER
22ac:21ac:trace:int21:DOSVM_Int21Handler returning: AX=3306 BX=0005 CX=2710 DX=0800 SI=0000 DI=12b7 DS=3c8f ES=11e7 EFL=00003246
```
BX=0005 which means it's still returning the wrong dos version.  Did you remove the semicolon in front of vdmdosver=?

**Comment by DarkameMaster** [comment]
Already worked! Sorry I didn't read that I needed to delete the semicolon, my bad!

**Comment by cracyc** [comment]
Is it doing something different now?

**Comment by DarkameMaster** [comment]
The program is working as it should, the only problem now is that the LPT plotter isn't receiving any instructions from the software. Do I need to install a previous version in order to make it work correctly? I did read that someone installed the Windows 1709 version in order to make it work his LPT device, but do you know what's happening?

**Comment by cracyc** [comment]
Try making a new trace.

**Comment by DarkameMaster** [comment]
The trace.txt file is very huge to send it here, what should I do?

**Comment by cracyc** [comment]
Try zipping it.  Text files compress well.

**Comment by DarkameMaster** [comment]
Here it is

[trace.zip](https://github.com/otya128/winevdm/files/10761805/trace.zip)

**Comment by cracyc** [comment]
This change might help https://github.com/otya128/winevdm/pull/1268

**Comment by cracyc** [comment]
Is it a usb device?  Then the port name might be not be lpt1.  You might need to use "net use" or something to map the device to the lpt1 device.

**Comment by DarkameMaster** [comment]
I already made it work! The problem was the COM port, it wasn't correctly connected in the motherboard. Thank you for the help!
