### ISSUE TITLE
Word Search Mania doesn't Work

### ISSUE THREAD

**Issue by WindowsNinetyTen** [otya128/winevdm#1267]
When I try to Open Word Search Mania, I get an error saying "Run=time error '380': Invalid property value."

**Comment by cracyc** [comment]
Need a trace.

**Comment by WindowsNinetyTen** [comment]
I tried my best to put some files but for some reason I can't seem to get permission to send them to a ZIP. So: Go to Archive.org, type in Galaxy of Games Gold Edition, download the ISO and click on it after it's finished. Then, go to setups, and then NewWordSearch.exe. Install the program and try to open it. You will then see it fail.

**Comment by cracyc** [comment]
The game needs to be installed to a directory which it can write to.  Install it to your user directory or the root of the c drive.

**Comment by WindowsNinetyTen** [comment]
I did it and the program works. But when I click the button with a clock on it, I get another message: "Run Time Error '31037': Error loading from file".
