### ISSUE TITLE
Interrupt 0D #GP When trying to print

### ISSUE THREAD

**Issue by weronnie** [otya128/winevdm#1271]
I've tried the stable release and the latest 2411 version both give me the issue. 
[trace.txt](https://github.com/otya128/winevdm/files/10877824/trace.txt)
![issue](https://user-images.githubusercontent.com/84687243/222621042-bc9cd353-be55-46dc-a1af-7e9a88122b2b.JPG)

**Comment by cracyc** [comment]
Make a trace with the instructions at https://github.com/otya128/winevdm/issues/226#issuecomment-779702542 .

**Comment by weronnie** [comment]
Thanks for the prompt response, here's the trace

[trace.txt](https://github.com/otya128/winevdm/files/10878154/trace.txt)

**Comment by cracyc** [comment]
There's something weird in the trace but not enough info to understand exactly what's happening.  Is the software available somewhere, maybe a demo?

**Comment by weronnie** [comment]
Hi, unfortunately this is a proprietary software that I can't share. If this is an option, do you do consulting? we would be willing to pay for your time to help us get this working.

**Comment by cracyc** [comment]
Email me at bs666_1 at hotmail.com
