### ISSUE TITLE
Dropdown list is shown behind button

### ISSUE THREAD

**Issue by hagsted** [otya128/winevdm#1275]
**Describe the bug**
I have a drop down list in the UI that is shown behind the button which sits just below the list. When I try to select anything in the list it seem that it is correctly place above the button. So it is merely cosmetic

**Expected behavior**
I expect the list to be shown on top of the button.

**Screenshots**
![image](https://user-images.githubusercontent.com/4332517/223111541-e7040dcb-838a-422a-86c0-04e8f5553afc.png)

**Environment (please complete the following information):**
 - Windows 11 22H2
 - Version: 2413

I cannot see any info in the trace added after I click the list. If I need to run with special option please advice me how to do it.

trace1.txt is made with:
set WINEDEBUG=+all,-snoop,-ldt,-fixup,-module,-global,-local,-disasm,-syslevel,-thunk

trace2.txt is made with:
set WINEDEBUG=+relay

Best regards Kristian
[trace1.txt](https://github.com/otya128/winevdm/files/10906164/trace1.txt)
[trace2.txt](https://github.com/otya128/winevdm/files/10906165/trace2.txt)

**Comment by cracyc** [comment]
Use the steps at https://github.com/otya128/winevdm/issues/226#issuecomment-779702542 to make a trace.

**Comment by hagsted** [comment]
I have added traces to the original post

**Comment by cracyc** [comment]
Something went wrong here.  Trace1 is cut off after the first few lines and trace2 is empty.

**Comment by hagsted** [comment]
I tried to make the traces again with the same winedebug, but got the same result. Instead I have made a trace with "set WINEDEBUG=+all. Which I have attached here.
[trace_OS.txt](https://github.com/otya128/winevdm/files/10918381/trace_OS.txt)

The software OS is communicating with some other software (EX) through files. I also have a trace for that, but I don't think it is relevant, and it is 31 MB large. If you want please tell me.

Best regards Kristian

**Comment by cracyc** [comment]
It's still cut off.  I don't know what to suggest because I haven't seen that happen before.

**Comment by hagsted** [comment]
Hi I tried to use version 2396 instead, and that seems to give a full trace, which I have attached.
"set WINEDEBUG=+all,-snoop,-ldt,-fixup,-module,-global,-local,-disasm,-syslevel,-thunk" was used 
[trace.txt](https://github.com/otya128/winevdm/files/10931010/trace.txt)

**Comment by cracyc** [comment]
There's nothing obvious in that trace.  Is there a way I can run it myself, a demo or something?

**Comment by hagsted** [comment]
I have attached an emulator version of the software. The version is somewhat old, compared to the version that we use in production. however it does show the same problem, albeit it is a little hard to locate a place where it is obvious.

- Copy STS folder c:\
- Go to c:\STS\MPX\EXE.
- Start EM (Emulator, needs to run)
- Start EX (Data exchange, needs to run)
- Start OS (Operator station, here the problem is visible)
- When asked login in, select administrator, password: "adm"
- Open the control menu and select Sequencer
- Press view, in the sequencer windows
- The dropdown behind button, is visible if you click in the "Description" field.
- It can also be seen if you press edit and click in the "Recipe" of "Clean recipe" field

Even as the list is shown behind the buttons, clicking on the button will select the entry in the last that should have been shown above.

[STS.zip](https://github.com/otya128/winevdm/files/10954243/STS.zip)

I do hope this can help you. And thanks for all you effort.

**Comment by cracyc** [comment]
This is caused by https://github.com/otya128/winevdm/blob/master/user/window.c#L3198 removing WS_CLIPSIBLINGS.  @otya128 would know what it's for.

**Comment by hagsted** [comment]
Again thanks for the quick solution. otya128 solution have been tested and is working for me.
