### ISSUE TITLE
Running a screensaver with /s sometimes doesn't work as intended

### ISSUE THREAD

**Issue by SilasLaspada** [otya128/winevdm#128]
Sometimes when running a screensaver with the /s switch, it opens the options/configuration box instead of the screensaver. Running the same command 100 times in a row, it happened twice. Just to be sure, I tried the same thing on Windows XP (running the screensaver with /s 100 times in a row on the command line) and it never happened, so it doesn't seem to be an issue with the screensaver itself. If the specific screensaver itself is important, I can link to it. Tested on the very newest build (Version 966)

**Comment by cracyc** [comment]
Often Windows allocates memory in build_command_line from below 1MB which MapLS then interprets as a request for DOS memory.  If HeapAlloc does this frequently it could cause lots of undebuggable random problems.  Maybe use VirtualAlloc to reserve all the address space below 1MB so HeapAlloc can't use it.

**Comment by SilasLaspada** [comment]
I honestly don't know what most of that means, but how can I test your suggestion? If you give me instructions I should be able to follow them at least.

**Comment by SilasLaspada** [comment]
Appears to be working now as of the newest commit! I tried over 100 times and it worked properly every time.
