### ISSUE TITLE
Curious George Comes Home: Crashes at launch

### ISSUE THREAD

**Issue by teconmoon** [otya128/winevdm#1284]
Try the latest version first.
Go [here](https://ci.appveyor.com/project/otya128/winevdm) and click `Environment: THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1`-> `Artifacts 1`-> `zip` to download the latest version.

Tested with build 2425

**Describe the bug**
When launching the game, it crashes. Screenshot and trace below.

**Expected behavior**
The game shouldn't crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/46909426/226070405-5be4a5c2-4ac4-412c-910f-3a639d9cc367.png)

**Environment (please complete the following information):**
![image](https://user-images.githubusercontent.com/46909426/226070428-5f454097-38c1-4473-bd93-8073357ccb29.png)

**Additional context**
If you forget to toggle the compatibility flag for 256 color mode, the game at least gets far enough to give you a proper error before exiting.

![image](https://user-images.githubusercontent.com/46909426/226070763-4e10528e-8111-4124-9e29-2d069bd25093.png)

**Trace File**
When getting the trace file, the otvdm.exe process wouldn't stop until I killed it in taskmgr.
[trace.txt](https://github.com/otya128/winevdm/files/11007005/trace.txt)

**Comment by cracyc** [comment]
This is a bug in the program that is reproducible in xp/ntvdm.  To get around it you need to either uncomment iamnotnt=1 in otvdm.ini or delete mss32.dll in the cgwin directory.  It works sometimes in ntvdm when mss32.dll fails to load.

**Comment by teconmoon** [comment]
Easy enough, thanks!
