### ISSUE TITLE
Redshift 1.2 astronomy software crashes upon launching REDSHIFT.EXE

### ISSUE THREAD

**Issue by CSmeds99** [otya128/winevdm#1287]
When launching the REDSHIFT.EXE binary, the program immediately crashes with an error message.

The program is normally supposed to launch as it does under the Windows 10 32-bit NTVDM.

Internet Archive URL for Redshift 1.2 ISO image:

https://archive.org/download/redshift_202204/REDSHIFT.iso

Screenshot of error message:

<img width="273" alt="Redshift 1 2" src="https://user-images.githubusercontent.com/99499673/230740310-2ba04613-4cc4-4f0b-a5c5-61e670527b80.png">

Windows 11 Pro 22H2 build 22621.1413
WineVDM version 2427

Trace:

[trace.txt](https://github.com/otya128/winevdm/files/11184025/trace.txt)

**Comment by cracyc** [comment]
#1288 fixes this crash.  Now crashes at exit.
