### ISSUE TITLE
Ace Venture Pet Detective (German) crashes after Intro

### ISSUE THREAD

**Issue by asc82** [otya128/winevdm#1290]
Try the latest version first.
Go [here](https://ci.appveyor.com/project/otya128/winevdm) and click `Environment: THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1`-> `Artifacts 1`-> `zip` to download the latest version.

**Describe the bug**
After the intro video has played, the german version of Ace Venture Pet Detective just crashes.

**Expected behavior**
It is supposed to run further like the english version.

**Screenshots**
n/a.

**Environment (please complete the following information):**
 - OS: Windows 11 22H2 [e.g. Windows 10 1903]
 - Version: 22621.1413 [e.g. version: 1523]

**Additional context**
When installing the game, it won't even start and error out saying that "ACE.BIN" could not be found, even though it is present in the folder. 
[trace-2.txt](https://github.com/otya128/winevdm/files/11217118/trace-2.txt)

It is very helpful to provide a trace file if possible.
Please note that this file contains detailed information about the program.
**Procedure**
1. Run the command prompt.
2. Set the environment variable:
```cmd
set WINEDEBUG=+all,-snoop,-ldt,-fixup,-module,-global,-local,-disasm,-syslevel,-thunk

```
3.
```cmd
*old-executable-file* 2> trace.txt
```
4. Upload trace.txt here.
[trace.txt](https://github.com/otya128/winevdm/files/11217093/trace.txt)

**Comment by cracyc** [comment]
The installer won't work correctly unless WINVER=3.1 and IAmNotNT=1 are uncommented in otvdm.ini.  Running it from the cdrom doesn't work because there's a acegame.sav file on the cd that shouldn't be there which is read only and the game can't handle it.

**Comment by asc82** [comment]
Thank you so much, that fixed it 😊
Is there a compatibility table somewhere where I could have looked that up?

**Comment by cracyc** [comment]
There isn't.  In this case though if a win16 program has an win32 installshield installer then those changes are required to force the 16 bit installer to run instead.
