### ISSUE TITLE
Problem with CASMATE PRO

### ISSUE THREAD

**Issue by Icarus1977** [otya128/winevdm#1295]
Hello all! I am new to GITHUB and not a native english speaker, so bear with me...

I am trying to use a very old software called CASMATE on 64 bits and have been able to make it work thanks to WINEVDM( thank you!!! @otya128 ). 

I believe @DarkameMaster was able to work with this software.

Unfortunatly, I am unable to use the FONTS, giving an error when we try to write anything.

[trace.zip](https://github.com/otya128/winevdm/files/11436473/trace.zip)

I include a TRACE, that shows :

0dd4:fixme:gdi:BiDiShape16 stub (no prototype)
SReg Load (045a6e47): Segment is not a data segment or readable code segment.

When the fault occurs, and the program crashes.... I have tried every trick I could think of and are unable to solve this issue.

Do you have any ideas??

I can share a working copy of the program if anybody wants to try. (it is 80Mb uncompressed)

Thank you!

**Comment by cracyc** [comment]
Try https://ci.appveyor.com/project/otya128/winevdm/builds/47003599/job/jxtyhcg7i2u2is7n/artifacts

**Comment by Icarus1977** [comment]
Great!!! This issue has been resolved! I will continue testing.
Thank you @cracyc !!!
