### ISSUE TITLE
Debris32 installation program won't run, complains about Windows Version

### ISSUE THREAD

**Issue by Nicholas-Steel** [otya128/winevdm#1297]
OTVDM 2435 Artifact tested.

**Describe the bug**
The installation program for Debris32 does not work, it displays a message that I'm trying to run it on an incompatible version of Windows. Here is the shareware release of the game: https://archive.org/details/Debris_201610

**Expected behavior**
The installation program should open and allow me to install the game.

**Screenshots**
![image](https://github.com/otya128/winevdm/assets/11567846/645ac278-fedb-4295-942d-c8d22fb8aa79)

**Environment (please complete the following information):**
Windows 10, 22H2

I have tried the Windows 95, 98, ME, XP Compatibility settings for the EXE file.

**Comment by cracyc** [comment]
The link is to the 16bit version which installs and runs ok other than some annoying pauses at start.  The 32bit version from https://archive.org/details/deb3210 also installs fine.  It doesn't run but it's a win32 program and so not a winevdm problem.  Anyway the error is from the win32 portion of the installer so it's also not a winevdm problem.  You can try using elevationshim, see https://github.com/otya128/winevdm/issues/1259.

**Comment by Nicholas-Steel** [comment]
Oh damn, I didn't realize that the copy I was looking at was like that. I originally had the copy you linked to but Windows Defender deleted parts of it so I went hunting for a download again.

The copy you linked to does kinda work? I'd have to do some more frequent runs of the program but it seems to **_intermittently_** generate some kinda instruction error.

In any case, I guess this can more or less be marked as solved.

**Comment by cracyc** [comment]
> The copy you linked to does kinda work? I'd have to do some more frequent runs of the program but it seems to intermittently generate some kinda instruction error.

I got the error right at start and it closed immediately so I thought it didn't work at all.  Anyway, you can close the issue yourself.

**Comment by Nicholas-Steel** [comment]
@cracyc, are you able to do a quick test of something for me that relates to this game since you've seemingly run its installer on your PC? I would like you to try moving any file on your computer that is named "debris32.exe" to another location on your Windows PC, via left clicking and dragging the file to another folder.

In my case, this is erroneously resulting in a shortcut to the EXE file getting created in the destination instead of the EXE file being either moved or copied to the destination.

This behaviour seems to be limited to files named "debris32.exe", files with other file names will drag 'n' drop correctly. The issue persists through reboots of my PC.

**Comment by cracyc** [comment]
It does default to "create link".  For me programs in the reg key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths also do that.
