### ISSUE TITLE
CA-Simply Money ver. 1 won't run, error message

### ISSUE THREAD

**Issue by jimspoon** [otya128/winevdm#1298]
When I tried to run Simply Money 1.0 (CASMMAIN.EXE) by dropping on otvdm.exe, a window appears but then the following error message pops up - "CA-Simply Money has been tested only for use on Windows 3.0 and 3.1.  Contact customer service for an upgrade."  Could there be any way around this?  

I am attaching a trace file, see lines 571 through 593 especially.  I'm running Windows 11 Home version 22H2 build 22621.1702.
[otdvm-debug.txt](https://github.com/otya128/winevdm/files/11566862/otdvm-debug.txt)

**Comment by emendelson** [comment]
Edit otvdm.ini and uncomment two lines: `WINVER=3.1` and `IAmNotNT=1`.

**Comment by jimspoon** [comment]
thanks, this fixed the problem, and Simply Money is now working under OTVDM.
