### ISSUE TITLE
Wrong colors in the space ship window when playing CivNet

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#130]
This happens after playing the game for quite long time.

![default](https://user-images.githubusercontent.com/1271736/51376607-66869200-1b11-11e9-93cb-6172ff938f06.png)

**Comment by cracyc** [comment]
Civnet appears to use wing.  Are you using top-of-tree?  If not get it from https://ci.appveyor.com/project/otya128/winevdm/build/artifacts and try it as there was, since the last release, a fix for wing palettes.  If so then a save file would help.

**Comment by Anixx** [comment]
I am using the top of the tree. What is the save file?

**Comment by cracyc** [comment]
A save game far enough to see the problem directly.  They are .sav files in the game directory.

**Comment by Anixx** [comment]
This does not persist if to load a saved game. Also, it does not repeat if to close and reopen the space ship dialog.

**Comment by Anixx** [comment]
This is difficult to reproduce, so I am closing this now.
