### ISSUE TITLE
Theme Hospital Does not install

### ISSUE THREAD

**Issue by xFN10x** [otya128/winevdm#1302]
**Describe the bug**
Theme Hospital from OG CD dosent install.

**Expected behavior**
I expected for it to install normally

**Environment (please complete the following information):**
 - OS: 1703 (Windows 10 Home)
 - Version 2437

**Additional context**
The console says this,
version: 2437
a5b4:fixme:module:LoadModule_wine_implementation Strange error set by CreateProcess: 740
2130:err:file:RedirectDriveRoot c:\stopthis.now => C:\Users\sonic\Desktop\OTVDM-~1\c\stopthis.now
and then doesent install

Trace
[trace.txt](https://github.com/otya128/winevdm/files/11768805/trace.txt)

**Comment by xFN10x** [comment]
Now i get the error that it cant find isfixload.exe

**Comment by xFN10x** [comment]
Ok i got that to work, but now it says 
c444:err:file:RedirectDriveRoot c:\stopthis.now => C:\Users\sonic\Desktop\OTVDM-~1\c\stopthis.now
 then hangs

**Comment by xFN10x** [comment]
Also, this is being read off a cd.

**Comment by cracyc** [comment]
Do you get an elevation message?

**Comment by xFN10x** [comment]
No i dont get anything after it says that

**Comment by cracyc** [comment]
Post a new trace.

**Comment by xFN10x** [comment]
Now i cant run the command to make a trace

**Comment by xFN10x** [comment]
Oh it worked
