### ISSUE TITLE
No implementation for GDI.GETSYSTEMICONFONT, setting to 0xdeadbeef

### ISSUE THREAD

**Issue by heipiao233** [otya128/winevdm#1306]
Try the latest version first.
Go [here](https://ci.appveyor.com/project/otya128/winevdm) and click `Environment: THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1`-> `Artifacts 1`-> `zip` to download the latest version.

**Describe the bug**
"0e58:err:fixup:apply_relocations No implementation for GDI.GETSYSTEMICONFONT, setting to 0xdeadbeef"
When running progman.exe

**Expected behavior**
Run it successfully

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 11 22H2]
 - Version [e.g. version: 2441]

**Additional context**

It is very helpful to provide a trace file if possible.
Please note that this file contains detailed information about the program.
**Procedure**
1. Run the command prompt.
2. Set the environment variable:
```cmd
set WINEDEBUG=+all,-snoop,-ldt,-fixup,-module,-global,-local,-disasm,-syslevel,-thunk
```
3.
```cmd
*old-executable-file* 2> trace.txt

```
4. Upload trace.txt here.

[a.log](https://github.com/otya128/winevdm/files/12156842/a.log)

**Comment by cracyc** [comment]
Where did this version of progman.exe come from?  GETSYSTEMICONFONT isn't in windows 3.0 or windows 3.1 gdi.exe.  It's probably similar to SystemParametersInfo(SPI_GETICONTITLELOGFONT) but it's not possible to implement without knowing what parameters it expects.
