### ISSUE TITLE
Microlathe crashes when saving image

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#131]
Microlathe can be found here:

http://www.marshallarts.co.za/technical.htm
It crashes when clicking "save image" in the menu.

**Comment by cracyc** [comment]
I can't reproduce this crash, it works fine here.

**Comment by Anixx** [comment]
Well, it now works for me as well. What I did since is updated winewdm and installed it (the crash happened when winevdm was not installed).

**Comment by cracyc** [comment]
If it's working then you should close this issue.
