### ISSUE TITLE
Some software runs too fast

### ISSUE THREAD

**Issue by majistik12** [otya128/winevdm#1314]
Is there a way or a trick to slow down the runtime?

**Comment by cracyc** [comment]
What software has this problem?

**Comment by majistik12** [comment]
The game is Catz 1, runs too fast, please help me limit emulation speed so i can play it.
Thank you for your help.

**Comment by cracyc** [comment]
You can use https://github.com/tomysshadow/OldCPUSimulator to slow it down.  "OldCPUSimulator.exe -t 1000 -sw otvdm.exe CATZ.EXE" runs it at a reasonable speed on my computer.

**Comment by majistik12** [comment]
Thank you! Thank you! Thank you! Thank you! Thank you! Thank you! Thank you!

**Comment by cracyc** [comment]
If it works for you then you should close this issue.
