### ISSUE TITLE
Can't install otvdm on Windows 10 Home

### ISSUE THREAD

**Issue by Jolanxbl** [otya128/winevdm#1318]
**Describe the bug**
I click install, a command window briefly opens then closes.

**Expected behavior**
Some sort of installer dialog, progress message or at least an error.

**Screenshots**
None. The window opens then closes, no text, nothing.

**Environment (please complete the following information):**
 - OS: Windows 10 Home
 - Version 22H2

**Additional context**
I only learned about this program from a very long and technical (overly complicated) post, while trying to get just 1 game, Icebreaker (LooneyLabs), to run. It last worked in Windows XP or 98.
https://techcommunity.microsoft.com/t5/modern-work-app-consult-blog/running-16-bit-applications-on-windows-10-64-bit/ba-p/1671418

It is very helpful to provide a trace file if possible.
(Just navigating Github is confusing enough)

**Comment by cracyc** [comment]
You need to run otvdmw and select the program you want to run from the file dialog or right click installw.inf and select install then run the program normally.

**Comment by xybytz** [comment]
I am having a similar error. It has something to do with cmake. Even though I installed it, it still wont work.

**Comment by KoghaandSooga** [comment]
> I am having a similar error. It has something to do with cmake. Even though I installed it, it still wont work. FYI, if it was (maybe) 32 bit or 64 bit and worked on windows xp, right clock on that program, click properties, click compatability, and select the version.

 Too bad. Sounded like a cool project. Modern smokers dopers.

**Comment by Jolanxbl** [comment]
Unsubscribing from this thread as I used PCem instead. Worked right away and didn't have the confusion of github to deal with.

**Comment by KoghaandSooga** [comment]
> Unsubscribing from this thread as I used PCem instead. Worked right away and didn't have the confusion of github to deal with.

Github is VERY confusing.
