### ISSUE TITLE
Serial port support in OTVDM

### ISSUE THREAD

**Issue by FR-Theo** [otya128/winevdm#132]
Hello and thanks for this usefull project,

I tested otvdm-Debug983 on Win7 x64 with a proprietary 16bits software that uses the serial port, the software launches well but when establishing a serial connection, the application crashes :

_interrupt 0D #GP (12DF:344C) flags 3206 err 1394 call far ptr [77AAh]_

Is serial port support currently implemented in OTVDM?

I can provide logs if needed,
Thanks,

**Comment by cracyc** [comment]
I think a "WINEDEBUG=+relay,+int21" trace is needed because there are multiple ways to access the com ports in win31.  There the USER api which appears to be implemented, comm.drv which isn't and msdos which I'm not sure.

**Comment by kketzal** [comment]
> I think a "WINEDEBUG=+relay,+int21" trace is needed because there are multiple ways to access the com ports in win31. There the USER api which appears to be implemented, comm.drv which isn't and msdos which I'm not sure.

HI there:
How can I make a trace?? Which files I must modify to put "WINEDEBUG=+relay,+int21"??

Thanks in advance.

**Comment by cracyc** [comment]
https://github.com/otya128/winevdm/issues/40#issuecomment-420954520

**Comment by john11396** [comment]
4470:err:comm:writeth async write failed, error 995 this is what i've had relationed to this MF

**Comment by john11396** [comment]
4380:err:comm:writeth async write failed, error 995
4060:err:comm:writeth async write failed, error 995
05d4:err:comm:writeth async write failed, error 995
05d4:err:comm:writeth async write failed, error 995
05d4:err:comm:writeth async write failed, error 995
3d28:err:comm:writeth async write failed, error 995
3d28:err:comm:writeth async write failed, error 995
3d28:err:comm:writeth async write failed, error 995
1b9c:err:comm:writeth async write failed, error 995
3c48:err:comm:writeth async write failed, error 995
3c48:err:comm:writeth async write failed, error 995
4200:err:comm:writeth async write failed, error 995
4200:err:comm:writeth async write failed, error 995
4200:err:comm:writeth async write failed, error 995
4254:err:comm:writeth async write failed, error 995
4254:err:comm:writeth async write failed, error 995
2ad0:fixme:comm:EscapeCommFunction16 no cid=0 found!
2ad0:fixme:comm:CloseComm16 no cid=0 found!
