### ISSUE TITLE
Keyboard latency when using an old game

### ISSUE THREAD

**Issue by stabnslice** [otya128/winevdm#1329]
I am experiencing keyboard delay issues whenever using an old game. Specifically, when using Mordor: Depth of Dejenol. 

The game work flawlessly otherwise. It seems specific to the arrow keys interacting with the map. It is only able to register 1 key every fraction of a second so it feels very slow to response. 

Any ideas on this issue?

**Comment by cracyc** [comment]
Seems okay to me.  Are you using the latest release?

**Comment by stabnslice** [comment]
I am (0.90). Are you getting immediate reaction with the arrow keys. Mine definitely delays a fraction of a second after just one or two directional movements. 
I tried Mordor using Win 3.1 with dosbox and it is working great.

**Comment by cracyc** [comment]
If you move with the arrow keys on the dungeon window do you have the problem too or is it only the map window?  Which version of windows are you using?  A trace might help too.

**Comment by stabnslice** [comment]
Looks like it is the same issue regardless of using the Dungeon arrows or the Keyboard arrows. 

Windows 11 version 10.0.22631

I'll work on getting a trace for you.

**Comment by stabnslice** [comment]
Okay, I figured out the issue. I've been using the otvdmw that was installed on my desktop folder. As soon as I moved it to the same location as Mordor (directly on the C folder, it worked a lot better. Still a bit off but 95% reaction with the keyboard now.

**Comment by cracyc** [comment]
https://github.com/otya128/winevdm/pull/1331 should improve key press response.
