### ISSUE TITLE
Supporting applications that use WINMEM32

### ISSUE THREAD

**Issue by roytam1** [otya128/winevdm#1341]
[KB73679](https://www.betaarchive.com/wiki/index.php/Microsoft_KB_Archive/73679) describes how 16bit applications to use it to preform 32bit operations in NE format, which of course not supported by 64bit OS.

and there are applications really use it for such purpose: https://virtuallyfun.com/2023/12/08/bsd-on-windows-things-i-wish-i-knew-existed/

**Comment by neozeed** [comment]
```0bf4:fixme:int31:DOSVM_Int31Handler Get Processor Exception Handler Vector (0x00)
0bf4:fixme:int31:DOSVM_Int31Handler Get Processor Exception Handler Vector (0x04)
0bf4:fixme:int31:DOSVM_Int31Handler Get Processor Exception Handler Vector (0x06)
0bf4:fixme:int31:DOSVM_Int31Handler Get Processor Exception Handler Vector (0x07)
0bf4:fixme:int31:DOSVM_Int31Handler Get Processor Exception Handler Vector (0x09)
0bf4:fixme:int31:DOSVM_Int31Handler Get Processor Exception Handler Vector (0x0c)
0bf4:fixme:int31:DOSVM_Int31Handler Get Processor Exception Handler Vector (0x0d)
0bf4:fixme:int31:DOSVM_Int31Handler Get Processor Exception Handler Vector (0x10)
0bf4:fixme:int31:DOSVM_Int31Handler Set Processor Exception Handler Vector (0x00)
0bf4:fixme:int31:DOSVM_Int31Handler Set Processor Exception Handler Vector (0x04)
0bf4:fixme:int31:DOSVM_Int31Handler Set Processor Exception Handler Vector (0x06)
0bf4:fixme:int31:DOSVM_Int31Handler Set Processor Exception Handler Vector (0x07)
0bf4:fixme:int31:DOSVM_Int31Handler Set Processor Exception Handler Vector (0x09)
0bf4:fixme:int31:DOSVM_Int31Handler Set Processor Exception Handler Vector (0x0c)
0bf4:fixme:int31:DOSVM_Int31Handler Set Processor Exception Handler Vector (0x0d)
0bf4:fixme:int31:DOSVM_Int31Handler Set Processor Exception Handler Vector (0x10)
0bf4:fixme:int31:DOSVM_Int31Handler allocate descriptor (0x0004), stub!```

Before it goes off the rails, this is from the output log.

**Comment by roytam1** [comment]
original author gave out some details about its internal design: https://github.com/h2oota/emacs-win64-msvc/issues/1#issuecomment-1849116052

**Comment by cracyc** [comment]
So it now runs programs but it fails to run scripts because the files are being closed by the new task.  File handles are currently global but need to be made per-task the way dos does it so a task can't close handles that were opened by a different program.

**Comment by cracyc** [comment]
It works now, how reliably I don't know but it can be installed and run basic programs.

![Screenshot 2023-12-22 211438](https://github.com/otya128/winevdm/assets/9255333/98f54383-8020-4c96-8f9c-ef173af8a5c1)

**Comment by neozeed** [comment]
@cracyc super cool, I was able to use your update to get apache online!  I couldn't think of anything immediately that interesting so it's online at : [bow.superglobalmegacorp.com](https://bow.superglobalmegacorp.com/).  I notice that on NTFS it uses junctions as symlinks which really angers xcopy.  I think me substing the 'root' disk also makes it unhappy, so I'm trying to use a vhd mounted under windows 10 with NTFS. 

For some reason running ls of all things bombs the system, it's not that stable, but it's also nice to see hack work as well.
![hack on windows 11](https://github.com/otya128/winevdm/assets/9031439/395eb1a6-677e-4c9b-a4ff-5f32cadc9910)

**Comment by neozeed** [comment]
Not sure it's worth mentioning but installing to a U: ntfs disk..

/dfs/c/win16app/bow/bsdsetup.sh: 67: Syntax error: end of file unexpected (expecting "}")

I get this weird error.

`
C:\disk1>\WineVDM\otvdm.exe setup
version: 2472
6e20:fixme:int31:DOSVM_Int31Handler Get Processor Exception Handler Vector (0x00)
6e20:fixme:int31:DOSVM_Int31Handler Get Processor Exception Handler Vector (0x04)
6e20:fixme:int31:DOSVM_Int31Handler Get Processor Exception Handler Vector (0x06)
6e20:fixme:int31:DOSVM_Int31Handler Get Processor Exception Handler Vector (0x07)
6e20:fixme:int31:DOSVM_Int31Handler Get Processor Exception Handler Vector (0x09)
6e20:fixme:int31:DOSVM_Int31Handler Get Processor Exception Handler Vector (0x0c)
6e20:fixme:int31:DOSVM_Int31Handler Get Processor Exception Handler Vector (0x0d)
6e20:fixme:int31:DOSVM_Int31Handler Get Processor Exception Handler Vector (0x10)
6e20:fixme:int31:DOSVM_Int31Handler Set Processor Exception Handler Vector (0x00)
6e20:fixme:int31:DOSVM_Int31Handler Set Processor Exception Handler Vector (0x04)
6e20:fixme:int31:DOSVM_Int31Handler Set Processor Exception Handler Vector (0x06)
6e20:fixme:int31:DOSVM_Int31Handler Set Processor Exception Handler Vector (0x07)
6e20:fixme:int31:DOSVM_Int31Handler Set Processor Exception Handler Vector (0x09)
6e20:fixme:int31:DOSVM_Int31Handler Set Processor Exception Handler Vector (0x0c)
6e20:fixme:int31:DOSVM_Int31Handler Set Processor Exception Handler Vector (0x0d)
6e20:fixme:int31:DOSVM_Int31Handler Set Processor Exception Handler Vector (0x10)
=====dump all modules=====
Module Flags Name Flag
 1567   030a    BOWINETX    MULTIPLEDATA | FRAMEBUF | CONSOLE | GUI
 147f   8309    BOWJCONV    SINGLEDATA | FRAMEBUF | CONSOLE | GUI | LIBMODULE
 142f   8021    WINNLS      SINGLEDATA | BUILTIN | LIBMODULE
 1457   8021    COMMDLG     SINGLEDATA | BUILTIN | LIBMODULE
 141f   8309    BOWPAD      SINGLEDATA | FRAMEBUF | CONSOLE | GUI | LIBMODULE
 139f   030a    BOWIOSX     MULTIPLEDATA | FRAMEBUF | CONSOLE | GUI
 138f   8309    BOWREGEX    SINGLEDATA | FRAMEBUF | CONSOLE | GUI | LIBMODULE
 1357   8309    BOWIOS      SINGLEDATA | FRAMEBUF | CONSOLE | GUI | LIBMODULE
 131f   8309    BOWKERN     SINGLEDATA | FRAMEBUF | CONSOLE | GUI | LIBMODULE
 12a7   030a    BOWPS       MULTIPLEDATA | FRAMEBUF | CONSOLE | GUI
 125f   8301    WINMEM32    SINGLEDATA | FRAMEBUF | CONSOLE | GUI | LIBMODULE
 1227   8021    VER         SINGLEDATA | BUILTIN | LIBMODULE
 1877   8021    CTL3D       SINGLEDATA | BUILTIN | LIBMODULE
 185f   8021    TOOLHELP    SINGLEDATA | BUILTIN | LIBMODULE
 119f   8021    SHELL       SINGLEDATA | BUILTIN | LIBMODULE
 1187   8021    SOUND       SINGLEDATA | BUILTIN | LIBMODULE
 116f   8021    MMSYSTEM    SINGLEDATA | BUILTIN | LIBMODULE
 1157   8021    MOUSE       SINGLEDATA | BUILTIN | LIBMODULE
 113f   8021    KEYBOARD    SINGLEDATA | BUILTIN | LIBMODULE
 1127   8021    DISPLAY     SINGLEDATA | BUILTIN | LIBMODULE
 110f   8021    USER        SINGLEDATA | BUILTIN | LIBMODULE
 10f7   8021    GDI         SINGLEDATA | BUILTIN | LIBMODULE
 10cf   8021    TIMER       SINGLEDATA | BUILTIN | LIBMODULE
 10b7   8021    COMM        SINGLEDATA | BUILTIN | LIBMODULE
 109f   8021    SYSTEM      SINGLEDATA | BUILTIN | LIBMODULE
 1007   8021    KERNEL      SINGLEDATA | BUILTIN | LIBMODULE
=====dump all modules=====
00B10000-00B19000 otvdm.exe
777E0000-77991000 ntdll.dll
76AA0000-76B90000 KERNEL32.DLL
75D50000-75FC4000 KERNELBASE.dll
76030000-76142000 ucrtbase.dll
75390000-753A5000 VCRUNTIME140.dll
6E4D0000-6E50A000 libwine.dll
686C0000-6873C000 krnl386.exe16
76770000-767ED000 ADVAPI32.dll
76150000-76214000 msvcrt.dll
617C0000-61832000 DSOUND.dll
755D0000-75652000 sechost.dll
75660000-758DD000 combase.dll
76840000-768FA000 RPCRT4.dll
733B0000-733F5000 powrprof.dll
759E0000-75B88000 USER32.dll
61700000-61799000 ResampleDmo.DLL
76DB0000-76DCA000 win32u.dll
76900000-7699C000 OLEAUT32.dll
617A0000-617BF000 winmmbase.dll
777A0000-777C3000 GDI32.dll
76D30000-76DA9000 msvcp_win.dll
776A0000-77782000 gdi32full.dll
76F30000-775C7000 SHELL32.dll
616F0000-616F9000 msdmo.dll
767F0000-7683B000 SHLWAPI.dll
60890000-6090F000 WINSPOOL.DRV
775D0000-77691000 shcore.dll
733A0000-733AE000 UMPDC.dll
76C80000-76CA5000 IMM32.DLL
73690000-736B9000 ntmarta.dll
6E900000-6E908000 system.drv16
6E8F0000-6E8F8000 comm.drv16
6E8E0000-6E8E8000 timer.drv16
68630000-686BC000 vm86.dll
76D10000-76D2B000 imagehlp.dll
6E570000-6E593000 gdi.exe16
68470000-68621000 user.exe16
74B80000-74B88000 VERSION.dll
74170000-74189000 MPR.dll
73320000-7339F000 UxTheme.dll
700A0000-70199000 AudioDevProps2.dll
75C00000-75D50000 ole32.dll
75FD0000-7602F000 WS2_32.dll
701D0000-70262000 NahimicOSD.dll
70410000-7042B000 ProductInfo.dll
758E0000-759DC000 MSCTF.dll
73F00000-73F13000 kernel.appcore.dll
76C00000-76C62000 bcryptPrimitives.dll
6E890000-6E899000 display.drv16
6E4C0000-6E4C8000 keyboard.drv16
6DCA0000-6DCA8000 mouse.drv16
6DC80000-6DC9A000 mmsystem.dll16
74190000-741C1000 WINMM.dll
6DC70000-6DC79000 sound.drv16
6DC60000-6DC6A000 shell.dll16
73400000-735D6000 dbghelp.dll
6D8F0000-6D9E9000 textinputframework.dll
70CB0000-70D7D000 CoreMessaging.dll
6D650000-6D8E1000 CoreUIComponents.dll
736E0000-737A7000 wintypes.dll
73240000-7324B000 CRYPTBASE.DLL
66EB0000-66F45000 TextShaping.dll
68440000-68461000 CABINET.DLL
73810000-73EFC000 windows.storage.dll
72550000-72617000 PROPSYS.dll
76A10000-76A92000 clbcatq.dll
660D0000-66150000 Windows.FileExplorer.Common.dll
736C0000-736DD000 profapi.dll
73190000-731CD000 CFGMGR32.dll
6E460000-6E4BF000 Windows.StateRepositoryPS.dll
63930000-63960000 windows.staterepositoryclient.dll
63910000-6392F000 edputil.dll
634E0000-63682000 urlmon.dll
6D9F0000-6DC28000 iertutil.dll
634B0000-634CD000 srvcli.dll
634D0000-634DB000 netutils.dll
753B0000-75456000 apphelp.dll
63480000-634A7000 cldapi.dll
73630000-73655000 SspiCli.dll
58700000-58785000 sxs.dll
60780000-60795000 NetworkExplorer.dll
607F0000-607FB000 LINKINFO.dll
60700000-60778000 ntshrui.dll
606F0000-606FE000 cscapi.dll
6DC40000-6DC49000 toolhelp.dll16
68430000-68438000 ctl3d.dll16
68420000-68428000 ctl3dv2.dll16
6DC50000-6DC59000 ver.dll16
03810000-03813000 LZ32.dll
68400000-6841C000 commdlg.dll16
76E70000-76F22000 COMDLG32.dll
57110000-571A1000 COMCTL32.dll
683F0000-683F9000 winnls.dll16
25: vm86.dll!load_x87function+0x7161 - 0x6867f7b0 0x68686911 (null):0
24: ntdll.dll!LdrSetDllManifestProber+0x11f - 0x778504c0 0x778505df (null):0
23: ntdll.dll!RtlUnwind+0x1c7 - 0x7784cb40 0x7784cd07 (null):0
22: ntdll.dll!KiUserExceptionDispatcher+0x26 - 0x77858d10 0x77858d36 (null):0

21: !KiUserExceptionDispatcher+0xfffffffff63ea237 - 0x77858d10 0x6dc42f47 (null):0

20: krnl386.exe16!LoadModule16+0x389 - 0x686f4260 0x686f45e9 (null):0
19: krnl386.exe16!LoadLibrary16+0x2f3 - 0x686f4a10 0x686f4d03 (null):0
18: krnl386.exe16!RestoreThunkLock+0xaa5 - 0x68700110 0x68700bb5 (null):0
17: krnl386.exe16!DOSVM_outport+0x961 - 0x686ea930 0x686eb291 (null):0
16: krnl386.exe16!GetPtr16+0x525 - 0x6870f250 0x6870f775 (null):0
15: krnl386.exe16!GetPtr16+0x602 - 0x6870f250 0x6870f852 (null):0
14: ntdll.dll!RtlIpv6AddressToStringA+0x136 - 0x77856580 0x778566b6 (null):0
13: ntdll.dll!RtlDeactivateActivationContextUnsafeFast+0x13e - 0x77826de0 0x77826f1e (null):0
12: ntdll.dll!LdrShutdownThread+0x1de - 0x778265d0 0x778267ae (null):0
11: ntdll.dll!RtlExitUserThread+0x4c - 0x7784e580 0x7784e5cc (null):0
10: krnl386.exe16!GlobalMapInternal+0xe4e6 - 0x686d2440 0x686e0926 (null):0
9: krnl386.exe16!RegFlushKey16+0x744 - 0x686f9610 0x686f9d54 (null):0
8: krnl386.exe16!vm_debug_get_entry_point+0x803 - 0x686f9db0 0x686fa5b3 (null):0
7: vm86.dll!disassemble_debug+0x11e4 - 0x68687170 0x68688354 (null):0
6: vm86.dll!wine_call_to_16_regs_vm86+0x53 - 0x68686e40 0x68686e93 (null):0
5: krnl386.exe16!K32WOWCallback16Ex+0x459 - 0x6870e100 0x6870e559 (null):0
4: krnl386.exe16!LoadModule16+0x7a3 - 0x686f4260 0x686f4a03 (null):0
3: krnl386.exe16!RestoreThunkLock+0xfcb - 0x68700110 0x687010db (null):0
2: KERNEL32.DLL!BaseThreadInitThunk+0x19 - 0x76ab7b90 0x76ab7ba9 (null):0
1: ntdll.dll!RtlInitializeExceptionChain+0x6b - 0x7784bcc0 0x7784bd2b (null):0
0: ntdll.dll!RtlClearBits+0xbf - 0x7784bbf0 0x7784bcaf (null):0
cs:ip=1117:0ed2 bp=48f8                 args(0000,0080,12c7,0000,12ef,0000,1aba,0001,4910,4b58)
cs:ip=0000:1c4c bp=4907                 args(4910,4b58,4960,0000,12ef,0000,0000,0458,102f,0000)
cs:ip=0001:1aba bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)
cs:ip=0005:0000 bp=0001                 args(4930,0000,09ae,4918,4918,6f42,5077,5773,6c43,7361)

address=753938E9
access address=FFFFFFFA
VM context
EAX:12EF48E6,ECX:48C2,EDX:12DF12CF,EBX:4B64
ESP:4884,EBP:48F8,ESI:00E9,EDI:4B51
ES:0000,CS:1117,SS:12EF,DS:12EF,FS:0000,GS:0000
IP:0ED2, address:02EF995A
EFLAGS:00003246

SEGV
`

**Comment by cracyc** [comment]
I installed it using subst and it worked fine although I didn't stress it hard.  A full trace for the crash would help although it is in win32 so the exact location of the crash can be found by running it in windbg.

**Comment by otya128** [comment]
Version 2472 does not include #1350. Try <https://ci.appveyor.com/project/otya128/winevdm/builds/48820555/job/0dm7kwy3wfntj7qx/artifacts> .
