### ISSUE TITLE
WinHLP32 in otvdm-for-old-windows-v0.9.0.zip doesn't run in ReactOS

### ISSUE THREAD

**Issue by roytam1** [otya128/winevdm#1344]
**Describe the bug**
`K32GetModuleFileNameExW` is not available in ReactOS.

**Expected behavior**
It should be able to run on ReactOS.

**Screenshots**
![image](https://github.com/otya128/winevdm/assets/1192577/3a8bea81-bf67-4f39-8b4e-2a080e3f582e)

**Environment (please complete the following information):**
 - OS: ReactOS
 - Version 0.4.15git-head

**Additional context**
I wonder if it is compiled with `PSAPI_VERSION` > 1.

**Comment by kristibektashi** [comment]
This should be reported to ReactOS as well

**Comment by roytam1** [comment]
> This should be reported to ReactOS as well

no, ReactOS is now in WINVER=0x502 level, which has no K32* API exported, just like XP(x64) and Windows Server 2003.

**Comment by learn-more** [comment]
Compiling with `-DPSAPI_VERSION=1` should fix this.

**Comment by roytam1** [comment]
> Compiling with `-DPSAPI_VERSION=1` should fix this.

yes thats what my PR does.
