### ISSUE TITLE
winhlp32 crashes when openning freepy.hlp from command-line

### ISSUE THREAD

**Issue by roytam1** [otya128/winevdm#1346]
**Describe the bug**
It crashes when openning freepy.hlp from command-line or DnD to winhlp32.exe (I replaced ROS winhlp32.exe with otvdm's one here):

```
Unhandled exception
ExceptionCode:    c0000005
Faulting Address: 00000000
CS:EIP 1b:40d1b3
DS 23 ES 23 FS 3b GS 0
EAX: 00000000   EBX: 00238120   ECX: 00000001
EDX: 00000002   EBP: 0022fe68   ESI: 0000001e   ESP: 0022fdb0
EDI: 00257560   EFLAGS: 00000202
Address:
<winhlp32.exe:d1b3> (C:\ReactOS\winhlp32.exe@400000)
Frames:
<winhlp32.exe:11bf9> (C:\ReactOS\winhlp32.exe@400000)
<winhlp32.exe:14a9d> (C:\ReactOS\winhlp32.exe@400000)
<winhlp32.exe:1363> (C:\ReactOS\winhlp32.exe@400000)
<kernel32.dll:11cde> (C:\ReactOS\system32\kernel32.dll@7c620000)
```

**Expected behavior**
It should open freepy.hlp without crashing.

**Screenshots**
![image](https://github.com/otya128/winevdm/assets/1192577/8e150281-6dbf-42ac-8c4a-469717c1a85a)

**Environment (please complete the following information):**
 - OS: ReactOS
 - Version 0.4.15-git-head

**Additional context**
If running winhlp32.exe and open freepy.hlp from its file dialog, it doesn't crash.

tested build from: https://ci.appveyor.com/project/otya128/winevdm/builds/48749573/job/f8st5b5j4envaplf
[freepy.hlp.zip](https://github.com/otya128/winevdm/files/13663084/freepy.hlp.zip)

**Comment by otya128** [comment]
This also reproduces on Windows.
It seems that not including a title in the hlp file causes a null dereference in WINHELP_GetWindowInfo.

**Comment by roytam1** [comment]
> It seems that not including a title in the hlp file causes a null dereference in WINHELP_GetWindowInfo.

I wonder if my fix in #1347 is a proper one?

**Comment by roytam1** [comment]
> It seems that not including a title in the hlp file causes a null dereference in WINHELP_GetWindowInfo.

checked ROS' winhlp32, it can open without crashing and the line I changed is intact in ROS version. so the root of problem may be in elsewhere?
and BTW after I changed that line, it doesn't show default title.
![image](https://github.com/otya128/winevdm/assets/1192577/133e476c-fd79-4cd9-a7d2-17a41684340e)

ROS version looks more sane:
![image](https://github.com/otya128/winevdm/assets/1192577/7aa5c5cd-f544-4f76-b9f1-98532135138a)

(I think this could be ROS problems)

**Comment by cracyc** [comment]
Reactos allocates space for the title even if the file doesn't have one (https://github.com/reactos/reactos/blob/master/base/applications/winhlp32/hlpfile.c#L2158) so it's just a different way of fixing it.

>BTW after I changed that line, it doesn't show default title.

Maybe lpszTitle should be filled with the default caption rather than just checking for null.

**Comment by otya128** [comment]
This seems to be a regression caused by adcbee17e906d5c079b3e279feb8c70ef7f37e01.
