### ISSUE TITLE
Choose folder and filename with Microsoft Print to PDF printer

### ISSUE THREAD

**Issue by fabiovannini** [otya128/winevdm#1348]
**Describe the bug**
Running Autocad LT with winevdm, and choosing "Microsoft Print to PDF" as the printer, a simple input field is displayed in which to insert the destination file instead of the standard Windows mask in which the folder and file name can be selected.

The save system still works fine, it's just a user interface issue

**Expected behavior**
The classic file saving mask should be displayed, as shown in the last screenshot (notepad 64 bit+ microsoft print to pdf)

**Screenshots**
1) Choosing Microsoft Print To PDF printer in Autocad LT
![1](https://github.com/otya128/winevdm/assets/16029886/f36893c5-ffc0-4454-96a0-9837cc6db72f)
2) A simple input field is displayed asking for the full path to the destination file
![2](https://github.com/otya128/winevdm/assets/16029886/e202ef54-0384-43dd-ae38-f81938ac9388)
3) This is what I expect, the screenshot refers to the 64 bit notepad of my windows installation and the Microsoft Print To Pdf printer
![3](https://github.com/otya128/winevdm/assets/16029886/b630dca6-3fb6-4471-b1f6-99f5f21ccdba)

**Environment**
 - OS: Windows 10 1903
 - Version: winevdm 0.90 Release

**Notes**
I don't know if it's fixable but it would be very convenient for me

**Comment by cracyc** [comment]
You need to uncomment EnableVisualStyle=1 and DisableAero=0 because windows will not allow the IFileDialog dialogs if visual styles are disabled.  This may cause other problems though as win16 programs sometimes misbehave with visual styles enabled.

**Comment by fabiovannini** [comment]
It works! Thank you for support :-)
