### ISSUE TITLE
Kid Pix for Windows (1992) crashes when clicking the Delicias menu after changing to Spanish language

### ISSUE THREAD

**Issue by CSmeds99** [otya128/winevdm#1349]
WineVDM build 2469

After choosing Switch to Spanish from the Goodies menu and then clicking the Spanish Delicias menu, causes Kid Pix to crash with several error messages.

The Spanish Delicias menu should display without a crash like in Windows XP Professional 32-bit NTVDM.

![Screenshot 2023-12-21 135816](https://github.com/otya128/winevdm/assets/99499673/a5e44fc7-e198-44ef-b95c-81bbc7698c88)
![Screenshot 2023-12-21 135836](https://github.com/otya128/winevdm/assets/99499673/0f630fdd-5151-45ad-9789-0892f2e9f19a)

Windows 11 Pro 23H2
OS Build 22631.2861

Kid Pix for Windows URL:
https://archive.org/download/KID_PIX_WIN/KID_PIX.zip

Trace:
[TRACE.TXT](https://github.com/otya128/winevdm/files/13745543/TRACE.TXT)

**Comment by cracyc** [comment]
This is a color depth issue and 256 color mode won't fix it.  LoadImage16 always creates a bitmap at the screen color depth and the resulting image int 32bpp mode is too large and trashes memory but only in spanish mode due to the height of the menu items.  There may not be a reliable way to fix it.

**Comment by CSmeds99** [comment]
I tried changing the color settings to 256 colors under compatibility mode. However on my Pentium IV Windows XP machine, Windows XP goes to 256 colors when I launch Kid Pix and the program runs fine. When I exit Kid Pix, Windows XP goes back to its normal color settings.

**Comment by cracyc** [comment]
It does crash the same way in winxp in 32bpp mode is it's not a winevdm bug.  That said a possible fix would be to make LoadImage16 create a dib instead of ddb in compatibility mode (LR_CREATEDIBSECTION doesn't work as it creates a 32bpp dib).
