### ISSUE TITLE
fool 16bit programs that they're really running in an environment without 32bit

### ISSUE THREAD

**Issue by roytam1** [otya128/winevdm#1352]
some programs like acrobat reader 3.01 16bit will not allow to run when 32bit host is detected, and showing message box like:

````
---------------------------
Acrobat
---------------------------
This 16-bit version of Acrobat will not run in 32-bit environments, please run the 32-bit version.
---------------------------
OK   
---------------------------
````

I wonder if we can fool it to run in otvdm?

**Comment by otya128** [comment]
Try setting the following in otvdm.ini:
```ini
WINVER=3.1
IAmNotNT=1
```

**Comment by roytam1** [comment]
> Try setting the following in otvdm.ini:
> 
> ```ini
> WINVER=3.1
> IAmNotNT=1
> ```

it works! thanks!
