### ISSUE TITLE
Borland Database installation fails

### ISSUE THREAD

**Issue by emendelson** [otya128/winevdm#1354]
Try the latest version first.
Go [here](https://ci.appveyor.com/project/otya128/winevdm) and click `Environment: THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1`-> `Artifacts 1`-> `zip` to download the latest version.

**Describe the bug**
I have a Windows 3.x-era application (which I can't name on the forum, but which I can send privately if needed) that tries to install the Borland Database, but fails with this error:
![Screenshot 2024-01-11 131638](https://github.com/otya128/winevdm/assets/5208505/1bc25740-87ef-4777-ab5f-e589ffa1a7c3)

**Expected behavior**
The installation should not fail.

**Environment (please complete the following information):**
OS: Windows 11
Version: 10.0.22631.3007

**Additional context**
The same CD installs in Win 3.11 running under DOSBox.

**Upload trace.txt here**

The installer installs its program and then runs the Borland Database installer. When I tried to run a trace, the installer crashed without an error message when it started to run the BDSETUP.EXE installer alone, for a trace, it wouldn't start at all. For what it's worth, here's the trace that ends by simply crashing:

[trace.zip](https://github.com/otya128/winevdm/files/13907069/trace.zip)

**Comment by cracyc** [comment]
What happens if you run bdsetup.exe directly?  If it fails can you provide just that since it's a redistributable?

**Comment by emendelson** [comment]
Here's the trace from BDSETUP.exe. 

[trace.txt](https://github.com/otya128/winevdm/files/13914690/trace.txt)

I think this ZIP contains all the relevant files; if not, I'll try again:

[BAMGR16.zip](https://github.com/otya128/winevdm/files/13914698/BAMGR16.zip)

**Comment by cracyc** [comment]
The borland 4.5 installer doesn't work either despite it definitely working in the past.  I checked with version 0.8.1 and it doesn't work there either but it does work in a newer version of winevdm in Windows 7.  I suspect Microsoft has broken it in Windows 11 with their progressive removal of (from their perspective) dead ntvdm compatibility from user32.  Windows isn't fixing up the lpCreateParams parameter of CREATESTRUCTA anymore.

**Comment by emendelson** [comment]
I don't envy you the kind of work that will go into this. I hope you can guess how deeply grateful so many of us are for what you're doing. Thank you. At least I hope this fix may be useful for other programs.

**Comment by emendelson** [comment]
The fix works. Amazing that you fixed it so quickly. Thank you.
