### ISSUE TITLE
Avalon does not start

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#136]
The game can be found here:
http://www.completelyfreesoftware.com/software/avalon.exe

After unpacking the self-extracting archive, start avalon.exe. It is not recognized as Win16 file type. If to run it explocitely with otvdm, it segfaults. Other executables, enddemo.exe and introdemo.exe also do not start.

**Comment by cracyc** [comment]
Those are DOS programs.  Use DOSBox.
