### ISSUE TITLE
help with compiler

### ISSUE THREAD

**Issue by girl16bit** [otya128/winevdm#1360]
Hi

I want to learn this book but I have no idea what compiler I need and if I can install it using winevdm
Somewhere I read about visual studio but what version I need?

https://github.com/yeokm1/programming-win31

Anybody can help?

**Comment by cracyc** [comment]
It says you need MSC 7 or Borland C++ 3.1.  MSVC 1.5 or Borland C++ 4.5 would probably also work.

**Comment by girl16bit** [comment]
Which of those should run in winevdm you think?

If I install them using winevdm, will the installer of the compiler also write files to my windows 10 folder or is everything written ONLY to the included windows folder of winevdm? I don't want old files in my windows 10 folder.

Thanks !

**Comment by cracyc** [comment]
By default winevdm will not place any files in the real windows/system dir.

> Which of those should run in winevdm you think?

I've tried MSVC 1.5 and Borland C 4.5 and both work well enough to compile programs.

**Comment by girl16bit** [comment]
> By default winevdm will not place any files in the real windows/system dir.

So it will never do this or only if you enable a setting? Can you tell me what setting it is, so I make sure it's never enabled?

**Comment by girl16bit** [comment]
In the readme: Run "install" shortcut or right-click on install.inf and select "Install"

Is this required to do or can I just drag and drop exe files without installing install.inf? What is this install.inf needed for?

**Comment by emendelson** [comment]
Look at the contents of the file, and you'll see exactly what it does:

https://github.com/otya128/winevdm/blob/master/install.inf

Or, to install it show that the console doesn't appear every time it runs:

https://github.com/otya128/winevdm/blob/master/installw.inf

**Comment by girl16bit** [comment]
> As for whether you can drag and drop files - why not try it and see what happens? It can't do any harm.

Seems to work without installing any .inf file too.
