### ISSUE TITLE
error during visual c++ 1.52 installation

### ISSUE THREAD

**Issue by girl16bit** [otya128/winevdm#1363]
**Describe the bug**
At the end of the installation, I get an error

**Expected behavior**
Not sure what this error means

**Screenshots**
![afbeelding](https://github.com/otya128/winevdm/assets/156975202/7ce0b00e-5860-48ee-8c7f-95007c8ab95b)

In the command window is this:
![afbeelding](https://github.com/otya128/winevdm/assets/156975202/dcd96ff5-bea3-4c1e-823c-53392ee31563)

**Environment (please complete the following information):**
Windows 10 22H2

**Comment by girl16bit** [comment]
- How to uninstall a program installed using winevdm?
- I saw shortcuts in the windows 10 start menu are made. Is there a way that winevdm does not make start menu shortcuts?

**Comment by girl16bit** [comment]
Can I safely do this, because it are INI files of winevdm that are changed, correct?

![afbeelding](https://github.com/otya128/winevdm/assets/156975202/1c12c053-0e2d-4d88-b37d-82d63ebd02f9)

**Comment by cracyc** [comment]
> Not sure what this error means

That means that the pathname for the start menu link was unparseable.  It's harmless.



> How to uninstall a program installed using winevdm?

You delete it manually unless the installed program has an uninstaller which few windows 3.1 programs do.



> I saw shortcuts in the windows 10 start menu are made. Is there a setting that winevdm does not make start menu shortcuts?

If the installer creates a start menu link winevdm has no setting to prevent that.



> Can I safely do this, because it are INI files of winevdm that are changed, correct? (or are it files of my windows 10 that are changed?)

This will change the system.ini and win.ini in the winevdm windows/system dir.  Your windows 10 files won't be modified.

**Comment by girl16bit** [comment]
Thanks! Everything is working :)
