### ISSUE TITLE
open watcom installer missing progress bar

### ISSUE THREAD

**Issue by girl16bit** [otya128/winevdm#1365]
**Describe the bug**
When installing open watcom for win 16 bit, the progress bar during installing is missing. only % text is shown

https://github.com/open-watcom/open-watcom-v2/releases/download/Current-build/open-watcom-2_0-c-win16.exe

**Expected behavior**
I think there should be a progress bar since there is a box in which it should appear

**Screenshots**

![afbeelding](https://github.com/otya128/winevdm/assets/156975202/a6d2c545-beeb-4cef-81d0-75cde9bb66c1)

**Environment (please complete the following information):**
Windows 10 22H2

**Comment by cracyc** [comment]
The compiler that comes with the win16 watcom is a dos program.  You can run it in dosbox or msdos-player but I don't recommend that.  Instead get the 64bit watcom and install the win16 compiler and win31 target support then it'll compile and run file.  Or get ms quickc which also works.

**Comment by cracyc** [comment]
> So you mean the 16 bit EXE (compiled by watcom) will run by using winevdm? Will it run automatically then by watcom and can I also debug it using winevdm inside the watcom debugger? I'm not sure what you mean. Because i'm looking for a debugger that works.
> I think I will need a virtual machine with old windows version because I tried many things and nothing works :(

A win16 exe not a 16bit dos exe.  I haven't used the watcom debugger for symbolic debugging but the borland ide debugger does work.
