### ISSUE TITLE
automatically run 16bit programs by other software

### ISSUE THREAD

**Issue by ghost** [otya128/winevdm#1367]
Hi

This is not a bug or issue with winevdm but I try to figure out how I can let other programs, that run compiled EXE files (like compiler), use winevdm to run the EXE.

So I installed open watcom, can compile a 16 bit windows EXE but open watcom doesn't run the EXE in winevdm. I can however run it using winevdm manually.

Is there a way I can configure winevdm so another program like open watcom runs the compiled EXE inside winevdm automatically?

**Comment by emendelson** [comment]
This may or not be the answer, but you'll only use two minutes by trying.

The problem may be that watcom is trying run the EXE with Windows' cmd.exe. You may be able to fix that by downloading FileOpen.exe linked below (equivalent of the Windows Start command) to the same folder with otvdm and then editing otvdm.ini to include the line:

`dosemu=FileOpen.exe`

Link to FileOpen.exe:

https://www.dropbox.com/scl/fi/dgwchwfgbcttulngvqakg/FileOpen.exe?rlkey=e21zoomxqjcapjxerasnxlme0&dl=0

It's built in AutoIt, so your antivirus may flag it. The source code is here, so you can build it yourself with AutoIt if you prefer:

https://www.dropbox.com/s/0xeop9v7x9pk6k6/FileOpen.au3?dl=0

**Comment by emendelson** [comment]
I've revised the comment above to provide the actual source of FileOpen.exe.
