### ISSUE TITLE
Taipei! Maggjong does not use color tiles

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#137]
The game is here:
http://toastytech.com/guis/Win1Taipei1.02.zip

The "COLOR" item in the menu is greyed out.

If the window is bigger than some size, the tiles are not shown at all.
Also, there is no sound (beeps).

**Comment by cracyc** [comment]
The window size issue is a logic error in the program and not sanely fixable without patching the program.  The beeps work if you try to select a blocked tile and have Default Beep enabled in the sound control panel.

**Comment by Anixx** [comment]
Hmm. I think I have default beep enabled... I use the sound scheme Utopia from Win98.

**Comment by Anixx** [comment]
"Select game" item also seems not to work.

**Comment by Anixx** [comment]
When the game is won, it also says "cannot find coura.fon" in the messagebox.

**Comment by cracyc** [comment]
Select Game doesn't even work in Windows 2.11, seems it wasn't implemented.  The Corua.fon "error" is a dumb victory message/joke.  There are two dozen or so of them in the game.

**Comment by Anixx** [comment]
With newer build the color item is still greyed out and the tiles B&W
