### ISSUE TITLE
Inverted Colors for Sierra game - Spelling Blizzard

### ISSUE THREAD

**Issue by rlowies** [otya128/winevdm#1372]
Hello, I verified this is in the latest version.

The colors appear inverted for https://archive.org/details/spelling-blizzard

Running BLIZZARD/BLIZZARD.EXE

![image](https://github.com/otya128/winevdm/assets/31868310/861da648-3657-44aa-876d-ed2e193aa612)

 Windows 11 22H2
[Version 10.0.22621.3007]

Here is a trace of me opening and closing the program, it turned out to be ~250mb so I needed to compress it.

[trace.zip](https://github.com/otya128/winevdm/files/14175637/trace.zip)

Any suggestions would be great!
Thanks!

**Comment by cracyc** [comment]
https://github.com/otya128/winevdm/pull/1374 helps a bit if DIBPalette=1 is commented in otvdm.ini.  It flickers a lot because the window needs to be redrawn for the palette changes to take effect, there may be no way in window 8+ where 256 color modes were removed to make it work better.
