### ISSUE TITLE
Micrographics draw neither installs, nor runs

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#138]
The program is here:
http://toastytech.com/guis/Micrografx%20Windows%20Draw%201.04.zip

Neither setup.exe from Setup Disk, nor draw.exe from Program Disk start.

**Comment by cracyc** [comment]
The installer is a dos program.  The draw.exe program works fine for me.

**Comment by Anixx** [comment]
draw.exe is not recognized as win16 app. If fed directly to otvdm, it indeed works.
