### ISSUE TITLE
Build using MinGW64

### ISSUE THREAD

**Issue by impeeza** [otya128/winevdm#1381]
Not a bug, only I wonder if is possible to build the repo using Only MSYS MinGW64, Installing Visual Studio is a long long task.

Thanks a lot for all your help.

**Comment by cracyc** [comment]
Yes, with cmake.

**Comment by impeeza** [comment]
Thanks a lot for the super quick answer.

Will try again because using the commands on the readme.md:

```git clone https://github.com/otya128/winevdm.git
cd winevdm
mkdir build
cd build
cmake ..
make```

I get:

![image](https://github.com/otya128/winevdm/assets/41979604/c94cf80a-dde3-4a39-8111-7c2dbe8767e6)
after the `cmake ..`  works fine, the make do not find any `makefile` file.

The files (and folders) created are:

![image](https://github.com/otya128/winevdm/assets/41979604/dfd00d7d-abe8-4108-89eb-3323b8bdb0fa)

**Comment by impeeza** [comment]
Ok, by default CMAKE generate Ninja builds.   I did change the comand for `cmake .. -G "MSYS Makefiles"` and now the `make` command generate errors:

![image](https://github.com/otya128/winevdm/assets/41979604/11bb480d-9394-43a8-b167-12b970ff6e97)


Am I missing some prerequisites?

**Comment by cracyc** [comment]
I have not tried to build it with mingw myself but the CI build works.  Maybe the log can give a hint https://ci.appveyor.com/project/otya128/winevdm/builds/49217955/job/m33u93oyx9psayms .

**Comment by impeeza** [comment]
Used that instructions and same result, thanks for your answer.
