### ISSUE TITLE
Mordor 1.1 overflow error

### ISSUE THREAD

**Issue by correospambasurilla** [otya128/winevdm#1384]
Edition Windows 11 Pro 
Version 23H2 
OS build 22631.3235
Windows Feature Experience Pack 1000.22687.1000.0

Installation ok.
Error starting the game and then crashes

<img width="456" alt="image" src="https://github.com/otya128/winevdm/assets/161988518/3446833b-7637-4ec0-aac7-f665bc45003b">

<img width="482" alt="image" src="https://github.com/otya128/winevdm/assets/161988518/5a07c427-8465-46d4-952d-77e0922d62aa">

Trace:  [trace.txt](https://github.com/otya128/winevdm/files/14471429/trace.txt)

You can download a zip file with the limited version of this game [here](https://archive.org/details/MordorTheDepthsofDejenol_1020) 

Before installation, you must download and copy this two files.
OTVDM-~1.0\\WINDOWS\\SYSTEM\\VBRUN300.DLL  ([download](https://archive.org/details/vbrunDLL))
OTVDM-~1.0\\WINDOWS\\SYSTEM\\WAVMIX16.DLL ([download](https://www.dllinstaller.com/dlls/wavmix16-dll))

Also I remember that on Windows 10 it worked fine

**Comment by cracyc** [comment]
This is caused by a display width calculation overflowing a 16bit value.  It probably didn't happen before because either you got a larger display or you were using a build that didn't have fpu exceptions enabled.  I'm not sure if it can be worked around in winevdm since it's a bug in the program itself and 640x480 compat mode isn't enough.

**Comment by cracyc** [comment]
I found a workaround.  Get https://ci.appveyor.com/project/otya128/winevdm/builds/49318069/job/pq1al752l8f224yh/artifacts and uncomment AdjustDPI in otvdm.ini and that will prevent the overflow error.

**Comment by correospambasurilla** [comment]
That was fast!!
That works perfectly!.
<img width="546" alt="image" src="https://github.com/otya128/winevdm/assets/161988518/0f4eb3cf-dcc8-4f93-9cde-1f307faaf363">


**Thanks a lot** 👍
