### ISSUE TITLE
BattleStar cannot start: cannot open splash box

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#139]
The game is here:

https://archive.org/download/win3_BStar/BStar.zip

**Comment by cracyc** [comment]
Seems to work fine here.

**Comment by Anixx** [comment]
![clipboard_20190208](https://user-images.githubusercontent.com/1271736/52462575-4a0fcf80-2b7c-11e9-981c-d0e030208ea4.png)
I attached the error message box.

**Comment by Anixx** [comment]
It now works for me in the most recent release.
