### ISSUE TITLE
Unsupported program WinWelt. Works fine on Win98, but not on OTVDM.

### ISSUE THREAD

**Issue by dreimer1986** [otya128/winevdm#1400]
Try the latest version first.
Go [here](https://ci.appveyor.com/project/otya128/winevdm) and click `Environment: THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1`-> `Artifacts 1`-> `zip` to download the latest version.

**Describe the bug**
The program should start by starting WinWelt.exe as it does on W98, but instead it takes a while and responds the way seen below.

**Expected behavior**
The geography learning game should open in fullscreen and show a worldmap with all countries highligted in different colors.

**Screenshots**
![image](https://github.com/otya128/winevdm/assets/29841368/af27f705-b45a-4f6f-8419-3fc6de213191)

**Environment (please complete the following information):**
 - OS: Windows 11 23H2, Windows 10 22H2 64 Bit
 - Version Newest as seen above.

**Additional context**
This game for some time was just sitting on my HDD after I got it from school about 20 years ago. I verified the game works fine with a Windows 98 SE setup inside 86Box and it works perfect. I will add a trace.txt, but the software is mixed 16 Bit and 32 Bit apps, so likely it won't be of much use... I created your WINEDEBUG as systemwide env var to get more output off the console window though. This one is waaaaay longer. The game can be found in here, too: https://starfox-page.de/reactos/ek.zip

It is very helpful to provide a trace file if possible.
Please note that this file contains detailed information about the program.
**Procedure**
1. Run the command prompt.
2. Set the environment variable:
```cmd
set WINEDEBUG=+all,-snoop,-ldt,-fixup,-module,-global,-local,-disasm,-syslevel,-thunk
```
3.
```cmd
*old-executable-file* 2> trace.txt
```
4. Upload trace.txt here.
[trace.txt](https://github.com/otya128/winevdm/files/15198518/trace.txt)
[trace2.txt](https://github.com/otya128/winevdm/files/15198584/trace2.txt)

**Comment by cracyc** [comment]
Winevdm mangles window class names which breaks this.  To work around it you can run tb60_16r.exe and put winwelt.exe into the open file dialog.  A real fix will be difficult.

**Comment by dreimer1986** [comment]
Well, that's way more than I expected :D This way it works quite nicely. Should I add a lil graphical nitpick in here, or make a new report?
It's more just a picture showing the problem:
![image](https://github.com/otya128/winevdm/assets/29841368/4bde29d2-fe55-4d1a-855e-ac94ef4688c3)
These and a few more graphics are rendered incorrectly. Looks a bit like only the transparency mask is shown? On exit looks a bit too dotted, too. This is all I found after a few playthroughs, rest works PERFECT!

[trace.txt](https://github.com/otya128/winevdm/files/15209569/trace.txt)

**Comment by cracyc** [comment]
You should make a new report but I can't repo it so it'll be hard to fix (for me).
![Screenshot 2024-05-04 092854](https://github.com/otya128/winevdm/assets/9255333/820713fa-12c8-486b-9b0a-29088f0b13f9)

**Comment by dreimer1986** [comment]
Interesting... OK, in that case I will try around a bit more and on other hardware, too. If I still can reproduce this on some other device, I will open a report. Until then.... Thanks for the trick to successfully open it :D
