### ISSUE TITLE
Mulle meck does not start, no trace log

### ISSUE THREAD

**Issue by Betarn** [otya128/winevdm#1409]
Hi,

I've downloaded the ISO file from here https://archive.org/details/mulle-meck-bilar but having trouble starting the game.

First I tried to start MULLE32.EXE using windows default executor, then I get the error message "xtra not found", "fileio".

When I try to start MULLE16.EXE and SETUP.EXE using otvdm it immediatly shuts down without any traces.

OS: Windows 10 Home 22H2
Version: 19045.4046

Any help is much appreciated.

**Comment by cracyc** [comment]
The setup failure is fixed in top-of-tree, get a build from https://ci.appveyor.com/project/otya128/winevdm/builds/49868699/job/kq5c9qa1fwt6vct0/artifacts .  Mulle16.exe works for me but also gives the xtra not found error, probably the setup program is required.

**Comment by Betarn** [comment]
thank you!

**Comment by Hulta94** [comment]
Hi,
Also interested in this game.

Can't access the build, can you make it again?

**Comment by cracyc** [comment]
Get the build from https://ci.appveyor.com/project/otya128/winevdm/builds/51316286/job/il9b66pp8hbabdak/artifacts, it includes these changes.

**Comment by cracyc** [comment]
https://ci.appveyor.com/project/otya128/winevdm/builds/53457276/job/md18bs7t07rtw1sa/artifacts
