### ISSUE TITLE
Winbar does not start, hungs at "reading control panel information"

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#141]
The program:
http://www.completelyfreesoftware.com/software/winbar.zip

Screenshot is attached.
![clipboard_20190208](https://user-images.githubusercontent.com/1271736/52463359-47fb4000-2b7f-11e9-9699-fa4db45a9c67.png)

The background window is a segfault message.

**Comment by cracyc** [comment]
For me, it starts but doesn't work properly likely due to it's use of global hooks which aren't feasible to fully implement.

**Comment by Anixx** [comment]
For me the error remains. Segfault window is attached.
![clipboard_20190209](https://user-images.githubusercontent.com/1271736/52518759-78fb7380-2c58-11e9-9e96-51233878fb34.png)

**Comment by Anixx** [comment]
Works for me now.
