### ISSUE TITLE
Question about Windows on ARM

### ISSUE THREAD

**Issue by WindowsNinetyTen** [otya128/winevdm#1419]
I'm only curious as to whether this works also on Windows for ARM's emulation layer. I have a Windows PC, but it is x86, and I already use this layer on it.

**Comment by emendelson** [comment]
Yes, it works. The only thing that doesn't work is not otvdm itself - the addon that displays icons for 16-bit apps doesn't have any effect. But otvdm seems to work perfectly.

**Comment by WindowsNinetyTen** [comment]
I see. Just curious. Thanks!

**Comment by kristibektashi** [comment]
> The only thing that doesn't work is not otvdm itself - the addon that displays icons for 16-bit apps doesn't have any effect. But otvdm seems to work perfectly.

This can be solved by using a Windhawk mod instead (just look for 16-bit icons, you'll find it)

**Comment by emendelson** [comment]
> > The only thing that doesn't work is not otvdm itself - the addon that displays icons for 16-bit apps doesn't have any effect. But otvdm seems to work perfectly.
> 
> This can be solved by using a Windhawk mod instead (just look for 16-bit icons, you'll find it)

Found it:

https://windhawk.net/mods/icon16bitfix
