### ISSUE TITLE
World Empire III: the world map is nearly empty

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#142]
The world map does not display all the necessary elements (there should be continents)
The game is here:
https://archive.org/download/win3_WorldEmp/win3_WorldEmp.zip

![clipboard_20190208](https://user-images.githubusercontent.com/1271736/52466986-a7ac1800-2b8c-11e9-9334-a330919498bb.png)

**Comment by cracyc** [comment]
Can't repo this either.  It does occasionally crash with a VB error.

**Comment by Anixx** [comment]
I cannot reproduce it now, closing.
