### ISSUE TITLE
WineVDM fails to open installation wizard for an old game

### ISSUE THREAD

**Issue by GGuyX** [otya128/winevdm#1422]
Try the latest version first.
Go [here](https://ci.appveyor.com/project/otya128/winevdm) and click `Environment: THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1`-> `Artifacts 1`-> `zip` to download the latest version.

**Describe the bug**
FullTilt! Pinball game installation wizard does not start up - Setup is preparing InstallShield Wizard progress bar does not go beyond 75% completion. This occurs after the game's setup file requests me (the user) to allow running the following command: `"C:\Users\Patryk\AppData\Local\Temp\_ins0432._mp"  -fD:\WIN95\SETUP.INS  -z1 -cx -xC:\Users\Patryk\AppData\Local\Temp\`

**Expected behavior**
Installation wizard for game FullTilt! Pinball starting up and installation of the game

**Screenshots**
![image](https://github.com/otya128/winevdm/assets/142028287/10d8dcc4-35ef-436b-b885-c83aa6cd3dec)
![image](https://github.com/otya128/winevdm/assets/142028287/ee1833b6-3793-4634-bcda-eaa57c34cfec)
![image](https://github.com/otya128/winevdm/assets/142028287/30050937-5bef-4358-8d55-eeb33c4004d5)
![image](https://github.com/otya128/winevdm/assets/142028287/78539e5b-d2f4-4fbc-9de2-fa32d26edf88)

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 22H2 (Build Build 19045.4598)
 - Version: 2514

**Additional context**
I'm trying to install an old game, FullTilt! Pinball by Maxis Software from 1995. The game has versions for Windows 3.11 and Windows 95. When trying to install Windows 95 version of the game using the provided installer/setup file and WineVDM, the installation wizard never opens up (See higher up/earlier for exact description of the problem). In addition to the problem described earlier, WineVDM also shows the following message in an Windows Terminal window: `6934:fixme:module:LoadModule_wine_implementation Strange error set by CreateProcess: 740`. All screenshots are provided higher up/earlier. The game is mounted as an virtual CD/DVD drive into the system using Alcochol 120% software. The game can be found and downloaded here for testing the problem described earlier: https://archive.org/details/full-tilt-pinball-1996-windows

**Comment by cracyc** [comment]
This is probably https://github.com/otya128/winevdm/issues/226 again.  The 32bit part of the installer is waiting for some other program to finish but it's not.  You can either use installsheild fix from that thread or look in task manager for 
"ins0432._mp" and check analyze wait chain to find the other program that is blocking it.

**Comment by GGuyX** [comment]
#"ins0432._mp" and check analyze wait chain to find the other program that is blocking it.
By this you mean that I need to know what is blocking or currently using this particular file and unlock it? I may be able to do that with a program that I use, LockHunter, as it's built specifically for the purpose of checking which files, no matter the type, are used by which other file (or program) on the system.

**Comment by GGuyX** [comment]
> This is probably #226 again. The 32bit part of the installer is waiting for some other program to finish but it's not. You can either use installsheild fix from that thread or look in task manager for "ins0432._mp" and check analyze wait chain to find the other program that is blocking it.

This is what I was able to find. I'm not too sure what to do about it next. Should I just terminate the process attempting to use the file? It seems to just be some component part of the installer so this is a little bit confusing.
![image](https://github.com/otya128/winevdm/assets/142028287/aa52354e-fc67-49d0-bfcf-dbec3f624ec0)

**Comment by cracyc** [comment]
It not waiting on a file.  Analyze wait chain is in task manager. https://techcommunity.microsoft.com/t5/ask-the-performance-team/alternative-tools-for-application-hangs/ba-p/1685245

**Comment by GGuyX** [comment]
That is interesting. I was never actually aware that task manager had a tool like this. I will check the file with it, thanks.

**Comment by GGuyX** [comment]
This is what I can give you. When setup is running, there is no other process that I can find to analyze with this, that has to do with the installer/game related.
![image](https://github.com/otya128/winevdm/assets/142028287/6ea6803b-ca04-44d2-bba5-cea0beb3c5eb)

**Comment by cracyc** [comment]
Kill the rundll32 process and the install will continue.

**Comment by GGuyX** [comment]
so.. I managed to get the setup to open.. but it tells me my setup isn't capable of running the game?
![image](https://github.com/otya128/winevdm/assets/142028287/5a9571ee-5037-444d-ae22-1057c95747ef)

**Comment by cracyc** [comment]
This is beyond what winevdm can do.  You can try these options https://www.vogons.org/viewtopic.php?t=94910 .

**Comment by GGuyX** [comment]
Thank you, I will look into this.
