### ISSUE TITLE
SEGV when loading Microsoft Network DLL (netapi)

### ISSUE THREAD

**Issue by jgdrg** [otya128/winevdm#1424]
Try the latest version first.
Go [here](https://ci.appveyor.com/project/otya128/winevdm) and click `Environment: THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1`-> `Artifacts 1`-> `zip` to download the latest version.

**Describe the bug**
When using a legacy third-party Windows 3.1 application, we found it was crashing when starting. After investigation it was found that the crash was occurring when netapi.dll was being loaded by the application.

**Expected behavior**
Application doesn't not crash when loading netapi.dll

**Screenshots**
SEGV message with test app.
![image](https://github.com/otya128/winevdm/assets/40196788/14bcc45d-f958-4468-bf47-1a5673afee62)
Working on XP
![image](https://github.com/otya128/winevdm/assets/40196788/d1a99326-b15e-4232-9c83-e503a0c8e4c0)

**Environment (please complete the following information):**
 - OS: Windows 10 and 11

**Additional context**
To replicate the issue more easily. I created a simple test application that loads the offending DLL.
Testapp.zip contains the test binary, source (for ref) and netapi DLL.
Copy into a folder and launch with Winedebug
C:\Testapp><path to>otvdm.exe testapp.exe

[Testapp.zip](https://github.com/user-attachments/files/16180461/Testapp.zip)

It is very helpful to provide a trace file if possible.
Please note that this file contains detailed information about the program.

4. Upload trace.txt here.
[winedebug.log](https://github.com/user-attachments/files/16180425/winedebug.log)

**Comment by cracyc** [comment]
That netapi.dll tries to talk to a dos driver which doesn't work under winevdm.  I think that a replacement netapi.dll would be needed that calls win32 apis directly.  Unfortunately, upstream wine doesn't have one.

**Comment by jgdrg** [comment]
Thanks for your response. As the application only calls one netapi function, I made a replacement netapi dll that calls the required win32 netapi functions, with some help from the Microsoft LAN manager programmer's reference (1990) . This seems to have sorted the issue.

**Comment by cracyc** [comment]
Any chance you can share it?

**Comment by jgdrg** [comment]
I can, not my best work. How do you want me to share it?

**Comment by cracyc** [comment]
However you want.  Making a pr would be best although it's not my decision about accepting it.

**Comment by jgdrg** [comment]
See https://github.com/otya128/winevdm/pull/1428
