### ISSUE TITLE
Reading data from the COM port does not work

### ISSUE THREAD

**Issue by nukee86** [otya128/winevdm#1425]
Try the latest version first.
Go [here](https://ci.appveyor.com/project/otya128/winevdm) and click `Environment: THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1`-> `Artifacts 1`-> `zip` to download the latest version.

**Describe the bug**
App succesfully connects to the device, sends some bytes, but is unable to read any data.

**Expected behavior**
I've got an old app which connects through serial port to a device. I had no success with connecting using all available versions of winevdm. In the app, there's a possibility to check COM connection using raw terminal. It seems, that data is sent from the program to device, but it gets nothing in return. I wrote a simple python script to test if any data comes, but I get none. On the screenshot I attached you can compare expected behavior on windows xp and then there's windows 10 version which is not getting any data.

**Screenshots**
![raw_win10](https://github.com/user-attachments/assets/c9e77c33-e893-4c3b-aeee-e40cf51567e0)
![raw_winxp](https://github.com/user-attachments/assets/dcf8f330-bccf-4219-8b9f-aa82d81387b2)

**Environment (please complete the following information):**
 - OS: Windows 10 Home
 - Version 21H1 and 22H2

Tested also on Windows 7 64-bit, same behavior.

**Additional context**
There is no crash or something like that. Program works without any problems, the only thing is it doesn't get any data coming from serial port.

[trace_raw.zip](https://github.com/user-attachments/files/16201593/trace_raw.zip)

**Comment by cracyc** [comment]
Try https://github.com/otya128/winevdm/pull/1426 .  This program sets a receive notification queue size of 160 bytes but never gets anywhere near that in your test so it isn't reading the input.  Win31 ignores the limit and sends the message after 100ms.   Ntvdm always sends the message if there's data available so i've changed it to work like that.

**Comment by nukee86** [comment]
Thank you for your effort. It works like a charm! In my tests with raw terminal and with a device simulator I wrote, all the responses are as expected. Let the thread open until I test the app on Monday on the real device. The app is supposed to allow monitoring of many devices through terminal windows. I will put it to max stress and see if it won't crash. I'm already amazed it succeed to run on windows 10.

May I know what you mean by 160 bytes receive notification queue size? PCom-Server program sets that size? It would be weird, cause I reverse engineered the data sent and it gets nowhere near that value at any moment.

**Comment by cracyc** [comment]
```
0130:Call USER.245: ENABLECOMMNOTIFICATION(0001,006f,00a0,ffff) ret=121f:e397 ds=1257
1880:0130:trace:comm:EnableCommNotification16 (1, 6f, 160, -1)
```
The third parameter sets the receive queue size.  It's set by the program.  Probably, on slower computers it needs the queue that large to avoid hanging the machine if data arrives too quickly.  On modern machines it doesn't matter.

**Comment by nukee86** [comment]
You were right - i sent huge amount of data and raw terminal printed out the input. I was curious if that was the case with normal connection. I looked through traces of new and old compilation. Both cases EnableCommNotification16 was the same:
```
1c6c:Call USER.245: ENABLECOMMNOTIFICATION(0001,0053,0001,ffff) ret=1217:51e6 ds=1257
120c:1c6c:trace:comm:EnableCommNotification16 (1, 53, 1, -1)
```
However, in old compilation program "stopped" getting data at 0x2E byte, while the new one gets through. Here are the pictures:
![trace_old](https://github.com/user-attachments/assets/3c16d9bc-c440-42cc-9656-1b47a873faf8)

![trace_new](https://github.com/user-attachments/assets/fed3ebd2-9dde-4caa-805d-a39aab6171fd)

Logs: [trace_new_old.zip](https://github.com/user-attachments/files/16203794/trace_new_old.zip)

Seems like your fix sort out this problem aswell :)

**Comment by nukee86** [comment]
I just tested communication on the real device. If I use COM port redirector, everything works fine. If I use real COM port in computer, i got no response again.

Here are my devices:
![devices](https://github.com/user-attachments/assets/60d5c6cc-3570-40af-9d8d-a955331cee68)

And here are traces for real com and vcoms to compare:
[trace_com.zip](https://github.com/user-attachments/files/16229717/trace_com.zip)

I mainly got to connect using real COM port, so it would be great if there's something you can find in the traces.

**Comment by cracyc** [comment]
There's nothing in the trace that suggests why it's not working.  Maybe there's something wrong with the connection or some incompatibility with your usb-serial adapter.
