### ISSUE TITLE
Most (all?) Win1.0 and Win2.0 apps have B&W window icons

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#143]
Particularly, Taipei mhjongg, Micrographix Draw, etc. This may be a reflection of the fact the icons are 3bpp. Maybe a fix similar to the bitmaps can work for icons as well?

**Comment by cracyc** [comment]
Windows 1 or 2 programs can't have color static icons.  Some draw their own icon area so they can animate which won't work in win95+.
