### ISSUE TITLE
Just Grandma And Me funky graphics

### ISSUE THREAD

**Issue by KoghaandSooga** [otya128/winevdm#1430]
Windows 10 64 bit.  I7 10th gen core.  Nivida 1650S graphics card.  

Just Grandma And Me Living Books 1.0 at first crashed because of color pallets too small so I did the compatible (8 bit) 256 colors trick thus removing the error message but the graphics only have show where you see half the picture as it draws itself in in a weird sort of way.  Can't do screenshots because it takes over the screen when running the program or otherwise I'd use snippit and post it here.

I was able to navigate basic menus despite this. Amazing this old thing ran at all! So yes winevdm does work but with some caveats.

**Comment by KoghaandSooga** [comment]
Okay by lowering the resolution I got it into a window so I could do a screen shot but can't show the funky graphics as whenever I click off it the graphics get itself fixed but this shot should show what I mean a little bit by some funky graphics. 
![Grandma And Me Menu on Windows 10 64 bit!!!](https://github.com/user-attachments/assets/e6b40687-60b6-433d-bd0d-209be2d1cc0a)

**Comment by cracyc** [comment]
This uses palette tricks that simply don't work in 24bit color on any version of windows (there are probably more than 2 dozen issues with programs that have color problems) so it's really a windows issue but we keep looking for workarounds.  https://github.com/otya128/winevdm/pull/1432 make this program work at least.
