### ISSUE TITLE
Interrupt 0D #GP (2A07:2233) flags 3216 err 0000mov eax, fs:[1000h+ebx*8] during Video Sequence inside Game

### ISSUE THREAD

**Issue by An4nke** [otya128/winevdm#1433]
**Describe the bug**
During playing an old Game (Opera Fatal) when pushing where a video sequence should start otvdmw.exe crashes with error message "Interrupt 0D #GP (2A07:2233) flags 3216 err 0000mov eax, fs:[1000h+ebx*8]"

**Expected behavior**
Push a Button ingame. After then a video sequence should start. During/After this video sequence an event inside the game should start and open a new level.

**Screenshots**
![opera_fatal_retro_on_windows_10_bug](https://github.com/user-attachments/assets/e7e73509-cc5a-442c-9a97-c8862fb77b11)

**Environment (please complete the following information):**
Installed latest Version (v0.9.0), downloaded: 2024-08-03.
Windows 10 Home 22H2 64-Bit x64 Processor
AMD Ryzen 5 1600X Six-Core Processor

**Additional context**
Originally the Game requires QtimePlayer for running properly.

It is very helpful to provide a trace file if possible.
Please note that this file contains detailed information about the program.
**Procedure**
1. Run the command prompt.
2. Set the environment variable:
```cmd
set WINEDEBUG=+all,-snoop,-ldt,-fixup,-module,-global,-local,-disasm,-syslevel,-thunk
```
3.
```cmd
*old-executable-file* 2> trace.txt
```
4. Upload trace.txt here.
[trace.txt](https://github.com/user-attachments/files/16645615/trace.txt)

**Comment by cracyc** [comment]
Check the qtw.ini in your winevdm windows directory and make sure the optimize line is set to bmp or dib.  Optimize=hardware will not work.

**Comment by An4nke** [comment]
Thank you for the fast reply.

Unfortunately adding `Optimize=dib` or `Optimize=bmp` into qtw.ini does not work.

I also installed the newest Version of QuickTime on my OS which does not work either.
I also tried to install the orginal Version Version of QuickTime (from the old Game CD) via otvdm which stuck inside the procedure.

**Trace-File**
[QTtrace.txt](https://github.com/user-attachments/files/16650511/QTtrace.txt)

**Original qwt.ini**
`[QuickTime for Windows]
VHDW Component=None
Video Hardware=Not directly supported
`
 These lines will written there even if you remove them.

**Comment by cracyc** [comment]
Does it say
```
[Video]
Optimize=DIB
```
in the qtw.ini as the [Video] line is also needed.  If that doesn't help a full trace is needed with the `set WINEDEBUG=+all,-snoop,-ldt,-fixup,-module,-global,-local,-disasm,-syslevel,-thunk`.  Don't use powershell as set doesn't work there, use cmd.

**Comment by An4nke** [comment]
Yes, it says
```
[Video]
Optimize=DIB
```
Here is the trace file from cmd:

**Comment by cracyc** [comment]
File link doesn't work.

**Comment by An4nke** [comment]
Excuse me, the file was so bit so I zipped it.
Here is a shorten version:
[trace_shorten.txt](https://github.com/user-attachments/files/16720027/trace_shorten.txt)

[Trace.zip](https://github.com/user-attachments/files/16720029/Trace.zip)

**Comment by cracyc** [comment]
Try a dev version from https://ci.appveyor.com/project/otya128/winevdm/builds/50421709/job/l3wdcqdr8kjii67t/artifacts

**Comment by An4nke** [comment]
Thanks for the reply.

Downloaded and installed the dev version now.
Tried the game with the game version. Now the bug appears a button click earlier.

**Trace-File (shortend):**
[trace_dev_shorten.txt](https://github.com/user-attachments/files/16728089/trace_dev_shorten.txt)

**Trace-File (zip verision):**
[TRACE_DEV.zip](https://github.com/user-attachments/files/16728090/TRACE_DEV.zip)

**Comment by cracyc** [comment]
Try https://ci.appveyor.com/project/otya128/winevdm/builds/50465680/job/hd6oj7mn3bgfybmu/artifacts

**Comment by An4nke** [comment]
It is working now perfectly. Thank you very much for the fast fix.

**Comment by Peter19800** [comment]
Hello, I have the same problem with the same game. Can you please offer me the same solution as An4nke?
Thanks!
