### ISSUE TITLE
Use Fluent design instead of Classic design

### ISSUE THREAD

**Issue by upintheairsheep** [otya128/winevdm#1434]
Hello, the second biggest issue with WineVDM is that it uses the Classic design language, which looks out-of-place in juxtaposition with the rest of the computer. Can you have Windows 11’s Fluent design (or MDL2 on Windows 10) be used instead? I’m sure Microsoft would not allow the Classic design language if they were to integrate this with modern Windows.

https://virtuallyfun.com/2018/07/15/winevdm/ This somehow uses the MDL2 design of Windows 10.

**Comment by cracyc** [comment]
You can uncomment ;EnableVisualStyle=1 and ;DisableAero=0 in otvdm.ini but this is not recommended as some software will not work properly which is why ntvdm also forces classic style for win16 programs.

**Comment by upintheairsheep** [comment]
@cracyc thanks! sorry for the late closure.
