### ISSUE TITLE
In Taipei! Mahjongg the resize cursor remains even inside the app area

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#144]
If to place the cursor on the window border, it becimes a two-sided arrow, indicating ability to resize the window. But if to move it now into the app window (along the green background) it still remains "window-resize" arrow, even though it is impossible to resize the window by clicking on the green field.

**Comment by cracyc** [comment]
The same thing happens in win2.11 so it's not a winevdm bug.
