### ISSUE TITLE
QT16INST Will Not Complete Installation Past SEGV on Build 2527

### ISSUE THREAD

**Issue by VoodooJosh** [otya128/winevdm#1441]
**Describe the bug**
When trying to install QuickTime 2.1.2, the installation becomes unresponsive when reaching the "update .ini" section and all that can be done is to close the installation window. Its installation is necessary for a program called Piano Discovery 3.0 by Jump! Music in order to use audio and video. As for what all does get installed before the installation fails, you do get some audio and video, but it gets cut off after about a second of playing.

**Expected behavior**
QuickTime should finish installation and become available to use.

**Screenshots**
![QTCapture](https://github.com/user-attachments/assets/29f4289b-93dd-4a13-8577-c6ed852a3078)

**Environment (please complete the following information):**
 - OS: Windows 10 Home
 - Version: 10.0.19044 Build 19044
**Additional context**
I am using build 2527 as it is the version that has worked best so far for running Piano Discovery and running the QuickTime installer.

[trace.txt](https://github.com/user-attachments/files/16924189/trace.txt)

I also have what is currently configured in the QTW file within otvdm:
[QTW.txt](https://github.com/user-attachments/files/16924191/QTW.txt)

**Comment by VoodooJosh** [comment]
I am happy to report that build 2530 did rectify the issue with installing QuickTime and now it is fully installed. Unfortunately, the program Piano Discovery 3.0 is still behaving the same where voice and video are cut off after about a second of playing but this might be for a different reason, and I can put a trace file for that in a separate issue if that would work best.

**Comment by cracyc** [comment]
Making a new issue would be best.

**Comment by VoodooJosh** [comment]
Will do, thank you!
