### ISSUE TITLE
QuickTime Audio & Video Cutting Off After Briefly Playing

### ISSUE THREAD

**Issue by VoodooJosh** [otya128/winevdm#1444]
**Describe the bug**
When using the program Piano Discovery 3.0 by Jump! Music, .WAV & .MOV files that are used with the program will play for a brief second before being cutoff. Video only works by scrubbing the QuickTime video player embedded. Music still works with the program because it is utilizing MIDI, it is only voice that is affected. QuickTime version is [2.1.1.57](https://archive.org/details/applequicktime32).

**Expected behavior**
For audio and video to play fully within Piano Discovery without being cutoff.

**Environment (please complete the following information):**
OS: Windows 10 Home and Windows 11 Home
Version: 10.0.19044 Build 19044 for Win10 and Version 10.0.22631 Build 22631 for Win11

**Additional context**
I am currently running build dev2530. It is worth noting that the individual .MOV & .WAV files located in the program files for Piano Discovery will play fully in the QuickTime Player thanks to the fix for[ issue 1441](https://github.com/otya128/winevdm/issues/1441) so I don't think that it is QuickTime itself that is the issue.

[trace.zip](https://github.com/user-attachments/files/16987699/trace.zip)
I uploaded the trace file in a zip because of its size but if it isn't usable, I can try and create a smaller trace file.

**Comment by VoodooJosh** [comment]
I also want to note that I tried uncommenting vm86.dll, haxmv.dll, and whpxvm.dll in the otvdm.ini file with no change.

**Comment by cracyc** [comment]
Try getting https://github.com/otya128/winevdm/pull/1448 and set DIBPalette=1 in otvdm.ini.

**Comment by VoodooJosh** [comment]
Thank you for the new release! Unfortunately, changing those settings did not show any improvement. I'll add some example files in zipped folders to show the exhibited behavior and maybe give some more insight. One folder for after altering the settings above, and one folder for what it should sound like using the QuickTime Player.

[Program Recording.zip](https://github.com/user-attachments/files/17104912/Program.Recording.zip)
[QuickTime Recordings.zip](https://github.com/user-attachments/files/17104914/QuickTime.Recordings.zip)

**Comment by cracyc** [comment]
Some Macromedia Director programs which use Quicktime have a similar problem which can be worked around with the fix I posted but yours is different.  There's really nothing in the trace or in your video that is obviously the problem.  I'd need to test it myself to find the problem.

**Comment by VoodooJosh** [comment]
That's interesting and good to know, but I completely understand. Here is a Google Drive link with the ISO for the version of the program I have been experimenting with for any and all who want to try it. Let me know if that doesn't work and I will try to make it accessible in another way.
https://drive.google.com/file/d/1k6Gi9txaNPllTxBrfqlkCBG4mlm0ZPCi/view?usp=sharing
