### ISSUE TITLE
INT21H function AH=3Dh (Open File) call problem with relative path specification.

### ISSUE THREAD

**Issue by nanitaro** [otya128/winevdm#1451]
**Describe the bug**
This is a problem I found in a game supplement to a Japanese adult game magazine named TECH GIAN.
When I proceed with the game, it hangs with a message box that says “The file data\B2\B01.bmp cannot be opened.” 
This message does not appear in the real environment of Windows 98SE.

The directory structure of this game is as follows
[dir.txt](https://github.com/user-attachments/files/17335924/dir.txt)

This game is started by executing Prin.exe.
When the game mode is switched during the game, SLG1.exe or SLG2.exe under WORK is executed from Prin.exe.
When SLG1.exe or SLG2.exe is executed, the message box in question appears.
The trace log shows that it is trying to open the data\B2\B01.bmp by specifying a relative path, but it is failing.
Line 88362 of the trace log.
>40b4:0738:trace:int21:INT21_CreateFile CreateFile called: function=3d, action=01, access/share=0000, create flags=0000, file=data\B2\B01. bmp.

Copy the DATA directory to \DEAR_P\STORY2, where the DATA directory is in the same hierarchy as the WORK directory. 
When Prin.exe is executed in this state, the error message box does not appear, and I confirmed that it works correctly.
This is probably because the current directory remains \DEAR_P\STORY2 even after SLG1.EXE is executed, and is not changed to \DEAR_P\STORY2\WORK.

**Expected behavior**
The game proceeds without error messages.

**Screenshots**
![msgbox](https://github.com/user-attachments/assets/69613446-3dc9-4fad-8710-56ab4b987c09)

**Environment (please complete the following information):**
 - OS: Windows 11 Home
 - Version 23H2 22631.4317

**Additional context**
As you can see from the trace log, other files are opened with absolute paths.
Since this is the only file with a relative path, I think it may be a bug in the game.
However, the file opens correctly in the actual Windows 98SE environment, so is it possible to interpret the relative path in the same way as in real Windows?

It is very helpful to provide a trace file if possible.
Please note that this file contains detailed information about the program.
**Procedure**
1. Run the command prompt.
2. Set the environment variable:
```cmd
set WINEDEBUG=+all,-snoop,-ldt,-fixup,-module,-global,-local,-disasm,-syslevel,-thunk
```
3.
```cmd
*old-executable-file* 2> trace.txt
```
4. Upload trace.txt here.
[trace.txt](https://github.com/user-attachments/files/17336029/trace.txt)

**Comment by cracyc** [comment]
Try https://github.com/otya128/winevdm/pull/1452
