### ISSUE TITLE
The text occupying two bytes of input space was incorrectly converted into one byte.

### ISSUE THREAD

**Issue by CHNdp** [otya128/winevdm#1453]
Hello, my running program involves inputting Chinese characters encoded with GBXXX. Each character occupies 2 bytes, but after inputting, it becomes 1 byte of garbled text.
I hope an expert can help solve this problem. Thank you very much.

![image](https://github.com/user-attachments/assets/742766a9-7f48-483f-95b3-6fb28fe9fb5d)
Uncheck and the problem is resolved

**Comment by cracyc** [comment]
Need more info like a trace.  Is the program available for testing?

**Comment by CHNdp** [comment]
> Need more info like a trace. Is the program available for testing?

[program.zip](https://github.com/user-attachments/files/17392224/program.zip)
Thank you, this is the test package.

**Comment by cracyc** [comment]
This is an msdos program which support is very incomplete in winevdm.  You might try the msdos-player with your program which has decent dbcs support just make sure the console code page is set to 936 which it might be by default.  I don't know how good dosbox-x chinese support is but you might try that too.

**Comment by CHNdp** [comment]
> This is an msdos program which support is very incomplete in winevdm. You might try the msdos-player with your program which has decent dbcs support just make sure the console code page is set to 936 which it might be by default. I don't know how good dosbox-x chinese support is but you might try that too.

The issue was resolved because I had checked the option to enable the legacy console.
After unchecking the legacy console, the program input functioned normally.
Thank you for your response.

**Comment by CHNdp** [comment]
Close
