### ISSUE TITLE
WPWin 6.1 crash on startup

### ISSUE THREAD

**Issue by emendelson** [otya128/winevdm#1462]
I think this may have come up before, but it seemed worth raising it again. WordPerfect for Windows 6.1, running under Windows 11, with the latest Appveyor executables, produces this error:

![image](https://github.com/user-attachments/assets/3cc4ec42-2dd7-4811-bb99-f049b77f1481)

Trace file attached.

[trace.zip](https://github.com/user-attachments/files/18011086/trace.zip)

**Comment by emendelson** [comment]
I downloaded and used build 2548 from the appveyor page but still got the same error, unfortunately. Maybe I'm doing something wrong?

Trace here:

[trace.zip](https://github.com/user-attachments/files/18111384/trace.zip)

**Comment by cracyc** [comment]
`version: 2550`
2550 doesn't contain the fix.

**Comment by emendelson** [comment]
Sorry! This was pure user stupidity (not the first time). I've now downloaded and used build 2548 from the appveyor page but still got the same error, unfortunately. Maybe I'm doing something wrong?

Trace here:

[trace.zip](https://github.com/user-attachments/files/18115352/trace.zip)

**Comment by cracyc** [comment]
```
67ec:Call WINSPOOL.91: DEVICECAPABILITIES(2587622c "Edward LaserJet P3015 PCL5",258f6ffc "Ne08:",0006,2597d47a "ç+¼",0000:0000) ret=2337:2bc0 ds=2597
67ec:Ret  WINSPOOL.91: DEVICECAPABILITIES() retval=0000001b ret=2337:2bc0 ds=2597
```
0006 is DC_BINS.  Your printer says is has 27 paper bins which seems odd and I suspect that wordperfect doesn't expect that many.  Can you try changing your default printer to the MS PDF printer which reports 0 bins?

**Comment by emendelson** [comment]
Hmm... 27 bins does sound like a lot. When I look at the actual physical LaserJet, I count exactly 1 bin. - Changing the default printer to MS PDF completely solves the problem. Now to see if I can fiddle with the printer driver. (I think I'm using the discontinued HP PCL5 driver, but there's no need to do so.)

Thank you and I'll close this.

**Comment by cracyc** [comment]
The patch in the pull request does fix a very similar crash to the one you have so it still is needed for it to work.
Disassembling wpwin61 shows that it only expects a max of 13 bins.

**Comment by emendelson** [comment]
I should have clarified that I only tested this with the pull-request version, not with anything else. So it's good to know that the fix will be there. Now to figure out how to change those bin numbers. I suspect that the HP PCL driver was designed to work with those huge corporate LaserJets that may, for all I know, have 27 bins in some models.
