### ISSUE TITLE
16bit VB3 Newbie question. 

### ISSUE THREAD

**Issue by dave3434-sudo** [otya128/winevdm#1463]
My very first session on Github!
I have installed otvdm-v0.9.0 to resurrect all my legacy 16bit VB applications on Win11 and it runs fine to the point where I can create a new project using otvdmw with a single form with a simple 'Hello world / exit' button. I can run it and save it so in order to show the project in the saved project list. However, as soon as I then select the project to modify it, it immediately rejects with the error box (hopefully following)...

![Ghub1](https://github.com/user-attachments/assets/60cfabd0-3d1d-423b-8e83-744451263db9)

Any suggestions as to where to start!?

**Comment by cracyc** [comment]
Try getting the dev build from https://ci.appveyor.com/project/otya128/winevdm/builds/51085084/job/fr8vl6097rg9f27k/artifacts .

**Comment by dave3434-sudo** [comment]
Wow. Thanks so much for your prompt assistance!
I installed and unzipped it but gave the same result when I came to open the project again. I thought maybe it's something to do with Path settings.. In my days it was somewhere in autoexec.bat and config.sys!
![Ghub2](https://github.com/user-attachments/assets/eac84fa3-a5a8-4181-a81c-8e931109f2e0)

**Comment by cracyc** [comment]
Try this new build https://ci.appveyor.com/project/otya128/winevdm/builds/51137952/job/bqkhyofjovabxqcg/artifacts

**Comment by dave3434-sudo** [comment]
Don't know who you are mate but you've made my life heaps easier and unlocked about 20 years worth of work on my old VB3 projects that used to be my main source of income. I would possibly have thrown it all in the trash if it was not for you taking the time to reply to my message.Installing that build has resurrected it all and I'm finally been able to make actual progress!Many, many thanks!Happy Xmas from downunder.Cheers, David.    On Tuesday 10 December 2024 at 05:57:26 GMT+11, cracyc ***@***.***> wrote:  
 
 


Try this new build https://ci.appveyor.com/project/otya128/winevdm/builds/51137952/job/bqkhyofjovabxqcg/artifacts
