### ISSUE TITLE
segv error crash during execution of 16-bit app

### ISSUE THREAD

**Issue by HermanJansen56** [otya128/winevdm#1465]
While executing a win3 application, on opening a new window, there is an segv error pop-up and then otvdm terminates.
See attached trace-file. 
(
0670:1390:trace:win:free_module_classes Class "WIN16119FAfxWnd" unregistered
0670:1390:trace:win:free_module_classes Class "WIN16119FAfxControlBar" unregistered
0670:1390:trace:win:free_module_classes Class "WIN16119FAfxMDIFrame" unregistered
0670:1390:trace:win:free_module_classes Class "WIN16119FAfxFrameOrView" unregistered
0670:1390:trace:win:enum_thread_window HWND 18074c destroyed
)
[otvdm_trace.zip](https://github.com/user-attachments/files/18060995/otvdm_trace.zip)

**Comment by cracyc** [comment]
Try https://ci.appveyor.com/project/otya128/winevdm/builds/51136591/job/1y58g80v4ksh4omy/artifacts

**Comment by HermanJansen56** [comment]
Wow! It works ! 
Thanks a lot!
Will this be incorporated in a new release?
