### ISSUE TITLE
Content of windows overflows boxes on windows 11 24H2, and some content are missing

### ISSUE THREAD

**Issue by hagsted** [otya128/winevdm#1468]
**Describe the bug**
On windows 24h2 some boxes seems to be to small and the content are either expanding out of the box or clipped. The best example and most annoying problem I have encountered is that a scroll bar is missing, you can travers down the list by keyboard, but my normal users are more mouse driven. This is working perfectly fine on 10 similar setups running windows 11 23h2. I have tried EnableVisualStyle as both enabled and disabled, the same goes for Aero. I have also tried changing from wphxvm.dll to vm86.dll, but nothing has helped on windows 11 24h2. I have also tried to change RealizeRedraw and DWMDesktopDCFix, to no avail.

**Expected behavior**
That all content is within the window of the program and all scrollbars appears as they should and only when necessary.

**Screenshots**
Here there are screenshots from a system running 23h2 (left) and one running 24H2 (right)
![No Scrollbar as expected 23h2](https://github.com/user-attachments/assets/3abe06a8-3dfb-4756-814a-b7a4875b6d24) ![Scrollbar should not be here 24h2](https://github.com/user-attachments/assets/87dbfda0-630d-4cc0-82fa-6769bd92ca66)
![scrollbar visible on 23h2](https://github.com/user-attachments/assets/0933ccc2-800f-4a93-a5ce-a12b9ee1c92e) ![scrollbar gone on 24h2](https://github.com/user-attachments/assets/cf0dd9f8-2e12-4526-89a1-a7389c585e5f)
![less of buttons overlapping boarder of windows 23h2](https://github.com/user-attachments/assets/cf619b6b-190a-4843-be12-1fda9d891d70) ![buttons overlapping boarder of windows 24h2](https://github.com/user-attachments/assets/ee575749-0f8c-4955-98a6-9948a4c42af3)
![less content overlapping boarder of windows 23h2](https://github.com/user-attachments/assets/f6ab47dc-008e-4b3b-a006-53c623da1060) ![content overlapping boarder of windows 24h2](https://github.com/user-attachments/assets/fc55796d-f4cd-4bd5-b3ee-7dcdcdbda392)

**Environment (please complete the following information):**
 - OS: [e.g. Windows 11 24h2]
 - Version [e.g. version: release 0.9], but also tested on version 2550

**Additional context**
Trace made with version 2550 :
[trace.txt](https://github.com/user-attachments/files/18107424/trace.txt)

Thanks for this great piece of work that has enabled us to upgrade our Production equipment to modern windows and all the conveniences of that.

Best regards Kristian Hagsted

**Comment by cracyc** [comment]
XP
![Screenshot 2024-12-12 201217](https://github.com/user-attachments/assets/df8046f2-da52-4f04-87cb-b62d19999695)
Win11 24H2
![Screenshot 2024-12-12 201235](https://github.com/user-attachments/assets/20004e63-d58a-4867-95eb-1f45de47d00c)

Looks like it's getting a WS_EX_WINDOWEDGE style from somewhere which is making the window border a few pixels wider.

**Comment by cracyc** [comment]
This is a windows bug but https://github.com/otya128/winevdm/pull/1469 is an attempt at a workaround.

**Comment by hagsted** [comment]
Hi cracyc

This does seem to fix the problem in ex.exe, or at least to the level that was seen in 23h2, with only a slight overflow at the bottom. However, when i start RE.EXE and try to open a file. I still don't get a scrollbar if the list is longer than what can be view, this screen dump is when running version 2553.
![image](https://github.com/user-attachments/assets/fda69111-bd2a-41a5-b20f-00102836ceac)

I have attached a trace of RE.exe running without any of the other files (version 2553).
[trace_re.txt](https://github.com/user-attachments/files/18161768/trace_re.txt)

If you need a guide for running RE.exe, just tell me.

Best regards Kristian Hagsted

**Comment by cracyc** [comment]
The last commit to https://github.com/otya128/winevdm/pull/1469 should fix that.

**Comment by hagsted** [comment]
Thank you cracyc.

It does fix it. Only thing I see as a difference between 23h2 and 24h2 now, is the extra scrollbar in the "Operator mode" windows. But this is of no consequences for operation, and not important to me at least.

Best regards Kristian Hagsted
