### ISSUE TITLE
MS Tetris is displayed with wrong window border (like that of irresponsive windows)

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#148]
The game is here:
https://archive.org/download/TETRIS_201612/TETRIS.zip

It is apparently viewed by the host system (Win 8.1) as a hung (irresponsive) application, because of this its windows are displayed using the theme for hung windows. The splash window is displayed OK though. 

A screenshot of the game window in front of normal File Explorer window is attached.
Also, the font background in score area is white, which seems wrong.

![tetr](https://user-images.githubusercontent.com/1271736/52519387-69cdf300-2c63-11e9-8f3b-d41239d7d753.png)

**Comment by Anixx** [comment]
The same happens with the in-game dialogs in Excile III:
![clipboard_20190209](https://user-images.githubusercontent.com/1271736/52519590-02fe0900-2c66-11e9-931d-94207947f73d.png)

**Comment by otya128** [comment]
In some cases it is not possible to disable Aero, but this is not a problem in quite a few cases.

**Comment by Anixx** [comment]
The problem is not about Aero, but seemingly in that the host windows thinks about the windows as irresponsive. It uses the system theme for hung and irresponsive windows (possibly also dims them down if that option is not disabled).

**Comment by Anixx** [comment]
In other words, all windows use either no theme or \Sessions\XX\Windows\ThemeYYYYYYYYY where XX is session number (in NT object file system) but the hung windows use \Windows\ThemeZZZZZZZZZZ which is session-indpendent.

**Comment by otya128** [comment]
I do not know about theme, but please try to append DisableAero=0 to otvdm.ini.

**Comment by Anixx** [comment]
Yes, this works! Is it possible to make this option default?


![clipboard_20190209 2](https://user-images.githubusercontent.com/1271736/52520288-a6541b80-2c70-11e9-8809-374d74d4c2be.png)

**Comment by Anixx** [comment]
![clipboard_20190209](https://user-images.githubusercontent.com/1271736/52520326-fa5f0000-2c70-11e9-843d-a53fc3221ae0.png)
Why at all when disable aero is set to 1, it uses that strange theme?

**Comment by Anixx** [comment]
This is a positive commit, but in my case I think IsThemeActive returns true.

Also, it possible to move the setting to the registry from the .ini file, so that I would not have to copy the same .ini file each time I install a newer version of otvdm?

**Comment by Anixx** [comment]
Would not it be more optimal if otvdm used the system settings by default (not trying to disable aero) and only disabled aero if the user explicitely requested it?

**Comment by Anixx** [comment]
Well, I have just tested and, in fact the fix works, so I close this issue.
