### ISSUE TITLE
In Rodent's Revenge, Risk and other games the subtopics of the help file are not accessible via menu

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#149]
The game is here: https://archive.org/download/rodents_revenge/rodents_revenge.zip

The Index menu item under Help works, but How to Play and Commands (which are the sub-topics of the first one) do not. 
It also cannot display the help on using help because winhelp.hlp is not found.

**Comment by Anixx** [comment]
The same problem is with the game Risk:
https://ia800202.us.archive.org/19/items/win3_Risk3x/win3_Risk3x.zip

And possibly, with many others.

**Comment by cracyc** [comment]
Wine's winhlp32 doesn't support HELP_KEY required for that to work.  For now you'd have to get Microsoft's 16bit winhelp.exe or 32bit winhlp32.exe (which they have a download for on their site).  For help on help you'd have to get winhelp.hlp from some version of windows.
