### ISSUE TITLE
Appveyor builds require VCRUNTIME140D.dll and ucrtbased.dll

### ISSUE THREAD

**Issue by phly95** [otya128/winevdm#15]
Not quite sure where these dlls can be gotten from. I installed visual studio, but it didn't help.

**Comment by neozeed** [comment]
That thing is building debug builds.  So that is the debug version of the VC2017 runtime.

Did you install VS 2017?  And make sure it has all the native platform support?  With all that work you could just compile WineVDM yourself....

**Comment by phly95** [comment]
I only just got the exe from the Microsoft website and clicked through the installer. I don't know anything about what platforms to select to get it working

**Comment by neozeed** [comment]
So it's pretty much given its not installed C++ by default...  Who ever setup the autobuild thing should have it do a release build..  although sticking with stable may be okay too ..   lots of things are in flux.

**Comment by otya128** [comment]
I configured to not use debug dll when building with appveyor, so I think that it is fixed in the latest build.

**Comment by phly95** [comment]
Thanks, that is quite helpful. The Red Alert installer is getting farther with the latest build (though is still crashing before getting to the installer)
