### ISSUE TITLE
Fields of Battle do not detect the screen color mode properly

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#150]
Here is the game:
https://archive.org/download/win3_Fieldsof/win3_Fieldsof.zip

When started it says it detected the number of colors 1 and so cannot start. Then suggests to force the desired number of colors via the .ini file.

In .ini file, if to set the number of colors 256 (which should be supported by the game) it still does not start and says it detected 1-color mode.

If to set the number of colors at 140, the game starts, but all colors are wrong:
![fields](https://user-images.githubusercontent.com/1271736/52524551-d0283500-2ca6-11e9-83f0-0da2de4da879.png)

**Comment by cracyc** [comment]
You can right click on the exe and set 256 color mode in the compatible tab to get rid of the error but the colors are still messed up.  The program messes with palette in ways which might just not be fixable.

**Comment by Anixx** [comment]
Perfectly works now.
