### ISSUE TITLE
Items on WinSong Composer palette are invisible

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#153]
http://toastytech.com/guis/Win1WinSong201SW.zip
![clipboard_20190209](https://user-images.githubusercontent.com/1271736/52524515-6a3bad80-2ca6-11e9-86a9-c6732cb4fafd.png)

They become visible if to minimize and then maximize the app.

Also, the MIDI items in the menu are greyed out, impossible to chose Play, Play all, and Play from start.

**Comment by cracyc** [comment]
The palette window gets a 0x31f message (WM_DWMNCRENDERINGCHANGED?) that then causes a WM_ERASEBKGND message but no WM_PAINT so the window is left empty.  The MIDI doesn't use MCI so it probably requires drivers which don't exists anymore.

**Comment by cracyc** [comment]
Just returning 0 in is_dialog_message_callback if msg==WM_DWMNCRENDERINGCHANGED fixes the problem but I'm not sure if there would be bad side effects to that.
