### ISSUE TITLE
Pubtech file organizer crashes on start

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#154]
http://toastytech.com/guis/PTFO211.zip

The program says there is not enough memory, then segfaults.
After the segfault it is impossible to exit the app. If to kill otvdm, the taskbar becomes unaccessible (ignores clicks).

The cursor icon inside the app is also wrong (black square).

The game.exe in the program folder also does not properly display the contents, then crashes otvdm entirely.

**Comment by cracyc** [comment]
This program is a disaster.  Don't try it and don't expect it to ever work properly.
