### ISSUE TITLE
Otvdm does not detect if the system already supports .hlp files

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#155]
I have installed the Microsoft update for the system to support the .hlp files (WinHlp32.exe) but Win16 programs open those files in WinHlp32.exe that comes with otvdm.

**Comment by Anixx** [comment]
For instance, the help file for Civilization I can be opened by the Microsoft's help viewer:

![clipboard_20190209](https://user-images.githubusercontent.com/1271736/52526030-72eaae80-2cbb-11e9-9cb3-1d192c572cac.png)

but from the game it is opened in much worse Wine's implementation:

![clipboard_20190209 2](https://user-images.githubusercontent.com/1271736/52526048-a1688980-2cbb-11e9-829e-696a44157b89.png)

**Comment by Anixx** [comment]
Also, the icon for .hlp files gets changed when otvdm is installed, from the MS one to the one from Wine. There is no way to reverse this.

**Comment by otya128** [comment]
If you want to open .hlp with winhlp32.exe, please remove wine version of winhlp32.exe.
Placing Windows 3.1's winhelp.exe is desirable, if you can.

**Comment by Anixx** [comment]
Fixed.
