### ISSUE TITLE
Civilization I splash screens are painted and can be passed only if to move mouse

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#156]
For instance, if not to move mouse after starting civwin.exe, the first splash screen is just black box without any inscription, and does not progress. Similarly, after choosing a game to load, one has to move mouse to progress. Clicking is not necessary, but any move is needed.

**Comment by cracyc** [comment]
I don't get a hang but the animation is very choppy.  Commenting out MsgWaitForMultipleObjects or setting dwMilliseconds to 0 in PeekMessage16 fixes it but I suspect that would cause regressions elsewhere.

**Comment by Anixx** [comment]
In my case the splash screen completely stops without mouse move. I think this is not an expected behavior (especially when the splash screen is still empty).

**Comment by Anixx** [comment]
I do not experience this problem after updating to the current build.

**Comment by Anixx** [comment]
I reopen this because it emerged again. I cannot tell what it depends on.

**Comment by Anixx** [comment]
This is indeed fixed now.
