### ISSUE TITLE
Strange filename issue when trying to print to the XPS driver from MS Word 2.0c

### ISSUE THREAD

**Issue by neozeed** [otya128/winevdm#16]
![printing to xps](https://user-images.githubusercontent.com/9031439/44441725-aef06100-a600-11e8-9d65-4038385ab484.PNG)

Word generated this strange message:

"There is an unrecoverable disk error on th efile rosoft Word 2.0.

[winword_2.0c_print_xps.txt.gz]

And attached is the log file.
(https://github.com/otya128/winevdm/files/2308793/winword_2.0c_print_xps.txt.gz)

Oddly enough it's not all bad, I was able to print to a physical printer!

![printing from word 2 0c onto brother laser printer](https://user-images.githubusercontent.com/9031439/44441781-f4149300-a600-11e8-89b1-d91b4a643b6c.jpg)

**Comment by otya128** [comment]
I fixed the API to get paper size.

**Comment by neozeed** [comment]
Yep it works!  I could 'print' the readme.doc from Word 2


[Microsoft Word - README.DOC.oxps.zip](https://github.com/otya128/winevdm/files/2318844/Microsoft.Word.-.README.DOC.oxps.zip)
