### ISSUE TITLE
Folio Views 3.1 crashing

### ISSUE THREAD

**Issue by hmaecke** [otya128/winevdm#161]
I have quite a bunch of databases running with Folio VIEWS 3.1 as retrieval software. On opening an NFO file OTVDM gives an error and Folio VIEWS finally is crashing on aborting. Please find attached a log file.

Just let me know if you need an image or any further information for testing!

Thanks,
Hartmut

[WINEDBG_PM2.LOG](https://github.com/otya128/winevdm/files/2855811/WINEDBG_PM2.LOG)

**Comment by cracyc** [comment]
Not enough info really.  Probably needs to be examined directly to fix.

**Comment by hmaecke** [comment]
You van download a 90 MB image for testing here: [https://1drv.ms/u/s!Ash1J_VmEdi6j1_fhjSXNTSNYcxJ](url)

Thanks,
Hartmut

**Comment by hmaecke** [comment]
Works very well now - thanks a lot! 👍
