### ISSUE TITLE
Loderunner the legend returns fails to install and run.

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#168]
https://archive.org/details/lode_runner_the_legend_returns_windows_3.1

The installer exits with "error reading sources".

If to start the game directly, it first displays a message that there will be no sound. Then it enters menu. If to try to run the game, it segfaults.

**Comment by cracyc** [comment]
The installer won't work because the zip from archive.org is already installed and the source images (cdrom or floppies) are missing.
