### ISSUE TITLE
segment crash on Jezzball 

### ISSUE THREAD

**Issue by neozeed** [otya128/winevdm#17]
From The Best of Microsoft Entertainment Pack ...

[JEZZBALL.txt.gz](https://github.com/otya128/winevdm/files/2318860/JEZZBALL.txt.gz)
Crash message on build 4ffac02608f18d4111263c50ebfc73c8da5653dd 

[JEZZBALL.zip](https://github.com/otya128/winevdm/files/2318862/JEZZBALL.zip)
I had to hunt for this, but here it is, password is winevdm

It's worth mentioning that all the other games *DO* run!!! Totally awesome!

**Comment by cracyc** [comment]
```
2ab4:Ret  USER.135: GETWINDOWLONG() retval=ffff1005 ret=11ff:0063 ds=1217
SReg Load (0344ab17): Segment is not a data segment or readable code segment.
```
Here's the offending code 
```
cseg07:0045                 inc     bp
cseg07:0046                 push    bp
cseg07:0047                 mov     bp, sp
cseg07:0049                 push    ds
cseg07:004A                 push    [bp+arg_0]      ; HWND
cseg07:004D                 call    ISWINDOW
cseg07:0052                 or      ax, ax
cseg07:0054                 cwd
cseg07:0055                 jz      short loc_4CDC
cseg07:0057                 push    [bp+arg_0]      ; HWND
cseg07:005A                 mov     ax, 0FFFCh
cseg07:005D                 push    ax              ; int
cseg07:005E                 call    GETWINDOWLONG
cseg07:0063                 mov     bx, ax
cseg07:0065                 mov     es, dx
```
It's using the top 16bits of the GWL_WNDPROC return value as a selector.

**Comment by otya128** [comment]
This program seems to be trying to access the built-in WNDPROC...
Fixed not to crash when accessing.

**Comment by neozeed** [comment]
![demo on latest commit](https://user-images.githubusercontent.com/9031439/44617242-e32e8080-a891-11e8-8f00-ad31de0cbab9.png)
Demo mode from latest commit, does the job!

![jezz ball high score unreadable](https://user-images.githubusercontent.com/9031439/44617248-ec1f5200-a891-11e8-8a87-536f2730648b.png)
Although I don't know what the issue is with invisible colours... I guess I have to restrict the game to 256 colours?

![jezz ball high score unreadable 2](https://user-images.githubusercontent.com/9031439/44617256-fccfc800-a891-11e8-9b2c-b964df3e7d5e.png)
Highlighting the text shows that I did type something in.
