### ISSUE TITLE
No sound effects in Lode Runner

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#175]
https://archive.org/details/lode_runner_the_legend_returns_windows_3.1

Upon starting the game, there is a message box that there will be no sound in the game. When the game starts, the music works well, but the sound effect do not work (they are enabled in the menu).

**Comment by cracyc** [comment]
I can't repo this, it works fine here.

**Comment by Anixx** [comment]
![clipboard_20190219](https://user-images.githubusercontent.com/1271736/53016331-0ce9ee00-3456-11e9-8045-b79ba1db78a4.png)

**Comment by cracyc** [comment]
I don't know what to say.  I don't get that dialog and the sounds work.

**Comment by Anixx** [comment]
Works now.
