### ISSUE TITLE
Black box around baloon tips in LodeRunner

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#176]
https://archive.org/details/lode_runner_the_legend_returns_windows_3.1
![clipboard_20190218](https://user-images.githubusercontent.com/1271736/52952388-05aadd80-338d-11e9-9d82-b83a8b6ebed9.png)

**Comment by otya128** [comment]
It is probably a problem caused by dwm.
I do not know whether it is fixable.

**Comment by Anixx** [comment]
I confirm, without DWM everything is okay.
