### ISSUE TITLE
Microsoft entertainment packs do not install

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#178]
https://winworldpc.com/download/c39ac3b8-c2b5-10c3-95c5-a011c3a4efbf/from/c3ae6ee2-8099-713d-3411-c3a6e280947e

https://winworldpc.com/download/463a4f4a-7b44-11c3-a4c2-ac5a5404c2a6/from/c3ae6ee2-8099-713d-3411-c3a6e280947e

I tried MEP1 and MEP4. In both the setup does not start. If to unpack the files manually, they still do not work.

**Comment by cracyc** [comment]
MEP1 installed fine here.  The programs run without issue also.

**Comment by Anixx** [comment]
The problem was caused by the long path with long folder names.
