### ISSUE TITLE
Dispdib.dll and Int 10h

### ISSUE THREAD

**Issue by cracyc** [otya128/winevdm#18]
The version of dispdib that comes with [Nitemare 3d](https://archive.org/details/win3_Nite3d3x) calls into the vbios with interrupt 10h which appears to get handled as an coprocessor fault.

**Comment by otya128** [comment]
I fixed to handle int 10h.

**Comment by neozeed** [comment]
![nightmare - 3d for windows v1 6](https://user-images.githubusercontent.com/9031439/44627158-85666b00-a95b-11e8-9d3f-7fe490714532.png)

It runs in a windows on commit e08ee6a3557171bdfad326be18f3560aa96b716c

Going full screen, and it'll crash.... (does it matter?)

[nite3w_fullscreen_crash.txt.gz](https://github.com/otya128/winevdm/files/2321425/nite3w_fullscreen_crash.txt.gz)
