### ISSUE TITLE
No subpixel smoothing other than in the menu bar

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#182]
For instance:

![clipboard_20190218](https://user-images.githubusercontent.com/1271736/52973507-019bb180-33c7-11e9-8242-c6585cff0400.png)

**Comment by otya128** [comment]
For maximum compatibility, anti-aliasing is disabled by default. Appending EnableFontAntialias=1 to ini will enable anti-aliasing.

**Comment by Anixx** [comment]
It seems this option does not affect all places:

![clipboard_20190219](https://user-images.githubusercontent.com/1271736/53014727-fc377900-3451-11e9-8af1-22a4f98b0964.png)

**Comment by otya128** [comment]
The system font is not a TrueType but a bitmap font.

**Comment by Anixx** [comment]
I think this dialog does not use System font. It is the default fond set up systemwide (in my case, Tahoma). But still it has no subpixel antialiasing.

Other dialogs also do not use anti-aliasing despite the option and they do not use System font:
![clipboard_20190219 2](https://user-images.githubusercontent.com/1271736/53026390-7e806700-346b-11e9-9147-0fde7744364d.png)
![clipboard_20190219 3](https://user-images.githubusercontent.com/1271736/53026475-abcd1500-346b-11e9-9618-4d868796c9e4.png)
![clipboard_20190219 4](https://user-images.githubusercontent.com/1271736/53026509-bedfe500-346b-11e9-863d-f23b1ee2d17e.png)

**Comment by otya128** [comment]
The mentioned System font is a font named "System", not Tahoma.
Older 16-bit programs use that font.
It is usually impossible to change. (It is in HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\GRE_Initialize\SmallFont\FONTS.FON **BUT DO NOT MODIFY IT.**)
![image](https://user-images.githubusercontent.com/4075988/53089977-6256f580-3551-11e9-8a6f-e8f5236059d6.png)

**Comment by Anixx** [comment]
The above dialogs do not use System, they use Tahoma (which is the system font on my system).

**Comment by otya128** [comment]
It looks like "MS Dialog" and "MS Serif" font, you can substitute the font.
If it is not the System font, try substitute different fonts for "MS Dialog", "MS Serif" and "MS Sans Serif" font.

**Comment by Anixx** [comment]
Font substitution works, but subpixel smoothing still does not.
