### ISSUE TITLE
Microsoft Excel 2.0 segfaults on start

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#188]
It segfaults when trying to run. 

Also, the setup crashes after entering path to disk2.

**Comment by cracyc** [comment]
It tries to write to the cs segment which isn't permitted in protected mode.  I'm not sure if this will be fixable.

**Comment by cracyc** [comment]
I took another look at this.  The CS writes can be worked around with a fault handler but then it does segment arithmetic.  That can probably be patched up but then it pokes at the kernel data segment which is not at all reasonable to try and make work.  Just use Excel 2.1d which does none of this and is pretty much identical.
