### ISSUE TITLE
Word 2 installer crashes

### ISSUE THREAD

**Issue by malxau** [otya128/winevdm#19]
I grabbed a detailed log (attached), and it looks to be related to FindWindow.  Note that in Win32 FindWindow treats values <64k as being atoms, which I don't see as documented behavior in Win16.  The app is passing in a value <64k, which may be a legitimate string pointer - I don't see any calls to GlobalAddAtom etc in the log.  Perhaps these need to be double buffered?

[wordsetup.log](https://github.com/otya128/winevdm/files/2329484/wordsetup.log)

**Comment by malxau** [comment]
On second thoughts/second look, I'll bet this is really an INTRESOURCE and FindWindowEx16 wants to use find_win16_class and compare against the string in the returned structure rather than the class string passed to FindWindow.  Unfortunately FindWindow doesn't have an HINSTANCE...

**Comment by otya128** [comment]
I fixed to use GlobalGetAtomNameA when a string pointer less than 0xFFFF is passed in RegisterClass, CreateWindow, FindWindow.

**Comment by malxau** [comment]
Yes, I just fetched this, compiled it, and it works.  It also fixed the next issue in this installer which I thought was unrelated.  Thanks!
