### ISSUE TITLE
Balance of power segfaults on start.

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#193]
http://toastytech.com/guis/BOPIMA.zip

Unpack the disk image and run bop.exe

**Comment by cracyc** [comment]
This does all kinds of bad things that are illegal in protected mode.  Like the other real mode only programs, they don't work in win31 or ntvdm.  Just for the hell of it, I patched this one to work https://archive.org/details/bs666_1_hotmail_Bop .
