### ISSUE TITLE
Font smoothing option does not affect most programs

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#196]
Here is a screenshot from Terminal program from Windows Chicago build 58:

![clipboard_20190221](https://user-images.githubusercontent.com/1271736/53199856-d57f6b00-3628-11e9-9254-bc7d34ae36ee.png)

https://winworldpc.com/download/42c2b8c3-90c2-b218-c39a-11c3a4e284a2/from/c3ae6ee2-8099-713d-3411-c3a6e280947e

Since it is a pre-release version of Windows 95, this program looks very similar to 32-bit applications, even though technically it is 16-bit.

It uses Tahoma font which is default font I use in my theme.

Still, it does not use font smoothing, despite font smoothing is enabled both in the host system and in otvdm.ini as "EnableFontAntialias=1"

The same happens with the majority of other programs.

**Comment by otya128** [comment]
Because this program don't use tahoma.
Old programs use "Helv", "Tms Rmn", "MS Dialog", "System", "FixedSys", "MS Serif" and "MS Sans Serif" font.

**Comment by Anixx** [comment]
It uses MS Serif or MS Sans Serif. On my system they are aliases for Tahoma. This means, the actual font used in Tahoma, but it has no smoothing.
