### ISSUE TITLE
FindWindow, PROGMAN and DDE

### ISSUE THREAD

**Issue by cracyc** [otya128/winevdm#201]
The Civ2 installer uses FindWindow to locate a PROGMAN class window and sends DDE messages to it directly to create the program group.  This doesn't work because the progman atom is replaced with progman16 which explorer doesn't recognize.  Maybe winevdm's ddemlevent hwnd should be substituted in FindWindow.

**Comment by leecher1337** [comment]
I found a very strange DDE behaviour regarding progman, maybe you have an idea:
WOW32 sends a WM_DDE_INITIATE to HWND_BROADCAST and asks for Progman.
Explorer.exe has a window of class DDEMLMom which replies to the Broadcast message with WM_DDE_ACK, creates a new dde Message window and sends its handle via this message. So far, so good, 16bit app now knows DDE window of progman.
So next, application sends a WM_DDE_EXECUTE to mentioned handle via SendMessage(). I verified with Spy++ that the Window handle is correct. SendMessage doesn't return an error, however, I verified with a debugger attached to explorer.exe that the target Window procedure of the message handling window (I also checked that with Spy++) never gets called, so DDE message just gets swallowed, no WM_DDE_ACK, sending applications hangs.
Did you also experience this strange behaviour or do you have a hint on how to debug that?

**Comment by cracyc** [comment]
Yep, https://github.com/otya128/winevdm/pull/252

**Comment by leecher1337** [comment]
Hehe, found out a few hours ago, too:
https://github.com/leecher1337/ntvdmx64/commit/1ad4b98dc10d32fc8d834a5be603110034f61859
Thanks anyway :)
