### ISSUE TITLE
In  Excel 2.01 the window control button of MDI client window when it is miximized is a black square

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#212]
![Clipboard_20190310](https://user-images.githubusercontent.com/1271736/54078844-9283ef80-42d8-11e9-88ca-e681314ef1e7.png)

**Comment by cracyc** [comment]
This uses LoadBitmap with OBM_OLD_CLOSE to get the icon then bitblts it to a 1bpp bitmap.  I'm not sure why it ends up as a black square.  NTVDM does the same.

**Comment by otya128** [comment]
In Windows 3.1, OBM_OLD_CLOSE of vga.drv is a monochrome bitmap.

**Comment by Anixx** [comment]
Fixed.

**Comment by Anixx** [comment]
Shold not the MDI child also have this "old close" button when in restored state?

**Comment by cracyc** [comment]
It draws the icon itself when maximized but not when windowed.
