### ISSUE TITLE
Excel 2.01d does not see expanded memory

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#213]
And the font selection dialog brings message "out of memory"

**Comment by otya128** [comment]
Perhaps Excel 2 can not handle a lot of fonts installed on modern computers.
Please try EnumFontLimitation=1.

**Comment by Anixx** [comment]
In the About dialog iut says there is no expanded memory.

**Comment by cracyc** [comment]
Expanded memory refers to LIM EMS and is not accessible for windows programs in protected mode.  If you run it in Windows 3.1 you'll still see 0KB expanded memory.
