### ISSUE TITLE
Artifacts around window control buttons of MDI child in Excel 3.0 and Excel 4.0

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#214]
Around the menu button (top left) and around the restore button (top right) of the MDI child there are unintended artifacts. They appear for instance if to push the button, but move the mouse from the button before releasing it.

![Clipboard_20190310 (2)](https://user-images.githubusercontent.com/1271736/54079401-8f8efc00-42e4-11e9-9df0-4da59b0cc469.png)

The same problem is in Excel 4.

Also, look at the buttons when About dialog is called.

Also, other artifacts appear if to resize the window:

![Clipboard_20190310](https://user-images.githubusercontent.com/1271736/54079417-f90f0a80-42e4-11e9-9074-38432f432c1a.png)

**Comment by cracyc** [comment]
The black line next to the system menu and restore button is intentional to make it look like a button rather than a menu item which is what it is.  You can see why in this picture.  Ntvdm looks the same for the restore button (but somehow it uses the MDI window icon for the system menu even though excel uses LoadBitmap with OBM_CLOSE, there must be some special case for this somewhere in ntvdm gdi).

![win31excel](https://user-images.githubusercontent.com/9255333/54097325-9453be80-437d-11e9-9865-57b244dbdb8f.png)

**Comment by Anixx** [comment]
> The black line next to the system menu and restore button is intentional 

No, initially there are no artifacts:

![Clipboard_20190312 (2)](https://user-images.githubusercontent.com/1271736/54211718-78216000-44ea-11e9-8802-2c9ac1c1264f.png)

Then the vertical or horizontal line appears, on mouse hover or MDI window maximize (from restore).

Horizontal line:
![Clipboard_20190312 (4)](https://user-images.githubusercontent.com/1271736/54211997-ed8d3080-44ea-11e9-9e76-87f7e977cfeb.png)

Also, the borders on the right button disappear on mouse hover.

**Comment by Anixx** [comment]
No, initially there are no artifacts:

![Clipboard_20190312 (5)](https://user-images.githubusercontent.com/1271736/54213340-eb2bd600-44ec-11e9-9bfa-c664a771cbbf.png)

Then vertical and/or horizontal lines appear on mouse hover or window maximize.
Two lines, a white vertical and black horizontal:

![Clipboard_20190312 (2)](https://user-images.githubusercontent.com/1271736/54213421-0991d180-44ed-11e9-908f-aa5223072455.png)

Only horizontal:
![Clipboard_20190312 (3)](https://user-images.githubusercontent.com/1271736/54213494-275f3680-44ed-11e9-800a-351c1ca33733.png)

Also the right button loses the borders on mouse hover:
![Clipboard_20190312 (4)](https://user-images.githubusercontent.com/1271736/54213551-4067e780-44ed-11e9-8c78-f862914c4512.png)

When the window is not active:

![sn](https://user-images.githubusercontent.com/1271736/54213570-4b227c80-44ed-11e9-98c0-1594eac2f7bb.PNG)

**Comment by cracyc** [comment]
Well, I can't reproduce this in Windows 10.  If you are using a windows version that has 3d effect rather than flat menus that might cause this because it won't expect to have to redraw the menu like that.

> When the window is not active:

This also happens in XP/Ntvdm (it then bluescreens the VM).

**Comment by Anixx** [comment]
By the way, why on your screenshot the column and row headers look like buttons while on my screenshots they look like ordinary cells? 

Also, what icons the MDI childs have (when minimized) in Win 3.1?

**Comment by cracyc** [comment]
For me they looks light very light buttons.  It probably depends on the system color scheme.
![Capture](https://user-images.githubusercontent.com/9255333/54247154-d60f7100-4505-11e9-8854-89a957dae714.PNG)

>Also, what icons the MDI childs have (when minimized) in Win 3.1?

They are the same as the unmaximized system menu icon.

**Comment by Anixx** [comment]
> For me they looks light very light buttons. It probably depends on the system color scheme.

Definitely, not. Is it Excel 4? Also I see that the Excel icon in the left corner looks better on your screenshot.

> They are the same as the unmaximized system menu icon.

And what the unmaximized system menu icons are? On my system they are the default icons.
![s](https://user-images.githubusercontent.com/1271736/54251113-ea2b9080-454e-11e9-82f9-654208fc0665.PNG)

**Comment by cracyc** [comment]
![Capture](https://user-images.githubusercontent.com/9255333/54305445-4fa27000-4595-11e9-88f8-f066c5ed6ad0.PNG)
![Capture](https://user-images.githubusercontent.com/9255333/54305495-69dc4e00-4595-11e9-9da0-26d7ec9695f2.PNG)

>Definitely, not. Is it Excel 4? Also I see that the Excel icon in the left corner looks better on your screenshot.

![Capture](https://user-images.githubusercontent.com/9255333/54305589-9f813700-4595-11e9-9297-dec9511c06c6.PNG)

**Comment by Anixx** [comment]
Strange, the isons are resized well on your system, unlike mine.

**Comment by Anixx** [comment]
I also wonder why you have the Excel window icon and the child icon so good-looking after resize?

On my system they are looking ugly (as most icons in Win16 apps if resized from 32px to 16px).

**Comment by Anixx** [comment]
In Excel the artifacts still appear on the restore button of the MDI child (top right corner). The sysmenu button of the child is indeed fixed.

**Comment by cracyc** [comment]
As far a I can tell, the restore button looks exactly the same in ntvdm as in winevdm.

**Comment by Anixx** [comment]
I am referring to the artifacts on the restore button that appear after hover and also the button's disappearance when the Excel window is not active.

**Comment by cracyc** [comment]
I don't see the button change at all when hovering.  It disappears in ntvdm also.

**Comment by Anixx** [comment]
After hover the left border of the button disappears and the right border becomed 1-px wide:
![Clipboard_20191030 (4)](https://user-images.githubusercontent.com/1271736/67892428-61a14500-fb5d-11e9-8bda-b3fb6cc0c796.png)

**Comment by Anixx** [comment]
If to press the button and then remove the mouse, also black lines around the button appear.

**Comment by Anixx** [comment]
Do I understand this correctly, the bitmaps do not get painted because modern Windows versions do not allow it and only support icons there? Maybe then just convert the bitmaps to icons on the fly? Or simply prohibit putting bitmaps there?

**Comment by cracyc** [comment]
It's because they are menu items and get grayed just like the text.  With real mdi programs they are still menu items but they get special cased so they look like buttons and don't turn gray.  Excel fakes the mdi so those special cases don't apply unless the left most item is a HBMMENU_SYSTEM bitmap where it replaces the regular system menu icon with the maximized child icon.  The fake buttons were created for win31 style drawing but win95+ is different enough so small issues will happen so any artifacts like you have on the restore button are probably dependent on many variables which is why it doesn't happen on my computer.
