### ISSUE TITLE
Fine Artist does not install

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#219]
I wonder whether it is my only issue (other people reported it worked), but Fine Artist installer does not install all necessary files and exits without a message. If to start Fine Artist executable after ithe installer quits, the following message appears:

![Clipboard_20190312](https://user-images.githubusercontent.com/1271736/54211231-a3577f80-44e9-11e9-8944-66bb64c2dca4.png)

And, indeed, the dll is absent.

**Comment by cracyc** [comment]
The dll is placed in the windows\system directory.  It doesn't seem to work unless run from cmd though.

**Comment by Anixx** [comment]
Well, now it seemingly installs, but the program segfaults on start.

**Comment by Anixx** [comment]
Seems fixed.
