### ISSUE TITLE
Unable to load DLL's from the virtual Windows\System directory

### ISSUE THREAD

**Issue by neozeed** [otya128/winevdm#22]
So I installed Windows 3.1 into dosbox, and access into c:\win16app\access

Then I coped the Windows into the c:\winevdm\windows directory and tried to run access ...

```
C:\win16app\ACCESS>\WineVDM\otvdm.exe MSACCESS.EXE
Could not load 'MSAJT200.DLL' required by 'MSACCESS', error=2

C:\win16app\ACCESS>dir \WineVDM\msajt200.dll /s
 Volume in drive C is Windows
 Volume Serial Number is EEC2-EAD7

 Directory of C:\WineVDM\windows\SYSTEM

09/01/2018  01:44 AM           994,496 MSAJT200.DLL
               1 File(s)        994,496 bytes

```

As you can see the file is there...

**Comment by otya128** [comment]
What error did you see?
I tried the latest commit but seemed to be able to load the DLL successfully from the virtual SYSTEM directory.
It is considered that another WINDIR is specified in otvdm.ini, or some kind of error has occurred in the DLL.

**Comment by TzOk83** [comment]
Try c:\winevdm\dll\windows instead of c:\winevdm\windows.

**Comment by neozeed** [comment]
I didn't realize that in the ini it has to be the full path to the virtual windows directory...

; Redirect windows directory
WINDIR=c:\winevdm\WINDOWS

works well enough

**Comment by otya128** [comment]
In v0.5.0 binary, the search process of the virtual WINDOWS directory seems to be wrong.
As a workaround, move dll\krnl386.exe16 to the directory where otvdm.exe is located.
