### ISSUE TITLE
SEGV Error Running 16bit Installer

### ISSUE THREAD

**Issue by sigmatechnologies** [otya128/winevdm#221]
First of all, I want to say that providing 16bit support on x64 based windows is awesome! Keep up the great work!

I'm attempting to run a Visual Basic 6.0 ActiveX Control installer called TabPro. I believe the installer was generated by Wise Installation System.  I attached a screen shot of the error itself. I also attached what I hope will be useful verbose log.

Thanks again for breathing life back into old software!

![image](https://user-images.githubusercontent.com/26175310/54241131-38f50e00-44ee-11e9-87bb-ae980f4d72eb.png)

[tabprolog.txt](https://github.com/otya128/winevdm/files/2959033/tabprolog.txt)

**Comment by otya128** [comment]
Perhaps I fixed this issue.
You can download the latest version from [here](
https://ci.appveyor.com/project/otya128/winevdm/builds/23038967/artifacts).
