### ISSUE TITLE
PC PaintBrush crushes on "clear" command

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#227]
http://toastytech.com/guis/pbrushwin122.zip

**Comment by Anixx** [comment]
![Clipboard_20190318](https://user-images.githubusercontent.com/1271736/54557335-8c220180-49c3-11e9-88a8-298cd1982531.png)

**Comment by cracyc** [comment]
Use the clear option.  Note that it behaves poorly in 32bit color mode, it was written when 16 colors was the max number of colors available (it works somewhat better in 256 color compat mode but sill not quite right).

**Comment by Anixx** [comment]
"Clear" instantly crashes the app

**Comment by Anixx** [comment]
[pb.zip](https://github.com/otya128/winevdm/files/2980452/pb.zip)

**Comment by cracyc** [comment]
I don't know what happened there but somehow PostQuitMessage was called while the dialog box was open which caused the program to exit.  I can't make the happen here.

**Comment by Anixx** [comment]
The problem is still there. Also on each secont start an error message is displayed:
![Clipboard_20191028](https://user-images.githubusercontent.com/1271736/67682433-02460800-f998-11e9-99ec-d30eed3cd4c7.png)

**Comment by Anixx** [comment]
Still exits on "clear" command.

**Comment by Anixx** [comment]
Also, sometimes starts and sometimes don't showing the error message posted above.

**Comment by Anixx** [comment]
Seems no crash any more, closing.
