### ISSUE TITLE
In SimLife help does not work

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#232]
Also, there is no sound.

**Comment by cracyc** [comment]
The music seems flaky.  It'll play but stop completely if the window loses focus.  The sounds are bad digital audio that only play when there's an event like disasters.  Help works fine with winehelp afaict.

**Comment by Anixx** [comment]
Help does not work with either Winhlp32 from MS or with that from Winevdm. Even if to open the help files directly.

**Comment by Anixx** [comment]
The message is "Impossible to open the help file, try to move it to another drive and retry".

Also, the program crashes on start in about 2/3 attempts to start it.

**Comment by Anixx** [comment]
The help files only have problems with MS Winhlp32. They are opened well in Winhlp32 from Wine. Too old format?

**Comment by Anixx** [comment]
Closing as the help format is outdated and other issues seem to be fixed.
