### ISSUE TITLE
Midas calculator has wrong window size

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#242]
![Clipboard_20190328](https://user-images.githubusercontent.com/1271736/55193667-4f6abd00-51b0-11e9-9bc3-12cba5a91ecf.png)
Can be found here:
http://toastytech.com/guis/morewin2.zip

**Comment by cracyc** [comment]
This is a logic error in the program.  It calculates the window size from the screen size and at 1920x1080 it overflows.
