### ISSUE TITLE
Layout in Win 1.0 control panel is wrong

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#249]
![Clipboard_20190403](https://user-images.githubusercontent.com/1271736/55436367-c59e6380-55a4-11e9-8336-7a2a5ffb2582.png)

**Comment by cracyc** [comment]
![Capture](https://user-images.githubusercontent.com/9255333/55486876-ae866280-55f2-11e9-9856-3267bc838a23.PNG)
Works okay here...

**Comment by Anixx** [comment]
The bug is still there. In the date/time screen the layout is also wrong:
![Clipboard_20190504](https://user-images.githubusercontent.com/1271736/57184543-8aee5a80-6ec5-11e9-9305-29f5643c7c26.png)

**Comment by Anixx** [comment]
This screenshot shows that other people also experience this problem under Win9x:

http://toastytech.com/guis/miscwin12.png

And the text here http://toastytech.com/guis/misc.html says "Off hand I don't know exactly why stuff is shifted around." So, this is not a WineVDM problem.
