### ISSUE TITLE
Windows 1.0 apps have no maximize/minimize buttons even though under Win 1 and Win 2 they had such options

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#251]
Maximize and restore were called "Zoom", and minimize was called "Icon". These options were available from the window menu or via double-click on the window titlebar. I think all resizable Win 1.0 windows should have attribute "WS_OVERLAPPEDWINDOW".

**Comment by Anixx** [comment]
Notepad from Win 1.0 as it looks now:
![Clipboard_20190403 (2)](https://user-images.githubusercontent.com/1271736/55441252-d229b880-55b2-11e9-8491-37e179198a2a.png)

Notepad from Win 1.0 after adding WS_OVERLAPPEDWINDOW and WS_EX_OVERLAPPEDWINDOW:
![Clipboard_20190403](https://user-images.githubusercontent.com/1271736/55441330-14eb9080-55b3-11e9-8a30-f4e86b6bb810.png)

**Comment by cracyc** [comment]
Win3.0 and up behave like winevdm does.  Win2.0 does add minimize and maximize buttons for win1.0 programs.  If the conditions under which they are added can be determined IMO the change would be okay otherwise overridding the styles in CreateWindow is likely to break windows that explicitly exclude those styles.

**Comment by Anixx** [comment]
The author here: http://toastytech.com/guis/misc.html says "All I had to do was set some bits in the header to make it think it was a Windows 2.x executable".
This means that Windows possibly determines whether a program is for Win 1.0 from the executable's header.

**Comment by cracyc** [comment]
Windows 2.0 adds the minimize and maximize buttons if the window has WS_CAPTION and WS_SIZEBOX style.

**Comment by Anixx** [comment]
Notepad from Windows 1.0 still has no maximize button

**Comment by Anixx** [comment]
In the release version of notepad everything is OK.
