### ISSUE TITLE
In Winword 1, the font name and font size selection combo boxes are empty

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#259]
The drop-down lists in those controls do not contain any items.

**Comment by cracyc** [comment]
It does the same even in win20.  If you type a font name and size into the text field it will use that font.  I'm not sure how to populate the combo box.

**Comment by cracyc** [comment]
Oddly, the drop down, on my computer, is populated now.  I double checked and it's empty on win2 and 3.  I don't know what changed.
