### ISSUE TITLE
WordPerfect 5.2 errors

### ISSUE THREAD

**Issue by emendelson** [otya128/winevdm#260]
Recent fixes have been very valuable. Thank you for these. Working with the latest appveyor build, I tried installing WordPerfect for Windows 5.2. The installation went perfectly, but when I launched WPWIN.EXE, I got this error message:

Shared Code Error
Unable to execute WPCDLL.EXE

And when I clicked OK, another message appeared:

Cannot initialize - The most probable reason is insufficient memory.

I haven't tried WPWin 6.x with the latest code, but will try to do so soon. This report is about WPWin 5.2 only.

**Comment by cracyc** [comment]
https://github.com/otya128/winevdm/pull/253 fixes this problem.
