### ISSUE TITLE
batch of errors in the corel draw suite 5.00

### ISSUE THREAD

**Issue by WINEVDMbetaTester** [otya128/winevdm#262]
I have tested the entire suite and all programs give errors similar to this one.

https://i.ibb.co/Fx4v05V/Err6.jpg

and

https://i.ibb.co/QrL4XpJ/Err7.jpg

**Comment by cracyc** [comment]
This has selfloading dlls that also have circular dependencies.  That doesn't currently work.

**Comment by WINEVDMbetaTester** [comment]
Well, I'll be testing the 2 and the 3.
