### ISSUE TITLE
MGFX Portfolio shows garbage after window resize

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#264]
![Clipboard_20190416 (2)](https://user-images.githubusercontent.com/1271736/56195346-74c74a00-603d-11e9-873f-c3f74dcde08f.png)

**Comment by cracyc** [comment]
I'm not certain but I suspect this is because it's a windows 1.0 program and thus doesn't handle resizing properly.  You can use the redraw option in the view menu to clear it up.
