### ISSUE TITLE
Calendar Creator Plus does not start

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#269]
https://winworldpc.com/download/e280a026-6d07-c3bc-c2bf-11c3a6c2bb2a/from/71c2ad43-2482-11e8-a4ce-fa163e9022f0

The program exits without a message after splash screen.

**Comment by cracyc** [comment]
It works for me...

**Comment by Anixx** [comment]
[ccwin.zip](https://github.com/otya128/winevdm/files/3093990/ccwin.zip)

Added backtrace

**Comment by Anixx** [comment]
The programm is still there (with default install). Non-default install cannot be completed at all.

**Comment by Anixx** [comment]
Seems fixed
