### ISSUE TITLE
Zombie Wars segfaults on game start

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#272]
https://www.classicdosgames.com/game/Zombie_Wars.html

**Comment by cracyc** [comment]
I can't repo this.

**Comment by Anixx** [comment]
If after the segfault choose "continue" the game area remains black, but it is possible to exit the program via menu.

Backtrace attached.
[zwars.zip](https://github.com/otya128/winevdm/files/3094045/zwars.zip)

**Comment by Anixx** [comment]
Works for me now.
