### ISSUE TITLE
Compile with MinGW-win32 for ReactOS?

### ISSUE THREAD

**Issue by roytam1** [otya128/winevdm#28]
I wonder if this project can compile with MingW(GCC) targeting Win32, to make a working win16 support for ReactOS?

**Comment by otya128** [comment]
I think that it is possible.
However, this project has been changed from wine so that it can be compiled with MSVC ++ (language extension, inline assembler, etc.).
It also fills the difference between the behavior of wine and windows.
Therefore, porting may be serious.

**Comment by jeditobe** [comment]
ReactOS really needs this stuff

**Comment by binarymaster** [comment]
Who and why pinged me? 🙄

**Comment by otya128** [comment]
[The latest version](https://ci.appveyor.com/project/otya128/winevdm/builds/24619883/job/feaouxtv49bv6vv5) works on ReactOS.
![image](https://user-images.githubusercontent.com/4075988/57930570-4618e980-78f1-11e9-88a1-72ca55ba0239.png)

**Comment by roytam1** [comment]
so you created 2 workarounds to make it work in ReactOS. Could you please file them in ReactOS' issue tracker (jira) so they will not be needed in the future?
