### ISSUE TITLE
In Winword 1.0 the buttons in dialogs do not have the side walls

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#292]
![ww1](https://user-images.githubusercontent.com/1271736/57028646-4c983780-6c48-11e9-9b42-e28f5a7c0cbb.PNG)

**Comment by cracyc** [comment]
This, I think, is the same as https://github.com/otya128/winevdm/issues/183.  I tried using DS_FIXEDSYS with old task dialogs but it didn't work.
