### ISSUE TITLE
Some applications (such as Star Traders) display titelbars and window borders from Aero Lite theme

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#293]
Star Traders (http://www.zap.org.au/software/trader/historic/win16/released/):

![Clipboard_20190502](https://user-images.githubusercontent.com/1271736/57061502-bc003c80-6cc5-11e9-9c12-371c4cfca223.png)
![Clipboard_20190502 (2)](https://user-images.githubusercontent.com/1271736/57061515-d0443980-6cc5-11e9-82a3-5f654e3e1d94.png)

This happens when host system is not themed, and does not depend on the value of EnableVisualStyle and DisableAero options.

A similar issue has been largely fixed with https://github.com/otya128/winevdm/issues/148
but still remains a problem in other apps.

**Comment by Anixx** [comment]
Expect No Mercy and Age Of Sail installers have the same problem.

**Comment by Anixx** [comment]
May be related: https://github.com/otya128/winevdm/issues/239

**Comment by Anixx** [comment]
HP-12C emulator installer has the same issue:
http://files.mpoli.fi/software/WIN16/UTILS/MISC/HP12C12.ZIP

**Comment by cracyc** [comment]
4play also does this.  It appears to be caused by the program setting the WS_OVERLAPPED style without WS_CAPTION.  Unless there's something that actually breaks because of this I'd be inclined to not try to mess with it.

**Comment by Anixx** [comment]
I reopen this because the problem remains in Star Traders, Expect No Mercy and Age Of Sail installers.
