### ISSUE TITLE
Cannot start game normal way in Balance of Power (1990 edition)

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#298]
The game: http://dl.old-games.ru/get/afJoSm5JJbkppQ1KxS9rbQ==,1557395027/pc/balance_of_power_the_1990_edition/files/Balance_of_Power_1990.rar

When starting the game the program suggests to create a savefile. When you choose the folder, the savefile is created but a message displayed "error creating save file" and the program exits.

If to choose to load a game and select the created savefile, a segmentation fault occurs.

The game can be started by selecting "start new game" and then double-clicking on an existing file.

**Comment by cracyc** [comment]
For me this shows the same problem as the file find issue as in https://github.com/otya128/winevdm/issues/187 but only after the save is created.  If the file doesn't exist it shows the error always.  Loading an existing file works fine here.
