### ISSUE TITLE
In Balance of Power (1990 edition) the action dialogs are not movable.

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#299]
For instance, if after game start choose "USSR actions" or "USSR other" the modal dialogs that appear cannot be moved via titlebar and cannot be exited (the X is greyed out) so making the game unplayable.

http://dl.old-games.ru/get/afJoSm5JJbkppQ1KxS9rbQ==,1557395027/pc/balance_of_power_the_1990_edition/files/Balance_of_Power_1990.rar

**Comment by cracyc** [comment]
This behaves almost the same in NTVDM.  If you press esc it'll close the window (in ntvdm you have to be at the "Beginning of Folder").

**Comment by Anixx** [comment]
Oh I thought I tried ESC but now it indeed works. But the windows do not move. Possibly related to https://github.com/otya128/winevdm/issues/258 and https://github.com/otya128/winevdm/issues/296

**Comment by Anixx** [comment]
Also notice that the X is also greyed out at the main window as well. Possibly, all these X-es should be active.

**Comment by cracyc** [comment]
In ntvdm it's the same, X is disabled and the dialog isn't movable.  Also, in win31 the system menu lacks a close option and the dialog isn't movable.
