### ISSUE TITLE
Softkey PC paintbrush 1.0 does not start, cannot load a .drv file

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#304]
https://winworldpc.com/download/467658c3-b218-c39a-11c3-a4e284a2c3a5/from/71c2ad43-2482-11e8-a4ce-fa163e9022f0
It says "ZSOFT381.DRV is not found or out of memory". The file is in otvdm/windows directory.

**Comment by cracyc** [comment]
This is similar to corel photopaint in https://github.com/otya128/winevdm/issues/276.  Loading windows native device drivers is very difficult because it would require emulation of a large amount of the win16 gdi internals.
