### ISSUE TITLE
hook called with wrong ds

### ISSUE THREAD

**Issue by cracyc** [otya128/winevdm#309]
Toolbook 3.0 comes with a sysinfo program that calls setwindowshookex.  The hook is then called with the wrong selector in ax.  At https://github.com/otya128/winevdm/blob/master/user/hook.c#L328 ax is set to the hinstance that the hook is created with but ntvdm suggests that it should use the value that ds is set when called like makeprocinstance.  I'm not confident enough of this to make a pr though.

**Comment by WINEVDMbetaTester** [comment]
testing with the latest version.

```
version: 1238
0cb4:fixme:toolhelp:NotifyRegister16 493: (0,11ef00c2,0), semi-stub.
0cb4:fixme:toolhelp:InterruptRegister16 593: (0000, 11ef:00ca), semi-stub.
=====dump all modules=====
Module Flags Name Flag
 23c7   8301    TB30FLT     NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAG
S_CONSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 231f   0303    TBKNET3     NE_FFLAGS_SINGLEDATA | NE_FFLAGS_MULTIPLEDATA | NE_F
FLAGS_FRAMEBUF | NE_FFLAGS_CONSOLE | NE_FFLAGS_GUI
 2267   8021    TOOLHELP    NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 2077   8301    TB30EDT     NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAG
S_CONSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 1b2f   8301    TB30BAS     NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAG
S_CONSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 19cf   8301    TB30CMP     NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAG
S_CONSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 19b7   8021    SHELL       NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 199f   8021    OLECLI      NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 1987   8021    WIN87EM     NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 196f   8021    COMMDLG     NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 175f   8301    TB30UTL     NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAG
S_CONSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 119f   030a    TB30        NE_FFLAGS_MULTIPLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFL
AGS_CONSOLE | NE_FFLAGS_GUI
 1187   8021    SOUND       NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 116f   8021    MMSYSTEM    NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 1157   8021    MOUSE       NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 113f   8021    KEYBOARD    NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 1127   8021    DISPLAY     NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 110f   8021    USER        NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 10f7   8021    GDI         NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 10c7   8021    TIMER       NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 10af   8021    COMM        NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 1097   8021    SYSTEM      NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 1007   8021    KERNEL      NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
=====dump all modules=====
otvdm.exe       00380000
ntdll.dll       77E30000
kernel32.dll    76E90000
KERNELBASE.dll  76C60000
ADVAPI32.dll    77990000
msvcrt.dll      77260000
sechost.dll     77830000
RPCRT4.dll      77700000
SspiCli.dll     75990000
CRYPTBASE.dll   75980000
VCRUNTIME140.dll        6EED0000
api-ms-win-crt-runtime-l1-1-0.dll       6EF00000
ucrtbase.DLL    69450000
api-ms-win-core-timezone-l1-1-0.dll     6EEF0000
api-ms-win-core-file-l2-1-0.dll 6EEB0000
api-ms-win-core-localization-l1-2-0.dll 6EEC0000
api-ms-win-core-synch-l1-2-0.dll        74DE0000
api-ms-win-core-processthreads-l1-1-1.dll       6EE90000
api-ms-win-core-file-l1-2-0.dll 6EEA0000
api-ms-win-crt-string-l1-1-0.dll        6EE70000
api-ms-win-crt-heap-l1-1-0.dll  6EE80000
api-ms-win-crt-stdio-l1-1-0.dll 698E0000
api-ms-win-crt-convert-l1-1-0.dll       698F0000
api-ms-win-crt-environment-l1-1-0.dll   69890000
api-ms-win-crt-math-l1-1-0.dll  698A0000
api-ms-win-crt-locale-l1-1-0.dll        69870000
apphelp.dll     74EB0000
AcLayers.DLL    69580000
USER32.dll      76FC0000
GDI32.dll       77180000
LPK.dll 76FB0000
USP10.dll       76BC0000
SHELL32.dll     75CE0000
SHLWAPI.dll     770C0000
ole32.dll       76D30000
OLEAUT32.dll    759F0000
USERENV.dll     751C0000
profapi.dll     751B0000
WINSPOOL.DRV    693F0000
MPR.dll 73C20000
IMM32.DLL       77120000
MSCTF.dll       76930000
libwine.dll     69690000
api-ms-win-crt-filesystem-l1-1-0.dll    69880000
api-ms-win-crt-utility-l1-1-0.dll       69680000
krnl386.exe16   69350000
DSOUND.dll      6EAF0000
WINMM.dll       74DF0000
POWRPROF.dll    6F010000
SETUPAPI.dll    75B10000
CFGMGR32.dll    76B90000
DEVOBJ.dll      75AF0000
system.drv16    69560000
comm.drv16      69540000
timer.drv16     69330000
vm86.dll        692B0000
imagehlp.dll    75CB0000
gdi.exe16       69280000
user.exe16      690D0000
VERSION.dll     73B80000
UxTheme.dll     75000000
display.drv16   690B0000
keyboard.drv16  69090000
mouse.drv16     69070000
PROPSYS.dll     74CE0000
mmsystem.dll16  69040000
sound.drv16     69020000
ctl3dv2.dll16   69000000
ctl3d.dll16     68FE0000
commdlg.dll16   68FB0000
COMDLG32.dll    76CB0000
COMCTL32.dll    74BE0000
win87em.dll16   68F90000
olecli.dll16    68F70000
OLECLI32.dll    68F50000
shell.dll16     68F30000
toolhelp.dll16  68F10000
dbghelp.dll     73D40000
14: vm86.dll!load_x87function+0x5951 - 0x692f1d70 (null)(0)
13: ntdll.dll!strncpy+0x2cf - 0x77ea5c30 (null)(0)
12: ntdll.dll!RtlCaptureContext+0x187 - 0x77e76b2b (null)(0)
11: ntdll.dll!RtlDosSearchPath_Ustr+0x994 - 0x77e75fdf (null)(0)
10: ntdll.dll!KiUserExceptionDispatcher+0xf - 0x77e40134 (null)(0)
=============================
9: vm86.dll!KiUserExceptionDispatcher+0xfffffffff1488a77 - 0x77e40134 (null)(0)
=============================
8: vm86.dll!load_x87function+0x2168 - 0x692f1d70 (null)(0)
7: vm86.dll!vm_inject+0x1547 - 0x692f8430 (null)(0)
6: vm86.dll!wine_call_to_16_regs_vm86+0x53 - 0x692f7d20 (null)(0)
5: krnl386.exe16!K32WOWCallback16Ex+0x46c - 0x693a1cb0 (null)(0)
4: krnl386.exe16!LoadModule16+0x7a5 - 0x693861a0 (null)(0)
3: krnl386.exe16!RestoreThunkLock+0xfac - 0x693926b0 (null)(0)
2: kernel32.dll!BaseThreadInitThunk+0x12 - 0x76ea33b8 (null)(0)
1: ntdll.dll!RtlInitializeExceptionChain+0x63 - 0x77e69e6f (null)(0)
0: ntdll.dll!RtlInitializeExceptionChain+0x36 - 0x77e69e6f (null)(0)
cs:ip=16d7:1dff bp=8b2e                 args(16d7,3370,1757,0000,0000,0000,0000,
0401,8b90,0bd7)
cs:ip=16d7:0000 bp=8b75                 args(3370,1757,0000,0000,0000,0000,0401,
8b90,005c,0000)
cs:ip=16d7:0000 bp=8bbb                 args(0409,3370,1757,2400,0010,0000,8b00,
0000,0000,0000)
cs:ip=16d7:0000 bp=8bf7                 args(0409,3370,1757,6935,8c16,8eff,0097,
2486,0097,005e)
cs:ip=16d7:0000 bp=8c1b                 args(3370,1757,1757,8c39,011c,1207,0000,
1757,0000,0390)
cs:ip=1207:0f9b bp=8c27(call 1327:0000) args(0000,1757,0000,0390,129f,1757,8cdf,
03c6,129f,0001)
cs:ip=1207:011c bp=8c39                 args(0001,0000,4473,6365,6d69,6c61,5400,
3342,5c30,4254)
cs:ip=129f:03c6 bp=8cdf(call 1207:0000) args(0001,0081,11e7,1756,0000,0001,1757,
8d05,1619,11ff)
cs:ip=1257:0262 bp=8cf3(call 129f:0000) args(0001,0081,11e7,0000,1756,1757,0001,
00b4,11ff,0001)
cs:ip=11ff:1619 bp=8d05(call 1257:022a) args(0001,8d10,8f04,8d60,0000,1757,0000,
0000,045b,1027)
cs:ip=11ff:00b4 bp=0001                 args(8d30,0000,3dae,8668,8d18,0000,0000,
0000,0092,0000)
cs:ip=11ff:0000 bp=0000                 args(0005,8d30,0000,3dae,8668,8d18,0000,
0000,0000,0092)
========================
address=692B63FD
access address=00000000
VM context
EAX:0000,ECX:0001,EDX:C00001,EBX:00BE
ESP:8AF6,EBP:8B2E,ESI:0076,EDI:0000
ES:0001,CS:16D7,SS:1757,DS:1357,FS:0000,GS:0000
IP:1DFF, address:02CD63C7
EFLAGS:00003202

SEGV
```
version: 1238
0cb4:fixme:toolhelp:NotifyRegister16 493: (0,11ef00c2,0), semi-stub.
0cb4:fixme:toolhelp:InterruptRegister16 593: (0000, 11ef:00ca), semi-stub.
=====dump all modules=====
Module Flags Name Flag
 23c7   8301    TB30FLT     NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAG
S_CONSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 231f   0303    TBKNET3     NE_FFLAGS_SINGLEDATA | NE_FFLAGS_MULTIPLEDATA | NE_F
FLAGS_FRAMEBUF | NE_FFLAGS_CONSOLE | NE_FFLAGS_GUI
 2267   8021    TOOLHELP    NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 2077   8301    TB30EDT     NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAG
S_CONSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 1b2f   8301    TB30BAS     NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAG
S_CONSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 19cf   8301    TB30CMP     NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAG
S_CONSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 19b7   8021    SHELL       NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 199f   8021    OLECLI      NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 1987   8021    WIN87EM     NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 196f   8021    COMMDLG     NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 175f   8301    TB30UTL     NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAG
S_CONSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 119f   030a    TB30        NE_FFLAGS_MULTIPLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFL
AGS_CONSOLE | NE_FFLAGS_GUI
 1187   8021    SOUND       NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 116f   8021    MMSYSTEM    NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 1157   8021    MOUSE       NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 113f   8021    KEYBOARD    NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 1127   8021    DISPLAY     NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 110f   8021    USER        NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 10f7   8021    GDI         NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 10c7   8021    TIMER       NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 10af   8021    COMM        NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 1097   8021    SYSTEM      NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
 1007   8021    KERNEL      NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS
_LIBMODULE
=====dump all modules=====
otvdm.exe       00380000
ntdll.dll       77E30000
kernel32.dll    76E90000
KERNELBASE.dll  76C60000
ADVAPI32.dll    77990000
msvcrt.dll      77260000
sechost.dll     77830000
RPCRT4.dll      77700000
SspiCli.dll     75990000
CRYPTBASE.dll   75980000
VCRUNTIME140.dll        6EED0000
api-ms-win-crt-runtime-l1-1-0.dll       6EF00000
ucrtbase.DLL    69450000
api-ms-win-core-timezone-l1-1-0.dll     6EEF0000
api-ms-win-core-file-l2-1-0.dll 6EEB0000
api-ms-win-core-localization-l1-2-0.dll 6EEC0000
api-ms-win-core-synch-l1-2-0.dll        74DE0000
api-ms-win-core-processthreads-l1-1-1.dll       6EE90000
api-ms-win-core-file-l1-2-0.dll 6EEA0000
api-ms-win-crt-string-l1-1-0.dll        6EE70000
api-ms-win-crt-heap-l1-1-0.dll  6EE80000
api-ms-win-crt-stdio-l1-1-0.dll 698E0000
api-ms-win-crt-convert-l1-1-0.dll       698F0000
api-ms-win-crt-environment-l1-1-0.dll   69890000
api-ms-win-crt-math-l1-1-0.dll  698A0000
api-ms-win-crt-locale-l1-1-0.dll        69870000
apphelp.dll     74EB0000
AcLayers.DLL    69580000
USER32.dll      76FC0000
GDI32.dll       77180000
LPK.dll 76FB0000
USP10.dll       76BC0000
SHELL32.dll     75CE0000
SHLWAPI.dll     770C0000
ole32.dll       76D30000
OLEAUT32.dll    759F0000
USERENV.dll     751C0000
profapi.dll     751B0000
WINSPOOL.DRV    693F0000
MPR.dll 73C20000
IMM32.DLL       77120000
MSCTF.dll       76930000
libwine.dll     69690000
api-ms-win-crt-filesystem-l1-1-0.dll    69880000
api-ms-win-crt-utility-l1-1-0.dll       69680000
krnl386.exe16   69350000
DSOUND.dll      6EAF0000
WINMM.dll       74DF0000
POWRPROF.dll    6F010000
SETUPAPI.dll    75B10000
CFGMGR32.dll    76B90000
DEVOBJ.dll      75AF0000
system.drv16    69560000
comm.drv16      69540000
timer.drv16     69330000
vm86.dll        692B0000
imagehlp.dll    75CB0000
gdi.exe16       69280000
user.exe16      690D0000
VERSION.dll     73B80000
UxTheme.dll     75000000
display.drv16   690B0000
keyboard.drv16  69090000
mouse.drv16     69070000
PROPSYS.dll     74CE0000
mmsystem.dll16  69040000
sound.drv16     69020000
ctl3dv2.dll16   69000000
ctl3d.dll16     68FE0000
commdlg.dll16   68FB0000
COMDLG32.dll    76CB0000
COMCTL32.dll    74BE0000
win87em.dll16   68F90000
olecli.dll16    68F70000
OLECLI32.dll    68F50000
shell.dll16     68F30000
toolhelp.dll16  68F10000
dbghelp.dll     73D40000
14: vm86.dll!load_x87function+0x5951 - 0x692f1d70 (null)(0)
13: ntdll.dll!strncpy+0x2cf - 0x77ea5c30 (null)(0)
12: ntdll.dll!RtlCaptureContext+0x187 - 0x77e76b2b (null)(0)
11: ntdll.dll!RtlDosSearchPath_Ustr+0x994 - 0x77e75fdf (null)(0)
10: ntdll.dll!KiUserExceptionDispatcher+0xf - 0x77e40134 (null)(0)
=============================
9: vm86.dll!KiUserExceptionDispatcher+0xfffffffff1488a77 - 0x77e40134 (null)(0)
=============================
8: vm86.dll!load_x87function+0x2168 - 0x692f1d70 (null)(0)
7: vm86.dll!vm_inject+0x1547 - 0x692f8430 (null)(0)
6: vm86.dll!wine_call_to_16_regs_vm86+0x53 - 0x692f7d20 (null)(0)
5: krnl386.exe16!K32WOWCallback16Ex+0x46c - 0x693a1cb0 (null)(0)
4: krnl386.exe16!LoadModule16+0x7a5 - 0x693861a0 (null)(0)
3: krnl386.exe16!RestoreThunkLock+0xfac - 0x693926b0 (null)(0)
2: kernel32.dll!BaseThreadInitThunk+0x12 - 0x76ea33b8 (null)(0)
1: ntdll.dll!RtlInitializeExceptionChain+0x63 - 0x77e69e6f (null)(0)
0: ntdll.dll!RtlInitializeExceptionChain+0x36 - 0x77e69e6f (null)(0)
cs:ip=16d7:1dff bp=8b2e                 args(16d7,3370,1757,0000,0000,0000,0000,
0401,8b90,0bd7)
cs:ip=16d7:0000 bp=8b75                 args(3370,1757,0000,0000,0000,0000,0401,
8b90,005c,0000)
cs:ip=16d7:0000 bp=8bbb                 args(0409,3370,1757,2400,0010,0000,8b00,
0000,0000,0000)
cs:ip=16d7:0000 bp=8bf7                 args(0409,3370,1757,6935,8c16,8eff,0097,
2486,0097,005e)
cs:ip=16d7:0000 bp=8c1b                 args(3370,1757,1757,8c39,011c,1207,0000,
1757,0000,0390)
cs:ip=1207:0f9b bp=8c27(call 1327:0000) args(0000,1757,0000,0390,129f,1757,8cdf,
03c6,129f,0001)
cs:ip=1207:011c bp=8c39                 args(0001,0000,4473,6365,6d69,6c61,5400,
3342,5c30,4254)
cs:ip=129f:03c6 bp=8cdf(call 1207:0000) args(0001,0081,11e7,1756,0000,0001,1757,
8d05,1619,11ff)
cs:ip=1257:0262 bp=8cf3(call 129f:0000) args(0001,0081,11e7,0000,1756,1757,0001,
00b4,11ff,0001)
cs:ip=11ff:1619 bp=8d05(call 1257:022a) args(0001,8d10,8f04,8d60,0000,1757,0000,
0000,045b,1027)
cs:ip=11ff:00b4 bp=0001                 args(8d30,0000,3dae,8668,8d18,0000,0000,
0000,0092,0000)
cs:ip=11ff:0000 bp=0000                 args(0005,8d30,0000,3dae,8668,8d18,0000,
0000,0000,0092)
========================
address=692B63FD
access address=00000000
VM context
EAX:0000,ECX:0001,EDX:C00001,EBX:00BE
ESP:8AF6,EBP:8B2E,ESI:0076,EDI:0000
ES:0001,CS:16D7,SS:1757,DS:1357,FS:0000,GS:0000
IP:1DFF, address:02CD63C7
EFLAGS:00003202

SEGV
```

**Comment by cracyc** [comment]
That trace is for the main toolbook program with has a different problem than the sysinfo program that my report is about.

**Comment by WINEVDMbetaTester** [comment]
sysinfo is a program designed with the Toolbook?

I have tried to use 2 multimedia programs, designed with the 4.0 toolkit and I also have problems, blockages are generated at the beginning or for a few minutes after being in operation.

ToolBook 4 and 5 are in 16 bits, if I'm not mistaken, 6 also has a version in 16. Unfortunately, it is impossible to test these versions, they are not found anywhere.

**Comment by cracyc** [comment]
>sysinfo is a program designed with the Toolbook?

It's a program that comes with toolbook.

Testing shows that by default ax on hookproc entry is set to ss in both ntvdm and win31.  Makeprocinstance has to be used to set it to anything else.
