### ISSUE TITLE
ProQuest Searchware

### ISSUE THREAD

**Issue by hmaecke** [otya128/winevdm#312]
The quite common retrieval software ProQuest Searchware gives an error on starting: "Failed to initialize Fulcrum API." Then the program quits.

Please find attached the software. It should be starting scanning the drives for a data CD instead of showing the error above. Just let me know if you need more information or a CD for testing.

[pqsearch.zip](https://github.com/otya128/winevdm/files/3182552/pqsearch.zip)

Thanks,
Hartmut

**Comment by hmaecke** [comment]
Thanks, but https://ci.appveyor.com/project/otya128/winevdm/build/artifacts does not provide a setup?

**Comment by otya128** [comment]
https://ci.appveyor.com/project/otya128/winevdm

1. Click "Environment: THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1"
2. Click "Artifacts 1"
3. Click "otvdm-master-***.zip" to download

**Comment by hmaecke** [comment]
![image](https://user-images.githubusercontent.com/43235494/58026123-14349c80-7b16-11e9-92d0-6061a5082799.png)
