### ISSUE TITLE
Does not work on 64-bit NT 5.2 (XP/2003)

### ISSUE THREAD

**Issue by dsp2003** [otya128/winevdm#32]
As the title says, the emulator fails to work on 64-bit NT 5.2.

Even when you fix the target subsystem version from 6 to 4 via HEX editing, and it finally asks you to select the binary, it still cannot start the 16-bit application (you can see the drwtsn32.exe shortly spawning in the Task Manager, then quietly dying together with otvdm.exe).

**Comment by otya128** [comment]
VC++ runtime is probably not compatible with Windows XP.
I think that it is good to compile it for Windows XP.

**Comment by angrylion7** [comment]
Right now it seems that winevdm also stopped working on Windows 7, because it now needs a Windows10-specific SetThreadDpiAwarenessContext API.

**Comment by DXGLdotinfo** [comment]
For the SetThreadDpiAwarenessContext API you could always load the entry point via LoadLibrary and GetProcAddress.

**Comment by TheElf01** [comment]
The VC++ 2017 runtimes still are XP compatible

**Comment by otya128** [comment]
I succeeded in running on Windows XP.
![image](https://user-images.githubusercontent.com/4075988/53155383-44949980-3600-11e9-9f35-f14de005edd5.png)

**Comment by otya128** [comment]
[otvdm-winxp-1029.zip](https://github.com/otya128/winevdm/files/2888639/otvdm-winxp-1029.zip)

**Comment by dsp2003** [comment]
Thank you. <3

**Comment by TheElf01** [comment]
> 
> 
> [otvdm-winxp-1029.zip](https://github.com/otya128/winevdm/files/2888639/otvdm-winxp-1029.zip)

Thanks a lot! if working great

**Comment by dsp2003** [comment]
The vanilla build still doesn't work on XP, and this one is now outdated. Is it possible to have an universal build?

**Comment by TheElf01** [comment]
> 
> 
> The vanilla build still doesn't work on XP, and this one is now outdated. Is it possible to have an universal build?

+1  or at leasy, otya128 explain us what changes did you made at otvdm to work on XP, to make vanilla build XP compatible, thanks a lot

**Comment by otya128** [comment]
Currently, [GCC build](https://ci.appveyor.com/project/otya128/winevdm/builds/24533304/job/by23dgueogx9uo40/artifacts) supports Windows XP.
MSVC build does not support Windows XP and there are no plans to support it.

**Comment by TheElf01** [comment]
> 
> 
> Currently, [GCC build](https://ci.appveyor.com/project/otya128/winevdm/builds/24533304/job/by23dgueogx9uo40/artifacts) supports Windows XP.
> MSVC build does not support Windows XP and there are no plans to support it.


Thanks a lot.  I can now die peacefully,  playing tetris on XP x64

Great work
