### ISSUE TITLE
SimCity 1.0 breaks in GCC build, exiting with "C RUNTIME ERROR".

### ISSUE THREAD

**Issue by neozeed** [otya128/winevdm#321]
I know that this is the 'unstable' branch but I thought it may be worth mentioning.

I've attached the folder, and set a password of password if anyone needs a copy to test with.
[SIMCITYW.zip](https://github.com/otya128/winevdm/files/3194718/SIMCITYW.zip)

C:\WIN16APP\SIMCITYW>SET WINEDEBUG=+all,-snoop,-ldt,-fixup,-module,-global,-local,-disasm,-syslevel

0470:2f74:trace:loaddll:MODULE_LoadModule16 Loaded module "krnl386.exe" : builtin
0470:2f74:trace:dll:fill_init_list (krnl386.exe) - START
0470:2f74:trace:dll:fill_init_list (krnl386.exe) - END
0470:2f74:trace:dll:NE_CallDllEntryPoint Calling krnl386.exe DllEntryPoint, cs:ip=1017:1e83
0470:2f74:warn:dosmem:DOSMEM_Init First megabyte not available for DOS address space.
0470:2f74:trace:task:TASK_Create cmdline='SCW.EXE ' task=1047
0470:2f74:trace:loaddll:MODULE_LoadModule16 Loaded module "system.drv" : builtin
0470:2f74:trace:dll:fill_init_list (system.drv) - START
0470:2f74:trace:dll:fill_init_list (system.drv) - END
0470:2f74:trace:loaddll:MODULE_LoadModule16 Loaded module "comm.drv" : builtin
0470:2f74:trace:dll:fill_init_list (comm.drv) - START
0470:2f74:trace:dll:fill_init_list (comm.drv) - END
0470:2f74:trace:loaddll:MODULE_LoadModule16 Loaded module "timer.drv" : builtin
0470:2f74:trace:dll:fill_init_list (timer.drv) - START
0470:2f74:trace:dll:fill_init_list (timer.drv) - END
0470:2f74:trace:winevdm:set_dll_path L"C:\\WineVDM\\dll"
0470:2f74:trace:winevdm:main GetCommandLine = '\WineVDM\otvdm.exe  SCW.EXE '
0470:2f74:trace:winevdm:main appname = 'C:\WIN16APP\SIMCITYW\SCW.EXE'
0470:2f74:trace:winevdm:main cmdline = ''
0470:2f74:trace:winevdm:main argv[0]: '\WineVDM\otvdm.exe'
0470:2f74:trace:winevdm:main argv[1]: 'SCW.EXE'
0470:2f74:trace:loaddll:MODULE_LoadModule16 Loaded module "gdi.exe" : builtin
0470:2f74:trace:dll:fill_init_list (gdi.exe) - START
0470:2f74:trace:dll:fill_init_list (gdi.exe) - END
0470:2f74:trace:dll:NE_CallDllEntryPoint Calling gdi.exe DllEntryPoint, cs:ip=10ff:1dc6
0470:2f74:trace:shell:ShellDDEInit bInit = TRUE
0470:2f74:trace:loaddll:MODULE_LoadModule16 Loaded module "user.exe" : builtin
0470:2f74:trace:dll:fill_init_list (user.exe) - START
0470:2f74:trace:dll:fill_init_list (user.exe) - END
0470:2f74:trace:dll:NE_CallDllEntryPoint Calling user.exe DllEntryPoint, cs:ip=1117:2005
0470:2f74:trace:loaddll:MODULE_LoadModule16 Loaded module "display.drv" : builtin
0470:2f74:trace:dll:fill_init_list (display.drv) - START
0470:2f74:trace:dll:fill_init_list (display.drv) - END
0470:2f74:trace:loaddll:MODULE_LoadModule16 Loaded module "keyboard.drv" : builtin
0470:2f74:trace:dll:fill_init_list (keyboard.drv) - START
0470:2f74:trace:dll:fill_init_list (keyboard.drv) - END
0470:2f74:trace:loaddll:MODULE_LoadModule16 Loaded module "mouse.drv" : builtin
0470:2f74:trace:dll:fill_init_list (mouse.drv) - START
0470:2f74:trace:dll:fill_init_list (mouse.drv) - END
allocate HANDLE 003C0604=>0021
HANDLE3216 003C0604 0021
0470:2f74:trace:loaddll:MODULE_LoadModule16 Loaded module "mmsystem.dll" : builtin
0470:2f74:trace:dll:fill_init_list (mmsystem.dll) - START
0470:2f74:trace:dll:fill_init_list (mmsystem.dll) - END
0470:2f74:trace:dll:NE_CallDllEntryPoint Calling mmsystem.dll DllEntryPoint, cs:ip=1177:0561
0470:2f74:trace:loaddll:MODULE_LoadModule16 Loaded module "sound.drv" : builtin
0470:2f74:trace:dll:fill_init_list (sound.drv) - START
0470:2f74:trace:dll:fill_init_list (sound.drv) - END
0470:2f74:trace:file:OpenFile16 "C:\\WIN16APP\\SIMCITYW\\SCW.EXE" OF_READ OF_SHARE_DENY_WRITE
0470:2f74:trace:file:OpenFile16 found L"C:\\WIN16APP\\SIMCITYW\\SCW.EXE"
0470:2f74:trace:file:Win32HandleToDosFileHandle Got 5 for h32 00000330
0470:2f74:trace:file:OpenFile16 (C:\WIN16APP\SIMCITYW\SCW.EXE): OK, return = 00000330
0470:2f74:trace:file:_lclose16 5 (handle32=00000330)
0470:2f74:trace:loaddll:MODULE_LoadModule16 Loaded module "C:\\WIN16APP\\SIMCITYW\\SCW.EXE" : native
0470:2f74:trace:dosmem:DOSMEM_Available  9f9fh of 9fa0h paragraphs available
0470:2f74:trace:dosmem:DOSMEM_InitDosMemory DOS conventional memory initialized, 653808 bytes free.
0470:2f74:trace:task:TASK_Create cmdline='' task=11df
0470:2ecc:trace:file:OpenFile16 "RMTOOLS.dll" OF_READ OF_SHARE_DENY_WRITE
0470:2ecc:trace:file:OpenFile16 found L"C:\\WIN16APP\\SIMCITYW\\RMTOOLS.dll"
0470:2ecc:trace:file:Win32HandleToDosFileHandle Got 5 for h32 00000344
0470:2ecc:trace:file:OpenFile16 (RMTOOLS.dll): OK, return = 00000344
0470:2ecc:trace:file:_lclose16 5 (handle32=00000344)
0470:2ecc:trace:loaddll:MODULE_LoadModule16 Loaded module "RMTOOLS" : native
2ecc:CallTo16(func=11ff:0821,ds=136f) ss:sp=136f:a284 ax=0000 bx=6000 cx=1000 dx=0000 si=0000 di=136e bp=0000 es=11e7 fs=0053
2ecc:Call KERNEL.91: INITTASK() ret=11ff:0829 ds=136f
     AX=0000 BX=6000 CX=1000 DX=0000 SI=0000 DI=136e ES=11e7 EFL=00003246
0470:2ecc:trace:selector:SELECTOR_FreeBlock (1387,1)
0470:2ecc:trace:dll:NE_InitDLL Calling LibMain for RMTOOLS, cs:ip=1397:0000 ds=146f di=146e cx=b3b0
2ecc:CallTo16(func=1397:0000,ds=146f) ss:sp=136f:a24e ax=0000 bx=0000 cx=b3b0 dx=0000 si=0000 di=146e bp=a278 es=146f fs=0053
2ecc:Call KERNEL.4: LOCALINIT(146f,0000,b3b0) ret=1397:0011 ds=146f
2ecc:Ret  KERNEL.4: LOCALINIT() retval=00000001 ret=1397:0011 ds=146f
2ecc:RetFrom16() ss:sp=136f:a24e  ax=0001 bx=0000 cx=0001 dx=0000 bp=a278 sp=a24e
0470:2ecc:trace:selector:SELECTOR_FreeBlock (11af,1)
0470:2ecc:trace:dll:fill_init_list (C:\WIN16APP\SIMCITYW\SCW.EXE) - START
0470:2ecc:trace:dll:fill_init_list (C:\WIN16APP\SIMCITYW\RMTOOLS.DLL) - START
0470:2ecc:trace:dll:fill_init_list (krnl386.exe) - START
0470:2ecc:trace:dll:fill_init_list (krnl386.exe) - END
0470:2ecc:trace:dll:fill_init_list (gdi.exe) - START
0470:2ecc:trace:dll:fill_init_list (gdi.exe) - END
0470:2ecc:trace:dll:fill_init_list (user.exe) - START
0470:2ecc:trace:dll:fill_init_list (user.exe) - END
0470:2ecc:trace:dll:fill_init_list (sound.drv) - START
0470:2ecc:trace:dll:fill_init_list (sound.drv) - END
0470:2ecc:trace:dll:fill_init_list (C:\WIN16APP\SIMCITYW\RMTOOLS.DLL) - END
0470:2ecc:trace:dll:fill_init_list (C:\WIN16APP\SIMCITYW\SCW.EXE) - END
0470:2ecc:trace:dll:NE_CallDllEntryPoint Calling krnl386.exe DllEntryPoint, cs:ip=1017:1e83
0470:2ecc:trace:dll:NE_CallDllEntryPoint Calling gdi.exe DllEntryPoint, cs:ip=10ff:1dc6
0470:2ecc:trace:dll:NE_CallDllEntryPoint Calling user.exe DllEntryPoint, cs:ip=1117:2005
2ecc:Ret  KERNEL.91: INITTASK() retval=none ret=11ff:0829 ds=136f
     AX=0001 BX=0081 CX=4314 DX=0001 SI=0000 DI=136e ES=11e7 EFL=00003246
0470:2ecc:trace:int21:DOSVM_Int21Handler AX=3500 BX=0081 CX=4414 DX=0001 SI=0000 DI=136e DS=136f ES=11e7 EFL=00003202
0470:2ecc:trace:int21:DOSVM_Int21Handler GET INTERRUPT VECTOR 0x00
0470:2ecc:trace:int21:DOSVM_Int21Handler returning: AX=3500 BX=0000 CX=4414 DX=0001 SI=0000 DI=136e DS=136f ES=11c7 EFL=00003202
0470:2ecc:trace:int21:DOSVM_Int21Handler AX=2500 BX=0000 CX=4414 DX=1ea0 SI=0000 DI=136e DS=11ff ES=11c7 EFL=00003202
0470:2ecc:trace:int21:DOSVM_Int21Handler SET INTERRUPT VECTOR 0x00
0470:2ecc:trace:int:DOSVM_SetPMHandler16 Set protected mode interrupt vector 00 <- 11ff:1ea0
0470:2ecc:trace:int21:DOSVM_Int21Handler returning: AX=2500 BX=0000 CX=4414 DX=1ea0 SI=0000 DI=136e DS=11ff ES=11c7 EFL=00003202
0470:2ecc:trace:int21:DOSVM_Int21Handler AX=306f BX=0003 CX=0000 DX=11ff SI=2f00 DI=2f00 DS=136f ES=136f EFL=00003246
0470:2ecc:trace:int21:DOSVM_Int21Handler GET DOS VERSION - version flag requested
0470:2ecc:trace:int21:DOSVM_Int21Handler returning: AX=0005 BX=0812 CX=3456 DX=11ff SI=2f00 DI=2f00 DS=136f ES=136f EFL=00003246
2ecc:Call KERNEL.23: LOCKSEGMENT(ffff) ret=11ff:42d4 ds=136f
2ecc:Ret  KERNEL.23: LOCKSEGMENT() retval=0000136f ret=11ff:42d4 ds=136f
2ecc:Call KERNEL.5: LOCALALLOC(0020,0202) ret=11ff:42ed ds=136f
2ecc:Ret  KERNEL.5: LOCALALLOC() retval=0000a2c0 ret=11ff:42ed ds=136f
2ecc:Call KERNEL.24: UNLOCKSEGMENT(ffff) ret=11ff:42f9 ds=136f
2ecc:Ret  KERNEL.24: UNLOCKSEGMENT() retval=00000000 ret=11ff:42f9 ds=136f
2ecc:Call KERNEL.23: LOCKSEGMENT(ffff) ret=11ff:42d4 ds=136f
2ecc:Ret  KERNEL.23: LOCKSEGMENT() retval=0000136f ret=11ff:42d4 ds=136f
2ecc:Call KERNEL.5: LOCALALLOC(0020,0010) ret=11ff:42ed ds=136f
2ecc:Ret  KERNEL.5: LOCALALLOC() retval=0000a4c8 ret=11ff:42ed ds=136f
2ecc:Call KERNEL.24: UNLOCKSEGMENT(ffff) ret=11ff:42f9 ds=136f
2ecc:Ret  KERNEL.24: UNLOCKSEGMENT() retval=00000000 ret=11ff:42f9 ds=136f
2ecc:Call KERNEL.30: WAITEVENT(0000) ret=11ff:0866 ds=136f
2ecc:Ret  KERNEL.30: WAITEVENT() retval=00000000 ret=11ff:0866 ds=136f
2ecc:Call USER.5: INITAPP(136e) ret=11ff:086f ds=136f
2ecc:Ret  USER.5: INITAPP() retval=00000001 ret=11ff:086f ds=136f
2ecc:Call USER.176: LOADSTRING(136e,2335,136f:419a,0020) ret=142f:0162 ds=146f
0470:2ecc:trace:user:LoadString16 inst=136e id=2335 buff=03317512 len=32
0470:2ecc:trace:resource:FindResource16 module=119f name=#0234 type=#0006
0470:2ecc:trace:resource:NE_FindTypeSection   Skipping type 800f
0470:2ecc:trace:resource:NE_FindTypeSection   Skipping type 800c
0470:2ecc:trace:resource:NE_FindTypeSection   Skipping type 800e
0470:2ecc:trace:resource:NE_FindTypeSection   Skipping type 8004
0470:2ecc:trace:resource:NE_FindTypeSection   Skipping type 8005
0470:2ecc:trace:resource:NE_FindTypeSection   Found type 8006
0470:2ecc:trace:resource:FindResource16     Found id 00000234
0470:2ecc:trace:resource:AllocResource16 module=119f res=0368 size=0
0470:2ecc:trace:resource:WIN16_LockResource16 (1387)
0470:2ecc:trace:user:LoadString16 "SimCity for Windows" loaded
0470:2ecc:trace:resource:FreeResource16 (1387)
2ecc:Ret  USER.176: LOADSTRING() retval=00000013 ret=142f:0162 ds=146f
2ecc:Call USER.176: LOADSTRING(136e,23f0,136f:16c8,0200) ret=142f:0162 ds=146f
0470:2ecc:trace:user:LoadString16 inst=136e id=23f0 buff=03314A40 len=512
0470:2ecc:trace:resource:FindResource16 module=119f name=#0240 type=#0006
0470:2ecc:trace:resource:NE_FindTypeSection   Skipping type 800f
0470:2ecc:trace:resource:NE_FindTypeSection   Skipping type 800c
0470:2ecc:trace:resource:NE_FindTypeSection   Skipping type 800e
0470:2ecc:trace:resource:NE_FindTypeSection   Skipping type 8004
0470:2ecc:trace:resource:NE_FindTypeSection   Skipping type 8005
0470:2ecc:trace:resource:NE_FindTypeSection   Found type 8006
0470:2ecc:trace:resource:FindResource16     Found id 00000240
0470:2ecc:trace:resource:AllocResource16 module=119f res=02d8 size=0
0470:2ecc:trace:resource:WIN16_LockResource16 (147f)
0470:2ecc:trace:user:LoadString16 "1.0ds" loaded
0470:2ecc:trace:resource:FreeResource16 (147f)
2ecc:Ret  USER.176: LOADSTRING() retval=00000005 ret=142f:0162 ds=146f
2ecc:Call USER.50: FINDWINDOW(136f419a "SimCity for Windows",00000000 (null)) ret=125f:003e ds=136f
HANDLE1632 0000 00000000
HANDLE1632 0000 00000000
HANDLE3216 00000000 0000
2ecc:Ret  USER.50: FINDWINDOW() retval=00000000 ret=125f:003e ds=136f
2ecc:Call USER.47: ISWINDOW(0000) ret=125f:0046 ds=136f
HANDLE1632 0000 00000000
2ecc:Ret  USER.47: ISWINDOW() retval=00000000 ret=125f:0046 ds=136f
2ecc:Call KERNEL.95: LOADLIBRARY(146f1396 "GDI.EXE") ret=1467:02c8 ds=146f
2ecc:Ret  KERNEL.95: LOADLIBRARY() retval=00001107 ret=1467:02c8 ds=146f
2ecc:Call KERNEL.20: GLOBALSIZE(1107) ret=1467:03f3 ds=146f
2ecc:Ret  KERNEL.20: GLOBALSIZE() retval=00000020 ret=1467:03f3 ds=146f
2ecc:Call KERNEL.18: GLOBALLOCK(1107) ret=1467:0403 ds=146f
2ecc:Ret  KERNEL.18: GLOBALLOCK() retval=11070000 ret=1467:0403 ds=146f
2ecc:Call KERNEL.19: GLOBALUNLOCK(1107) ret=1467:0466 ds=146f
2ecc:Ret  KERNEL.19: GLOBALUNLOCK() retval=11070000 ret=1467:0466 ds=146f
2ecc:Call KERNEL.115: OUTPUTDEBUGSTRING(136f2fb6 "C RUNTIME ERROR ") ret=11ff:416e ds=136f
     AX=2fe5 BX=1107 CX=2fb6 DX=0003 SI=0000 DI=136e ES=136f EFL=00003002
2ecc:Ret  KERNEL.115: OUTPUTDEBUGSTRING() retval=none ret=11ff:416e ds=136f
     AX=2fe5 BX=1107 CX=2fb6 DX=0003 SI=0000 DI=136e ES=136f EFL=00003002
2ecc:Call KERNEL.115: OUTPUTDEBUGSTRING(136f2fe5 "R6003\r\n- integer divide by 0\r\n") ret=11ff:4175 ds=136f
     AX=2fe5 BX=1107 CX=2fb6 DX=0003 SI=0000 DI=136e ES=136f EFL=00003002
2ecc:Ret  KERNEL.115: OUTPUTDEBUGSTRING() retval=none ret=11ff:4175 ds=136f
     AX=2fe5 BX=1107 CX=2fb6 DX=0003 SI=0000 DI=136e ES=136f EFL=00003002
2ecc:Call KERNEL.137: FATALAPPEXIT(0000,136f2fb6 "C RUNTIME ERROR ") ret=11ff:1eb9 ds=136f
0470:2ecc:err:task:FatalAppExit16 "C RUNTIME ERROR "
0470:2ecc:trace:selector:SELECTOR_FreeBlock (11f7,1)
0470:2ecc:trace:task:TASK_ExitTask Killing task 11df
0470:2ecc:trace:selector:SELECTOR_FreeBlock (11af,1)
0470:2ecc:trace:task:TASK_ExitTask this is the last task, exiting

**Comment by cracyc** [comment]
I get an "insufficient system resources" error.  Your trace shows it failing in about the same place so the user and gdi heaps being only 20 bytes is probably the problem.

**Comment by otya128** [comment]
I've fixed to allocate enough local heap in a52517a59ca2ea646d92d727434d98576e515f74.

**Comment by neozeed** [comment]
Great that did it!

I tested what I have handy,   SimEarth, EXCEL 3, SimLife, SimCity and Word for Windows 2.0c
