### ISSUE TITLE
Battle chess regression

### ISSUE THREAD

**Issue by cracyc** [otya128/winevdm#324]
https://github.com/otya128/winevdm/commit/1288f8d3cf37622456129baed8b684ad9c7a2203 appears to have caused https://github.com/otya128/winevdm/issues/33 to return.

**Comment by parrotgeek1** [comment]
Why was this change even made?

**Comment by otya128** [comment]
1288f8d changed to assign a value to Win32ClientInfo.dwExpWinVer before Win32ClientInfo was initialized.
