### ISSUE TITLE
Smartdraw is unable to start

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#327]
http://mpolibbs.steptail.com/software/WIN16/GRAPHICS/SMRTDRAW.ZIP

**Comment by cracyc** [comment]
This fails in OLEREGISTERSERVER with OLE_ERROR_CLASS.  Seems like it can't write to the registry without EnableRegistryRedirection=1 and ole can't find the class in the registry with it.  If you run it once elevated then it'll set it's registry entries and work without issue even normally.

**Comment by Anixx** [comment]
I tried to run it from an elevated command prompt. It goes somewhat further but silently exits after "create new drawing" dialog or after choosing "new" from the pull-down menu.

**Comment by Anixx** [comment]
I think this may be connected to the fact I have no printing service running.
