### ISSUE TITLE
Graphics workshop segfaults on start

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#328]
http://mpolibbs.steptail.com/software/WIN16/GRAPHICS/GWSWN11N.ZIP

Graphics workshop segfaults on start. Plus, if to choose "continue" its main window does not use the icon from the executable.

**Comment by cracyc** [comment]
Seems to work without issue with the latest build.

**Comment by Anixx** [comment]
Still segfaults here.

**Comment by cracyc** [comment]
You seem to get lots of segfaults that I don't.  I'd like to know if there's one or multiples causes but I need traces to have any hope of finding out.

**Comment by Anixx** [comment]
Seems fixed
