### ISSUE TITLE
VistaRTM compat mode

### ISSUE THREAD

**Issue by cracyc** [otya128/winevdm#341]
Sometimes otvdm automatically enables vista compat mode.  This causes problems with Delphi icons.  I traced the problem to apphelp hooking getdc and releasedc and the hook running the message loop resulting in recursive message passing.  It's easy enough to disable but I'm wondering the reason for enabling it and noting that it can cause problems.

**Comment by otya128** [comment]
Required to enable NoPaddedBorder before user32.dll is loaded, but user32.dll may be loaded.
In that case, enable VistaRTM compatibility mode.
I just want to enable NoPaddedBorder, but I'm using VistaRTM compatible mode by compromise.
(It is possible by  using Microsoft compatibility administrator).

||NoPaddedBorder|
|---|---|
|![image](https://user-images.githubusercontent.com/4075988/58364501-5122d980-7ef0-11e9-990f-2c215ac79259.png)|![image](https://user-images.githubusercontent.com/4075988/58364486-f38e8d00-7eef-11e9-946d-6d9f877853d3.png)|
|![image](https://user-images.githubusercontent.com/4075988/58364507-6bf54e00-7ef0-11e9-928a-458a0b1179a0.png)|![image](https://user-images.githubusercontent.com/4075988/58364484-ebcee880-7eef-11e9-8eac-b74d48f0e711.png)|
