### ISSUE TITLE
Instant Recall locks up with full-text search

### ISSUE THREAD

**Issue by emendelson** [otya128/winevdm#360]
Instant Recall 2.1 was a popular information manager and address book for 16-bit Windows. It runs in winevdm, but with one problem: If you press Ctrl-W for a full-text search, enter a search string, and press Enter, then the application locks up, and otvdm.exe has to be shut down from the Task Manager.

I've put together a test system with a small database that shows the problem:

https://www.dropbox.com/s/8jovqqjm81c5zxc/IR-test.7z?dl=1

Unzip it so that the contents are in C:\IR, run the program, and press Ctrl-W, enter a search string, press Enter, and get the lockup.

You can also press Ctrl-F for a simpler search (for main entries only). That works perfectly, It's only Ctrl-W that causes the lockup.

I tested with the latest recommended build from Appveyor.

**Comment by cracyc** [comment]
This one seems pretty crazy.  The search progress dialog has an ownerdraw button placed way outside the dialog boundaries.  That button getting a WM_DRAWITEM message triggers the search to start.  In Windows 10 that button never gets the message but in xp/ntvdm it works properly.  If the button in moved into the dialog so it's visible, then it works in winevdm.  I'd be interested to know whether it works in Windows 10 x86 ntvdm to see if there's a workaround or if newer windows version just broke it.

**Comment by emendelson** [comment]
The Ctrl-W search works perfectly in 32-bit Windows 10, and I'll be glad to do any other test you need. 

I work mostly in 32-bit Windows 10, but dual-boot to 64-bit Win10 when necessary. One reason I'm so grateful for this project is that it will someday let me give up 32-bit Windows...

**Comment by cracyc** [comment]
Turns out this is related to the underlying problem in https://github.com/otya128/winevdm/issues/25.  According to https://jeffpar.github.io/kbarchive/kb/080/Q80898/ Windows 3.0 sends a lot of unnecessary WM_PAINT messages to windows which are visible but can't be seen.  In fact if you edit the header of irwin.exe or msdos.exe to set the version to 3.10, they behave in ntvdm just like winevdm.  So we need to figure out where the extra paints need to be done.

**Comment by emendelson** [comment]
Thanks for working on this! I hope the solution may be useful for other programs also...

**Comment by emendelson** [comment]
Just wanted to say Thank You for fixing this!
