### ISSUE TITLE
Unable to find unstable build

### ISSUE THREAD

**Issue by mauriciofaria** [otya128/winevdm#361]
I have an issue with an application that does not find the CD-ROM drive and, searching in the issues, seems it was addressed after the latest stable build.
I would like to test the unstable one in order to see if this CD-ROM issue is corrected or not, but the link in the README.md file points to the AppVeyor website and I was unable to find a download link for the binaries...
Is there one ? Or there are only the stable ones ?

**Comment by WINEVDMbetaTester** [comment]
I hope you understand my English

enter here https://ci.appveyor.com/project/otya128/winevdm . down click . on the one above (THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1) . and then in the artifacts section

**Comment by mauriciofaria** [comment]
Thanks, I found it.
Well, despite being an old developer, this was a bit hard for someone new to that environment...
Anyway thanks !
