### ISSUE TITLE
In Flight Commander 2 the minimap (overview map) is useless

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#363]
It does not display anything except a few dots.
![Clipboard_20190530](https://user-images.githubusercontent.com/1271736/58635819-81ef7e00-82f7-11e9-8f75-f6aaaa4d87db.png)

https://www.myabandonware.com/game/flight-commander-2-3jw#Windows%203.x

**Comment by cracyc** [comment]
That's what it is supposed to look like. https://www.youtube.com/watch?v=3nKzjwt-XkI
