### ISSUE TITLE
Problems with sound compressor detection

### ISSUE THREAD

**Issue by WINEVDMbetaTester** [otya128/winevdm#364]
I'm about to close one of the bug reports. is the one that refers to the encyclopedias.

I still have the problem with the Windows sound compressor. Which is notified at the beginning of the encyclopedia and leaves no possibility of opening it.

This will solve all the problems with the DK encyclopedias.

In the past, the error occurred when using XP, since the encyclopedias worked in Windows 3.1 to Windows ME. There was a patch to add some lines to the system.ini file, and this problem could be fixed. but it is not possible to find that patch anywhere.

Cracyc. You can download this encyclopedia and review this problem. I'm sure that reviewing the system.ini after installation could solve this whole problem.

 https://archive.org/details/EyewitnessHistoryOfTheWorldCD-ROMForWindowsISBN0-7894-0042-11995

**Comment by cracyc** [comment]
The ini fix doesn't work because winevdm doesn't support win16 codecs so I made a fix so it'll work with the win32 ones.  There are still drawing issues and the movies won't play in windows 10 unless you add 

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Drivers32]
"vidc.iv32"="C:\WINDOWS\system32\ir32_32.dll
```

to the registry.
