### ISSUE TITLE
Can't open 16 bit programs directly, and problem with Projector Skeleton

### ISSUE THREAD

**Issue by HomerBender77** [otya128/winevdm#376]
When I try to open 16-bit programs directly by clicking on the program (after of course having used the install.reg file), I get an error message saying that "the specified path does not exist" and that I should "check the path, and then try again." How can I fix this? Need I edit anything in the install.reg file? 

And also, certain programs which use Projector Skeleton (like the old Blue's Clues shockwave games) have distorted audio and the cursor is black instead of its normal color. How can this be fixed?

**Comment by cracyc** [comment]
You need to edit it following the instructions in it.

```
; good: "MappedExeName"="C:\\otvdm\\otvdm.exe"
; bad: "MappedExeName"="C:\otvdm\otvdm.exe"
; not recommended: "MappedExeName"="C:\\Windows\\otvdm\\otvdm.exe"
"MappedExeName"="C:\\PATH\\TO\\otvdm.exe"
```

**Comment by HomerBender77** [comment]
Thanks, cracyc. But what exactly should I add/remove to this section? Please give examples if you can.

**Comment by cracyc** [comment]
You need to replace "C:\\PATH\\TO\\otvdm.exe" with the full path on your computer to otvdm.exe.

**Comment by HomerBender77** [comment]
That did the trick. Thanks!
