### ISSUE TITLE
Seems to work with simple apps only?

### ISSUE THREAD

**Issue by hmaecke** [otya128/winevdm#40]
Trying a simple 16 bit executable works without a problem, but with a more complex app with dlls and ini files I get an error like this:

---------------------------
SEGV
---------------------------
address=00000000
access address=00000000
32bit
16bit context
EAX:5000000,ECX:132F,EDX:0000,EBX:0000
ESP:958E,EBP:95C0,ESI:0000,EDI:131E
ES:131F,CS:132F,SS:1267,DS:131F
IP:004C, address:00D0F3F4
EFLAGS:00003000

SEGV

---------------------------
Wiederholen   Abbrechen   
---------------------------

What does this mean and how can I fix it?

Thanks a lot for any ideas on this!

**Comment by otya128** [comment]
win16 APIs are roughly implemented, except for OLE and too old APIs.
To find the cause, I want a more verbose log, so please do the following steps.
1. Run cmd.exe
2. ```SET WINEDEBUG=+all,-snoop,-ldt,-fixup,-module,-global,-local,-disasm,-syslevel```
3. ```*exe-file* 2> *log-file*```
4. Upload log-file and tell the version

**Comment by hmaecke** [comment]
Thanks for your fast respond! I use the last stable build of OTVDM 0.5.0a on a WIndows 2008 R2 server.

Content of the log file is:

10d0:trace:winevdm:main 1115: GetCommandLine = 'otvdmw.exe  --app-name C:\HH\Prog.nm\CDEWIN\CDEWIN.EXE '
10d0:trace:winevdm:main 1116: appname = 'C:\HH\Prog.nm\CDEWIN\CDEWIN.EXE'
10d0:trace:winevdm:main 1117: cmdline = ''
10d0:trace:winevdm:main 1118: argv[0]: 'otvdmw.exe'
10d0:trace:winevdm:main 1118: argv[1]: '--app-name'
10d0:trace:winevdm:main 1118: argv[2]: 'C:\HH\Prog.nm\CDEWIN\CDEWIN.EXE'
10d0:trace:loaddll:MODULE_LoadModule16 1107: Loaded module "krnl386.exe" : builtin
10d0:trace:dll:fill_init_list 896: (krnl386.exe) - START
10d0:trace:dll:fill_init_list 912: (krnl386.exe) - END
10d0:trace:dll:NE_CallDllEntryPoint 779: Calling krnl386.exe DllEntryPoint, cs:ip=100f:1e43
10d0:warn:dosmem:DOSMEM_Init 420: First megabyte not available for DOS address space.
10d0:trace:task:TASK_Create 339: cmdline='--app-name C:\HH\Prog.nm\CDEWIN\CDEWIN.EXE ' task=103f
10d0:trace:loaddll:MODULE_LoadModule16 1107: Loaded module "system.drv" : builtin
10d0:trace:dll:fill_init_list 896: (system.drv) - START
10d0:trace:dll:fill_init_list 912: (system.drv) - END
10d0:trace:loaddll:MODULE_LoadModule16 1107: Loaded module "comm.drv" : builtin
10d0:trace:dll:fill_init_list 896: (comm.drv) - START
10d0:trace:dll:fill_init_list 912: (comm.drv) - END
10d0:trace:loaddll:MODULE_LoadModule16 1107: Loaded module "gdi.exe" : builtin
10d0:trace:dll:fill_init_list 896: (gdi.exe) - START
10d0:trace:dll:fill_init_list 912: (gdi.exe) - END
10d0:trace:loaddll:MODULE_LoadModule16 1107: Loaded module "user.exe" : builtin
10d0:trace:dll:fill_init_list 896: (user.exe) - START
10d0:trace:dll:fill_init_list 912: (user.exe) - END
10d0:trace:dll:NE_CallDllEntryPoint 779: Calling user.exe DllEntryPoint, cs:ip=10f7:1fe5
10d0:trace:file:OpenFile16 347: "display.drv" OF_READ OF_SHARE_DENY_WRITE 
10d0:warn:file:OpenFile16 467: (display.drv): return = HFILE_ERROR error= 2
10d0:trace:loaddll:MODULE_LoadModule16 1107: Loaded module "keyboard.drv" : builtin
10d0:trace:dll:fill_init_list 896: (keyboard.drv) - START
10d0:trace:dll:fill_init_list 912: (keyboard.drv) - END
10d0:trace:loaddll:MODULE_LoadModule16 1107: Loaded module "mouse.drv" : builtin
10d0:trace:dll:fill_init_list 896: (mouse.drv) - START
10d0:trace:dll:fill_init_list 912: (mouse.drv) - END
10d0:trace:loaddll:MODULE_LoadModule16 1107: Loaded module "mmsystem.dll" : builtin
10d0:trace:dll:fill_init_list 896: (mmsystem.dll) - START
10d0:trace:dll:fill_init_list 912: (mmsystem.dll) - END
10d0:trace:dll:NE_CallDllEntryPoint 779: Calling mmsystem.dll DllEntryPoint, cs:ip=113f:0541
10d0:trace:loaddll:MODULE_LoadModule16 1107: Loaded module "sound.drv" : builtin
10d0:trace:dll:fill_init_list 896: (sound.drv) - START
10d0:trace:dll:fill_init_list 912: (sound.drv) - END
10d0:trace:file:OpenFile16 347: "C:\\HH\\Prog.nm\\CDEWIN\\CDEWIN.EXE" OF_READ OF_SHARE_DENY_WRITE 
10d0:trace:file:OpenFile16 430: found "C:\\HH\\Prog.nm\\CDEWIN\\CDEWIN.EXE"
10d0:trace:file:OpenFile16 459: (C:\HH\Prog.nm\CDEWIN\CDEWIN.EXE): OK, return = 0000010C
10d0:trace:file:Win32HandleToDosFileHandle 221: Got 0 for h32 0000010C
10d0:trace:file:_lclose16 482: 0 (handle32=0000010C)
10d0:trace:loaddll:MODULE_LoadModule16 1114: Loaded module "C:\\HH\\Prog.nm\\CDEWIN\\CDEWIN.EXE" : native
10d0:trace:dosmem:DOSMEM_InitDosMemory 353: 10d0:trace:dosmem:DOSMEM_Available 651:  9f9fh of 9fa0h paragraphs available
DOS conventional memory initialized, 653808 bytes free.
10d0:trace:task:TASK_Create 339: cmdline='' task=11a7
1074:trace:file:OpenFile16 347: "MFC250.DLL" OF_READ OF_SHARE_DENY_WRITE 
1074:trace:file:OpenFile16 430: found "C:\\HH\\Prog.nm\\CDEWIN\\MFC250.DLL"
1074:trace:file:OpenFile16 459: (MFC250.DLL): OK, return = 0000012C
1074:trace:file:Win32HandleToDosFileHandle 221: Got 0 for h32 0000012C
1074:trace:file:_lclose16 482: 0 (handle32=0000012C)
1074:trace:loaddll:MODULE_LoadModule16 1107: Loaded module "WIN87EM.DLL" : builtin
1074:trace:loaddll:MODULE_LoadModule16 1107: Loaded module "COMMDLG.DLL" : builtin
1074:trace:loaddll:MODULE_LoadModule16 1107: Loaded module "SHELL.DLL" : builtin
1074:trace:loaddll:MODULE_LoadModule16 1114: Loaded module "MFC250.DLL" : native
1074:trace:file:OpenFile16 347: "CP.DLL" OF_READ OF_SHARE_DENY_WRITE 
1074:trace:file:OpenFile16 430: found "C:\\HH\\Prog.nm\\CDEWIN\\CP.DLL"
1074:trace:file:OpenFile16 459: (CP.DLL): OK, return = 00000140
1074:trace:file:Win32HandleToDosFileHandle 221: Got 0 for h32 00000140
1074:trace:file:_lclose16 482: 0 (handle32=00000140)
1074:trace:loaddll:MODULE_LoadModule16 1107: Loaded module "TOOLHELP.DLL" : builtin
1074:trace:loaddll:MODULE_LoadModule16 1114: Loaded module "CP.DLL" : native
1074:trace:file:OpenFile16 347: "MFC_EXT.DLL" OF_READ OF_SHARE_DENY_WRITE 
1074:trace:file:OpenFile16 430: found "C:\\HH\\Prog.nm\\CDEWIN\\MFC_EXT.DLL"
1074:trace:file:OpenFile16 459: (MFC_EXT.DLL): OK, return = 00000144
1074:trace:file:Win32HandleToDosFileHandle 221: Got 0 for h32 00000144
1074:trace:file:_lclose16 482: 0 (handle32=00000144)
1074:trace:file:OpenFile16 347: "TER.DLL" OF_READ OF_SHARE_DENY_WRITE 
1074:trace:file:OpenFile16 430: found "C:\\HH\\Prog.nm\\CDEWIN\\TER.DLL"
1074:trace:file:OpenFile16 459: (TER.DLL): OK, return = 00000140
1074:trace:file:Win32HandleToDosFileHandle 221: Got 0 for h32 00000140
1074:trace:file:_lclose16 482: 0 (handle32=00000140)
1074:trace:loaddll:MODULE_LoadModule16 1107: Loaded module "OLECLI.DLL" : builtin
1074:trace:loaddll:MODULE_LoadModule16 1114: Loaded module "TER.DLL" : native
1074:trace:loaddll:MODULE_LoadModule16 1114: Loaded module "MFC_EXT.DLL" : native
1074:trace:file:OpenFile16 347: "RECFMT.DLL" OF_READ OF_SHARE_DENY_WRITE 
1074:trace:file:OpenFile16 430: found "C:\\HH\\Prog.nm\\CDEWIN\\RECFMT.DLL"
1074:trace:file:OpenFile16 459: (RECFMT.DLL): OK, return = 00000144
1074:trace:file:Win32HandleToDosFileHandle 221: Got 0 for h32 00000144
1074:trace:file:_lclose16 482: 0 (handle32=00000144)
1074:trace:loaddll:MODULE_LoadModule16 1114: Loaded module "RECFMT.DLL" : native
1074:trace:file:OpenFile16 347: "PRINT.DLL" OF_READ OF_SHARE_DENY_WRITE 
1074:trace:file:OpenFile16 430: found "C:\\HH\\Prog.nm\\CDEWIN\\PRINT.DLL"
1074:trace:file:OpenFile16 459: (PRINT.DLL): OK, return = 00000140
1074:trace:file:Win32HandleToDosFileHandle 221: Got 0 for h32 00000140
1074:trace:file:_lclose16 482: 0 (handle32=00000140)
1074:trace:loaddll:MODULE_LoadModule16 1107: Loaded module "COMPOBJ.DLL" : builtin
1074:trace:loaddll:MODULE_LoadModule16 1114: Loaded module "PRINT.DLL" : native
1074:trace:file:OpenFile16 347: "MFCO250.DLL" OF_READ OF_SHARE_DENY_WRITE 
1074:trace:file:OpenFile16 430: found "C:\\HH\\Prog.nm\\CDEWIN\\MFCO250.DLL"
1074:trace:file:OpenFile16 459: (MFCO250.DLL): OK, return = 00000144
1074:trace:file:Win32HandleToDosFileHandle 221: Got 0 for h32 00000144
1074:trace:file:_lclose16 482: 0 (handle32=00000144)
1074:trace:file:OpenFile16 347: "MFCOLEUI.DLL" OF_READ OF_SHARE_DENY_WRITE 
1074:trace:file:OpenFile16 430: found "C:\\HH\\Prog.nm\\CDEWIN\\MFCOLEUI.DLL"
1074:trace:file:OpenFile16 459: (MFCOLEUI.DLL): OK, return = 00000140
1074:trace:file:Win32HandleToDosFileHandle 221: Got 0 for h32 00000140
1074:trace:file:_lclose16 482: 0 (handle32=00000140)
1074:trace:loaddll:MODULE_LoadModule16 1107: Loaded module "OLE2.DLL" : builtin
1074:trace:loaddll:MODULE_LoadModule16 1107: Loaded module "STORAGE.DLL" : builtin
1074:trace:loaddll:MODULE_LoadModule16 1114: Loaded module "MFCOLEUI.DLL" : native
1074:trace:loaddll:MODULE_LoadModule16 1107: Loaded module "OLE2DISP.DLL" : builtin
1074:trace:loaddll:MODULE_LoadModule16 1114: Loaded module "MFCO250.DLL" : native
1074:trace:file:OpenFile16 347: "ISIWIDG.DLL" OF_READ OF_SHARE_DENY_WRITE 
1074:trace:file:OpenFile16 430: found "C:\\HH\\Prog.nm\\CDEWIN\\ISIWIDG.DLL"
1074:trace:file:OpenFile16 459: (ISIWIDG.DLL): OK, return = 00000144
1074:trace:file:Win32HandleToDosFileHandle 221: Got 0 for h32 00000144
1074:trace:file:_lclose16 482: 0 (handle32=00000144)
1074:trace:loaddll:MODULE_LoadModule16 1114: Loaded module "ISIWIDG.DLL" : native
1074:CallTo16(func=1207:1c8e,ds=1267) ss:sp=1267:9608 ax=0000 bx=5000 cx=1fa0 dx=0000 si=0000 di=1266 bp=0000 es=11af fs=0053
1074:Call KERNEL.91: INITTASK() ret=1207:1c96 ds=1267
     AX=0000 BX=5000 CX=1fa0 DX=0000 SI=0000 DI=1266 ES=11af EFL=00003000
1074:trace:selector:SELECTOR_FreeBlock 162: (127f,1)
1074:trace:dll:NE_InitDLL 699: Calling LibMain for MFC250, cs:ip=1287:0054 ds=131f di=131e cx=0400
1074:CallTo16(func=1287:0054,ds=131f) ss:sp=1267:95d2 ax=0000 bx=0000 cx=0400 dx=0000 si=0000 di=131e bp=95fc es=131f fs=0053
1074:Call KERNEL.4: LOCALINIT(131f,0000,0400) ret=1287:0080 ds=131f
1074:Ret  KERNEL.4: LOCALINIT() retval=00000001 ret=1287:0080 ds=131f
1074:Call KERNEL.23: LOCKSEGMENT(ffff) ret=1287:008d ds=131f
1074:Ret  KERNEL.23: LOCKSEGMENT() retval=0000131f ret=1287:008d ds=131f
1074:Call KERNEL.3: GETVERSION() ret=1287:0092 ds=131f
1074:Ret  KERNEL.3: GETVERSION() retval=05005f03 ret=1287:0092 ds=131f
1074:Call KERNEL.102: DOS3CALL() ret=1287:00a7 ds=131f
     AX=305f BX=0000 CX=0001 DX=0500 SI=0000 DI=131e ES=131f EFL=00003000
1074:trace:int21:DOSVM_Int21Handler 4157: AX=305f BX=0000 CX=0001 DX=0500 SI=0000 DI=131e DS=131f ES=131f EFL=00003000
1074:trace:int21:DOSVM_Int21Handler 4569: GET DOS VERSION - version flag requested
1074:trace:int21:DOSVM_Int21Handler 5377: returning: AX=0005 BX=0812 CX=3456 DX=0500 SI=0000 DI=131e DS=131f ES=131f EFL=00003000
1074:Ret  KERNEL.102: DOS3CALL() retval=none ret=100f:0b0c ds=131f
     AX=0005 BX=0812 CX=3456 DX=0500 SI=0000 DI=131e ES=131f EFL=00003000
1074:Call WIN87EM.1: __FPMATH() ret=1287:012d ds=131f
     AX=0000 BX=0000 CX=132f DX=0000 SI=0000 DI=131e ES=131f EFL=00003000
1074:trace:int:_fpMath 187: (cs:eip=132f:004c es=131f bx=0000 ax=5000000 dx=0000)
=====dump all modules=====
Module Flags Name Flag
 167f	8301	ISIWIDG	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_CONSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 1667	8021	OLE2DISP	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 164f	8021	STORAGE	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 1637	8021	OLE2	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 15f7	8305	MFCOLEUI	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_CONSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 158f	8309	MFCO250	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_CONSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 1577	8021	COMPOBJ	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 153f	8309	PRINT	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_CONSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 14c7	8309	RECFMT	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_CONSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 14af	8021	OLECLI	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 145f	8301	TER	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_CONSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 13bf	8309	MFC_EXT	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_CONSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 13a7	8021	TOOLHELP	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 136f	8309	CP	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_CONSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 1357	8021	SHELL	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 133f	8021	COMMDLG	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 1327	8021	WIN87EM	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 126f	8309	MFC250	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_CONSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 1167	030a	CDE	NE_FFLAGS_MULTIPLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_CONSOLE | NE_FFLAGS_GUI
 114f	8021	SOUND	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 1137	8021	MMSYSTEM	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 111f	8021	MOUSE	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 1107	8021	KEYBOARD	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 10ef	8021	USER	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 10d7	8021	GDI	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 10a7	8021	COMM	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 108f	8021	SYSTEM	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 1007	8021	KERNEL	NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
=====dump all modules=====
20: load_x87function - 0x6f5f1700 (null)(0)
19: RtlCaptureContext - 0x77963533 (null)(0)
18: RtlDestroyEnvironment - 0x77962ff6 (null)(0)
17: KiUserExceptionDispatcher - 0x77910154 (null)(0)
=============================
16: vm_debug_get_entry_point - 0x6f866af0 (null)(0)
15: dasm_buffer_dump - 0x6f5f7410 (null)(0)
14: wine_call_to_16_regs_vm86 - 0x6f5f7240 (null)(0)
13: K32WOWCallback16Ex - 0x6f87a550 (null)(0)
12: MapHModuleSL - 0x6f863e50 (null)(0)
11: MapHModuleSL - 0x6f863e50 (null)(0)
10: MapHModuleSL - 0x6f863e50 (null)(0)
9: InitTask16 - 0x6f86e450 (null)(0)
8: vm_debug_get_entry_point - 0x6f866af0 (null)(0)
7: dasm_buffer_dump - 0x6f5f7410 (null)(0)
6: wine_call_to_16_regs_vm86 - 0x6f5f7240 (null)(0)
5: K32WOWCallback16Ex - 0x6f87a550 (null)(0)
4: LoadModule16 - 0x6f861e40 (null)(0)
3: RestoreThunkLock - 0x6f86d620 (null)(0)
2: BaseThreadInitThunk - 0x770c342b (null)(0)
1: RtlInitializeExceptionChain - 0x779397cf (null)(0)
0: RtlInitializeExceptionChain - 0x779397cf (null)(0)
========================
17: dasm_buffer_dump - 0x6F5F7410
16: dasm_buffer_dump - 0x6F5F7410
15: dasm_buffer_dump - 0x6F5F7410
14: wine_call_to_16_regs_vm86 - 0x6F5F7240
13: K32WOWCallback16Ex - 0x6F87A550
12: MapHModuleSL - 0x6F863E50
11: MapHModuleSL - 0x6F863E50
10: MapHModuleSL - 0x6F863E50
9: InitTask16 - 0x6F86E450
8: vm_debug_get_entry_point - 0x6F866AF0
7: dasm_buffer_dump - 0x6F5F7410
6: wine_call_to_16_regs_vm86 - 0x6F5F7240
5: K32WOWCallback16Ex - 0x6F87A550
4: LoadModule16 - 0x6F861E40
3: RestoreThunkLock - 0x6F86D620
2: BaseThreadInitThunk - 0x770C342B
1: RtlInitializeExceptionChain - 0x779397CF
0: RtlInitializeExceptionChain - 0x779397CF
address=00000000
access address=00000000
32bit
16bit context
EAX:5000000,ECX:132F,EDX:0000,EBX:0000
ESP:958E,EBP:95C0,ESI:0000,EDI:131E
ES:131F,CS:132F,SS:1267,DS:131F
IP:004C, address:008CF474
EFLAGS:00003000

SEGV
11c4:trace:selector:SELECTOR_FreeBlock 162: (127f,1)
1074:trace:selector:SELECTOR_FreeBlock 162: (11bf,1)
1074:trace:task:TASK_ExitTask 575: Killing task 11a7
1074:trace:task:TASK_ExitTask 586: this is the last task, exiting
