### ISSUE TITLE
winevdm build dev1365+ not work on XP

### ISSUE THREAD

**Issue by TheElf01** [otya128/winevdm#407]
Hi, until GCC dev1362 winevdm was working on XP x64 without problem

https://ci.appveyor.com/project/otya128/winevdm/builds/25934744

But on dev1365 executable fail with "Gettickcount64 could not be located in...  kernel32.dll"

the problem is in the file "libwinpthread-1.dll"

If i replace with version from dev1362, even latest dev1371 work fine

thanks

**Comment by otya128** [comment]
Fixed.
