### ISSUE TITLE
In Harvard Draw for Windows installer the list of program groups is empty

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#411]
https://winworldpc.com/product/harvard-draw-for-win/10
![Clipboard_20190824](https://user-images.githubusercontent.com/1271736/63640205-250d2500-c6a6-11e9-842e-416bbd8f79d8.png)

**Comment by Anixx** [comment]
![Clipboard_20190824](https://user-images.githubusercontent.com/1271736/63640194-0eff6480-c6a6-11e9-925a-f41c2e87e198.jpg)

**Comment by cracyc** [comment]
It gets the list of groups from progman.ini.  If it the parses the grp file to get the group name it's probably not worth trying to implement.  It doesn't work in ntvdm either.
