### ISSUE TITLE
ABC Snapgraphix installer cannot create the installation directory

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#412]
This happens even if it is run with elevated rights.
https://winworldpc.com/download/c5bdc396-c2ae-29c2-a652-11c3a5c28f13/from/c3ae6ee2-8099-713d-3411-c3a6e280947e

To install one has to create the whole programm's directory tree manually before the installation.

**Comment by cracyc** [comment]
It's not even trying to create the directories.  I can't find the cause though.
