### ISSUE TITLE
Artemis Presents installer hangs at the end of installation

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#414]
And does not create a program group.
https://winworldpc.com/download/fec653fb-2aed-11e8-a4ce-fa163e9022f0/from/c3ae6ee2-8099-713d-3411-c3a6e280947e

**Comment by cracyc** [comment]
Worked here, maybe post a trace.

**Comment by Anixx** [comment]
Not it gives this:
![изображение](https://user-images.githubusercontent.com/1271736/81987666-c5471780-9642-11ea-9d9a-68bd01bb5893.png)
Cannot continue.

**Comment by cracyc** [comment]
This happens to me when I don't put the PRESENTS.002 file from the second disk image in the same directory as the installer.

**Comment by Anixx** [comment]
Works well now.
