### ISSUE TITLE
Borland Office 2.0 does not install

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#415]
The progress indicator remains at zero

https://winworldpc.com/download/0c3b31c2-b57e-c592-11c3-a6e280947e52

**Comment by cracyc** [comment]
It works here just extremely slowly.  Like https://github.com/otya128/winevdm/issues/156 setting dwMilliseconds to 0 in PeekMessage16 fixes it.  It'd be best for @otya128 to look at the problem because I don't know what the MsgWaitForMultipleObjects fixes so I can't regression test any changes.

**Comment by Anixx** [comment]
Perhaps the same problem affects Novell Perfect Office which also takes ages to copy each file.
https://winworldpc.com/download/556bdee6-25a3-11e8-a4ce-fa163e9022f0
