### ISSUE TITLE
ctl3dv2.dll16.spec

### ISSUE THREAD

**Issue by hmaecke** [otya128/winevdm#42]
A program I recently installed complains on starting about a missing ctl3dv2.dll16.spec file. After clicking OK the program starts anyway.
The otvdm directory contains a ctl3dv2.dll16 file, but where do I get the ctl3dv2.dll.spec file and where to store it to avoid the messsage?

BTW: Is there a possibility to hide the DOS Window which starts before the 16 Bit program is starting?

Thanks a lot for your time!

**Comment by otya128** [comment]
What error message is displayed? Please tell the full text of the error message.
If you want to hide the DOS window, please use otvdm**w**.exe instead of otvdm.exe.

**Comment by hmaecke** [comment]
The message is
"---------------------------
otvdmw.exe - Systemfehler
---------------------------
Das Programm kann nicht gestartet werden, da ctl3dv2.dll16.spec auf dem Computer fehlt. Installieren Sie das Programm erneut, um das Problem zu beheben. "

This means "the program cannot be started as ctl3dv2.dll16.spec is missing in your computer. Reinstall the program to resolve the problem".

Using otvdmw indeed hides the DOS box - thanks a lot! :-)

**Comment by hmaecke** [comment]
Meanwhile I have more programs which require the ctl3dv2.dll16.spec...

**Comment by neozeed** [comment]
You should have the following files in the dll directory:

```
ctl3d.dll16
ctl3dv2.dll16
```

There shouldn't be any spec files needed at runtime...

**Comment by hmaecke** [comment]
Thanks, but the files are present. The stable version has an own dll folder, but this version does not work for my 16 bit apps at all. The unstable versions contain the files directly in the program directory, but regardless if I additionally copy the *16 files to a subdir dll or not: the ctl3dv2.dll16.spec is still reported as missing...

**Comment by neozeed** [comment]
Is there any app that you can mention to poke at?

The best I had just complained that the version was wrong, then just loaded away.

**Comment by hmaecke** [comment]
The app loads anyway after clicking the error message OK, that's correct. Nevertheless I'm unsure if this problem may subsequently evoke other problems I encounter in some apps. The program that show this error are CD-ROM based databases such as "Patrologia Latina Database" or "International Bibliography of Maps and Atlases", quite special programs, I know...

I furthermore tried to see what's happening when the app starts with MDeb (that's a dependency tool for 16 bit apps), but here the error does not occur at all. That's what's happening under control of MDeb:
Loading module:ctl3dv2.dll16.spec
	 File:0x0000057c Base: 0x69f90000 Unicode: 1
**Loading module:ctl3d.dll16.spec
	 File:0x00000580 Base: 0x69f50000 Unicode: 1
Unloading module:ctl3d.dll16.spec**
Loading module:win87em.dll16
	 File:0x00000584 Base: 0x69f50000 Unicode: 1
So here the module is loaded and unloaded again...

**Comment by hmaecke** [comment]
Thanks, but no. I tested both dev352 and dev354. Now on starting my apps I get reported that ctl3dv2.dll16 is missing (not ...spec). Funny enough the file is there:

![image](https://user-images.githubusercontent.com/43235494/45688778-910c1280-bb52-11e8-988e-507c6ed6177f.png)

**Comment by hmaecke** [comment]
Great, dev357 solves the problem - thanks a lot! Now I'll be able to do some further testing and see if my subsequently ocurring errors have been related or not... ;-)
