### ISSUE TITLE
Otvdm does not exit after exiting XTreeGold

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#423]
The otvdm process still resides in memory.

**Comment by cracyc** [comment]
It runs a background task, WNFSVT3 (it's window title is "DO NOT DESTROY!!!! CPS PC Tools for Windows Version 3 File Services Background Controller Task."), which never exits.  I'm not sure if it's supposed to stay running when xtree exits but if so I don't think there's a sane way to make it go away.
