### ISSUE TITLE
Lotus Organizer 1.0 creates an empty program group

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#425]
https://winworldpc.com/download/c3b53ec3-a45c-226d-11c3-a7cb86c2bd52

And puts the program's shortcut outside the group and with no icon.

**Comment by cracyc** [comment]
Worked without issue for me.

**Comment by Anixx** [comment]
Looks fixed except the guided tour shortcut has no icon:
![изображение](https://user-images.githubusercontent.com/1271736/81935126-c94e4780-95f8-11ea-996f-b2b55742f6ba.png)

**Comment by Anixx** [comment]
Seems fixed
