### ISSUE TITLE
Borland Office 2.0 installer: cannot create file

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#439]
![Clipboard_20190905](https://user-images.githubusercontent.com/1271736/64343391-279c4280-cff5-11e9-818a-7ab0a0635ae7.png)
After choosing "Ignore" the installation continues.
This happens with several files.

At the end of installation the following message appears:
![Clipboard_20190905 (2)](https://user-images.githubusercontent.com/1271736/64344350-f1f85900-cff6-11e9-91bf-9dc409fca16e.png)

No program group is created.

**Comment by cracyc** [comment]
These don't run after install because they place some dlls in a shared directory then set the path in autoexec.bat to point at it.  PATH16 has to be set to that directory which is c:\odapi to run them.
