### ISSUE TITLE
install.reg does not work 

### ISSUE THREAD

**Issue by jamie-marchant** [otya128/winevdm#448]
Every program I try after running "install.reg" results in an error like this: 
"[Window Title]
C:\Games\16bitemutest\Jman\1\JMAN.EXE

[Content]
C:\Games\16bitemutest\Jman\1\JMAN.EXE
The specified path does not exist.

Check the path, and then try again.

[OK]
"
So far only "install.reg" does not work, otvdmw.exe runs just fine if you run it directly.

**Comment by jamie-marchant** [comment]
Oh you have to change the "install.reg"... Hmm now I get the usual "this app won't run on your PC".

**Comment by Anixx** [comment]
The current version does not have install.reg, it has install.inf. So you are using something outdated.

**Comment by jamie-marchant** [comment]
Oh yes, that makes sense, I am using the latest stable relae I guess the version in testing uses something else. Ok, I'll wait for the next stable release.

**Comment by jamie-marchant** [comment]
By the way useing the install.inf from the latest srouce does inergrate the software correctly.
