### ISSUE TITLE
Windows NT reported 

### ISSUE THREAD

**Issue by jamie-marchant** [otya128/winevdm#449]
Hi: 
 I get: 
---------------------------
Installation Problem
---------------------------
This version of Video for Windows does not run on Windows NT.
---------------------------
OK   
---------------------------
"
Even running the emualtor in Windows 95 compatibility mode. Shouden't the emulator report Windows 95 or 3.11?

**Comment by jamie-marchant** [comment]
Ok I have tried for a while now but for some reason, it does not want to clear the formating in that post, sorry.

**Comment by jamie-marchant** [comment]
otvdm.ini says it's reporting Windows 95, so I wonder why Video For Windows can see past this...

**Comment by otya128** [comment]
Please try appending `IAmNotNT=1` to otvdm.ini.

**Comment by jamie-marchant** [comment]
I saw that at the same time you posted, yes that fixed this issue, thanks.
