### ISSUE TITLE
MSDOS Executive 1.0

### ISSUE THREAD

**Issue by cracyc** [otya128/winevdm#45]
The Windows 1.0 version of msdos.exe almost works it just crashes a lot when opening dialogs (about dialog included).  The reason is it that it subtracts bx (stack size) from sp (top of the stack) and expects that to be the stack bottom but the stack frame and return address are placed on the stack so the top is sizeof(STACK16FRAME) + 4 lower which causes a later lstrcpy to overwrite part of the data segment.

**Comment by parrotgeek1** [comment]
This issue occurs even on windows XP. I doubt it will ever be fixed here.
