### ISSUE TITLE
Borland Office 2.0 installer: cannot create destination file

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#450]
The bug is still there:
![Clipboard_20190912](https://user-images.githubusercontent.com/1271736/64785306-bae4f300-d574-11e9-9143-efeccde7b590.png)

Additionally, the installer segfaulted during the installation.

**Comment by Anixx** [comment]
I disabled all indexing on my computer, maybe that makes the difference.

**Comment by cracyc** [comment]
https://ci.appveyor.com/project/otya128/winevdm/builds/27401057/job/ljg4qad8alg7r97x/artifacts

Try this build.

**Comment by Anixx** [comment]
Should not I wait until the commit merged?

**Comment by cracyc** [comment]
It's a draft commit.  I want to know if it works first.

**Comment by Anixx** [comment]
Yes, it works, this bug is fixed.

**Comment by Anixx** [comment]
Well, reopen until the commit merged
