### ISSUE TITLE
In programs built with Visual Basic 1.0 the menu bar is invisible until mouse hover

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#452]
![Clipboard_20190913](https://user-images.githubusercontent.com/1271736/64851689-947c9180-d620-11e9-8668-8fd5aec519d5.png)

The same affects Alientic:
![Clipboard_20190913 (2)](https://user-images.githubusercontent.com/1271736/64853764-c7c11f80-d624-11e9-9c4f-99858cfd9c49.png)

**Comment by cracyc** [comment]
This happens with a bunch of visual basic 1.0 programs.  It might be related to vb building the menu at runtime and calling drawmenubar to show it.

**Comment by cracyc** [comment]
It doesn't happen when theming is enabled so it probably has something to do with that.  Maybe related to https://github.com/otya128/winevdm/issues/518.

**Comment by Anixx** [comment]
In AlienTic this still happens with recent build. Unfortunately I cannot reopen this issue.
