### ISSUE TITLE
System.ini file not writable 

### ISSUE THREAD

**Issue by jamie-marchant** [otya128/winevdm#455]
I have had a few setup programs(including the freely downaloable "Video For Windows") that can't write to my System.ini. This is useing the stable release of "winevdm".

**Comment by Anixx** [comment]
You should not use the "stable" release, it is about a year old.

**Comment by jamie-marchant** [comment]
I can't find the download linke here: https://ci.appveyor.com/project/otya128/winevdm, where is it?

**Comment by Anixx** [comment]
From that place you should click THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1

**Comment by jamie-marchant** [comment]
Thanks. This issue still happens in the latest version.

**Comment by jamie-marchant** [comment]
Because the issue has been fixed I am closeing this bug report.
