### ISSUE TITLE
WpWinfrom Borland Office 2.0 does not start

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#459]
First this:
![Clipboard_20190913 (3)](https://user-images.githubusercontent.com/1271736/64889175-6a08f380-d675-11e9-8f63-4b6ff7d51a37.png)
Then this:
![Clipboard_20190913 (4)](https://user-images.githubusercontent.com/1271736/64889208-7ab96980-d675-11e9-9cca-0dc18c211152.png)
Should I set some environment variables?
I tried to set path16=C:\ODAPI and also put the same in otvdm.ini, but still no result.

Local Settings Utility segfaults.

**Comment by cracyc** [comment]
Needs elevation.

https://github.com/otya128/winevdm/pull/447#issuecomment-529138189

**Comment by Anixx** [comment]
After I elevated it, the main window appeared, but
![Clipboard_20190913 (5)](https://user-images.githubusercontent.com/1271736/64889659-75105380-d676-11e9-9d5a-2d367db20097.png)
