### ISSUE TITLE
Insufficient memory message when starting Word Perfect from Borland Office 2.0

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#463]
![64889208-7ab96980-d675-11e9-9cca-0dc18c211152 1](https://user-images.githubusercontent.com/1271736/64890382-3380a800-d678-11e9-8f9e-cbaaa9907bb6.png)
The program then continues seemingly normally.

**Comment by cracyc** [comment]
I get the "not enough global memory" error due to the default printer name length problem.
