### ISSUE TITLE
redirect "System" font to "FixedSys" for win1/2 programs

### ISSUE THREAD

**Issue by roytam1** [otya128/winevdm#481]
since "System" font is fixed pitch font in win1 and 2, IMO it is better to redirect "System" font to "FixedSys" for win1/2 programs.

**Comment by Anixx** [comment]
Do you know a way to determine if a program is Win1/2?

**Comment by roytam1** [comment]
> Do you know a way to determine if a program is Win1/2?

check version in NE header

**Comment by otya128** [comment]
It is difficult because the System font is used when no font is specified.

**Comment by roytam1** [comment]
> It is difficult because the System font is used when no font is specified.

can we "pre-select" FixedSys for that?

**Comment by Anixx** [comment]
> check version in NE header

If this is possible, then this should be fixable as well:
https://github.com/otya128/winevdm/issues/251

**Comment by roytam1** [comment]
> If this is possible, then this should be fixable as well

I think there is something already done like this:
https://github.com/otya128/winevdm/commit/f51d3f88e39af97058908d7540e0a720bbf02ea2

**Comment by roytam1** [comment]
and dialog templates are needed to be enlarged for getting font information in. how to do this?

**Comment by cracyc** [comment]
It seems like the DS_FIXEDSYS flag would do it but that doesn't work so you'd have to in DIALOG_ParseTemplate16 add DS_SETFONT with result->facename = "FIXEDSYS".

**Comment by cracyc** [comment]
To change the non-dialog font since the default dc font is system, SelectFont(hdc, GetStockObject(SYSTEM_FIXED_FONT)) would have to be called for every dc at creation and use except windows with CS_OWNDC and CS_PARENTDC.

**Comment by roytam1** [comment]
it work very well! thanks!
