### ISSUE TITLE
Avast AntiVirous does not like winevdm 

### ISSUE THREAD

**Issue by jamie-marchant** [otya128/winevdm#499]
Tested on another machine and Avast would not let winevdm run, anything we can do about this?

**Comment by cb88** [comment]
I'm not sure that there is even much point to running a 3rd party antivirus on windows 10.... you could always just tell Avast to ignore the path winedvm is at right?

**Comment by maximilien-noal** [comment]
Avast doesn't like a LOT of things (dgVoodoo2, easyHook, ...).

This is an issue with Avast and other AVs.

Only solution : remove Avast.

**Comment by jamie-marchant** [comment]
I will probably do that when I reinstall things on that machine.
