### ISSUE TITLE
QuickC for Windows crashes on load (missing WIN87EM calls)

### ISSUE THREAD

**Issue by neozeed** [otya128/winevdm#5]
I wanted to fire up the ancient QuickC for Windows.. and it crashed out.  Looks like missing win87em calls.

Thanks again for winevdm, it's super awesome!

D:\qemu-0.10.5\sc\QCWIN\BIN>c:otvdm.exe QCWIN.EXE
err:fixup:apply_relocations 211: No implementation for WIFEMAN.__WIN87EMINFO, setting to 0xdeadbeef
err:fixup:apply_relocations 211: No implementation for WIFEMAN.__WIN87EMRESTORE, setting to 0xdeadbeef
err:fixup:apply_relocations 211: No implementation for WIFEMAN.__WIN87EMSAVE, setting to 0xdeadbeef
err:fixup:apply_relocations 211: No implementation for WIFEMAN.__WIN87EMINFO, setting to 0xdeadbeef
err:fixup:apply_relocations 211: No implementation for WIFEMAN.__WIN87EMSAVE, setting to 0xdeadbeef
=====dump all modules=====
Module Flags Name Flag
 13b7   8309    QCWINDBG        NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_CONSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 139f   8021    COMMDLG NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 1387   8021    WIFEMAN NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 1167   030a    QCWIN   NE_FFLAGS_MULTIPLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_CONSOLE | NE_FFLAGS_GUI
 114f   8021    SOUND   NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 1137   8021    MMSYSTEM        NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 111f   8021    MOUSE   NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 1107   8021    KEYBOARD        NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 10ef   8021    USER    NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 10d7   8021    GDI     NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 10a7   8021    COMM    NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 108f   8021    SYSTEM  NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 1007   8021    KERNEL  NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
=====dump all modules=====
11: vm86_vectored_exception_handler - 0xf4877f0 c:\users\jsteve\source\repos\winevdm-master\vm86\msdos.cpp(756)
10: RtlUnwind - 0x77252820 (null)(0)
9: KiUserExceptionDispatcher - 0x7725c690 (null)(0)
=============================
8: protected_mode_exception_handler - 0xf487f10 c:\users\jsteve\source\repos\winevdm-master\vm86\msdos.cpp(1008)
7: vm86main - 0xf4880f0 c:\users\jsteve\source\repos\winevdm-master\vm86\msdos.cpp(1179)
6: wine_call_to_16_regs_vm86 - 0xf487d10 c:\users\jsteve\source\repos\winevdm-master\vm86\msdos.cpp(898)
5: K32WOWCallback16Ex - 0xf259630 c:\users\jsteve\source\repos\winevdm-master\krnl386\wowthunk.c(673)
4: NE_StartTask - 0xf241770 c:\users\jsteve\source\repos\winevdm-master\krnl386\ne_module.c(1341)
3: task_start - 0xf24d070 c:\users\jsteve\source\repos\winevdm-master\krnl386\task.c(482)
2: BaseThreadInitThunk - 0x77038460 (null)(0)
1: RtlValidSecurityDescriptor - 0x77252ed0 (null)(0)
0: RtlValidSecurityDescriptor - 0x77252ed0 (null)(0)
========================
9: print_stack - 0x0F488A70
8: catch_exception - 0x0F488B50
7: vm86main - 0x0F4880F0
6: wine_call_to_16_regs_vm86 - 0x0F487D10
5: K32WOWCallback16Ex - 0x0F259630
4: NE_StartTask - 0x0F241770
3: task_start - 0x0F24D070
2: BaseThreadInitThunk - 0x77038460
1: RtlValidSecurityDescriptor - 0x77252ED0
0: RtlValidSecurityDescriptor - 0x77252ED0
Access violation
address=7610DDC2
access address=0F48D56C
32bit
16bit context
AX:C23A,CX:0000,DX:0500,BX:20B2
SP:C232,BP:C248,SI:083C,DI:C265
ES:137F,SS:12DF,CS:137F,DS:137F
IP:0DCC, address:0F49CC2D

Interrupt 0D #GP (12DF:0DC7) flags 3092 err DEA8
call    0DEADh:0BEEFh

**Comment by neozeed** [comment]
Thanks, I just compiled [130,405](https://i.imgur.com/aD4A4Ei.png) lines of code on one program plus the F2C compiler, and it worked! Awesome!

**Comment by otya128** [comment]
That’s great!
