### ISSUE TITLE
HP12C ans SmartAccounts installers do not exit after installation

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#514]
http://files.mpoli.fi/software/WIN16/UTILS/MISC/HP12C12.ZIP
http://files.mpoli.fi/software/WIN16/UTILS/MISC/SMTACC.ZIP

After saying installation complete the otvdm.exe process still remains in the memory.

**Comment by cracyc** [comment]
As I said in https://github.com/otya128/winevdm/issues/334#issuecomment-497982577 this is a bug in the installers that also happens in ntvdm.
