### ISSUE TITLE
Too bold text in Win 1.0 programs

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#520]
![Clipboard_20191027](https://user-images.githubusercontent.com/1271736/67634505-a1e69600-f8c5-11e9-99bc-58dd159f9bb3.png)

![Clipboard_20191027 (2)](https://user-images.githubusercontent.com/1271736/67634511-ae6aee80-f8c5-11e9-92ec-f895d1700d7e.png)
![Clipboard_20191027 (3)](https://user-images.githubusercontent.com/1271736/67634516-bfb3fb00-f8c5-11e9-9eba-e8208f3f1c40.png)

**Comment by Anixx** [comment]
![Clipboard_20191027 (4)](https://user-images.githubusercontent.com/1271736/67634543-2cc79080-f8c6-11e9-9387-d4b0aeb36f41.png)

**Comment by Anixx** [comment]
This happens in the release version as well.

**Comment by cracyc** [comment]
Windows appears to force dialog font to be bold.  Setting DS_3DLOOK forces normal weight but makes the dialogs look gray.  DS_FIXEDSYS should also fix the problem but it doesn't appear to work with programs that identify as lower than win 4.00; we set 3.10 to fix other drawing issues.

**Comment by Anixx** [comment]
DS_3DLOOK seems to be a good solution to me (I favor mo modern looks).

There should be other solutions as well, because under NTVDM the appearance is satisfactory.

**Comment by Anixx** [comment]
Also, the layout problems in the dialogs may be related to the font being too thick.

**Comment by roytam1** [comment]
it looks fine here (win7 x64, classic theme):
![image](https://user-images.githubusercontent.com/1192577/67637715-3aa60180-f918-11e9-9ed3-28f95d73b73a.png)

**Comment by Anixx** [comment]
So... What may be the cause?

**Comment by roytam1** [comment]
> What may be the cause?

don't you think you should provide OS version and theme you're using?

**Comment by Anixx** [comment]
I am using Win8.1, Classic theme.

**Comment by Anixx** [comment]
Re-tested under the default Win8.1 theme, the result is the same.

**Comment by Anixx** [comment]
Do you use the most recent build?

**Comment by roytam1** [comment]
> Do you use the most recent build?

sure. if not, it won't use FixedSys font.

for your reference, left is otvdm, right is ntvdm, in win8.1 32bit, deviantart classic win8.1 theme.
![image](https://user-images.githubusercontent.com/1192577/67638266-7d1e0d00-f91d-11e9-932e-4b6ef8560aac.png)

**Comment by Anixx** [comment]
I established

1. It does not depend on what is in the otvdm folder (with newly downloaded Winevdm all the same)
2. It does not depend on what is in the executable's folder (standalone control.exe looks the same)
3. It does not depend on the host OS theme (the same with the default theme, classic or non-classic themes, as well as Win2000 scheme and metrics)
4. I re-installed the fixedsys fonts family - the result is the same
5. I removed the Font Substitution branch from the registry - the result is the same.

**Comment by cracyc** [comment]
I read somewhere the asian fonts are not bolded by default in dialogs.  If roytam1 is using japanese windows and fixedsys has a japanese code page then they'll be normal type.

**Comment by Anixx** [comment]
Interesting. Can I test it on non-Asian machine?

**Comment by Anixx** [comment]
Also, is a version wtith DS_3DLOOK so that I could test it?

**Comment by cracyc** [comment]
I just pushed a fix that uses DLGTEMPLATEEX to set the font weight.  It looks the same as DS_3DLOOK except the background is not gray and the edit controls are flat.

**Comment by Anixx** [comment]
By the way, NTVDM seems not to use Fixedsys, but some another font.

**Comment by Anixx** [comment]
>  It looks the same as DS_3DLOOK except the background is not gray and the edit controls are flat.

Good. I possibly would even prefer 3DLOOK.

**Comment by Anixx** [comment]
Is there a ready-to-test buld before the request merged?

**Comment by cracyc** [comment]
>By the way, NTVDM seems not to use Fixedsys, but some another font.
In the pic roytam1 posted above the ntvdm font is the regular win3 System font.  My XP 32bit VM does the same.
>Is there a ready-to-test buld before the request merged?
Click the green check on the pull request page to get it from appveyor.

**Comment by Anixx** [comment]
Thanks. All works now.
![Clipboard_20191027 (5)](https://user-images.githubusercontent.com/1271736/67639869-e726ba00-f8fd-11e9-8ccd-2f2751c70c9c.png)

**Comment by Anixx** [comment]
I wonder why roytam1's preview area has a border around the window. Mine has none.

**Comment by cracyc** [comment]
Because he showed the windows 2 version as ntvdm won't run any windows 1 programs.

**Comment by Anixx** [comment]
By the way if I force DS_3DLook on that dialog, nothing happens...

**Comment by cracyc** [comment]
Here's the difference with the write 2 file open dialog:
no 3d
![win2_no3d](https://user-images.githubusercontent.com/9255333/67640532-28e93d80-f8c9-11e9-9792-2e1d4f47d445.PNG)
3d
![win2_3d](https://user-images.githubusercontent.com/9255333/67640534-2c7cc480-f8c9-11e9-84d7-d223fd6bb8ba.PNG)

**Comment by Anixx** [comment]
The second one looks simply great! Is there any way to introduce it at least as an option in otvdm.ini?
