### ISSUE TITLE
Regression: Win1.0 terminal cannot be resized or maximized.

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#521]
When started it appears out of screen.
At best it looks like this:

![Clipboard_20191027 (5)](https://user-images.githubusercontent.com/1271736/67634652-719ff700-f8c7-11e9-8475-7576ee15ad43.png)

Its size cannot be increased.

**Comment by cracyc** [comment]
What's the exact version?  Terminal 1.02 works fine (it also won't maximize but it won't in Windows 2 either).

**Comment by Anixx** [comment]
Indeed, the release version works well.
