### ISSUE TITLE
In Write 1.00 backspace key fails after exclamation, question signs, ampersand etc

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#523]
If to write a text with exclamation or question sign at the end, invoking the backspace so to erase the sign fails.

**Comment by cracyc** [comment]
This also happens in win3 (not in win2 though).

**Comment by cracyc** [comment]
Windows 2 write is also affected but because undo hot key is changed the symptom is different.  Also, for machines with large screens, a logic bug in the program causes End to not go all the way to the end of the line in all (win 1,2 and 3) versions of Write.
