### ISSUE TITLE
Collins English Dictionary (Pre-Installed Version) won't run, also Setup errors out !

### ISSUE THREAD

**Issue by alienfxfiend** [otya128/winevdm#553]
I tried the setup files from Vetusware, but I get a ddeinitiate error, also the pre-installed version (I got from a friend who installed it & uploaded it) errors out with a cancel\ continue error box, further pilfering found the words Thunk & Interrupt. Here's the pre-installed folder that won't run ~> [Collins Pre-installed Zip Folder Clean](https://dl.dropboxusercontent.com/s/mrk1taq8212jfg5/COLLINS.zip) Here's the error console output ~> [Error Paste](https://pastebin.com/JiqEvajh) Please resolve this, I used this app a lot. On a side note, The Thinking Mans Thesaurus executed without any errors but is _very_ slow when searching for a word ! Also similar to the "Euchre" bug report. I noticed there are some folders named Windows, do I need to move them to Windows or anything ? During the Setup I get "NonFatal Error At Script Line 477. ddeinitiate failed. OK"

**Comment by emendelson** [comment]
I don't know if it's useful, but here's an ISO image of the actual CD bought on eBay:

https://1drv.ms/u/s!AoSNu6f2nqiumRjD8kUto7-OBeAw?e=i2sskl

Maybe this is different from the VetusWare files? The DOS version runs under vDos and DOSBox, by the way.

**Comment by cracyc** [comment]
Are you using the newest build from appveyor?

**Comment by alienfxfiend** [comment]
> 
> 
> I don't know if it's useful, but here's an ISO image of the actual CD bought on eBay:
> 
> https://1drv.ms/u/s!AoSNu6f2nqiumRjD8kUto7-OBeAw?e=i2sskl
> 
> Maybe this is different from the VetusWare files? The DOS version runs under vDos and DOSBox, by the way.

Collins English Dictionary runs fine on Windows XP, just not with otvdm. The ISO has the same problem. I managed to get The Thinking Man's Thesaurus to work though, just not this. Oh & VDAT 1.6 worked too, so I got my hopes up.



> 
> 
> Are you using the newest build from appveyor?

What is Appveyor, & where can I find the latest build on there ??

**Comment by cracyc** [comment]
https://ci.appveyor.com/project/otya128/winevdm/build/job/sv1o7munadfdcl2k/artifacts

**Comment by alienfxfiend** [comment]
> 
> 
> https://ci.appveyor.com/project/otya128/winevdm/build/job/sv1o7munadfdcl2k/artifacts

So is it fixed ? :) When can I expect a Release ?

**Comment by cracyc** [comment]
> So is it fixed ? 

Don't know.  Try it and find out.

> When can I expect a Release ?

Hopefully soon as we're getting more than a few bug reports for thing already fixed,

**Comment by alienfxfiend** [comment]
[COLLINS.zip](https://github.com/otya128/winevdm/files/7532920/COLLINS.zip)
Please I need to use this dictionary app urgently: "Collins English Dictionary", it errors out with an error message when running it with OTVDM under Windows 10. Even with the 0.8 update. 😢 It would help my field of work tremendously if you can please fix it !!
