### ISSUE TITLE
CD-ROM detection fails (The Lion King Animated Storybook)

### ISSUE THREAD

**Issue by Athari** [otya128/winevdm#557]
I'm trying to run The Lion King Animated Storybook. It works in Win2000 32-bit VM, but when I run it through WineVDM, the following message is displayed:

> **The Lion King**
> The "The Lion King" CD-ROM was not found in the CD-ROM drive. Please insert and press Retry.
> `Retry` `Cancel`

Trying to investigate what's causing it, I came across this [code of GetDriveType](https://github.com/otya128/winevdm/blob/e5b24700126e83b569ebc4e3a2ee19c887210e63/krnl386/file.c#L1580) (the executable does import the function):

```c++
/***********************************************************************
 *           GetDriveType   (KERNEL.136)
 * Get the type of a drive in Win16.
 *
 * RETURNS
 *  The type of the Drive. For a list see GetDriveTypeW from kernel32.
 *
 * NOTES
 *  Note that it returns DRIVE_REMOTE for CD-ROMs, since MSCDEX uses the
 *  remote drive API. The return value DRIVE_REMOTE for CD-ROMs has been
 *  verified on Win 3.11 and Windows 95. Some programs rely on it, so don't
 *  do any pseudo-clever changes.
 */
UINT16 WINAPI GetDriveType16( UINT16 drive ) /* [in] number (NOT letter) of drive */
{
    UINT type;
    WCHAR root[3];

    root[0] = 'A' + drive;
    root[1] = ':';
    root[2] = 0;
    type = GetDriveTypeW( root );
    if (type == DRIVE_CDROM) type = DRIVE_REMOTE;
    else if (type == DRIVE_NO_ROOT_DIR) type = DRIVE_UNKNOWN;
    return type;
}
```

Could this be the cause? I don't understand the reasoning. Why is functionality of MSCDEX affecting DRIVE_CDROM return value? What is DRIVE_REMOTE value being "verified" supposed to mean?

--------

**[Update]**

Returning `DRIVE_CDROM` causes this:

> **The Lion King**
> "The Lion King" cannot be played since this computer lacks 
>      *  a CD-ROM drive
> `OK`

So... Windows 3x doesn't even support `DRIVE_CDROM` value and all applications expect `DRIVE_REMOTE`? I wonder what breaks CD-ROM detection then...

**Comment by cracyc** [comment]
MSCDEX uses the MSDOS redirector api which makes it look like a network drive thus DRIVE_REMOTE.  The newest build, for me, still fails but a different way.

**Comment by Athari** [comment]
@cracyc Huh, I just realized that the version from the master branch does get past this error indeed. Now I see this after switching to completely black full-screen:

> **The Lion King**
> An error occurred attempting to read the CD.
> `OK`

Console log contains:

> 2dc0:fixme:mmsys:mmioSetBuffer16 473: really ?

This is more complicated.

**Comment by cracyc** [comment]
```
1e78:Call MMSYSTEM.1210: MMIOOPEN(13ff6692 "E:/data/boot.stm",0000:0000,00000000) ret=13a7:10a9 ds=13ff
1e78:Ret  MMSYSTEM.1210: MMIOOPEN() retval=00000032 ret=13a7:10a9 ds=13ff
1e78:Call MMSYSTEM.1217: MMIOSETBUFFER(0032,14ff0014,00008000,0000) ret=13a7:1114 ds=13ff
1e78:fixme:mmsys:mmioSetBuffer16 473: really ?
1e78:Ret  MMSYSTEM.1217: MMIOSETBUFFER() retval=00000005 ret=13a7:1114 ds=13ff
```

https://github.com/otya128/winevdm/blob/master/mmsystem/mmio16.c#L473

It's calling mmioSetBuffer when the pmmioinfo parameter to mmioOpen was null which causes it to return MMSYSERR_INVALHANDLE.  It might be that is actually harmless and shouldn't return an error.

**Comment by Athari** [comment]
If I understood correctly, `mmioOpen` doesn't work properly — it creates an unusable HMMIO which causes all functions interacting with it to fail because there's no corresponding thunk. According to documentation, this is not only supposed to work correctly, it's the [suggested usage](https://docs.microsoft.com/en-us/previous-versions/dd757331%28v%3dvs.85%29):

> Unless you are opening a memory file, specifying the size of a buffer for buffered I/O, or specifying an uninstalled I/O procedure to open a file, this parameter should be NULL.

So, I fixed the function to best of my ability:

```diff
diff --git a/mmsystem/mmio16.c b/mmsystem/mmio16.c
index 92499b1d..7649ce99 100644
--- a/mmsystem/mmio16.c
+++ b/mmsystem/mmio16.c
@@ -316,7 +316,32 @@ HMMIO16 WINAPI mmioOpen16(LPSTR szFileName, MMIOINFO16* lpmmioinfo16,
 	lpmmioinfo16->wErrorRet = mmioinfo.wErrorRet;
         lpmmioinfo16->hmmio     = HMMIO_16(mmioinfo.hmmio);
     } else {
-	ret = mmioOpenA(szFileName, NULL, dwOpenFlags);
+	MMIOINFO	        mmioinfo;
+	struct mmio_thunk*      thunk = NULL;
+
+	memset(&mmioinfo, 0, sizeof(mmioinfo));
+
+	EnterCriticalSection(&mmio_cs);
+	if (!(thunk = MMIO_AddThunk(NULL, NULL)))
+	{
+	    LeaveCriticalSection(&mmio_cs);
+	    return 0;
+	}
+
+	mmioinfo.pIOProc = (LPMMIOPROC)thunk;
+	if (!szFileName)
+	    mmioinfo.adwInfo[0] = (DWORD)DosFileHandleToWin32Handle(mmioinfo.adwInfo[0]);
+
+    	ret = mmioOpenA(szFileName, NULL, dwOpenFlags);
+
+	if (!ret || (dwOpenFlags & (MMIO_PARSE | MMIO_EXIST)))
+	{
+	    thunk->pfn16 = NULL;
+	    thunk->hMmio = NULL;
+	}
+	else thunk->hMmio = ret;
+	if (ret && (dwOpenFlags & MMIO_ALLOCBUF)) FIXME("ooch\n");
+	LeaveCriticalSection(&mmio_cs);
     }
     return HMMIO_16(ret);
 }
```

Not entirely sure whether it's correct, but the app gets past the loading of media. Now I get to the point where all I see is a black screen — no graphics, no sound. But not errors either. The log with `WINEDEBUG=+relay,+mmsys` config is spammed with `GetMessage` and other functions for working with messages. The list of GDI functions used is suspiciously empty (no bitmaps created, only `SetDIBitsToDevice` is called — it isn't supposed to work, right?). Something is happening with palettes, including wrecking my system with `SetSysColors`. Now system common controls have weird colors — white background and black selection rectangle. I hope it doesn't persist.

I'm stuck at the moment and don't know how to proceed.

**Comment by cracyc** [comment]
I suspect mmioAdvance.  It tries to copy the file into ram 32K at a time but instead the buffer gets filled with the same data every time.

**Comment by Athari** [comment]
@cracyc Do you think this can completely stop the game from working? I don't know neither this API nor implementation, so at this point I'd rather find a way to skip the sound part and see something other than the black screen, if possible. X)

The `SetDIBitsToDevice` function is called 3 times, every time with black 640x480@8 bitmap data with completely black palette...

**Comment by cracyc** [comment]
It probably gets confused because it never finds the end of the file.  Anyway, https://github.com/otya128/winevdm/pull/558 fixes it.

**Comment by Athari** [comment]
@cracyc Awesome, it works! Thank you!

Setup.exe still doesn't work, by the way. The release version of WineVDM runs, but doesn't copy files or create links in the main menu (it should copy 4 files and create 3 links). The master version crashes with AV when I press the "Setup" button. Doesn't really matter (the "installed" version of the game still requires the CD and the executable works just fine directly from the CD), but it's one more source of compactibility problems if you're interested.

**Comment by cracyc** [comment]
For me it installs properly but if I click play now at the end, it segfaults.  I'd need a trace to try and fix your crash.
