### ISSUE TITLE
overflow error

### ISSUE THREAD

**Issue by Rarder44** [otya128/winevdm#563]
Program: ALPA250.exe 
old CAM for a CNC.

**Describe the bug**
when I try to calculate the machine's operating time, the program does not work properly (there are 2 examples attached):
1) a negative execution time is calculated
2) an "Overflow" message is displayed and the program closes

In both examples I used the same drawing with the same tool; only the length of the grinding path changes.

**Expected behavior**
Calculate the correct time and don't crash

**Screenshots**
1)
![1-negative number](https://user-images.githubusercontent.com/1337415/70788041-4d717a00-1d90-11ea-9ef0-0098ba445f7b.png)

2) 
![2-overflow](https://user-images.githubusercontent.com/1337415/70788042-4e0a1080-1d90-11ea-8418-0d61b57a2299.png)

**Environment (please complete the following information):**
Windows 10 -> 10.0.17763.864
Version  -> 1560 (lastest)

**Additional context**
the trace files are too big, I upload them to google drive.
 https://drive.google.com/drive/folders/1ro0kHCQGc2Qd7voNRw4IWwbd0bXxvcBa?usp=sharing

**Comment by cracyc** [comment]
This is likely a floating point emulation bug.  There's not enough information in the trace to debug it.  Would probably need access to the program.

**Comment by Rarder44** [comment]
if there are no problems for you, I can prepare a package containing the program and a txt file to explain how to replicate the problem.

**Comment by cracyc** [comment]
Okay

**Comment by Rarder44** [comment]
here are the necessary instructions and files

[Instructions.docx](https://github.com/otya128/winevdm/files/3964711/Instructions.docx)
[otvdm.zip](https://github.com/otya128/winevdm/files/3964713/otvdm.zip)
[EASYCAD.zip](https://github.com/otya128/winevdm/files/3964714/EASYCAD.zip)

**Comment by cracyc** [comment]
I did reproduce the problem in winevdm so I tried other things to get a sense of what is supposed to happen.  The program crashes in XP/ntvdm in a whpx vm, crashes in Wine and crashes Qemu running windows 98.  It does work in Dosbox with windows 3.1 but the overflow error and negative time occur there too.  Is there an emulation (or even a real machine), running which OS, where it works without the error?

**Comment by Rarder44** [comment]
Complete history:
the program currently runs under a XP machine running Windows 7 (windows xp mode).
I had to change the computer and the program no longer works; I was able to understand that the problem is related to the win87em library (the one that emulates the x87 cooprocessor for floating point calculations). the library refers to a virtualization feature of some processors that is no longer present in modern processors.
a temporary solution was the use of HIDE87 (winfloat) which goes to tell the SO that the co-processor does not exist, going to redirect the calculations to the CPU; obviously this method impacts a lot on performance.
so I tried with other virtualization systems, and the only one I found functional is winevdm which goes to completely rewrite the win87em library.
I therefore believe that the problem is related to that library: I downloaded the source, compiled and attached the debugger to the process but not completely knowing the source (as the various libraries interact) I could not identify the problem.

**Comment by Rarder44** [comment]
at the moment I still have the possibility to run the program in a working machine, if you tell me what you need (log, memory dump, etc.) I will provide them to you.

**Comment by cracyc** [comment]
No need, I know what the problem is, it's just a difficult one to fix.  About "going to redirect the calculations to the CPU; obviously this method impacts a lot on performance" you do know that unless you enable HAXM, winevdm is full emulation.  You might want to do some further performance testing.

**Comment by Rarder44** [comment]
yes of course, maybe I expressed myself badly.
I honestly don't know what methodology is used when the cooprocessor is "hidden" and I don't know therefore how it goes to emulate the calculations; I know however with certainty (after numerous tests) that using the HIDE87.COM any application I use (along with ALPA250 there are other applications) are very slow; they are less slowed with emulation via winevdm.
I tried to emulate using HAXM but it doesn't seem to work ... I have to do further tests.

**Comment by Rarder44** [comment]
I checked:
with hamx enabled the program crashes when opening when calling the _fpMath with ebx = 000a (case 10:) with the error
"Run-Time Check Failure # 2 - Stack around the variable 'fpustate' was corrupted."
I should try to do tests ...
I don't know if this problem could be related to the previous one or maybe it's better to open another "issue"

**Comment by Rarder44** [comment]
ok, I changed the length of the array, (from 100 to 1000) and now it's not the problem anymore.
(actually the magic number is 108)
obviously now there are other problems ... but maybe it's better to first make everything work normally ...

**Comment by Rarder44** [comment]
with the latest builds the problem has "reappeared".
(1659 is functional, 1686 is not ... I don't know exactly in which build the problem was re-introduced)

going to perform the calculation of the times, the program continues to load and the following strings continue to scroll in the console:
Unmasked x87 exception (CW: 1332, SW: 45e1)
Unmasked x87 exception (CW: 1332, SW: 47e1)
Unmasked x87 exception (CW: 1332, SW: 47e1)
Unmasked x87 exception (CW: 1332, SW: 45e1)
....

Using HAXM the problem does not occur
