### ISSUE TITLE
WordPerfect 7 says it only installs under Windows 95

### ISSUE THREAD

**Issue by emendelson** [otya128/winevdm#567]
WordPerfect for Windows 7.0's setup program gives an error message saying that it doesn't run under Windows NT, only in Windows 95. I tried changing the compatibility settings on SETUP.EXE to Windows 95, and it gave an error message "PerfectOffice Setup Program" - "Key not found in set file: CannotRunEXE." (Behind this message is a box saying "Copying Temporary Files. Please Wait..."

This is one of the versions available at WinWorldPC.com, but I'm not entirely certain which. The file date is 5/2/1996.

**Comment by emendelson** [comment]
Here is a complete installer setup (made up from 19 disk images at WinWorldPC.com) that demonstrates the problem. When you try to run Install.exe, you get a message saying that it only runs under Windows 95, not NT:

http://www.columbia.edu/~em36/WP7Win95only.7z

**Comment by Anixx** [comment]
The setup is a 32-bit application it has nothing to do with otvdm. You can try to run it in Windows 95 compatibility mode.

**Comment by emendelson** [comment]
Apologies for wasting everyone's time. If I had spent thirty seconds thinking about this, I would have realized that it was irrelevant to Winevdm.
