### ISSUE TITLE
Oxford Hachette French English Dictionary menu bar errors

### ISSUE THREAD

**Issue by PBreeze** [otya128/winevdm#568]
Try the latest version first.
Go [here](https://ci.appveyor.com/project/otya128/winevdm) and click `Environment: THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1`-> `Artifacts 1`-> `zip` to download the latest version.

**Describe the bug**
The Oxford Hachette French English Dictionary installs from CD and runs under Oxford's SuperLex v1.3.  The dictionary works but a click on either 'File' or 'Book' on the menu bar brings up an error box which reads:

address=77DC5AF
access address=67388BAC
VM context
EAX:B6B8 ...  (there is more here if you need it but I have to copy it all manually)

Interrupt 0D #GP (127F:9F33) flags 3256 err 0000
push  word ptr es:[bx+4h]

**Expected behavior**
A click on the menu bar entry should bring up a menu

**Screenshots**
![Hachette error](https://user-images.githubusercontent.com/59335560/71557542-63916280-2a3f-11ea-9d5d-bb27c5647304.jpg)

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10 1903]
 - Version [e.g. version: 1523]

**Additional context**

It is very helpful to provide a trace file if possible.
Please note that this file contains detailed information about the program.
**Procedure**
1. Run the command prompt.
2. Set the environment variable:
```cmd
set WINEDEBUG=+all,-snoop,-ldt,-fixup,-module,-global,-local,-disasm,-syslevel,-thunk
```
3.
```cmd
*old-executable-file* 2> trace.txt
```
4. Upload trace.txt here.

**Comment by cracyc** [comment]
The program changes the menu in it's window creation message handler so when it reaches https://github.com/otya128/winevdm/blob/master/user/window.c#L3136 the menu handle it sets is already destroyed.

**Comment by PBreeze** [comment]
Does this mean that I am stuck with the problem in this program or is there some workaround?

**Comment by PBreeze** [comment]
Does this mean I am stuck with the problem in this program or is there a workaround

**Comment by cracyc** [comment]
https://github.com/otya128/winevdm/pull/569 fixes it
