### ISSUE TITLE
In WinText demo the coordinates indicator in the titlebar overlaps with the minimize button. 

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#570]
In WinText demo the coordinates indicator in the titlebar overlaps with the minimize button. Since in Win2 the buttons are thicker and there is no overlap, maybe Winevdm reports the button size incorrectly? It seems in Win1, Win2 and Win3.x the indicator aligns with the window buttons finely even though they have different size in all these systems.

**Comment by cracyc** [comment]
This is hard coded.  It puts the text one icon width to the left on win1 and two icons on win2 and above.  It doesn't account for the possibility of three and looks the same on ntvdm.
