### ISSUE TITLE
Request: Per-application settings in otvdm.ini

### ISSUE THREAD

**Issue by emendelson** [otya128/winevdm#581]
In the future, would it be possible to have per-application settings in otvdm.ini, something like this:

[xw.exe]
EnumFontLimitation=1

This would let specific applications have different settings from the default settings used by other applications.

If something like this exists already, my apologies for time-wasting!

**Comment by cracyc** [comment]
We've got that for 256 color and 640x480 mode but unfortunately that's limited by the available options in the the compatibility tab.

**Comment by emendelson** [comment]
Do you mean that we should use that setting in the Compatibility tab for each application? I tried it with XyWrite for Windows, but it still starts up in full-screen mode. Am I missing something obvious?

**Comment by cracyc** [comment]
It only matters to programs that force a fullscreen window that can't be resized but only use a 640x480 section.  The magnifier can then be used to zoom it (https://github.com/otya128/winevdm/issues/561).
