### ISSUE TITLE
Notabene 9.0 reports that it requires window NT 3.51 build 1057 or above

### ISSUE THREAD

**Issue by PBreeze** [otya128/winevdm#583]
Try the latest version first.
Go [here](https://ci.appveyor.com/project/otya128/winevdm) and click `Environment: THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1`-> `Artifacts 1`-> `zip` to download the latest version.

I have installed Notabene 9.0 in Windows 7 64 bit but when I try to run the program it reports

""Wrong version of operating system; requires Window NT 3.51 (build 1057 or above)" 

The installation established an ,INI file in the OTVDM\Windows directory which reports the OS as Windows 95.  I'm not sure how to overcome this.
![NB9 error](https://user-images.githubusercontent.com/59335560/71988214-63574b00-3227-11ea-9e89-0b50f948ad81.jpg)

**Describe the bug**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10 1903]
 - Version [e.g. version: 1523]

Windows 7 64 bit

**Additional context**

It is very helpful to provide a trace file if possible.
Please note that this file contains detailed information about the program.
**Procedure**
1. Run the command prompt.
2. Set the environment variable:
```cmd
set WINEDEBUG=+all,-snoop,-ldt,-fixup,-module,-global,-local,-disasm,-syslevel,-thunk
```
3.
```cmd
*old-executable-file* 2> trace.txt
```
4. Upload trace.txt here.

**Comment by emendelson** [comment]
Nota Bene 9 is 32-bit software that won't run under 64-bit Windows for some unknown reason. Otvdm won't have any effect on it. (I've made the same mistake about other software.):

https://www.notabene.com/windows7.html

**Comment by PBreeze** [comment]
I am waiting for a response from Notabene technical support but my belief was that Notabene 9 is not 32 bit.  At the moment I think it is 16 bit and that only with Notabene 10 did they move to 32 bit software.  When I installed notabene 9, the software produced nbsetup.ini in otvdm\windows and I would only have expected this if otvdm was invoked.  (However I am prepared to be corrected on all of this.)

**Comment by emendelson** [comment]
You are probably right!

**Comment by cracyc** [comment]
A trace will be needed to have any hope of fixing it.

**Comment by PBreeze** [comment]
I am not familiar with the process of creating a trace file, so I hope this is what is required:

[trace.txt](https://github.com/otya128/winevdm/files/4036701/trace.txt)

**Comment by cracyc** [comment]
When it finishes try a build from https://ci.appveyor.com/project/otya128/winevdm/builds/29981970/job/ks621jap7d8hha59
