### ISSUE TITLE
Shell from 16-bit app to cmd.exe?

### ISSUE THREAD

**Issue by emendelson** [otya128/winevdm#593]
Some 16-bit Windows applications (for example, XyWrite; also I think WordPerfect 5.x, but I'm away from the machine that has it)) have a feature that runs a DOS command or shells to DOS. These cause errors under otvdm. Is it possible to add an option that will run a command in cmd.exe or shell to cmd.exe when a program tries to shell to DOS?

**Comment by cracyc** [comment]
You can set the dos emulation in the otvdm.ini file by default it's otvdm.exe itself.  The emulator needs to be able to take a filename on the command line like the msdos player so using dosbox would be awkward.  Xywrite's "go to dos" option runs command.com so you'd have to have a command.com file somewhere thats in both the winevdm path and the host path.

**Comment by emendelson** [comment]
Thank you for that - I'm traveling with a Mac, or I hope I would have looked at otvdm.ini for this...

Now I wonder if it's possible to write a fake "command.com" that would do nothing but launch cmd.exe with whatever parameters were entered for "command.com"....

**Comment by cracyc** [comment]
Winevdm will check the type of program it's running before running it so if you copy cmd.exe to command.com then it'll run it as a windows program or a batch file called command.com that runs cmd.exe.  Alternatively, use a dos emulator with a builtin command.com, doesn't require drive mapping, and can run windows programs (does vDos do this? I'm not sure).

**Comment by emendelson** [comment]
Wait - I didn't realize that the MSDOS Player does all this. I simply hadn't looked at that program before.

**Comment by cracyc** [comment]
No, it doesn't, I'm just suggesting ways to do what you said you wanted.

**Comment by emendelson** [comment]
Ah - I didn't see your message when I posted mine. Sorry about the confusion.

vDos needs drive mapping but can be set up to map all existing drives automatically on startup. It may be the way to accomplish this. I'll experiment.
