### ISSUE TITLE
Small font in 16 bit programs

### ISSUE THREAD

**Issue by PBreeze** [otya128/winevdm#596]
Try the latest version first.
Go [here](https://ci.appveyor.com/project/otya128/winevdm) and click `Environment: THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1`-> `Artifacts 1`-> `zip` to download the latest version.

It seems that with many 16 bit programs there is a windows font that cannot be controlled with any display settings in windows.  This is not a bug in OTVDM but I wonder if OTVDM can offer any solution.

Typical of the small font is the text in XYWrite for Windows shown here:

![XYwrite with small font](https://user-images.githubusercontent.com/59335560/72540099-4ef2fe00-3878-11ea-9570-835f4f4b5ce0.jpg)

It is possible to increase the font size by scaling but this affects all fonts and means resetting everything.  Is there any way of getting hold of this one font and resizing it?

**Describe the bug**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10 1903]
 - Version [e.g. version: 1523]

**Additional context**

It is very helpful to provide a trace file if possible.
Please note that this file contains detailed information about the program.
**Procedure**
1. Run the command prompt.
2. Set the environment variable:
```cmd
set WINEDEBUG=+all,-snoop,-ldt,-fixup,-module,-global,-local,-disasm,-syslevel,-thunk
```
3.
```cmd
*old-executable-file* 2> trace.txt
```
4. Upload trace.txt here.

**Comment by cracyc** [comment]
This would, I think, be a very difficult thing to make work properly without help from the OS.  There are quit a few programs, especially games that draw only to a 640x480 window (see https://github.com/otya128/winevdm/issues/561), that would benefit from Windows being able to scale a window and all of it's contents.  Barring that though, I don't think this is reasonably doable.

**Comment by PBreeze** [comment]
That does not surprise me.   A shame.  I can probably get around it in this case, especially if we can get notabene 9 to run.  That is essentially built on the top of XYWrite code but has additional facilities to change fonts within the program.  Anyway, thanks for your reply.

**Comment by PBreeze** [comment]
It has just occurred to me that it may be possible to control the font to some extent if the old "oemfonts.fon=" setting from win.ini can be implemented.  Is this possible, or indeed useful?

**Comment by PBreeze** [comment]
I have found a solution under Windows 7 64 bit for this problem.  It involves editing the registry.  Go to:

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\GRE_Initialize\SmallFont

Here you will find three keys that define the fonts for FIXEDFON.FON, FONTS.FON AND OEMFONT.FON.  To increase the draft font size in XYWrite for Windows (and incidentally to change it to a sans serif font) change they key value of OEMFONT.FON from vga850.fon to 8514oem.fon.  The log off and back on or reboot and all should be well.

This is the setting that would pertain if the magnification was set to 125% but you can force the font just for this setting with the above edit.  This is also equivalent to the font setting that XyWin would have taken from system.ini under windows 3.11. 

I have also changed several other .FON fonts under such as COURE and SMALLE in the key below:

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts

to get larger on-screen fonts in some of the 16 bit programs I can now run.  Changing E to F fonts, eg COURE to COURF forces a larger font.  So far as I can see these settings only affect the 16 bit programs.  All the standard 32 bit and 64 bit programs take their font settings from the windows 7 theme in operation.

**Comment by cracyc** [comment]
That will affect any program which uses the SYSTEM_FONT, SYSTEM_FIXED_FONT or OEM_FIXED_FONT stock objects (https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-getstockobject) which will be few from after Windows 97 and Windows NT 4.0.

**Comment by PBreeze** [comment]
Yes.   It does seem to affect fonts in several 16 bit programs I am now able to use.  The changes I have made are equivalent to selecting 125% magnification in Windows, but only for these fonts.  I will close this now.
