### ISSUE TITLE
Redirect LPT# and COM# output to file?

### ISSUE THREAD

**Issue by emendelson** [otya128/winevdm#600]
Probably this is impossible, but I thought I was worth asking. The msdos player redirects LPT1 output to a disk file. Is it possible to have an option in winevdm that would redirect LPT# and COM# output to a file in the same way?

**Comment by cracyc** [comment]
Not impossible just kind of difficult to do in winevdm directly.  The best way to do this is to get a virtual com port like https://sourceforge.net/projects/com0com/ or https://www.hw-group.com/software/hw-vsp3-virtual-serial-port that would permit connecting software that uses serial ports to an ip socket.  As for lpt you'd want to look into "net use lpt1" with a generic text only print connected to the FILE: port which (i believe) will prompt where to save to output.

**Comment by emendelson** [comment]
Thanks for those alternatives - I didn't know about the virtual com port software. The reason I'm asking is that I want to be able to distribute an installer for 16-bit software that wants to print to LPT1 only, and I don't want to interfere with other users' NET USE setup. I've put together some complicated workarounds, but a redirect option would be nice to have. This is NOT something I'm asking for if it's difficult to do.
