### ISSUE TITLE
XyWrite can't find its Help items

### ISSUE THREAD

**Issue by emendelson** [otya128/winevdm#603]
Another problem with latest code and XyWrite for Windows:

Help/Index brings up the help screen for "New" (but I can open the index from there) 

Help/Glossary produces the hourglass cursor, then nothing

Help/Keyboard Help produces the hourglass, cursor then nothing

Help/Using Help produces an error "Cannot find 'winhelp.hlp. etc."

I don't think XyWin uses standard Windows Help, but I can't be certain.

**Comment by cracyc** [comment]
https://github.com/otya128/winevdm/pull/604 fixes these (except the winhelp.hlp where you need a copy of that file in your windows path, windows doesn't include it anymore).

**Comment by emendelson** [comment]
Thank you again!
