### ISSUE TITLE
"Visual Accounts 2000" does not draw its screen correctly

### ISSUE THREAD

**Issue by PBreeze** [otya128/winevdm#608]
**Describe the bug**
The accounting program visual accounts 2000 does not draw its screen correctly in Windows 7 64 bit.  I have attached screenshots below to show the problem which can be seen most clearly at the bottom of the screen where the buttons are only half visible.  In full screen, these disappear off screen.  I have also seen a problem when I selectively change the MS Sans Serif 8, 10, 12 .. font from SSERIFE to SSERIFF in the registry.  This controls the font on much of the screen but with the larger font there are missing letters.

**Screenshots**
The screen shot below is the erroneous version:
![Visual Accounts screen](https://user-images.githubusercontent.com/59335560/73075074-027c7380-3eb3-11ea-96ba-c9de7db7d8c3.jpg)

The shot below is how it should look.  This is taken for the same program in Windows XP

![Visual accounts 1](https://user-images.githubusercontent.com/59335560/73075141-2d66c780-3eb3-11ea-8b00-1acbd2160471.jpg)

**Environment (please complete the following information):**
Windows 7 64 bit

**Additional context**
[trace.txt](https://github.com/otya128/winevdm/files/4108852/trace.txt)

**Comment by cracyc** [comment]
This is cause by the large font in the menu.  On Windows 10 with the default settings the buttons are only slightly shifted down.  It can also be reproduced in XP/NTVDM by selecting extra large fonts in the Display Properties control panel.

**Comment by PBreeze** [comment]
OK. Nothing to be done then.

**Comment by otya128** [comment]
"Account" group box is not drawn correctly.

**Comment by PBreeze** [comment]
I presume, then, the problem is with the original software.  Do you think there is any simple way to fix this?

**Comment by cracyc** [comment]
The group box problem is not with the software, it can be reproduced in vb3 by making a frame control and putting a label in it.  The window size problem is with the software.

**Comment by PBreeze** [comment]
I am not a coder so I  do not know precisely what that implies.  Is there a fix, then, so that the "Account" group box will be drawn correctly?

**Comment by cracyc** [comment]
Not yet but it seem likely to be fixable.

**Comment by PBreeze** [comment]
I have tested 1638 but the screen is still not drawn correctly.  If it is of any help there is a demo version of the program here:

https://visualaccounts.co.uk/vadown.htm

Scroll down to "Visual Accounts 2000 (previous version)" and download the previous version.  You will see on this page that there is a 32 bit version but this forces a location for data files to be stored and this does not suit me, which is why I have stuck with the 16 bit version.

**Comment by PBreeze** [comment]
Sorry that should have read "download the business version."

**Comment by cracyc** [comment]
The patch fixes the account frame visibility.  The windows size problem is a bug in the program.

**Comment by PBreeze** [comment]
OK.  Thanks.  Do you want to close this now?
