### ISSUE TITLE
People are using the old version of Winevdm and spread bad word about it.

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#610]
For instance:
https://www.computerhope.com/forum/index.php?topic=175637.0

===
Please, read more carefully what I'm writing.

First:
NTVDM is even part of 32-bit Windows - look into legacy features which is possible to include into Windows without any extra installation.
NTVDMx64 (and I'm using it) is 64-bit version of NTVDM for 64-bit Windows.
NTVDM is abbreviation of NT Virtual DOS Machine.
You need not DOSBox for this. NTVDMx64 is not part of Windows and requires extra installation.
WineVDM is similar but allows to run even Win16 apps. Current version is 0.70.
To make you sure look at https://github.com/otya128/winevdm and try it.

My goal is to make WineVDM able to start Win16 apps directly without otvdm command like NTVDM and NTVDMx64 starts DOS 16-bit apps.
Simply handle error message to avoid showing it and jump to recall application by otvdm command automatically - simply: Handle Win16 application by starting EXE file and after above mentioned error jump to call otvdm command.
Currently WineVDM is not able to correctly to install Win16 apps - it think never will.

Miro
===

**Comment by emendelson** [comment]
I responded to the question on the website, and then responded to a followup. I think we can all ignore that thread now.
