### ISSUE TITLE
Crash with "integer divide by 0" error when accessing to COM port

### ISSUE THREAD

**Issue by FR-Theo** [otya128/winevdm#615]
Hello and Thanks for the awesome work on this project !
A few months ago I tried to launch with otvm an application needing serial ports, after a 1st error which was actually caused by a lack of access rights ([#132](https://github.com/otya128/winevdm/issues/132)), the software did not crash, but as I do not have the equipment to which the software connects, I didn't had the possibility to go further in my test.

Now, I have another 16bits program as well as the associated serial equipment and I would have liked to try to emulate the 16bits software by otvdm, but the program crashe when accessing to the COM port :

_**Describe the bug**_
The industrial software "SIMEAS PAR" is correctly launched by otvdm, however it crashes when trying to access the serial port to send or receive data : 

_1624:Call KERNEL.137: FATALAPPEXIT(0000,1287357d "integer divide by 0") ret=124f:4cab ds=1287
17e0:1624:err:task:FatalAppExit16 1876: "integer divide by 0"_

Other functions of the software seem to work, only the access to the serial port causes the crash.

The error message "integer divide by 0" is displayed and the application is closed.

_**Environment (please complete the following information):**_
Windows 7 SP1 x64
otvdm-master-1642

_**Additional context**_
The installer of this software adds files to "C: \WINDOWS \" ('ini' files) and "C: \WINDOWS\SYSTEM" (CTL3DV2.DLL and LZEXPAND.DLL). These files are present in the 'WINDOWS' directory of otvdm (default CTL3DV2.DLL and LZEXPAND.DLL files had been replaced at setup)

Here is the log file : [https://www.dropbox.com/transfer/AAAAAGY0sVwVTXpoJnW01vKn7tiu72RaC-5wMgXzNH9IWEqmzpRKaZ0](https://www.dropbox.com/transfer/AAAAAGY0sVwVTXpoJnW01vKn7tiu72RaC-5wMgXzNH9IWEqmzpRKaZ0)

Thanks,

**Comment by cracyc** [comment]
The error isn't in the trace.  To have any hope of fixing it, we need to see the actual error.

**Comment by FR-Theo** [comment]
Sorry, wrong log file...
Here is the error : [https://www.dropbox.com/transfer/AAAAACN5EaRgiN2MEVBL8R5n1Ue-F_WDQBALQnY8FxP6LtivAM6gmL4](https://www.dropbox.com/transfer/AAAAACN5EaRgiN2MEVBL8R5n1Ue-F_WDQBALQnY8FxP6LtivAM6gmL4)

**Comment by cracyc** [comment]
It's still not clear what's wrong.  I think I'd have to try the program myself.

**Comment by FR-Theo** [comment]
Thanks Cracyc for your answer,

Here is the program (setup or an archive containing files & otvdm) : https://www.dropbox.com/transfer/AAAAAG85VMkycRWg9M_L96mWuIEy9oiriA8-5unebWf36RK56RxcvGA

The crash occur when accessing to the COM port, for exemple with "File">"Send", "File">"Receive" or "Device">"View Data...".

**Comment by cracyc** [comment]
So the dlls that come with the program have a heapsize of 0x10 in their ne headers which is far too small.  Ntvdm sets it to 0x800 anyway but I'm not sure if it does that for all modules with a small heap or if there's some override somewhere.

**Comment by FR-Theo** [comment]
Thanks for the troubleshooting and for the new build !!
No more error here too ! I will try with the equipment and come back to confirm result.
