### ISSUE TITLE
Inverted color bug

### ISSUE THREAD

**Issue by mrjoey98** [otya128/winevdm#623]
I'm running Microsoft Musical Instruments with otvdm and the first thing I noticed was that the colors within the program are inverted.
![{18D78EA3-23DB-4C14-8188-D93A00DFF9C2} png](https://user-images.githubusercontent.com/49084307/74499164-e156e380-4eb0-11ea-9d3f-6c6a8cd07b6d.jpg)

Sound plays and everything, but these colors are pretty bothersome.
There's also nothing in the console window.
![Annotation 2020-02-13 222515](https://user-images.githubusercontent.com/49084307/74499170-e4ea6a80-4eb0-11ea-8bd2-2521dfba0258.jpg)

I am running Windows 10 1909 64-bit and I'm using the most recent version of otvdm.

**Comment by otya128** [comment]
Try the most recent version first.
Go [here](https://ci.appveyor.com/project/otya128/winevdm) and click `Environment: THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1`-> `Artifacts 1`-> `zip` to download the latest version.

**Comment by Anixx** [comment]
Why did not you use the most recent version?

**Comment by mrjoey98** [comment]
Quick update: _Now_ I'm using the most recent version. No more inverted colors, so problem solved! Thanks a bunch!
