### ISSUE TITLE
Hypervisor error - Disk Full - exception #GP

### ISSUE THREAD

**Issue by Rarder44** [otya128/winevdm#626]
**Describe the bug**
I had already filed a report.
(link: https://github.com/otya128/winevdm/issues/582)
Now, after some updates regarding HAMX I have tested the functionality again and I have found a "change" of the problem:
In addition to the "Disk Full" error, an error message is written with the exception "exception #GP".

**Environment (please complete the following information):**
Windows 10 -> 10.0.17763.864
Version -> 1657 (lastest)

Trace:
[trace.txt](https://github.com/otya128/winevdm/files/4245718/trace.txt)

**Comment by otya128** [comment]
I fixed a related floating point issue.
Please try again the latest version.

**Comment by Rarder44** [comment]
I did tests with the 1659 and it didn't give me any more problems.
Thank you.
I close the issue.
