### ISSUE TITLE
error in display while zooming

### ISSUE THREAD

**Issue by Rarder44** [otya128/winevdm#627]
**Describe the bug**
Error related to the suite of programs described here:
https://github.com/otya128/winevdm/issues/563

The program in question is a CAD.
When I go to zoom, at a high percentage (there is no zoom percentage displayed on the screen, so I don't know exactly "when") the view of the lines drawn by problems near the nodes.
Either "inversions" of lines occur, or some connections are not displayed correctly (I attach an example video).
If I go to use the selection tool, however, the new "incorrect" lines are not selectable; clicking instead where the line should be, the selection takes place.

The program works properly at other zoom levels.

The same problem occurs in the corresponding CAM program (the one described in the issue linked above).

If I run the program with HAXM, after a certain zoom level, the program crashes with a Hypervisor error:
"exception #DE"

**Expected behavior**
Display lines correctly / do not crash with HAXM

**Environment (please complete the following information):**
Windows 10 -> 10.0.17763.864
Version -> 1663 (lastest)

**Additional context**
[trace.zip](https://github.com/otya128/winevdm/files/4289440/trace.zip)
[Video Example.zip](https://github.com/otya128/winevdm/files/4289446/Video.Example.zip)

**Comment by cracyc** [comment]
This is a bug in the program.  If I make the window smaller than 1280x1024 it works correctly.  Any larger and it breaks in winevdm and ntvdm both.

**Comment by Rarder44** [comment]
ok, in fact if I reduce the window size, the problem does not occur without HAXM; 
with HAXM, however, after a certain zoom level the program crashes.

**Comment by cracyc** [comment]
I can't use haxm because I need whpx but it looks like haxvm calls panic for most exceptions even if, as is the case for divide errors in visual basic, a handler is set.

**Comment by Rarder44** [comment]
so there is no possibility to solve this problem? (or possibly a workaround)

**Comment by cracyc** [comment]
The haxm problem probably can be fixed but I can't because I wouldn't be able to test it currently.

**Comment by Rarder44** [comment]
with the new fix, using haxm, the program does not crash in any resolution (at higher resolutions than 1280x1024 it still does not print the lines correctly ... but nothing can be done ...)

**Comment by Rarder44** [comment]
I have done other tests, and I noticed that the problem is unrelated to the resolution 1280x1024.
The problem is always related to the resolution:
the problem occurs when one of the two joined lines is longer than X, where X varies according to the screen resolution.

I made a video where I do a test; I'm going to test with 3 different configurations (video 1)
1 - fullscreen 1920x1080 -> ERROR
2 - very small -> OK
3 - intermediate screen (lower than 1280x1024) -> ERROR

this problem, as I said before, goes in proportion to the lines concerned: as in the video (Video 2) using a resolution lower than 1280x1024 (or equal) the problem occurs ONLY with some lines higher than a given proportion.
1 - "short" line -> OK
2 - one of the 2 lines is long -> ERROR

obviously, that this problem didn't show up in windows 98 / xp .... (I can't try with ntvdm to test if the problem persists even in that virtualization)

[video.zip](https://github.com/otya128/winevdm/files/4355264/video.zip)

**Comment by cracyc** [comment]
>the problem occurs when one of the two joined lines is longer than X, where X varies according to the screen resolution.

The problem is a 16bit signed integer underflow when calling the gdi line function.

> obviously, that this problem didn't show up in windows 98 / xp .... (I can't try with ntvdm to test if the problem persists even in that virtualization)

I've reproduced it in both ntvdm and windows 98.  There's no way to fix it.

**Comment by Rarder44** [comment]
> I've reproduced it in both ntvdm and windows 98. There's no way to fix it.
sorry, I did tests with old PCs, you are actually right, the problem has always been there but the lines were displayed "differently" and therefore I believed that the problem was not there.

I apologize again and thank you.
(I noticed that with the latest updates there has been a problem very similar to one previously had ... I re-open that thread)
