### ISSUE TITLE
My old money bank software (GestComptes) crashing after launch

### ISSUE THREAD

**Issue by aldweb** [otya128/winevdm#633]
**Describe the bug**
My old money bank software (GestComptes, 16 bits French software running fine until Windows XP) crashing after launch.

**Screenshots**
![image](https://user-images.githubusercontent.com/61916846/76150142-5e880980-60a7-11ea-8ffa-665a33966637.png)

**Environment (please complete the following information):**
 - OS: Windows 10 1909 family edition

**Comment by cracyc** [comment]
This isn't enough info, need a trace.

**Comment by aldweb** [comment]
Sure, here you are, trace file attached.

[trace.txt](https://github.com/otya128/winevdm/files/4302542/trace.txt)

And here is another screenshot showing the software working like a charm in DosBox :

![image](https://user-images.githubusercontent.com/61916846/76152945-a9b11500-60c5-11ea-8bc4-ae524077f832.png)

I hope this will help,
Best regards,
aldweb

**Comment by cracyc** [comment]
Unfortunately, there's nothing obvious in the trace.  I'd probably have to test the program directly.

**Comment by aldweb** [comment]
If you wish, I can send it to you. 
Maybe not attach it here altough it is an abandoware by our days...
How do you want me to send it to you?

**Comment by cracyc** [comment]
send it to bs666_1@hotmail.com

**Comment by aldweb** [comment]
Sent.

Best regards,
aldweb

**Comment by aldweb** [comment]
Good job, very impressive result, my software now works like a charm!
Thank you so much.

aldweb
