### ISSUE TITLE
Error on running setup.exe on a game

### ISSUE THREAD

**Issue by alexceltare2** [otya128/winevdm#643]
I'm getting the following error when I run "Disney's Timon & Pumbaa's Jungle Games" setup.exe:
![c](https://user-images.githubusercontent.com/7403035/76711079-c4f2d480-6704-11ea-9f12-388dface4745.png)

**Environment (please complete the following information):**
 - OS: Windows 7 SP1 64-bit
 - WineVDM ver: 0.7

**Comment by cracyc** [comment]
Try the newest build from https://ci.appveyor.com/project/otya128/winevdm THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1-> Artifacts 1-> zip

**Comment by alexceltare2** [comment]
Yep, that definitely fixed it. Thanks. One thing however, it seems that it doesn't create Start Menu shortcuts and it says "Could not add file 'Game' to Program Manager group". Probably needs better Start Menu referencing. Cheers.

**Comment by cracyc** [comment]
We've fixed lots of start menu issues, win16 software abused that interface.  Need to know what you are trying to use to attempt to fix it.
