### ISSUE TITLE
Could not load otvdm.ini

### ISSUE THREAD

**Issue by alexceltare2** [otya128/winevdm#644]
**Describe the bug**
I'm trying to hide the taskbar in a full-screen game but changing otvdm.ini file doesn't do it. I've tried changing values, removing the semicolons ";" but nothing changes. It's like the WineVDM doesn't reference/see the otvdm.ini file.

**Environment (please complete the following information):**
 - OS: Windows 7 SP1 64-bit
 - WineVDM: Version build 1685

**Comment by otya128** [comment]
FixScreenSize is 0 by default, so you don't need to edit it. It seems to be another issue.

**Comment by alexceltare2** [comment]
I see. So changing the otvdm.ini is supposed to also change the 16-bit app upon restart? Because if so, it currently doesn't change anything. Do i need to place the file somewhere else than in the "C:/otvdm/" root folder?

**Comment by otya128** [comment]
Not enough information. Please refer to [this](https://github.com/otya128/winevdm/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and report.

**Comment by alexceltare2** [comment]
> Not enough information. Please refer to [this](https://github.com/otya128/winevdm/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and report.

Fine, I'll do it by the book.
**Describe the bug:** Any 16-bit app that I launch starts with the taskbar visible. I was expecting that a tweak in otvdm.ini will change that but I found out that nothing changes whatever I do in that file. (Disabling aero, enabling screen fix by un-commenting....)

**Expected behavior:** A 16-bit app should respond to argument changes in otvdm.ini by editing the file, saving it, then running the app again.

**Screenshots:** 
![shot1](https://user-images.githubusercontent.com/7403035/79217345-a0defc00-7e46-11ea-9a59-61bc592d1f0b.png)

**Environment:**
- OS: WIndows 7 SP1 64-bit
- Version: otvdm-1690

**Additional context:** Everything is explained in the "Describe the bug" and "Expected behavior", however I'm not entirely sure if otvdm.ini is supposed to reside in the same folder as "C:/otvdm/" or if i need to perform a registry tweak or environment variable to "load it in".

**Debug trace.txt:**
[trace.txt](https://github.com/otya128/winevdm/files/4474874/trace.txt)

**Comment by emendelson** [comment]
There's nothing in otvdm.ini that says the taskbar can be hidden. The easiest way to hide the taskbar is to use Windows Settings -> Taskbar, and turn on "Automatically hide the taskbar in desktop mode."

Alternately, try this:

https://www.thefreewindows.com/3252/hide-completely-the-windows-taskbar-using-a-hotkey-and-unhide-it-with-taskbar-control/

There doesn't seem to be a bug here, and it doesn't seem to have anything to do with loading otvdm.ini, as in the title of the thread. Perhaps you might want to close this and reopen it as an enhancement request - asking for an option to hide the taskbar when a 16-bit application is in full-screen mode.

**Comment by alexceltare2** [comment]
> There's nothing in otvdm.ini that says the taskbar can be hidden. The easiest way to hide the taskbar is to use Windows Settings -> Taskbar, and turn on "Automatically hide the taskbar in desktop mode."
> 
> Alternately, try this:
> 
> https://www.thefreewindows.com/3252/hide-completely-the-windows-taskbar-using-a-hotkey-and-unhide-it-with-taskbar-control/
> 
> There doesn't seem to be a bug here, and it doesn't seem to have anything to do with loading otvdm.ini, as in the title of the thread. Perhaps you might want to close this and reopen it as an enhancement request - asking for an option to hide the taskbar when a 16-bit application is in full-screen mode.

You're missing the point. otvdm.ini has a few tweaks that you can enable/disable by un-commenting and setting as "1" to enable certain parameters (eg. DisableAero=1) but they don't work as intended. So the .ini file doesn't work as expected.

**Comment by alexceltare2** [comment]
I'm closing this issue as I found out a workaround. Apparently, my display is a Full HD (1920x1080) resolution so full screen apps will suffer from not being displayed properly on high DPI displays. The solution was to enable "Disable display scaling on high DPI settings" in Properties>Compatibility for "otvdm.exe" and "otvdmw.exe".
