### ISSUE TITLE
The Dark Eye - game doesn't detect QuickTime

### ISSUE THREAD

**Issue by MrPepka** [otya128/winevdm#650]
I have a problem with The Dark Eye. Namely, despite the installation of QuickTime attached to the game disc, the game at startup still does not detect the codec and displays a message about not finding it. Is there a way to do this? Compatibility modes doesn't work for me

**Comment by cracyc** [comment]
Using the installer on this disk worked for me.  The videos are cut off unless 256 color mode is set though.

**Comment by MrPepka** [comment]
Okay, I was able to properly install QuickTime and launch the game. I copied the installation file to the game folder and from there installed the slick codec. Now the game is working
