### ISSUE TITLE
Mathematica 2.2.1

### ISSUE THREAD

**Issue by gretom** [otya128/winevdm#652]
Try the latest version first.
Go [here](https://ci.appveyor.com/project/otya128/winevdm) and click `Environment: THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1`-> `Artifacts 1`-> `zip` to download the latest version.

**Describe the bug**
I installed winevdm 4/11/2020, then installed my old Mathematica 2.2.1 for Windows.  Everything went perfectly until I tried to do a calculation.  I typed 2+2, but when I hit Shift-Enter, the Mma window disappeared.  It was as if I had not opened Mma.

**Expected behavior**
In Mma, just typing Enter moves you to the next line.  To get a line to be calculated, you need to type Shift-Enter. Then the result should appear on the next line.
**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10 1903] Windows 10 Home
 - Version [e.g. version: 1523]  1903

**Additional context**

It is very helpful to provide a trace file if possible.
Please note that this file contains detailed information about the program.
**Procedure**
1. Run the command prompt.
2. Set the environment variable:
```cmd
set WINEDEBUG=+all,-snoop,-ldt,-fixup,-module,-global,-local,-disasm,-syslevel,-thunk
```
3.
```cmd
*old-executable-file* 2> trace.txt
```
4. Upload trace.txt here.

**Comment by cracyc** [comment]
There's two more issues where esp is getting destroyed, which might be able to be fixed the same as ebp with context.Esp = (context.Esp & ~0xFFFF) | ((size_t)dynamic_getWOW32Reserved()) & 0xFFFF;, and fs is getting set to the host fs after vm_inject which I'm not sure how to fix.

**Comment by gretom** [comment]
Thanks for the reply.  Have to admit I'm not a software developer, and I
don't know what some of your abbreviations meant, but I do appreciate your
getting back to me so soon.  I'll pray and think and tinker and see what
can be done.

Gratefully,

 Tom
*Tom Greenlee*
gretom@bethel.edu

**Comment by cracyc** [comment]
No worries, it's just notes for myself and anyone else who could fix it.  @otya128 might have a better idea how to fix the fs problem.

**Comment by cracyc** [comment]
Basic functionality seems okay but I don't know enough about how to use it to really test.  whpx also appears to work if compute intensive things are too slow.

**Comment by gretom** [comment]
Thanks, GitHub team, for looking into this.
Gratefully,

*Tom Greenlee*
gretom@bethel.edu
