### ISSUE TITLE
Dead Sea Scrolls Electronic Database 1 - App Generates multiple protection fault errors

### ISSUE THREAD

**Issue by dcharlespyle** [otya128/winevdm#661]
The app will run mostly fine but closing various windows in the app will cause general protection errors.

![image](https://user-images.githubusercontent.com/5110398/81612879-bd654a00-939a-11ea-9355-88d0fe3dd78a.png)

Also happens when exiting the app, which will generate two or more errors on exiting.

![image](https://user-images.githubusercontent.com/5110398/81612959-dff76300-939a-11ea-83c6-89b41dea5948.png)

![image](https://user-images.githubusercontent.com/5110398/81612981-e685da80-939a-11ea-9cfd-2f6fd7bdc014.png)

![image](https://user-images.githubusercontent.com/5110398/81613233-5300d980-939b-11ea-805c-1fb6d956e8a3.png)

![image](https://user-images.githubusercontent.com/5110398/81613279-657b1300-939b-11ea-9c40-0b03de0a3958.png)

Hoping this is fixable, too.  Trace attached.
[trace.zip](https://github.com/otya128/winevdm/files/4612159/trace.zip)

**Comment by cracyc** [comment]
These trace are from an old version.  Try it with a up to date build from https://ci.appveyor.com/project/otya128/winevdm/build/job/hn6fk447ja95x6b4/artifacts .

**Comment by dcharlespyle** [comment]
Sorry about that!  I thought I had the latest stable release.  Downloaded and tried the updated build you linked, and now get the following:
![image](https://user-images.githubusercontent.com/5110398/81617440-ae829580-93a2-11ea-939f-cbcb793df7dc.png)

Printing now functions without crashing the app but generates the following error on printing.

![image](https://user-images.githubusercontent.com/5110398/81617701-2b157400-93a3-11ea-8b6d-cadeff6b6ce7.png)

The app doesn't crash out anymore, though.  Exiting still generates the following:

![image](https://user-images.githubusercontent.com/5110398/81617828-6152f380-93a3-11ea-8424-0493469267f4.png)
![image](https://user-images.githubusercontent.com/5110398/81617844-67e16b00-93a3-11ea-8cd3-b1efe5484add.png)

It also no longer displays the original icon for the app.  It is some generic icon from elsewhere in the file.  Trace included from newer build.
[trace.zip](https://github.com/otya128/winevdm/files/4612405/trace.zip)

**Comment by dcharlespyle** [comment]
Also saw the following error with newer build.
![image](https://user-images.githubusercontent.com/5110398/81618886-8b0d1a00-93a5-11ea-88e4-6ead46bee13e.png)

**Comment by dcharlespyle** [comment]
Also see this on printing a frame of text.
![image](https://user-images.githubusercontent.com/5110398/81619403-c1976480-93a6-11ea-9e89-ccf341596a3a.png)

Below is what I am trying to print but get nothing but blank page with header and footer.

![image](https://user-images.githubusercontent.com/5110398/81619449-decc3300-93a6-11ea-9acc-12b03fb48fd4.png)
If you need another trace from this, I can send one up.

**Comment by cracyc** [comment]
```
4824:Call KERNEL.21: GLOBALHANDLE(2526) ret=1337:0cd7 ds=138f
4824:Ret  KERNEL.21: GLOBALHANDLE() retval=25270000 ret=1337:0cd7 ds=138f
SReg Load (037e3d2e): Segment is not a data segment or readable code segment.
```
Uh, this is passing a handle to a function that expects a selector and it does it in other places too.  I'm not sure what it expects to get back...

**Comment by cracyc** [comment]
Here's test build to try https://ci.appveyor.com/project/otya128/winevdm/builds/32807533/job/56wqke7dt6kfig6s/artifacts

**Comment by dcharlespyle** [comment]
I've tried the new build and it's near perfect!  No errors on closing windows or exiting the app.  There is just one more serious error that hangs up the print queue and throws up a dialog that cannot be closed.  And nothing prints of the text.  The message stays for a long time "setting up..." but does nothing else.  If I clear the queue, which requires stopping the spooler process and manually deleting the files, I can print again.

![image](https://user-images.githubusercontent.com/5110398/81635405-6c6f4900-93ce-11ea-811c-15de998c2a38.png)
![image](https://user-images.githubusercontent.com/5110398/81635457-801aaf80-93ce-11ea-8709-ac85edae12e0.png)

Printing from the graphic windows still prints perfectly, though.  New Trace attached:
[trace.zip](https://github.com/otya128/winevdm/files/4613226/trace.zip)

Thank you very much for the work you have done so far.

**Comment by cracyc** [comment]
Try the build at https://ci.appveyor.com/project/otya128/winevdm/builds/32864576/job/hw7k5krcn94gg78a/artifacts .

**Comment by dcharlespyle** [comment]
Outstanding!  Seems to have solved all the problems that were being experienced.  Even successfully printed Information Cards without crashing, and with its contents being printed as expected.  Thank you very, very much.  You've just made it possible to save over 90 GBytes of diskspace.  I no longer have need of a full Hyper-V Windows 10 32-bit VM to run the two programs that had similar usages.  I have one other program but if it still also has its problem I'll file under a new issue report.  This issue, I think, can now be closed.  No more GPFaults thus far, either.  Again, thank you very, very much for working on this!  Wish I could use HAXM, too, but Linux Subsystem still uses the Hypervisor that comes with Windows 10 Pro.  So, for now, dealing with slowness in loading of images in parts of the program (brings me back to the old days of Windows 95/NT :-)) is welcome in exchange for not having to run it in a VM to work with the program and do work with it.  Maybe in future I can brush up on my old, rusty programming skills and find a way to have it run with Windows 10's default hypervisor.  In the meantime, the WineVDM is great as is.  I've added mention of WineVDM on Amazon.com.  I have yet to see it appear in one of my reviews of a product but thought you should know I at least made the effort.
