### ISSUE TITLE
Lotus 1-2-3 1.1 segfaults on pushing "restore" button of MDI child

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#669]
If to choose "continue" in the error window, the program continues. The error happens always on pushing this button.

**Comment by cracyc** [comment]
This only happens for me when the mdi window is maximized.  Selecting the restore command from the system menu works properly.  The problem also happens in ntvdm so is unlikely to be fixable easily if at all.

**Comment by Anixx** [comment]
Yes, it happens when the MDI child is maximized only.

**Comment by Anixx** [comment]
Minimize button from maximized position also segfaults.

**Comment by cracyc** [comment]
Turns out the patch was wrong and the real reason why the problem doesn't happen in win95 is because it successfully dereferences the null pointer rather than crashing.
