### ISSUE TITLE
In DISCO Komandir the Fn keys do not work

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#673]
http://old-dos.ru/dl.php?id=4949
This happens in versions 2.10 and 3.00 (both for Win16)

The Fn keys except F9 and F10 do not work.
The program is a file manager with interface similar to Norton Commander, but intended for Windows.

**Comment by cracyc** [comment]
The link points to a win32 program.  I found a win16 version at http://old-dos.ru/dl.php?id=4949 and it works fine for me.

**Comment by Anixx** [comment]
Fixed the link.

**Comment by Anixx** [comment]
Local problem
