### ISSUE TITLE
Civilization II v2.42 crashes

### ISSUE THREAD

**Issue by angrylion7** [otya128/winevdm#7]
Tested without the game's CD in the drive and using this build:
https://ci.appveyor.com/project/otya128/winevdm/build/1.0.65/artifacts
The game works well in Windows XP's NTVDM.

The main exe (it migth take more than a minute to fully load with this debug build) has sound issues and then crashes on "load a game" with the following output:
```
=====dump all modules=====
Module Flags Name Flag
 2d0f   8309    ICONLIB NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_CO
NSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 1abf   8021    WING    NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIB
MODULE
 1a07   8309    ICONLIB NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_CO
NSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 199f   8021    WIN87EM NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIB
MODULE
 1987   8021    TOOLHELP        NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FF
LAGS_LIBMODULE
 196f   8021    COMMDLG NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIB
MODULE
 193f   8309    SMEDSNET        NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_F
FLAGS_CONSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 18e7   8309    MSACM   NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_CO
NSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 188f   8309    AVIFILE NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_CO
NSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 1877   8021    SHELL   NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIB
MODULE
 17f7   8309    MSVIDEO NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_CO
NSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 1167   030a    CIV2    NE_FFLAGS_MULTIPLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_
CONSOLE | NE_FFLAGS_GUI
 114f   8021    SOUND   NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIB
MODULE
 1137   8021    MMSYSTEM        NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FF
LAGS_LIBMODULE
 111f   8021    MOUSE   NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIB
MODULE
 1107   8021    KEYBOARD        NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FF
LAGS_LIBMODULE
 10ef   8021    USER    NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIB
MODULE
 10d7   8021    GDI     NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIB
MODULE
 10a7   8021    COMM    NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIB
MODULE
 108f   8021    SYSTEM  NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIB
MODULE
 1007   8021    KERNEL  NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIB
MODULE
=====dump all modules=====
20: fninit - 0x69517dfc (null)(0)
19: fninit - 0x69517dfc (null)(0)
18: RtlGetProcessHeaps - 0x776b3a21 (null)(0)
17: RtlCaptureContext - 0x776a3533 (null)(0)
16: RtlDestroyEnvironment - 0x776a2ff6 (null)(0)
15: KiUserExceptionDispatcher - 0x77650154 (null)(0)
=============================
14: mmioAdvance - 0x7006e324 (null)(0)
13: mmioAdvance - 0x7006e324 (null)(0)
12: SizeofResource16 - 0x698187fc (null)(0)
11: SizeofResource16 - 0x698187fc (null)(0)
10: SizeofResource16 - 0x698187fc (null)(0)
9: fninit - 0x69517dfc (null)(0)
8: fninit - 0x69517dfc (null)(0)
7: SizeofResource16 - 0x698187fc (null)(0)
6: SizeofResource16 - 0x698187fc (null)(0)
5: WOWGlobalLock16 - 0x714b1325 (null)(0)
4: SizeofResource16 - 0x698187fc (null)(0)
3: SizeofResource16 - 0x698187fc (null)(0)
2: BaseThreadInitThunk - 0x74f7342b (null)(0)
1: RtlInitializeExceptionChain - 0x776797cf (null)(0)
0: RtlInitializeExceptionChain - 0x776797cf (null)(0)
========================
11: fninit - 0x69517DFC
10: fninit - 0x69517DFC
9: fninit - 0x69517DFC
8: fninit - 0x69517DFC
7: SizeofResource16 - 0x698187FC
6: SizeofResource16 - 0x698187FC
5: WOWGlobalLock16 - 0x714B1325
4: SizeofResource16 - 0x698187FC
3: SizeofResource16 - 0x698187FC
2: BaseThreadInitThunk - 0x74F7342B
1: RtlInitializeExceptionChain - 0x776797CF
0: RtlInitializeExceptionChain - 0x776797CF
Access violation
address=CCCCCCCC
access address=CCCCCCCC
32bit
16bit context
AX:9FA2,CX:0000,DX:0000,BX:A04C
SP:9F56,BP:A01C,SI:0000,DI:0013
ES:17E7,SS:113F,CS:17EF,DS:17EF
IP:038C, address:028A35E4
EFLAGS:00003086

SEGV
```

The map editor, civ2map.exe crashes on selecting the size of the world, outputting the following:
```
=====dump all modules=====
Module Flags Name Flag
 19f7   8309    ICONLIB NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_CO
NSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 19a7   8021    WING    NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIB
MODULE
 1907   8309    ICONLIB NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_CO
NSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 187f   8021    WIN87EM NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIB
MODULE
 1867   8021    TOOLHELP        NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FF
LAGS_LIBMODULE
 184f   8021    COMMDLG NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIB
MODULE
 181f   8309    SMEDSNET        NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_F
FLAGS_CONSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 17c7   8309    MSACM   NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_CO
NSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 176f   8309    AVIFILE NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_CO
NSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 1757   8021    SHELL   NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIB
MODULE
 16d7   8309    MSVIDEO NE_FFLAGS_SINGLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_CO
NSOLE | NE_FFLAGS_GUI | NE_FFLAGS_LIBMODULE
 1167   030a    CIV2MAP NE_FFLAGS_MULTIPLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_
CONSOLE | NE_FFLAGS_GUI
 114f   8021    SOUND   NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIB
MODULE
 1137   8021    MMSYSTEM        NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FF
LAGS_LIBMODULE
 111f   8021    MOUSE   NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIB
MODULE
 1107   8021    KEYBOARD        NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FF
LAGS_LIBMODULE
 10ef   8021    USER    NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIB
MODULE
 10d7   8021    GDI     NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIB
MODULE
 10a7   8021    COMM    NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIB
MODULE
 108f   8021    SYSTEM  NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIB
MODULE
 1007   8021    KERNEL  NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIB
MODULE
=====dump all modules=====
16: fninit - 0x69517dfc (null)(0)
15: fninit - 0x69517dfc (null)(0)
14: RtlGetProcessHeaps - 0x776b3a21 (null)(0)
13: RtlCaptureContext - 0x776a3533 (null)(0)
12: RtlDestroyEnvironment - 0x776a2ff6 (null)(0)
11: KiUserExceptionDispatcher - 0x77650154 (null)(0)
=============================
10: fninit - 0x69517dfc (null)(0)
9: fninit - 0x69517dfc (null)(0)
8: fninit - 0x69517dfc (null)(0)
7: SizeofResource16 - 0x698187fc (null)(0)
6: SizeofResource16 - 0x698187fc (null)(0)
5: WOWGlobalLock16 - 0x714b1325 (null)(0)
4: SizeofResource16 - 0x698187fc (null)(0)
3: SizeofResource16 - 0x698187fc (null)(0)
2: BaseThreadInitThunk - 0x74f7342b (null)(0)
1: RtlInitializeExceptionChain - 0x776797cf (null)(0)
0: RtlInitializeExceptionChain - 0x776797cf (null)(0)
========================
11: fninit - 0x69517DFC
10: fninit - 0x69517DFC
9: fninit - 0x69517DFC
8: fninit - 0x69517DFC
7: SizeofResource16 - 0x698187FC
6: SizeofResource16 - 0x698187FC
5: WOWGlobalLock16 - 0x714B1325
4: SizeofResource16 - 0x698187FC
3: SizeofResource16 - 0x698187FC
2: BaseThreadInitThunk - 0x74F7342B
1: RtlInitializeExceptionChain - 0x776797CF
0: RtlInitializeExceptionChain - 0x776797CF
Access violation
address=771EC54F
access address=695E0170
32bit
16bit context
AX:0000,CX:0000,DX:0000,BX:01B6
SP:831C,BP:8332,SI:0000,DI:00D7
ES:16C7,SS:13E7,CS:16CF,DS:16CF
IP:79D3, address:695E3C20
EFLAGS:00003046

Interrupt 00 #DE (13E7:79CF) flags 3046 err 0000
div     word ptr [esi+0Ch]
```

**Comment by otya128** [comment]
I want a more verbose log, so please do the following steps.

1.  Run cmd.exe
2. ```SET WINEDEBUG=+all,-snoop,-ldt,-fixup,-module,-global,-local,-disasm ```
3. ```*exe-file* 2> *log-file*```
4. Upload log-file

**Comment by angrylion7** [comment]
I created these log files with this build:
https://ci.appveyor.com/project/otya128/winevdm/build/1.0.77/artifacts

One caveat is that these "access violation" windows that pop up have two buttons on them: retry and abort. When I hit retry, new "access violation" windows appear, which is fine. But whenever I click "abort" to stop this windows spawning process, otvdm.exe then crashes (I'm using Windows 7 x64 SP1 if that matters), which is probably not what you intended to happen. In the case of civ2map.exe, after hitting "abort" otvdm.exe consistently crashes in kernelbase.dll with "exception offset" == 0000c54f, and as for civ2.exe, after hitting "abort", according to Windows 7, otvdm.exe crashes in "StackHash_0a9e". Anyway, if I just click "abort", then after this otvdm.exe crash the resulting log files end abruptly and seem to preserve no information about the game's crash. So I generated both of these log files by clicking "retry" once and then clicking "abort", which seems to generate (hopefully?) correctly looking log files.

Also, both Civilization II exe's crash in this manner, whether I use msvideo.dll, avifile.dll and msacm.dll, which the game installs only if they're not already present in the SYSTEM folder (i.e., on real Windows 3.1), or newer versions of these dll's which already exist in fresh installs of Windows 9x and NT5.

[civ2.exe.log.zip](https://github.com/otya128/winevdm/files/2247578/civ2.exe.log.zip)
[civ2map.exe.log.zip](https://github.com/otya128/winevdm/files/2247579/civ2map.exe.log.zip)

**Comment by angrylion7** [comment]
@otya128 Thank you for fixing these two crashes. There are more crashes in civ2.exe. Should I report them here, open a separate issue, or is it too early in the project's life span to bother you with them?

**Comment by neozeed** [comment]
I just tried build 57d4d4e447555d95a7da9b23a89d5b028b508299 and I got this fun error..

i386: Invalid REP/opcode F6 combination

Although that is all that was printed, sadly I wasn't logging everything.  It seems that playing existing scenarios works better than starting a new game...?

Anyways I downloaded the 'rip' + patch from here:

https://www.myabandonware.com/game/sid-meier-s-civilization-ii-453

Anyways once I patched the 'RIP'  I can start the game and once I found the city it deadlocks ... 

[civ2_newcampaign_lock.txt.gz](https://github.com/otya128/winevdm/files/2322643/civ2_newcampaign_lock.txt.gz)

**Comment by neozeed** [comment]
Tried it again, and captured the REP opcode thing

0e4c:trace:msg:WINPROC_CallProc32ATo16 1391: (77E589C0, 000B06BE, SBM_SETSCROLLINFO(00E9), 00000000, 035DD54C)
0e4c:trace:thunk:K32WOWHandle16HWND 129: handle32 0xB06BE->handle16 0x046F
0e4c:trace:thunk:K32WOWHandle32HWND 122: handle16 0x046F->handle32 0xB06BE
0e4c:CallTo16(func=13df:5c14,ds=16c7,046f,00e9,0000,035d,d54c) ss:sp=16c7:9e7c ax=16c7 bx=0000 cx=0000 dx=0000 si=0000 di=0000 bp=9ea6 es=16c7 fs=0053
0e4c:Call USER.129: GETCLASSWORD(046f,ffee) ret=13df:5c31 ds=16c7
0e4c:trace:thunk:K32WOWHandle32HWND 122: handle16 0x046F->handle32 0xB06BE
0e4c:trace:thunk:K32WOWHandle32HWND 122: handle16 0x046F->handle32 0xB06BE
0e4c:Ret  USER.129: GETCLASSWORD() retval=00020014 ret=13df:5c31 ds=16c7
0e4c:Call USER.135: GETWINDOWLONG(046f,0010) ret=13df:5c44 ds=16c7
0e4c:trace:thunk:K32WOWHandle32HWND 122: handle16 0x046F->handle32 0xB06BE
0e4c:Ret  USER.135: GETWINDOWLONG() retval=ffff1010 ret=13df:5c44 ds=16c7
i386: Invalid REP/opcode E5 combination

[Invalid_REPopcode_E5_combination.txt.gz](https://github.com/otya128/winevdm/files/2337355/Invalid_REPopcode_E5_combination.txt.gz)

From CIV2 1.06 27-Mar-96

**Comment by otya128** [comment]
I guess this crash occurred by failing to check the existence of MMSYSTEM.DLL.
For the moment, I think that it can be avoided by making a dummy WINDOWS \ SYSTEM \ MMSYSTEM.DLL.

**Comment by angrylion7** [comment]
OK, adding a dummy MMSYSTEM.DLL helps avoid the crash, but the game cannot be tested properly, because it often accesses its internal help system during gameplay, and on every such access, including a click on Civilopedia >> Civilization Advances in the main menu panel, a window appears, saying "the file "get_info.REC" cannot be opened because the following error has occurred: no such file or directory". After this message, the game sort of freezes, as in many of its functions stop working.

Should I add more dummy DLLs?

**Comment by neozeed** [comment]
Are you using the Wine help program?

Try winhlp32 from Windows 95..  Or NT 3.51/4.0

**Comment by angrylion7** [comment]
@neozeed this error message is shown by PEDIA\get_info.exe in the game folder, even if one simply tries to run that .exe (obviously, it shouldn't appear in either case). What makes you believe this executable uses Windows help? winhlp32.exe or winhelp.exe is not shown among the running processes under Windows XP's WoW, only get_info.exe is there. Are you able to run get_info.exe without this error message in winevdm? Anyway, I tried placing an old winhlp32 in a few places where it made sense without any effect.

**Comment by neozeed** [comment]
@angrylion7 yeah it crashes HARD.

[GET_INFO.TXT.gz](https://github.com/otya128/winevdm/files/2384435/GET_INFO.TXT.gz)

password is winevdm
[pedia.zip](https://github.com/otya128/winevdm/files/2384438/pedia.zip)

**Comment by neozeed** [comment]
Build https://github.com/otya128/winevdm/commit/6e11a24e7953e3619d2e5a0d3471a9fac0a499b1 hangs the Civilopedia with a black window, but it doesn't crash.  and CIV2 crashes hard now.

**Comment by angrylion7** [comment]
Looks like civ2.exe and get_info.exe work fine now, but civ2map.exe cannot show any windows.

**Comment by angrylion7** [comment]
No crashes or softlocks now, judging from my cursory testing.
