### ISSUE TITLE
Civilization for Windows v1.2.0 crashes

### ISSUE THREAD

**Issue by angrylion7** [otya128/winevdm#720]
Using this build
https://ci.appveyor.com/project/otya128/winevdm/builds/33769584/job/pflmvh3m167oh5ss
I get random-ish crashes in Civilization for Windows v1.2.0 that don't happen under Windows XP's WoW. The same happened with a winevdm build of circa 100 commits ago. I use default winevdm settings on Windows 7 x64. Finally I found a guaranteed way to trigger a crash that looks similar to my others crashes:
1. Start a new game and choose any options
2. Once you have gained control, press B on the keyboard and don't release the B key until it crashes (while naming a new city bbb...)

The connection between this fanciful way to trigger the crash and sporadic gameplay crashes that I had is that these regular-gameplay crashes, for all I know, also seemed to revolve around "founding a new city" in-game action. This setup seems to cause a crash 100% in winevdm without tracing, 0% in Windows XP WoW and, sadly, less than 50% in winevdm with tracing. Another setup that I tried, that didn't even involve pressing keyboard keys, also worked rather poor with tracing enabled, btw. Anyway, trace.txt produced with the method described above attached.

[trace.zip](https://github.com/otya128/winevdm/files/4873074/trace.zip)

**Comment by cracyc** [comment]
Can't reproduce in Windows 10 and don't have Windows 7 handy for testing.  The only weirdness I saw was the city name not following the city with the English on Earth but that also happens in ntvdm.

**Comment by angrylion7** [comment]
I'm sorry, all these crashes I had were in fact caused by having mistakenly applied WinXP compatibility mode to otvdm.exe. No idea when or why did I tick that checkbox, but it persists when replacing an existing winevdm installation with files from a newer build. Funny that most Win16 programs ran just fine with this.
