### ISSUE TITLE
Civilization I v1.2.0: garbled duplicated text

### ISSUE THREAD

**Issue by angrylion7** [otya128/winevdm#721]
Using this build
https://ci.appveyor.com/project/otya128/winevdm/builds/33910415/job/5afpfk2j7sotjm3l/artifacts
I have a problem with text in-game that doesn't occur under Windows XP's WoW. I attached a screenshot.
1. Start a new game and build a new city
2. Go to the city screen
3. Click on the icon of the currently produced unit or city improvement just below the Exit button
4. Click HELP, then click OK just once, which should show information including the cost of the unit / improvement, then exit.

This doesn't happen with EnumFontLimitation=1, but with that setting some text elsewhere in the game is incorrectly offset, and the font is not the one intended by developers, I suppose? 

![civ1help](https://user-images.githubusercontent.com/16341594/86543622-0106ab00-bf29-11ea-8ecd-60069f63fa09.png)

**Comment by cracyc** [comment]
It does sort of happen in ntvdm as first the font is larger then after going to help it's smaller.  Winevdm doesn't clear the box before drawing the smaller font for some reason.

**Comment by angrylion7** [comment]
Indeed, it doesn't happen with winevdm on Windows 7 x64 and DWM disabled. Since you say it's unfixable without disabling DWM, I guess I should close this issue.

**Comment by cracyc** [comment]
>Since you say it's unfixable without disabling DWM

Yup, to be clear though it's a bug in the program, not the DWM, as they shouldn't have forced a window repaint there.  Thankfully, like the other DWM problem, https://github.com/otya128/winevdm/issues/176, it's fairly minor.
