### ISSUE TITLE
Microsoft Baseball & Basketball Titles

### ISSUE THREAD

**Issue by anonimuos** [otya128/winevdm#728]
I have been testing various 16-bit Microsoft Home series titles on 64-bit Windows 10 with OTVDM. This is a great project and the devs porting it to Windows have done a great job. Here are some compatibility issues with various titles:

**Microsoft Complete Baseball 94** - This does not install on Windows 10 with OTVDM - Setup hangs. But the program runs with manual installation with file copying. Videos play perfectly in Complete Baseball 94, but you get errors in some sections like when you click "Trivia" causing the app to crash. No such error on NTVDM of 32-bit Windows XP.

You can try this title here as well as the 95 edition: https://legendsworld.net/adventure/game/7790

Here's how to do a manual installation: install it on Windows XP or Windows Me. Copy the files from C: drive and the INI file from C:\Windows to C:\otvdm\Windows. Make sure the CD image is mounted. Then the program runs.

**Microsoft Complete Baseball 95** - This does not install either on Windows 10 with OTVDM - Setup hangs. But the program runs with manual installation with file copying. There are no crashes but videos don't play in Complete Baseball 95 on Windows 10 with OTVDM but play just fine on Windows XP 32-bit NTVDM. All the necessary Indeo 3.2 codecs are installed but videos don't play on Windows 10. In place of videos, I get a blank empty area.

**Microsoft Complete NBA Basketball 94** does not install on Windows 10 with OTVDM but runs with manual installation with file copying. Videos do not play in Complete Basketball 94 on Windows 10 with OTVDM and Indeo 3.2 codec files present but do play on Windows XP 32-bit NTVDM. In place of videos, I get a blank empty area.

You can get the Basketball ISO here: https://legendsworld.net/adventure/game/9358

To make sure it was not a codec issue, I did try other software titles too like Bookshelf or 16-bit versions of Encarta which also use the same Indeo codec and the videos in them played on Windows 10 64-bit with OTVDM.

I am not sure all of these are NTVDM issues but just thought I would report on my findings since on an XP Virtual Machine, the videos do play properly, there are no crashes, even though Baseball **94** videos did play on Windows 10 with OTVDM as well (but not Baseball **95** or Basketball **94**.

**Comment by cracyc** [comment]
The installers hang in the "searching for installed components" part.  This isn't a bug in winevdm as it searches the entire hdd and fails on modern machines with large numbers of directories.

**Comment by anonimuos** [comment]
I know 😀 I already said in my post I could manually install them. 😀 I was raising the issue about videos not playing which play in XP's NTVDM. Is there any fix for that? 😀

**Comment by anonimuos** [comment]
Thank you very much and amazing! Confirmed fixed!

**Comment by anonimuos** [comment]
Forgot to post screenshot of this specific error I get on Baseball 94 when I press the Trivia button:
https://i.imgur.com/RAlR8hu.jpg

**Comment by anonimuos** [comment]
For some reason these apps hang when "Help" button is pressed. However I am able to manually launch Help:
Baseball 94: C:\otvdm\WINDOWS\SYSTEM\MVIEWER2.EXE F:\BAGGAGE\BBHELP.MVB
Baseball 95: C:\otvdm\WINDOWS\SYSTEM\MVIEWER2.EXE F:\BAGGAGE\HELPBS95.MVB
Basketball 94: C:\otvdm\WINDOWS\SYSTEM\MVIEWER2.EXE F:\BAGGAGE\BKTHELP.MVB

**Comment by cracyc** [comment]
Make sure the viewerpath is set properly in baseball.ini or bktball.ini.

**Comment by anonimuos** [comment]
Yes correcting the path fixed that too. All issues with these apps gone.
