### ISSUE TITLE
Microsoft Multimedia Beethoven does not work correctly

### ISSUE THREAD

**Issue by anonimuos** [otya128/winevdm#730]
Edit: See comment below for easily accessible disc image of program and tools required to mount it.

Microsoft Multimedia Beethoven - The Ninth Symphony (available     ̶̶̶f̶̶̶r̶̶̶o̶̶̶m̶̶̶ ̶̶̶B̶̶̶e̶̶̶t̶̶̶a̶̶̶A̶̶̶r̶̶̶c̶̶̶h̶̶̶i̶̶̶v̶̶̶e̶̶̶ ̶̶̶F̶̶̶T̶̶̶P̶̶̶         * ***BELOW*** *  as a Mixed Mode CD image) installs ok but the buttons do not work correctly and certain menus don't render. (The Contents button specifically). ̶N̶o̶t̶e̶ ̶t̶h̶a̶t̶ ̶t̶o̶ ̶m̶o̶u̶n̶t̶ ̶t̶h̶e̶ ̶C̶D̶ ̶i̶m̶a̶g̶e̶ ̶o̶f̶ ̶t̶h̶i̶s̶ ̶t̶i̶t̶l̶e̶,̶ ̶y̶o̶u̶ ̶n̶e̶e̶d̶ ̶a̶n̶ ̶a̶p̶p̶ ̶l̶i̶k̶e̶ ̶D̶a̶e̶m̶o̶n̶ ̶T̶o̶o̶l̶s̶ ̶P̶r̶o̶ ̶8̶.̶3̶ ̶a̶s̶ ̶i̶t̶ ̶i̶s̶ ̶t̶h̶e̶ ̶o̶n̶l̶y̶ ̶a̶p̶p̶ ̶t̶h̶a̶t̶ ̶I̶ ̶k̶n̶o̶w̶ ̶o̶f̶ ̶y̶e̶t̶ ̶t̶h̶a̶t̶ ̶c̶a̶n̶ ̶c̶o̶r̶r̶e̶c̶t̶l̶y̶ ̶m̶o̶u̶n̶t̶ ̶m̶i̶x̶e̶d̶ ̶m̶o̶d̶e̶ ̶C̶D̶s̶ ̶(̶a̶u̶d̶i̶o̶ ̶t̶r̶a̶c̶k̶s̶ ̶a̶n̶d̶ ̶d̶a̶t̶a̶ ̶t̶r̶a̶c̶k̶s̶)̶ ̶i̶n̶ ̶B̶I̶N̶/̶C̶U̶E̶ ̶f̶o̶r̶m̶a̶t̶.̶

The other 4 titles run ok with OTVDM:
- Microsoft Multimedia Stravinsky - The Rite of Spring (this sometimes produces errors but mostly otherwise runs fine).
- Microsoft Multimedia Strauss - Three Tone Poems
- Microsoft Multimedia Schubert - The Trout Quintet
- Microsoft Multimedia Mozart - The Dissonant Quartet

In XP's NTVDM, Beethoven and Stravinsky work correctly so something is not working in OTVDM for this title.

**Comment by anonimuos** [comment]
I converted the BIN/CUE disc image to the CloneCD CCD/IMG/SUB disc format which can also store a Mixed Mode CD image (Audio CD and data tracks). I've uploaded it here. This format can be easily mounted by a _**freeware**_ called Virtual CloneDrive (supports all operating systems from Windows XP 32-bit to Windows 10 64-bit) so there is no need for Daemon Tools. Be sure to mount the CCD file, not the IMG file with Virtual CloneDrive so Explorer sees the data tracks but Windows Media Player sees the audio track.

When the program is installed, the Beethoven EXE sees both tracks. This app's Setup luckily does not hang searching for installed components on 64-bit Windows 10 with OTVDM, but some of the menus/app buttons do not work correctly in OTVDM while they work fine in NTVDM.

I've observed by comparing with NTVDM that the buttons which try to show a menu - Contents, Movement, Chapters, and Glossary buttons do not work and cause the program to hang. It might be a minor issue.

You can compare in XP 32-bit's NTVDM by mounting the disc image first in a 64-bit Windows 10 host OS and then in a virtual machine of XP guest (VirtualBox or VMware) - basically just mount the host OS optical drive with passthrough and the mixed mode CD works in the VM too.

**Comment by cracyc** [comment]
> I've observed by comparing with NTVDM that the buttons which try to show a menu - Contents, Movement, Chapters, and Glossary buttons do not work and cause the program to hang. It might be a minor issue.

I don't get a hang but the menus work in xp/ntvdm but fail (for me) in win7/ntvdm.  The problem is that SetMenu returns failure when a popup menu is set to a window.

```
64fc:Call USER.41: CREATEWINDOW(1bb7002e "TBKDLLPOPMENU",00000000 (null),80000000,030e,02d8,8000,8000,002b,0000,1bb6,00000000) ret=1baf:22a7 ds=1bb7
64fc:CallTo16(func=1baf:2416,ds=15af,0000,0000,1207,1abc,0000,0000,8000,0000,030e,02d8,0000,0000,002b,0000,1bb6,0000,0000,0046,0081,0000,15af,56ae) ss:sp=15af:56d0 ax=1bb7 bx=0006 cx=0000 dx=0000 si=0046 di=0000 bp=56fa es=15af fs=0053
...
64fc:Ret  USER.41: CREATEWINDOW() retval=00000046 ret=1baf:22a7 ds=1bb7
64fc:Call USER.415: CREATEPOPUPMENU() ret=1baf:248d ds=1bb7
64fc:Ret  USER.415: CREATEPOPUPMENU() retval=00000047 ret=1baf:248d ds=1bb7
64fc:Call USER.411: APPENDMENU(0047,0000,0001,15af55fa) ret=1baf:269d ds=1bb7
64fc:Ret  USER.411: APPENDMENU() retval=00000001 ret=1baf:269d ds=1bb7
...
64fc:Call USER.158: SETMENU(0046,0047) ret=1baf:24b4 ds=1bb7
64fc:Ret  USER.158: SETMENU() retval=00000000 ret=1baf:24b4 ds=1bb7
```

There might be no way to fix it.

**Comment by anonimuos** [comment]
Since this title uses a program called [ToolBook](https://en.wikipedia.org/wiki/ToolBook) (https://winworldpc.com/product/toolbook/30), I am trying to see if I can obtain a 32-bit version which upgrades the TBK file to a version compatible with 32-bit OS.

**Comment by cracyc** [comment]
The setmenu appears to only be used to make sure the menu is destroyed with the window so just ignoring the failure seems to be fine as long as winevdm can handle the clean up.

**Comment by anonimuos** [comment]
Splendid! FIXED!!!! Thank you very much!
