### ISSUE TITLE
Software Toolworks Star Wars Chess

### ISSUE THREAD

**Issue by anonimuos** [otya128/winevdm#731]
Some functionality in Software Toolworks Star Wars Chess game does not work with OTVDM. In XP's NTVDM, it works perfectly. Install with Install.exe, not SChess.exe.

Here is the ISO so you can fix it (it is abandonware now): https://mega.nz/file/nUE2gKra#l2pzMf7PN6x5dtgNaE2wPxJeT78JO6_X-xcumj3OQvs

The Error message I get is: DeleteObject failed in SmartDelete.

**Comment by cracyc** [comment]
I think this a dup of https://github.com/otya128/winevdm/issues/725 as the same error occurs there.

**Comment by anonimuos** [comment]
OMG thank you thank you thank you!! This awesome game from 1993 now runs on 64-bit Windows! So cool!!
