### ISSUE TITLE
DLL errors in Microsoft Complete Basketball 95

### ISSUE THREAD

**Issue by anonimuos** [otya128/winevdm#735]
In the 16-bit version of Microsoft Complete Basketball 95:  https://mega.nz/file/WcsngYSJ#_Cjn8raaRzpikuMH3iVPJUJ_RdjAjGEiV6cbjRzlyIU which can be installed by running the command:

F:\ASETUP16\ACMSETUP.EXE /T BKT95.stf /O "_" /S F:\

I see mentions of missing DLLs and don't understand where these DLLs need to be placed. In fact while MEDVDLL.DLL exists for this program, some of the DLLs mentioned like NODLL.DLL don't exist anywhere on its CD.

Screenshot:  https://i.imgur.com/OVmgHTB.png

I run the 16-bit version because the 32-bit version doesn't play videos.

**Comment by cracyc** [comment]
This expects the return from getclassinfo to contain the hinstance rather than the module handle.  I changed it to return the hinstance if it's module is the same as the class module.

**Comment by anonimuos** [comment]
Fixed. Awesome! Thank you so much! It's a shame the 32-bit version of Complete Basketball 95 still has broken videos. But the 16-bit version now works perfect thanks to OTVDM. Both have feature parity so I will just happily use the 16-bit version.

**Comment by anonimuos** [comment]
The apps gives an error message when "Help" button is pressed. CANNOT FIND C:\WINDOWS\SYSTEM

But I am able to manually open help:

Basketball 95: C:\otvdm\WINDOWS\SYSTEM\MVIEWER2.EXE F:\BAGGAGE\HELPBK95.MVB
