### ISSUE TITLE
Microsoft Fine Artist 1.1 gives out of memory error but 1.0 is ok

### ISSUE THREAD

**Issue by anonimuos** [otya128/winevdm#737]
Running the latest OTVDM AppVeyor build as of this bug report.

Microsoft Fine Artist 1.1/1.1 b (https://winworldpc.com/product/microsoft-fine-artist/1x) installs fine but gives this error: https://i.imgur.com/M9Z5anU.png

Fine Artist 1.0 works OK.

**Comment by cracyc** [comment]
I'm not sure why but if run from explorer the program loses focus before it's window is created causing the error above.  If run from the command line or otvdmw file selector it works properly.  NTVDM doesn't seem to have this issue so it probably can be fixed I haven't any idea how.

**Comment by anonimuos** [comment]
Oh that's strange. The newer version 1.1b doesn't run for me from command line or otvdmw either.

**Comment by cracyc** [comment]
For me on Windows 10 1.1 behaves the same as 1.0,

**Comment by anonimuos** [comment]
On my Windows 7 PC, Fine Artist 1.1b also runs OK if I set its shortcut to run Maximized
