### ISSUE TITLE
Magic School Bus Explores Solar System fails to run, runs OK in NTVDM

### ISSUE THREAD

**Issue by anonimuos** [otya128/winevdm#752]
Running the latest build as of 26 July 2020. The app The Magic School Bus Explores the Solar System (https://mega.nz/file/3cUhhCxT#h4Moe6UO8UElKNUuh-BkAlfGlV1H2SofQ7T2DVD30d4) installs fine but gives the error as shown in the screenshot:
https://i.imgur.com/prd9Jr1.png

All paths in the INI are correct but it can't find some files for some reason or load them.

On Windows XP 32-bit NTVDM, the app installs and runs OK.

**Comment by cracyc** [comment]
https://github.com/otya128/winevdm/pull/753 makes it work after install so if it's already installed you'd have to run setup again.  Setup has another problem where it tries to use verqueryvalue on wowexec.exe with too small of a buffer so even if a dummy wowexec dll is added it still doesn't work.  IAmNotNT need to be set in otvdm.ini to work around this.

**Comment by anonimuos** [comment]
All fixed 👍

**Comment by anonimuos** [comment]
This fixes a lot of other programs from Microsoft Kids that used a similar style of installer. Thank you again.
