### ISSUE TITLE
Julia Child: Home Cooking doesn't run, Interrupt 0D error

### ISSUE THREAD

**Issue by anonimuos** [otya128/winevdm#756]
Running the latest build of OTVDM as of 28th July, 2020.

The app Julia Child: Home Cooking with Master Chefs (download and mount image from here: https://www.legendsworld.net/site/download.php?mirror=13394) doesn't run correctly and continuously gives "Interrupt 0D" errors.

Here's a screenshot:
https://i.imgur.com/kVCkd9N.png

Here's a trace:
[trace.zip](https://github.com/otya128/winevdm/files/4988180/trace.zip)

The Setup for this app hangs so it has to be manually installed. Microsoft supplies a batch file on its CD to manually install it. From cmd prompt at E:\ where E: is CD drive letter with the Julia Child CD mounted, run this command:

E:\AAMSSTP\MANUAL\PSS.BAT InstallDirectory WindowsDirectory
e.g.
E:\AAMSSTP\MANUAL\PSS.BAT C:\MSJulia C:\otvdm\Windows

Then edit C:\otvdm\Windows\MSJULIA.INI to point to correct install location and CD drive letter.

The program starts but then gives continuous errors as mouse is hovered over the bottom buttons. Trace is attached.

_________________________________________________

P.S. Unrelated but I have updated the issues on other 2 programs also, Beethoven (https://github.com/otya128/winevdm/issues/730) and Frank Lloyd Wright (https://github.com/otya128/winevdm/issues/733) with more info and the CD images, so you can easily test the programs for fixing the errors. Please take a look :)

**Comment by cracyc** [comment]
This problem is caused by https://github.com/otya128/winevdm/commit/8ec3aff00f0e734f938fcae97df4ac848cb20a46 where the usage count is incremented twice.  The program calls FreeResource then GlobalFree even if the free fails.  Without knowing what the change fixes I don't want to mess with it.

**Comment by anonimuos** [comment]
OK. The same Interrupt 0D error occurs in the Windows Entertainment Pack, game, Klotski.

**Comment by cracyc** [comment]
GP faults can happen for a very wide variety of reasons and most of those have been fixed already.

**Comment by anonimuos** [comment]
I see. So the cause is different for each General Protection fault. I didn't know that. Thank you.

**Comment by otya128** [comment]
>This problem is caused by 8ec3aff where the usage count is incremented twice. The program calls FreeResource then GlobalFree even if the free fails. Without knowing what the change fixes I don't want to mess with it.
This is a commit that fixed a setup program crashing, but it worked after reverting.

**Comment by anonimuos** [comment]
Even after this revert/commit, the error is the same: https://i.imgur.com/kW9vZEL.png

**Comment by anonimuos** [comment]
Yes it's fixed. With today's fix, the following first-party/Microsoft apps work. Some are pure 16-bit or hybrid 32-bit & 16-bit titles, or where installer components are 16-bit and as of the latest build, all of these work mostly fine. Some old 16-bit MS Office apps also work though not all (not in this list). Excuse me if some apps are pure 32-bit in the list in which case OTVDM does not play any role.

![image](https://user-images.githubusercontent.com/46422834/89131392-140d9a80-d52a-11ea-8a06-a696c6b68fe8.png)

Thank you very much. Now I will test more complex 16-bit games.
