### ISSUE TITLE
Automap Streets 4.0 (1995) gives interrupt 0D errors at startup

### ISSUE THREAD

**Issue by anonimuos** [otya128/winevdm#760]
I downloaded latest AppVeyor build of OTVDM just now. Automap Streets 4.0 ( https://mega.nz/file/7JdjmYgJ#JSiWd8aziLRC1ujxH8RPQeAksAf9ls_ZXf8KPkUrnQ8 ) does not run at all and gives interrupt 0D errors. It installs and runs ok in XP NTVDM. Setup may hang on Windows 10 but can be manually installed as per %cddrive%:\MSSETUP\MANUAL\PSS.bat or by installing in XP VM and copying files over.

This is the error I get:
https://i.imgur.com/gMMSr60.png

**Comment by anonimuos** [comment]
Nope no luck yet after this change. Getting the same error.

**Comment by cracyc** [comment]
Works for me.  I'd have to see a trace.

**Comment by anonimuos** [comment]
Also https://github.com/otya128/winevdm/issues/756 got unfixed after this change.

**Comment by cracyc** [comment]
They are separate pull requests.  Until they both get pulled you can only use one or the other at a time.

**Comment by anonimuos** [comment]
I see. My bad. Here is the trace:
[trace.zip](https://github.com/otya128/winevdm/files/5016577/trace.zip)

**Comment by cracyc** [comment]
Looks like you're using IAmNoNT=1 in your otvdm.ini.  IMO it's not a good idea unless something requires it to work.  Anyway, I added a fix for that case too.

**Comment by anonimuos** [comment]
Fixed! Thank you! I hope you checked the list that I posted of programs that are compatible with OTVDM now: https://github.com/otya128/winevdm/issues/756#issuecomment-667722718 You guys are doing GREAT WORK.
