### ISSUE TITLE
Bicycle Baccarat (16-bit game) causes Interrupt 0D errors

### ISSUE THREAD

**Issue by anonimuos** [otya128/winevdm#766]
A 16-bit game called Bicycle Baccarat (BACC.EXE) from this old title, Bicycle Casino (https://wowroms.com/en/roms/windows-3.x/bicycle-casino-blackjack-poker-baccarat-roulette/152992.html) shows Interrupt 0D error when e.g. the game is started and you press the buttons in the game at the bottom, after it starts - ↑, 2, 3 , 4, ↑    $,  ✔,  ❌.  Also it crashes sometimes upon File menu -> Exit. Here are 2 traces for those crashes:

[BaccaratTrace.zip](https://github.com/otya128/winevdm/files/5037608/BaccaratTrace.zip)
[BaccTrace.zip](https://github.com/otya128/winevdm/files/5038194/BaccTrace.zip)

Actually the same crash also happens for Bicycle Blackjack (BJ.EXE) from that suite of games.

**Comment by cracyc** [comment]
This happens for me if you press one of the buttons at the bottom before the cards are dealt.  The error also happens in ntvdm and win31 so it's a bug in the program.

**Comment by anonimuos** [comment]
Oh indeed. I see! Thank you
