### ISSUE TITLE
Old app Willow Pond Audio's full WAVE & MIDI functionality not working

### ISSUE THREAD

**Issue by anonimuos** [otya128/winevdm#768]
Is OTVDM supposed to have MIDI support and microphone or input support? There is this old app that I used to use in the Windows 95 days called Willow Pond Audio: https://mega.nz/file/7dMTVQqZ#OE_N2XTYBeJ40nKpqwDiklz8loULOc_GVae5WZVsJTI

It is a suite of 5 audio apps: Presto Arranger, Media Rack, Wave Shaper, WinChime and the launcher.

It installs fine but does not work properly. The Presto Arranger (the MIDI app) seems to be OK.

The CD Player, MIDI Player, Talking clock and Wave player which are part of the "Media Rack" app all work but the main mediarck.exe itself does not work.

The Wave Shaper opens but I could not get it to play wave files. The WinChime works erratically - if I hold down the mouse click, it plays the full sound, if I click and let go, the sound is cut off.

The launcher gives an error - unable to open mixer device.

**Comment by cracyc** [comment]
The winchime is flaky in ntvdm also.  This launcher error is fixed but if you use a digital audio output (spdif and likely hdmi) it'll display a different error, it's a bug in the program.  The midi player hangs for a bit when starting a music file, this is a windows bug (https://github.com/otya128/winevdm/issues/704#issuecomment-647133758).  Audio input should work but isn't well tested.

**Comment by anonimuos** [comment]
I see. WinChime is flaky even in Windows 95 VM! I remember it was ok on real hardware with real drivers (but that was VxD Windows 95 drivers or DOS drivers loaded via Autoexec.bat - I don't remember which). Anyway thanks a ton, the app of concern, Presto Arranger works great. My dad recorded a lot of MIDI songs with its keyboard. He will be delighted to see it working again.

**Comment by anonimuos** [comment]
Wave Shaper works.
