### ISSUE TITLE
Error when use release 0.7 (SEGV Error)

### ISSUE THREAD

**Issue by josemora1** [otya128/winevdm#782]
Hi. Im using the last release (0.7) and Tried to install 16 bit software but the following error appeared: 
Window Title: SEGV
access address: FFFFFFFF
Vm context
EAX: 1207AD24, ECX: 0000, EDX: 12571257, EBX: OCA03
ESP: ACEC, EBP: BC46, ESI: 0000, EDI: 0001,
EFLAGS: 00003207.

Thank You in advance.

**Comment by cracyc** [comment]
Try using the latest build from https://ci.appveyor.com/project/otya128/winevdm/builds/34806589/job/n02ya3ap2l27akjv/artifacts and if that doesn't work more info like what you are trying to run is needed.

**Comment by josemora1** [comment]
Thank You, Now it Works! Thanks for the great work you have done with this application..
