### ISSUE TITLE
Microsoft World of Flight gives errors

### ISSUE THREAD

**Issue by anonimuos** [otya128/winevdm#783]
Running the latest AppVeyor build.

Microsoft World of Flight - 1995 title (get the ISO here: https://archive.org/details/world-of-flight) gives errors sometimes when clicking the Options -> Random Jumps button.

It can be run with this command (F is CD/ISO drive letter):
F:\DATA\00SETUP\APP\FLYEXP16.EXE Flight16.DLL /w F:\DATA\00SETUP\APP\FLYWAV16.DLL MSFLIGHT.THE

32-bit version can run with:
F:\DATA\00SETUP\APP\FLYEXP32.EXE Flight32.DLL /w F:\DATA\00SETUP\APP\FLYWAV32.DLL MSFLIGHT.THE

**Comment by cracyc** [comment]
I can't reproduce this.  What kind of errors?  A trace might help.

**Comment by anonimuos** [comment]
Here's a trace file attached:
[WOFTrace.zip](https://github.com/otya128/winevdm/files/5259834/WOFTrace.zip)

**Comment by cracyc** [comment]
I don't see the error in the trace.  What error message is it showing.

**Comment by anonimuos** [comment]
![image](https://user-images.githubusercontent.com/46422834/93972894-de9a6600-fd90-11ea-8727-92b018a46160.png)

**Comment by cracyc** [comment]
The version of OTOON16.DLL that comes with oceans is not compatible with flight.  You need to replace it in your winevdm windows/system directory.

**Comment by anonimuos** [comment]
Ohh!! It must be the version from Oceans. Thank you for your time on this.
