### ISSUE TITLE
whpxvm.dll doesn't work (Hypervisor error: vm86main:1110 exception)

### ISSUE THREAD

**Issue by anonimuos** [otya128/winevdm#785]
Running the latest AppVeyor build and have downloaded the package from https://github.com/otya128/winevdm/issues/699#issuecomment-646020250

Hyper-V Platform is installed and enabled in Windows Features. Running Windows 10 Enterprise version 1803. Hyper-V itself runs VMs just fine.

Trace attached if it helps:
[whpxvmtrace.txt](https://github.com/otya128/winevdm/files/5286272/whpxvmtrace.txt)

What to do?

**Comment by cracyc** [comment]
This pr adds some extra debug info for exceptions.  https://ci.appveyor.com/project/otya128/winevdm/builds/35420972/job/512hq7275n9o2n9u/artifacts

**Comment by anonimuos** [comment]
Nothing happens with this build when I normally run the EXE. No error. No program runs. Here's the trace.

[whpxvm-trace-debug.txt](https://github.com/otya128/winevdm/files/5287165/whpxvm-trace-debug.txt)

**Comment by cracyc** [comment]
try this new one https://ci.appveyor.com/project/otya128/winevdm/builds/35422864/job/toq93k6lma6m0546/artifacts

**Comment by anonimuos** [comment]
Now get:
![image](https://user-images.githubusercontent.com/46422834/94349975-4e497300-0067-11eb-85af-59a8f9efd2bb.png)

[whpxvm-trace-debug2.txt](https://github.com/otya128/winevdm/files/5287312/whpxvm-trace-debug2.txt)

**Comment by cracyc** [comment]
It's calling wine_call_to_16_regs inside the vm even though that's supposed to be unmapped.   I don't know why that's happening, my only quick guess is that 1803 is older than whpxvm was tested with since it was added in 2020.

**Comment by anonimuos** [comment]
Well I have Windows 10 Enterprise 2004 and 20H2 also on the same machine for testing purposes (they have some breaking compatibility issues which is why I am still on 1803 Enterprise which is still under MS support).

There are no issues with WHPXVM and OTVDM in 2004 and 20H2. Everything works with excellent like-native performance. Even the apps where I faced issues with Intel HAXM - Star Wars Chess, Microsoft Ultimate Frank Lloyd Wright, Microsoft Gahan Wilson's: The Ultimate Haunted House all run with no errors, no issues and like-native performance. It does not even feel like emulation.

WHPVXM is definitely a more issue-free VM accelerator for me to use than HAXM.

**Comment by otya128** [comment]
I have confirmed that it works on Windows 10 1803.

**Comment by anonimuos** [comment]
Indeed fixed. Thank you to otya128 and crazyc, it now works on 1803.
