### ISSUE TITLE
Microsoft Multimedia Audio CD titles don't work WHPXVM

### ISSUE THREAD

**Issue by anonimuos** [otya128/winevdm#789]
Running the latest build (dev1852) of OTVDM/wineVDM which fixes compatibility with WHPXVM on 1803.

If vm=whpxvm.dll is on, the titles which use Mixed Mode CDs (Audio CD+data) - Microsoft Multimedia Beethoven, Mozart, Schubert, Strauss, Stravinsky do not run. There is no error shown. They just silently fail. When vm=whpxvm.dll is off, they run fine.

Once Stravinsky produced this error:

---------------------------
Microsoft Multimedia Stravinsky
---------------------------
Unexpected error  6 : Overflow
---------------------------
OK   
---------------------------

You can download any of the 5 titles here:
https://1drv.ms/u/s!AuZ9cnz1PMy-fGXFsTU33c7l6ig?e=2u7wJx

You can mount them with the freeware Virtual CloneDrive which can properly mount these disc images with Explorer seeing the data track and Windows Media Player seeing the audio track.

Update: Exact same titles have problem with vm=gvm.dll (I installed the GVM driver and it runs other apps mostly ok).

**Comment by cracyc** [comment]
Beethoven works now too in whpx (at least without the cd which is a pain to mount).

**Comment by anonimuos** [comment]
All 5 titles working now, thanks to implementing x87 functions. Thank you.
