### ISSUE TITLE
WHPXVM and Microsoft Entertainment Pack games

### ISSUE THREAD

**Issue by anonimuos** [otya128/winevdm#790]
Running the latest build (dev1852) of OTVDM/wineVDM which fixes compatibility with WHPXVM on 1803.

If vm=whpxvm.dll is on, some games give errors and don't run. These include:
- Jigsawed
- RattlerRace
- Rodent's Revenge
- Tic Tac Drop

The error is:

---------------------------
Hypervisor error
---------------------------
vm86main:1134
exception #DE
---------------------------
OK   
---------------------------
This is the link for the Entertainment Pack games:
https://1drv.ms/u/s!AuZ9cnz1PMy-gQxQI5eA-XDINI3W?e=oqiZmB

Let me know if I need to upload a trace.

Update: Exact same games have problem with vm=gvm.dll (I installed the GVM driver and it runs other apps mostly ok).

**Comment by cracyc** [comment]
This is fixed by https://github.com/otya128/winevdm/commit/749cc569230dca353e805cddb7ff8a3fcb5eeffd for whpx.  The x87 support needs to be done for gvm for that.

**Comment by anonimuos** [comment]
Fixed. Thank you very much.

**Comment by anonimuos** [comment]
Fixed.

**Comment by anonimuos** [comment]
Forgot to add that compatibility of maximum number of Win16 apps has never been better in wineVDM/otvdm than this build. With and without WHPVXM, everything just works but with WHPXVM, it especially runs works faassst.
