### ISSUE TITLE
WinGroove 16-bit software MIDI synth gives errors both with and without WHPXVM

### ISSUE THREAD

**Issue by anonimuos** [otya128/winevdm#792]
There is this old 16-bit app which is a software MIDI synth and player, called WinGroove: https://mega.nz/file/bcdHxAha#-wmr2IpOAbFR12m-ANKSxEaEuuAmFMydi8bVrfS8M4s While it installs ok and even plays MIDI files, it gives errors when the Player is quit. Also, does not run at all with WHPXVM enabled.

**Comment by cracyc** [comment]
The exit crash is caused by timecb3216 calling the callback with ds set to a leftover value from a task that exited.  I'm not sure the right way to fix it since vm_inject doesn't take any register values.  Ntvdm appears to set ds to the hintance of the task that sets the timer.

**Comment by anonimuos** [comment]
Fixed. The "Create WAVE file" functionality is very slow with WHPXVM but very fast with software only emulation and no VM.
