### ISSUE TITLE
How to download from appveyor site?

### ISSUE THREAD

**Issue by kristibektashi** [otya128/winevdm#796]
Not really an issue but more of a question. There is no download button on the site and I have tried every button but it doesn't work. Do I have to use a command-line utility suck as git clone? Please help me

**Comment by piratesephiroth** [comment]
Click on the Job name then select the Artifacts tab.

**Comment by anonimuos** [comment]
Bookmark this URL: https://ci.appveyor.com/project/otya128/winevdm/history

Click latest build e.g. currently dev1859. Then click Environment: THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1. Then click Artifacts. Then click otvdm-master-1859.zip to download the ZIP. It won't have an installer. You will have to extract it to where OTVDM is installed earlier.

If you want an installer that initially sets up everything automatically, go here: http://www.columbia.edu/~em36/otvdm.html and download the Inno Setup installer. Currently that was last updated in August 2020. After it installs, you can download the latest build ZIP to get changes from last 2-3 months and overwrite the files.

Be careful about overwriting your otvdm.ini. If you have changed or customized settings, don't overwrite it.

**Comment by emendelson** [comment]
@anonimuos Actually I updated the installer earlier this month but forgot to update the web page. I updated the installer again today, and this time I remembered to update the web page.

**Comment by hmaecke** [comment]
I did as anonimuos suggested, but I can't find any link to a ZIP file at all. Maybe I'm kinda blind...?

**Comment by piratesephiroth** [comment]
> 
> 
> I did as anonimuos suggested, but I can't find any link to a ZIP file at all. Maybe I'm kinda blind...?

come on man... are you even trying?
https://filebin.net/niw9uuis8mqvwnsp/dl.mp4?t=iz6dpa71

**Comment by otya128** [comment]
If you are using an ancient browser such as Internet Explorer, use a modern browser such as Edge, Firefox or Chrome.

**Comment by hmaecke** [comment]
Sorry, my fault - I simply didn't find the Artifacts tab. So I really have been sorta blind.

However it did not solve my initial problem... :-(

**Comment by anonimuos** [comment]
> @anonimuos Actually I updated the installer earlier this month but forgot to update the web page. I updated the installer again today, and this time I remembered to update the web page.

Thanks a lot for updating the installer, but are you sure you updated the page? :) The installer's digital signature says October 25, 2020 but the page still says "Note: Installer last updated 14 August 2020" for me.
