### ISSUE TITLE
Workplace Shell 1.51 for Windows setup fails with disk error

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#797]
https://winworldpc.com/download/47c3ba33-c2b3-18c3-9a11-c3a4e284a2ef

**Comment by Anixx** [comment]
https://i.ibb.co/nnPwTJK/image.png

**Comment by cracyc** [comment]
The install.txt,license.txt and readme.1st files are corrupt because they are saved with unix line endings.  Changing them to dos (crlf) endings and removing one line makes it install properly.  Running it gets the same error as https://github.com/otya128/winevdm/issues/798.
