### ISSUE TITLE
Worplace Shell 1.40 does not startl: wpshell.ini is missing

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#798]
https://winworldpc.com/download/40e280a0-c3a3-e280-a646-c2b211c3a6ef

The wpshell.ini file is missing after installation.

**Comment by cracyc** [comment]
With https://github.com/otya128/winevdm/pull/804 pmtowp.exe can be used to create wpshell.ini then the program runs.  It doesn't appear to work quite right though.  Related bug 797 isn't a winevdm bug but this problem affects that version too.
