### ISSUE TITLE
Where to download the latest unstable version?

### ISSUE THREAD

**Issue by hmaecke** [otya128/winevdm#799]
Hi,

I'd like to download an unstable version, but can't see a download link at https://ci.appveyor.com/project/otya128/winevdm.

So, how / where can I download an unstable version (zip file)?

Reason why is that I encounter problems starting certain apps under Windows 2019 which worked at least with Windows 2012 R2: They simply don't start, but neither give any error message.

Thanks,
Hartmut

**Comment by piratesephiroth** [comment]
see #796
