### ISSUE TITLE
Seems to be some problem with CreateIconFromResourceEx16

### ISSUE THREAD

**Issue by neozeed** [otya128/winevdm#8]
I had this crash on SimCity and Castle of the Winds 1....

>=====dump all modules=====
Module Flags Name Flag
 12c7   8021    COMMDLG NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 1167   0302    CASTLE  NE_FFLAGS_MULTIPLEDATA | NE_FFLAGS_FRAMEBUF | NE_FFLAGS_CONSOLE | NE_FFLAGS_GUI
 114f   8021    SOUND   NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 1137   8021    MMSYSTEM        NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 111f   8021    MOUSE   NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 1107   8021    KEYBOARD        NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 10ef   8021    USER    NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 10d7   8021    GDI     NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 10a7   8021    COMM    NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 108f   8021    SYSTEM  NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
 1007   8021    KERNEL  NE_FFLAGS_SINGLEDATA | NE_FFLAGS_BUILTIN | NE_FFLAGS_LIBMODULE
=====dump all modules=====
54: frstor - 0x50452160 (null)(0)
53: RtlUnwind - 0x777f2820 (null)(0)
52: KiUserExceptionDispatcher - 0x777fc690 (null)(0)
=============================
51: dasm_buffer_dump - 0x50457ea0 (null)(0)
50: dasm_buffer_dump - 0x50457ea0 (null)(0)
49: wine_call_to_16_regs_vm86 - 0x50457d10 (null)(0)
48: K32WOWCallback16Ex - 0xf419af0 (null)(0)
47: K32WOWCallback16Ex - 0xf419af0 (null)(0)
46: K32WOWCallback16Ex - 0xf419af0 (null)(0)
45: CreateIconFromResourceEx16 - 0xff846e0 (null)(0)
44: AddClipboardFormatListener - 0x73e9b9d0 (null)(0)
43: DispatchMessageW - 0x73e979c0 (null)(0)
42: DispatchMessageW - 0x73e979c0 (null)(0)
41: SystemParametersInfoW - 0x73e9a180 (null)(0)
40: KiUserCallbackDispatcher - 0x777fc620 (null)(0)
39: CopyRect - 0x73e87e10 (null)(0)
38: DefMDIChildProcA - 0x73e814d0 (null)(0)
37: DefMDIChildProcA - 0x73e814d0 (null)(0)
36: DefMDIChildProcA - 0x73e814d0 (null)(0)
35: DefMDIChildProcA - 0x73e814d0 (null)(0)
34: MapHModuleSL - 0xf403600 (null)(0)
33: vm_debug_get_entry_point - 0xf4062b0 (null)(0)
32: dasm_buffer_dump - 0x50457ea0 (null)(0)
31: wine_call_to_16_regs_vm86 - 0x50457d10 (null)(0)
30: K32WOWCallback16Ex - 0xf419af0 (null)(0)
29: K32WOWCallback16Ex - 0xf419af0 (null)(0)
28: K32WOWCallback16Ex - 0xf419af0 (null)(0)
27: CreateIconFromResourceEx16 - 0xff846e0 (null)(0)
26: AddClipboardFormatListener - 0x73e9b9d0 (null)(0)
25: DispatchMessageW - 0x73e979c0 (null)(0)
24: DispatchMessageW - 0x73e979c0 (null)(0)
23: GetScrollInfo - 0x73e78e40 (null)(0)
22: DialogBoxIndirectParamAorW - 0x73e749f0 (null)(0)
21: DialogBoxIndirectParamAorW - 0x73e749f0 (null)(0)
20: DialogBoxIndirectParamA - 0x73ebb1a0 (null)(0)
19: DialogBoxIndirectParamA - 0x73ebb1a0 (null)(0)
18: DialogBoxIndirectParamA - 0x73ebb1a0 (null)(0)
17: MapHModuleSL - 0xf403600 (null)(0)
16: vm_debug_get_entry_point - 0xf4062b0 (null)(0)
15: dasm_buffer_dump - 0x50457ea0 (null)(0)
14: wine_call_to_16_regs_vm86 - 0x50457d10 (null)(0)
13: K32WOWCallback16Ex - 0xf419af0 (null)(0)
12: K32WOWCallback16Ex - 0xf419af0 (null)(0)
11: K32WOWCallback16Ex - 0xf419af0 (null)(0)
10: K32WOWCallback16Ex - 0xf419af0 (null)(0)
9: MapHModuleSL - 0xf403600 (null)(0)
8: vm_debug_get_entry_point - 0xf4062b0 (null)(0)
7: dasm_buffer_dump - 0x50457ea0 (null)(0)
6: wine_call_to_16_regs_vm86 - 0x50457d10 (null)(0)
5: K32WOWCallback16Ex - 0xf419af0 (null)(0)
4: LoadModule16 - 0xf4017c0 (null)(0)
3: RestoreThunkLock - 0xf40ccb0 (null)(0)
2: BaseThreadInitThunk - 0x74048460 (null)(0)
1: RtlValidSecurityDescriptor - 0x777f2ed0 (null)(0)
0: RtlValidSecurityDescriptor - 0x777f2ed0 (null)(0)
========================
52: dasm_buffer_dump - 0x50457EA0
51: dasm_buffer_dump - 0x50457EA0
50: dasm_buffer_dump - 0x50457EA0
49: wine_call_to_16_regs_vm86 - 0x50457D10
48: K32WOWCallback16Ex - 0x0F419AF0
47: K32WOWCallback16Ex - 0x0F419AF0
46: K32WOWCallback16Ex - 0x0F419AF0
45: CreateIconFromResourceEx16 - 0x0FF846E0
44: AddClipboardFormatListener - 0x73E9B9D0
43: DispatchMessageW - 0x73E979C0
42: DispatchMessageW - 0x73E979C0
41: SystemParametersInfoW - 0x73E9A180
40: KiUserCallbackDispatcher - 0x777FC620
39: CopyRect - 0x73E87E10
38: DefMDIChildProcA - 0x73E814D0
37: DefMDIChildProcA - 0x73E814D0
36: DefMDIChildProcA - 0x73E814D0
35: DefMDIChildProcA - 0x73E814D0
34: MapHModuleSL - 0x0F403600
33: vm_debug_get_entry_point - 0x0F4062B0
32: dasm_buffer_dump - 0x50457EA0
31: wine_call_to_16_regs_vm86 - 0x50457D10
30: K32WOWCallback16Ex - 0x0F419AF0
29: K32WOWCallback16Ex - 0x0F419AF0
28: K32WOWCallback16Ex - 0x0F419AF0
27: CreateIconFromResourceEx16 - 0x0FF846E0
26: AddClipboardFormatListener - 0x73E9B9D0
25: DispatchMessageW - 0x73E979C0
24: DispatchMessageW - 0x73E979C0
23: GetScrollInfo - 0x73E78E40
22: DialogBoxIndirectParamAorW - 0x73E749F0
21: DialogBoxIndirectParamAorW - 0x73E749F0
20: DialogBoxIndirectParamA - 0x73EBB1A0
19: DialogBoxIndirectParamA - 0x73EBB1A0
18: DialogBoxIndirectParamA - 0x73EBB1A0
17: MapHModuleSL - 0x0F403600
16: vm_debug_get_entry_point - 0x0F4062B0
15: dasm_buffer_dump - 0x50457EA0
14: wine_call_to_16_regs_vm86 - 0x50457D10
13: K32WOWCallback16Ex - 0x0F419AF0
12: K32WOWCallback16Ex - 0x0F419AF0
11: K32WOWCallback16Ex - 0x0F419AF0
10: K32WOWCallback16Ex - 0x0F419AF0
9: MapHModuleSL - 0x0F403600
8: vm_debug_get_entry_point - 0x0F4062B0
7: dasm_buffer_dump - 0x50457EA0
6: wine_call_to_16_regs_vm86 - 0x50457D10
5: K32WOWCallback16Ex - 0x0F419AF0
4: LoadModule16 - 0x0F4017C0
3: RestoreThunkLock - 0x0F40CCB0
2: BaseThreadInitThunk - 0x74048460
1: RtlValidSecurityDescriptor - 0x777F2ED0
0: RtlValidSecurityDescriptor - 0x777F2ED0
Access violation
address=758DDDC2
access address=5045D57C
32bit
16bit context
AX:12BF,CX:0000,DX:0000,BX:0000
SP:6C92,BP:6CCA,SI:0000,DI:0000
ES:12BF,SS:73EB,CS:12BF,DS:12BF
IP:1139, address:5046CC2D
EFLAGS:00003006

Interrupt 0D #GP (73EB:1139) flags 3006 err 73E8

I had downloaded it from here:

[https://archive.org/details/win3_CasWin1](https://archive.org/details/win3_CasWin1)

**Comment by otya128** [comment]
I want a more verbose log, so please do the following steps.

1.  Run cmd.exe
2. ```SET WINEDEBUG=+all,-snoop,-ldt,-fixup,-module,-global,-local,-disasm,-syslevel```
3. ```*exe-file* 2> *log-file*```
4. Upload log-file

**Comment by neozeed** [comment]
Okay, here goes!
[CASTLE1.log.gz](https://github.com/otya128/winevdm/files/2245140/CASTLE1.log.gz)

**Comment by neozeed** [comment]
I just tried the build from 34 minutes ago and it "seems" okay.

![castle of the winds](https://user-images.githubusercontent.com/9031439/43463070-4de08f36-950a-11e8-8ff9-21762b331f26.png)

Of course I've never played this thing before so ...

**Comment by neozeed** [comment]
I think this is back...

Could not create status bar toolbox: Could not create bitmap button

[SimCity_v1.0_3095a6b.txt.gz](https://github.com/otya128/winevdm/files/2290347/SimCity_v1.0_3095a6b.txt.gz)

And just like last time the password is winevdm
[SIMCITYW_v1.0.zip](https://github.com/otya128/winevdm/files/2290360/SIMCITYW_v1.0.zip)

**Comment by neozeed** [comment]
SCW 1.0 works in 4ed45fa4f707bc473e25add7682fb483a43a1036 Fix MMIO_ALLOCBUF

broken in 43686a1a195e0e5c3a04d34ac8d8567019783a02 Add WM_MOUSEWHEEL support(forcibly)
broken in a54ef032ae103301f013fe11e35add66f90aa719 Remove

**Comment by neozeed** [comment]
I just took the latest source, and manually reverted a54ef032ae103301f013fe11e35add66f90aa719 and Sim City works again

**Comment by otya128** [comment]
I think that I fixed this issue.

**Comment by neozeed** [comment]
@otya128 yes, that works for Sim City v1.0 now!  I'll try to put together a bunch of protected mode Win16 stuff to test through!

Thanks again for your awesome work!!!

**Comment by neozeed** [comment]
I just noticed that the toolbar doesn't render at all... 

![simcity for windows 1 0 using winevdm_2018_08_16](https://user-images.githubusercontent.com/9031439/44184878-b8cb1d80-a143-11e8-9379-5cd32b2e06df.png)
I had this build from around 8/16 that doesn't render

![simcity for windows 1 0 using winevdm_2018_07_30b](https://user-images.githubusercontent.com/9031439/44184888-c54f7600-a143-11e8-8a49-5ff7fb4f72ba.png)
And this one from 07/30 that does... I'll have to jump through some regressions to look

**Comment by otya128** [comment]
I fixed the mistake of converting menus, so it should have been fixed.

**Comment by neozeed** [comment]
@otya128 yep that fixed it!

**Comment by neozeed** [comment]
@parrotgeek1 I was pretty sure that @otya128 had kept it open for a reason.

**Comment by neozeed** [comment]
testing build 28dd1385a0cfdb6b9e6a5838c1c038e8c5435e4b that SimCity still works.

![simcity under build 28dd1385a0cfdb6b9e6a5838c1c038e8c5435e4b](https://user-images.githubusercontent.com/9031439/45565843-7e11ed80-b887-11e8-9f5f-1c5bd3d7615e.JPG)

I don't know if it's worth mentioning, but the file open dialog never populates.....
![load a city shows nothing](https://user-images.githubusercontent.com/9031439/45565852-8e29cd00-b887-11e8-8ca8-d05f2bdb16b9.JPG)

But at least you can type in the name of a city (winevdm.cty), and it'll load without error at this point.

password is winevdm
[swimcityw.zip](https://github.com/otya128/winevdm/files/2384310/swimcityw.zip)

**Comment by neozeed** [comment]
I think we can close this?  Granted the "Load a City Name" doesn't populate... but overall it's working!
