### ISSUE TITLE
Burn: Cycle freezes after launching game

### ISSUE THREAD

**Issue by MrPepka** [otya128/winevdm#801]
I can't run Burn: Cycle under WineVDM (the game is 16-bit written on Windows). As I do this, the game shows a white window and freezes. Interestingly, WineVDM doesn't seem to recognize games at all (or at least that's what the trace.txt file says). I am using the latest version of WineVDM (build 1860). Can this game be repaired?
<img width="1920" alt="2020-11-01" src="https://user-images.githubusercontent.com/38865931/97805188-da494e80-1c54-11eb-96ae-911c9ba94653.png">
[trace.txt](https://github.com/otya128/winevdm/files/5471000/trace.txt)

**Comment by cracyc** [comment]
It's not playable and colors are messed up but those problems might be fixable.
![burncycle](https://user-images.githubusercontent.com/9255333/97815792-3b255680-1c56-11eb-9adb-ad3a1d8f4eef.png)

**Comment by MrPepka** [comment]
If I could know, how do I run this game under WineVDM?

**Comment by cracyc** [comment]
To run it requires a change I haven't submitted yet.
