### ISSUE TITLE
Disney's Animated Storybook: Toy Story - QuickTime error

### ISSUE THREAD

**Issue by MrPepka** [otya128/winevdm#803]
When I run this game via WineVDM I get this message
<img width="1920" alt="2020-11-05" src="https://user-images.githubusercontent.com/38865931/98304778-eb7dbc80-1fc0-11eb-92d4-70043c29899f.png">
What should I do? All QuickTime files this game requires are located in the WINDOWS\SYSTEM folder in the game installation folder. When I click OK, I have an Interrupt 0D message, and after clicking Continue, the game crashes

**Comment by cracyc** [comment]
Quicktime may not have installed properly due to https://github.com/otya128/winevdm/pull/820.  Try again with https://ci.appveyor.com/project/otya128/winevdm/builds/36393378/job/m608hrqoxi6r1e4c/artifacts.

**Comment by MrPepka** [comment]
Unfortunately, the new version did not help. So should I reinstall the game, QuickTime or just wait for one more patch?

**Comment by cracyc** [comment]
Run qtinstal.exe in the cdrom other dir.

**Comment by MrPepka** [comment]
Now the game started up, played the intro, then crashed. I don't have the strength to play this game anymore
