### ISSUE TITLE
People still use and test version 0.7, not the latest version

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#813]
https://return2.net/run-16-bit-amipro-3-on-64-bit-windows-10/

**Comment by 0x6A7232** [comment]
Release a new version?  Call it 0.7.1 if you want.   Bump it up by .1 for every release you think people should use.

**Comment by coldacid** [comment]
Yes, please. I maintain the [Chocolatey package](https://community.chocolatey.org/packages/winevdm "winevdm") for this, and without new tags and related builds on this repository, the automated package builder doesn't create new packages.

**Comment by Anixx** [comment]
If it is possible, please package the current version manually, at least once. It is infinitely more advanced than the tagged version.

**Comment by coldacid** [comment]
@Anixx I'd still need a new version number for a manually built package. 0.7.x wouldn't be acceptable since that could be a legit version down the road.
