### ISSUE TITLE
In WPS links to some icons are not created when converting Windows groups. This seems not to depend on the icon's bit depth

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#815]
There are some icons that are displayed but others are not:
![изображение](https://user-images.githubusercontent.com/1271736/98759908-c206cb80-23da-11eb-98ec-0a9d1d061393.png)
![изображение](https://user-images.githubusercontent.com/1271736/98759963-dc40a980-23da-11eb-9099-f463571e23b9.png)
![изображение](https://user-images.githubusercontent.com/1271736/98760131-4f4a2000-23db-11eb-836c-14a6ca2133a7.png)
![изображение](https://user-images.githubusercontent.com/1271736/98760142-54a76a80-23db-11eb-9848-3afa97291a1a.png)
![изображение](https://user-images.githubusercontent.com/1271736/98760147-58d38800-23db-11eb-9410-7b8eac5c2e54.png)

The links to the missing icons are not created in the program group conversion, but if created manually, the icons are shown well.

For instance, this program after the conversion has no icon but when the link to the icon added manually, the icon appears well:
![изображение](https://user-images.githubusercontent.com/1271736/98830016-928ba980-2442-11eb-93b4-339960a7d2b8.png)

**Comment by cracyc** [comment]
https://github.com/otya128/winevdm/pull/817/ mostly fixes this.  The remaining missing icons appear to be due to windows directory redirection.

**Comment by Anixx** [comment]
Tjhis definitely improved the situation, but some groups still show no icons, for instance, that of Skype, despite the link to the executable being correct.

**Comment by Anixx** [comment]
Fixed, closing
