### ISSUE TITLE
Could not allocate a handle

### ISSUE THREAD

**Issue by saabigh** [otya128/winevdm#816]
Hi,

we have this "Could not allocate a handle" message in our environment. 
The Win16 app is still functioning though, but the shape of the mouse pointer changes: it gets the look of the ICO file from the shortcut icon of the application. There are some feature bounded to the mouse pointer (displaying some data while the user moves the pointer, etc...), so this is a bit annyoing for the user. 
How could we avoid this behaviour? Of course restarting the Win16 application helps but after it in various amount of time (1-3 
 hours) the pointer changes again.  

Thanks for any suggestion.
 

We run the Win16 app with otvdm.exe, here are the outputs from the command window:  
(winmnd.exe is the Win16 application)

•	Microsoft Windows [Version 10.0.18362.1139]
•	(c) 2019 Microsoft Corporation. Minden jog fenntartva.
•	
•	c:\winmnd>c:\tools\otvdm\otvdm.exe winmnd.exe
•	version: 1056
•	66c8:err:thunk:get_handle16_data 143: Could not allocate a handle.
•	
•	c:\winmnd>c:\tools\otvdm\otvdm.exe winmnd.exe
•	version: 1056

**Comment by cracyc** [comment]
That version is really old, get the developer version and try that.  Otherwise, a trace for 10min or so might give a hint as to where the handle leak is.

**Comment by saabigh** [comment]
> That version is really old, get the developer version and try that. Otherwise, a trace for 10min or so might give a hint as to where the handle leak is.

Thank you! It might worth a try with the developer version...

**Comment by saabigh** [comment]
Ok, I couldn't get thrugh compiling the dev version (Visual Studio2019), there are only 50 compiling error what i get. 
(yes, binutils, bison and flex installed, PropertySheet.props edited)  

I'm not quite a developer-minded person, I'll never solve this myself, so does anybody have a compiled developer version...? :)

**Comment by saabigh** [comment]
Oh, I'm stupid, I've found it. (behind the unstable link...)
Unfortunatelly our enterpise threat-detection system quarantined the DLLs ant the OTVDMW.exe too. Fine.... :(

**Comment by saabigh** [comment]
Threat detection says its a WS.Reputation1. vulnerability, not quite serious. Defining some exceptions for Symantec Enterprise it is manageable. I'm runnig now the 1871 version succesfully.

**Comment by cracyc** [comment]
If it works then close the issue.  Also please sub nit it to Symantec as a false positive if possible,

**Comment by Athari** [comment]
@saabigh 
@cracyc 
I'd say calling "WS.Reputation.1" a vulnerability or threat is incorrect, as all it means is few people are using this software. It's the same problem of running a random executable on a non-dev machine and receiving "I don't wanna run it" message from Windows. I highly doubt Symantec would care about a false positive as this is purely statistics based. They don't care even about much more serious cases of false positives (my custom RunDll executable with literally one line of code in main still gets reported as suspicious by 50% of AVs).

**Comment by saabigh** [comment]
Version 1871 works fine without any trouble. 
 Thanks for all of your support here!
