### ISSUE TITLE
Windows Defender Reporting virus and preventing download of otvdm-master-1787

### ISSUE THREAD

**Issue by dcharlespyle** [otya128/winevdm#821]
Title is self-explanatory.  Windows Defender is detecting a virus in otvdm.exe in ZIP file.
![image](https://user-images.githubusercontent.com/5110398/99890892-359da980-2c21-11eb-997d-02db7bfd39de.png)
Cannot download because of it.  As soon as it does, Defender removes it.  SmartScreen in the Edge Browser also states that there is a virus and won't download it.  I can force that but then Defender automatically quarantines it again.

**Comment by dcharlespyle** [comment]
Same with otvdm-master-1870.zip

**Comment by emendelson** [comment]
You'll need to make an exception for it in Windows Defender; search the internet for the way to do this. 

Or, of course, you can choose not to use otvdm, if you think it's really dangerous.

**Comment by dcharlespyle** [comment]
Same with otvdm-master-1869.zip

**Comment by dcharlespyle** [comment]
I tried to do that and make an exception.  It now allows the download, but as soon as I try to open the zip file it gets removed and throws another warning.  Never had this issue before. Otvdm-master-1855 is fine.  That is the one currently installed.  Windows has not tried to remove it, either.

**Comment by dcharlespyle** [comment]
Same with otvdm-master-1866.zip

**Comment by dcharlespyle** [comment]
Same with otvdm-master-1865.zip

**Comment by dcharlespyle** [comment]
Same, all the way down to otvdm-master-1862.zip.  I can add an exception, and it will then download, but then as soon as I try to open the zip file, the entire archive gets deleted and I get the same error.  Hmmm.

**Comment by emendelson** [comment]
Make an exception for the folder that contains the download; also for the folder where you'll place the application. Then send the application to Microsoft with a report of a false positive. Search the web for the link.

**Comment by dcharlespyle** [comment]
Windows Defender isn't the only one reporting infection.  Here is what is seen on the Linux side:
![image](https://user-images.githubusercontent.com/5110398/99891299-8d3e1400-2c25-11eb-9885-276804c4e685.png)

**Comment by anonimuos** [comment]
I usually disable Defender using Winaero Tweaker. It's nothing but a nuisance that also reduces file system performance.

**Comment by dcharlespyle** [comment]
I don't have issues with system performance involving Defender.  But I've got two malware solutions (both in Windows and Linux) reporting something wrong since sometime after otvdm-master-1855.  I've submitted the file for analysis.  But having experience with systems compromised by malware, and loss of data, disabling the solutions is the last thing I want to do.

**Comment by dcharlespyle** [comment]
Windows Defender no longer reporting it as infected but Clamav and one other solution still are stating it is potentially unwanted software and/or unsafe.  Closing this because Defender no longer is doing so as of today.
