### ISSUE TITLE
SEGV (segfault) on program launch for LARS

### ISSUE THREAD

**Issue by hektech** [otya128/winevdm#824]
Testing on latest version (1871).

Not expecting anyone else to have this software (LARS), as it is specialty software for library binderies.

Testing on Win10 64bit.  When launching, it segfaults a few times, then exits.  The main program window does appear, but never populates with anything other than the main menus.  (One cannot click the menus to see if they are working; the window is not accessible.)

I am attaching here the terminal output.  I will try to get the full trace as requested as soon as possible.

[otvdm_lars_error.txt](https://github.com/otya128/winevdm/files/5631535/otvdm_lars_error.txt)

**Comment by hektech** [comment]
Here is the trace as suggested.  Thank you for any insight you can offer!

[trace.txt](https://github.com/otya128/winevdm/files/5631609/trace.txt)

**Comment by cracyc** [comment]
`161c:Call USER.85: DRAWTEXT(0044,00000010 #0010,ffff,149f:61d8,0025) ret=11ff:2279 ds=149f`

Well, 0000:0010 isn't a valid address, that's why it crashes.  Windows 3.1 appears to just ignore this error and continue so it might just be an error in the program (but it might not be).

**Comment by hektech** [comment]
You are brilliant, sir.  The program can now successfully open.  Thank you!  Unfortunately, the software is now segfaulting on the next screen.  I will try to run another trace in the morning.  Maybe it is something similar, maybe not.

**Comment by hektech** [comment]
Okay, the debug log was very long, so I truncated it a hundred lines or so before the next fault event.  If I cut out something important, please let me know.

[trace_segv_2_excerpt.txt](https://github.com/otya128/winevdm/files/5636871/trace_segv_2_excerpt.txt)

**Comment by hektech** [comment]
Okay, I decided to try following the same pattern as the last change, and wrapped the contents of GetTextExtent16() in a __TRY block, returning 0 on error.  This seemed to work!  Unfortunately, despite a functional result, the resulting build looks nothing like the builds offered here, so I am not very confident in it.  I do not really know what I am doing, I've done some Linux dev, but never built anything on Windows before, and basically never used Visual Studio before (other than for the simplest things, and that was years ago).  I am going to comment on the build ticket and see if I can get some clarity there.

**Comment by cracyc** [comment]
That does appear to be right based on ntvdm behavior so I did it in https://github.com/otya128/winevdm/pull/826.

**Comment by hektech** [comment]
Marking this closed, as I haven't hit any SEGV after these two commits.  Thank you for your work on this.  Running into different issues now, but will open a new Issue for it.
