### ISSUE TITLE
Unlocking error in LARS

### ISSUE THREAD

**Issue by hektech** [otya128/winevdm#830]
Testing latest master build.

In software LARS, when trying to create a new Job, the software reports a file locking issue, then an assertion failure.  If you click "OK", more of the same messages keep coming.  Clicking "Cancel" on the assertion error kills the program.

It should also be noted that the file in question is being accessed over a network file share mapped to a drive letter.

I am attaching a full debug trace, and also screen shots of the two dialog boxes.  The trace includes just once set, then the "Cancel"/kill.
[trace_unlocking_error.txt](https://github.com/otya128/winevdm/files/5655435/trace_unlocking_error.txt)
![unlocking_error_1](https://user-images.githubusercontent.com/1065804/101409320-bdcfb000-38ab-11eb-9556-f469157130a9.png)
![unlocking_error_2](https://user-images.githubusercontent.com/1065804/101409334-c0caa080-38ab-11eb-9b49-9bf6998146d4.png)

Thank you!

**Comment by cracyc** [comment]
Try https://ci.appveyor.com/project/otya128/winevdm/builds/36708414/job/ydiona5unugdup4j/artifacts

**Comment by cracyc** [comment]
XP/ntvdm seems to behave the same as winevdm right now while win98 and dos share.exe the same as the above pull request.  Does this program work in ntvdm?

**Comment by hektech** [comment]
Thanks again for quick work.  Unfortunately, the patch does not help.  Made another trace, but not too enlightening.  To my relatively untrained eyes, it looks the same, just with a new error code (as one might expect).  Here it is anyway:
[trace_unlocking_1887.txt](https://github.com/otya128/winevdm/files/5660939/trace_unlocking_1887.txt)

I found a small doc with the underlying DB error, but it also doesn't really say anything we don't already know:
"-110 Unlocking File
An error occurred while unlocking part of a file. This error can occur when an attempt is made to unlock bytes that were not locked with File4::lock."

The program works fine in NTVDM.

It seems the error must happen earlier in the execution (to state the obvious :) ).  Suspicious to me are all the attempts to lock the same exact file region over and over, and all the attempts to read system date and time.  I am gradually starting to make some sense of these logs, but I have a long way to go!

Your work is very much appreciated.

**Comment by cracyc** [comment]
Not having access to the program makes it harder.  The invalid _LLSEEK just before the lock retries looks like a possible problem:
```
26a4:Call KERNEL.84: _LLSEEK(0005,effffffe,0000) ret=14bf:d5ec ds=14df
26a4:Ret  KERNEL.84: _LLSEEK() retval=ffffffff ret=14bf:d5ec ds=14df
```
I'm not sure what it expects.

**Comment by hektech** [comment]
Hmm, good point.  I am not sure what it is trying to do there, but it does seem that we might need to check for errors in _llseek16 and return HFILE_ERROR16 instead of just passing through.  Looking at this: https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-_llseek

What do you think?  Does the idea have any legs?

**Comment by cracyc** [comment]
http://www.retroarchive.org/garbo/windows/desktop/dtools11.zip uses the same db library.  The 0xeffffffe is intentional, still don't understand why.
```
push    dx
push    cx              ; ptr
mov     ax, 0FFFEh
mov     dx, 0EFFFh
push    dx
push    ax              ; pos
mov     ax, 1
mov     dx, 0
push    dx
push    ax              ; bytes
call    FILE4LOCK
```

**Comment by hektech** [comment]
Crude mutex indeed!  Well, I am glad one of us has a grasp on what is going on.  That latest pull request resolves this issue for us.  Thank you again for your efforts.  With any luck, we'll have smooth sailing from here.
