### ISSUE TITLE
Is there something like 'Idle Sensitivity'?

### ISSUE THREAD

**Issue by daFritz84** [otya128/winevdm#840]
Hi all, 

I run a win16 license server application which constantly polls for connections and completely saturates one cpu core. NTVDM had some feature called 'Idle Sensitivity' which somehow limited application polling for events. Is there some similar setting in winevdm, or are there other means to limit cpu usage?

Here is some screenshot of the 'Idle Sensitivity' slider I'm looking for:
![image](https://user-images.githubusercontent.com/3084809/102617103-ef146f80-4138-11eb-8809-ce6dfed02529.png)

**Comment by cracyc** [comment]
A configurable forced sleep in Peekmessage might work but I'd need to see a trace to be sure.

**Comment by daFritz84** [comment]
I'm already at home now. But I will try to get a trace recorded next week. 

Anyways, the "high cpu load - polling for events" is just a hypothesis. But I have other applications, i.e. the accompanying client, which behaves completely normal with winevdm. It's just the license server which is eating up cpu power.

**Comment by daFritz84** [comment]
I got a trace: [trace.txt](https://github.com/otya128/winevdm/files/5720058/trace.txt)

It seems like it does loop around PEEKMESSAGE. The following calls are repeated continously:
```
0df8:Call USER.109: PEEKMESSAGE(124f:8612,0000,0000,0000,0001) ret=14a7:3e25 ds=164f
0df8:Ret  USER.109: PEEKMESSAGE() retval=00000000 ret=14a7:3e25 ds=164f
0df8:Call WINSOCK.1: ACCEPT(038c,124f:8578,124f:85a2) ret=16ef:4db0 ds=1777
0df8:Ret  WINSOCK.1: ACCEPT() retval=ffffffff ret=16ef:4db0 ds=1777
0df8:Call WINSOCK.111: WSAGETLASTERROR() ret=16ef:4dbc ds=1777
0df8:Ret  WINSOCK.111: WSAGETLASTERROR() retval=00002733 ret=16ef:4dbc ds=1777
```

**Comment by cracyc** [comment]
Give https://ci.appveyor.com/project/otya128/winevdm/builds/36924880/job/t7gitvu42j1ag7xi/artifacts a try.  Set the sleep length in the otvdm.ini file.

**Comment by daFritz84** [comment]
Thank you so much! Works like a charm.
May I ask what unit of measurement `PeekMessageSleep` has? I assume ms?

**Comment by cracyc** [comment]
Yes, milliseconds.

**Comment by daFritz84** [comment]
Thanks again for the prompt implementation. I will close the issue now.
