### ISSUE TITLE
Instant Artist 1.0 for Windows does not run

### ISSUE THREAD

**Issue by anonimuos** [otya128/winevdm#845]
Running the latest build of otvdm, dev1906. Instant Artist 1.0 for Windows installs fine but nothing happens when it is run.

You can get the abandonware app here: https://winworldpc.com/download/2763290e-9057-11e9-ab10-fa163e9022f0

**Comment by cracyc** [comment]
Works for me.  Need a trace.

**Comment by Anixx** [comment]
Confirming the problem. Otwdm process does not exit, loads the processor.

**Comment by anonimuos** [comment]
[IATrace.zip](https://github.com/otya128/winevdm/files/5760692/IATrace.zip)

Here's a trace.

**Comment by cracyc** [comment]
Try enabling EnumFontLimitation in your otvdm.ini.

**Comment by anonimuos** [comment]
Fixed. That gets it working! Thank you. Closed.
