### ISSUE TITLE
Some freezes in Midisoft Recording Session

### ISSUE THREAD

**Issue by OltScript313** [otya128/winevdm#846]
Hello,

I am using the latest build (1906) of OTVDM and as I commonly use Recording Session to listen to some MIDI files with it, and I discovered an annoying bug...
When the MIDI file is playing, every once in a while, after a while, it suddenly freezes, to unlock it and you have to move the mouse a little or press a key on the keyboard...

It freezes quite often, unfortunately......

Using : Windows 7 x64, OTVDM build 1906

The Software : [SESSION.zip](https://github.com/otya128/winevdm/files/5784886/SESSION.zip)

**Comment by cracyc** [comment]
The problem looks like vm_inject is waiting on the inject_event when the running thread calls GetMessage.  I'm not sure the right way to handle it.
