### ISSUE TITLE
#852 because closed before fixed

### ISSUE THREAD

**Issue by destroyer667** [otya128/winevdm#860]
I have now tested version dev1926 on several different Windows 10 machines.
Unfortunately, I still have the problem that the menu can not be used and that the windows turn white with each popup.
All computers have Windows 10 64 bit version 2004 (build 19041.746) and Microsoft Office 2019 installed. 
The console also shows the same errors on all computers when starting:

![Toffi konsole fehler](https://user-images.githubusercontent.com/73582776/105853871-754c8d00-5fe6-11eb-82b9-b67d36f106b0.png)

I do not know what is meant by this could be a dwm failure and how or if it can be fixed. 

I hope it can be fixed and thank you in advance.

note: since dev1917 the user.exe16 file no longer works my program says i need a licensed 3.1 version to run the program i always have to use an older version of the file

**Comment by cracyc** [comment]
https://ci.appveyor.com/project/otya128/winevdm/builds/37465161/job/i2on9p1oi4h3dg1w/artifacts should fix the note problem.

**Comment by destroyer667** [comment]
Thanks it works all failures are fixed 👍 
one more question the program runs very slowly some functions or windows need 2-4min to open. Is it possible to do something to it otherwise it seems to run perfectly :)

**Comment by cracyc** [comment]
Since you have windows 10 you can use whpx, see https://github.com/otya128/winevdm/issues/699, or haxm if you have an intel cpu.  The program is single threaded and uses peekmessage so it'll always use all of one cpu core.  That's actually bad as it will make your cpu hot so you might want to try setting peekmessagesleep in otvdm.ini.

**Comment by destroyer667** [comment]
> Since you have windows 10 you can use whpx, see #699, or haxm if you have an intel cpu. The program is single threaded and uses peekmessage so it'll always use all of one cpu core. That's actually bad as it will make your cpu hot so you might want to try setting peekmessagesleep in otvdm.ini.

sorry i don't understand how to use/enable whpx in ovtm. can you possibly explain? is there a difference between otvdm.exe and otvdmw.exe besides the console because with otvdm.exe some databases don't load that with otvdm.exe.

**Comment by cracyc** [comment]
Read the linked thread for the options in Windows Features and the needed dll package then add vm=whpxvm.dll to otvdm.ini.

> is there a difference between otvdm.exe and otvdmw.exe besides the console because with otvdm.exe some databases don't load that with otvdm.exe.

Other than the console window and as long as everything else is the same there should be no difference between then.

**Comment by destroyer667** [comment]
It doesn't seem to matter what you set in the "otvdm.ini" it always takes 2 minutes 40 seconds (time stopped) to open the "serial numbers" window. can it be that the access to the MSaccses databases is too slow?
if both exe files are the same except for the "console" then I don't understand why the "Install (no console).ink" doesn't load the data under "Stammdaten" -> "Vorgang" but the "Install.ink" does load the database. 

with console:
![mit console](https://user-images.githubusercontent.com/73582776/106106870-772d6200-6146-11eb-80b3-c329b5dafd51.png)

without console:
![ohne console](https://user-images.githubusercontent.com/73582776/106106895-814f6080-6146-11eb-88a2-e7d063692df4.png)


could possibly also be due to the slow access to the msaccsess databases

**Comment by otya128** [comment]
Note that vm=whpxvm.dll must be added above [EnumFontLimitation].
Example: [otvdm.ini.txt](https://github.com/otya128/winevdm/files/5885945/otvdm.ini.txt)

**Comment by destroyer667** [comment]
> Note that vm=whpxvm.dll must be added above [EnumFontLimitation].
> Example: [otvdm.ini.txt](https://github.com/otya128/winevdm/files/5885945/otvdm.ini.txt)

yes i have set it that way i have not noticed any special changes in the performance.
