### ISSUE TITLE
Print succeeds on 1056 but fails on 1925

### ISSUE THREAD

**Issue by mschink** [otya128/winevdm#861]
**Describe the bug**
Printing through FoxPro 2.6 fails on the newest (admittedly unstable) releases

**Expected behavior**
We expect the print job to complete without the "Printer not ready" error.

**Environment (please complete the following information):**
 - OS: Windows 10 19042.746
 - Version 20H2

**Additional context**
Each trace shows a different message: the failure with "Printer not ready." and the success with "Opening Printer" dialogs.
[1925_fail.txt](https://github.com/otya128/winevdm/files/5875699/1925_fail.txt)
[1056_success.txt](https://github.com/otya128/winevdm/files/5875700/1056_success.txt)

**Comment by cracyc** [comment]
Try https://ci.appveyor.com/project/otya128/winevdm/builds/37464782/job/8ct4dlidbokhdc4x/artifacts

**Comment by mschink** [comment]
Brilliant! no issues printing using 1927. Thank you!
