### ISSUE TITLE
Access Performence

### ISSUE THREAD

**Issue by destroyer667** [otya128/winevdm#868]
I have now tested with my program so some. I had to determine that if I access empty databases or small databases everything loads very quickly. with larger databases it just loads forever. but that happens only under Otvdm under Xp it runs smoothly.

the key combinations ctrl+1, ctrl+2 etc unfortunately do not work.
the key combinations can be viewed under "Hilfe" -> "Tasten"

I hope you can still do something
THX

**Comment by cracyc** [comment]
https://ci.appveyor.com/project/otya128/winevdm/builds/37561414/job/lbfnb2ukgwts5jk7/artifacts should improve macro behavior.  If whpx doesn't help the performance then you can try haxm but I wouldn't really expect a difference.  Otherwise I don't understand why it don't seem to help for you as almost everything else is significantly faster with whpx or haxm.

**Comment by destroyer667** [comment]
> https://ci.appveyor.com/project/otya128/winevdm/builds/37561414/job/lbfnb2ukgwts5jk7/artifacts should improve macro behavior. If whpx doesn't help the performance then you can try haxm but I wouldn't really expect a difference. Otherwise I don't understand why it don't seem to help for you as almost everything else is significantly faster with whpx or haxm.
> 
> I imported 1.5M record sample data into an access table. To move to the last row takes 2-3 min with the emulation and ~10 sec with whpx. That's the only way I can think of to ry to repo your problem.

Super the shortcuts work now. Thanks

can you use the test data to see how long it takes to open the window under "Reports" -> "Seriennummern"?
Could it perhaps be related to the fact that the databases are on the network and not locally?

**Comment by cracyc** [comment]
Almost instantly, there's only a handful of records though.  My table test didn't show a significant difference between local and over a gigabit ethernet link.  If your report uses a complex query it might slow things down though.

**Comment by destroyer667** [comment]
> Almost instantly, there's only a handful of records though. My table test didn't show a significant difference between local and over a gigabit ethernet link. If your report uses a complex query it might slow things down though.

I can't otherwise explain why it takes so long to load. It always takes at least 2:40min to open the window. Even so, the windows always open a little delayed that is still okay but 2:40min are just too long for a window that normally takes 10-20 seconds.
