### ISSUE TITLE
Interrupt 0D #GP err FFFC

### ISSUE THREAD

**Issue by leovincentseles** [otya128/winevdm#877]
The game Elory goes Bugzerk can be downloaded from [here](https://archive.org/download/elroy/elroy.zip)

**Try the latest version first.**
- Yes

**Describe the bug**
- ![image](https://user-images.githubusercontent.com/36748589/107620987-89ec7e80-6c90-11eb-80bf-b257316bef7f.png)

**Expected behavior**
- I can run BUGZERK.exe in Windows XP

**Environment (please complete the following information):**
 - OS: Windows 10 1909
 - Version 1952
 
**Upload trace.txt here.**
[trace.txt](https://github.com/otya128/winevdm/files/5964311/trace.txt)

**Comment by cracyc** [comment]
```
0574:05c0:trace:int21:INT21_GetCurrentDirectory 733: drive 4
0574:05c0:trace:int21:INT21_GetCurrentDirectory 835: D:=Downloads\Elroy goes Bugzerk
```
You need to make this directory name 8.3 char or give it a short file name with `fsutil file setshortname <PathName> <shortname>`.

**Comment by leovincentseles** [comment]
Thank you very much. I can run the game successfully now!
