### ISSUE TITLE
Crash opening game Tibia (version 3.0)

### ISSUE THREAD

**Issue by rsribeiro** [otya128/winevdm#887]
**Describe the bug**
Crash when the application is opened.

**Expected behavior**
Application does not crash. Other more recent versions of the game open just fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/11283302/108610317-b1e48c00-73cc-11eb-9ece-a3c10fbd38ff.png)

**Environment (please complete the following information):**
 - OS: Windows 10 20H2
 - Version 1966

**Additional context**
[trace.txt](https://github.com/otya128/winevdm/files/6016812/trace.txt)

**Comment by cracyc** [comment]
This is a bug in the program.  If you set 640x480 mode it works, then you can resize the window.  Once it gets larger than a certain size it fails.

**Comment by rsribeiro** [comment]
Thank you, that was exactly the issue.
