### ISSUE TITLE
Printer Crash

### ISSUE THREAD

**Issue by destroyer667** [otya128/winevdm#899]
i use the version dev1995

the performance problem with the accsess database has been solved. it runs quite stable so far only :

when i want to print something from my program (Toffi) it crashes sporadically. about every second - third time printing causes a crash without error message.
it does not matter which printer is selected.
I hope you can fix it thanks

**Comment by cracyc** [comment]
Try https://ci.appveyor.com/project/otya128/winevdm/builds/38239996/job/91ob9sj2glciyw6h/artifacts

**Comment by destroyer667** [comment]
thanks for fixing the problem quickly.
We noticed something else andzwar if you have in input fields certain lengths of text is the Kurser shifted have greed 2 images:

![image](https://user-images.githubusercontent.com/73582776/111319064-ec58e600-8665-11eb-8df1-4e0387d1d8ad.png)



![image](https://user-images.githubusercontent.com/73582776/111318975-d519f880-8665-11eb-89db-553cfda470ec.png)

I hope you can fix it thanks
