### ISSUE TITLE
Borland C++ 4.5.2 crashes when starting exe file from IDE

### ISSUE THREAD

**Issue by LegacyFreak** [otya128/winevdm#906]
Hello,
thanks for fixing issue #900. Linking now works in Borland C++ 4.5.2.
Now I get another problem. When I start a compiled exe file, I get the following error (see screenshot and trace).
This only happens in win16 projects. Win32 files start without a problem.
I am also able to run the win16 exe outside the IDE under otvdm.

![Screenshot](https://user-images.githubusercontent.com/68747203/112036723-444d8c00-8b41-11eb-859f-0fe6a9562433.jpg)
[trace.zip](https://github.com/otya128/winevdm/files/6184361/trace.zip)

**Comment by cracyc** [comment]
GUI debugging is black magic on win16 due to the cooperative design which is why most win16 debuggers ran in text mode (tdw,codeview,softice).  The microsoft ide for msvc and quickc both also fail, only watcom wdw currently works.

**Comment by LegacyFreak** [comment]
Hello,
thanks for your reply, but the crash also happens when I start the program inside the IDE without debuggung.

**Comment by LegacyFreak** [comment]
Hello,
thanks for the patch, but now there is another error message in the same situation (see screenshot an trace).

![Screenshot](https://user-images.githubusercontent.com/68747203/112522346-cc2fd200-8d9d-11eb-8be9-cc84a84bdfb4.jpg)
[trace.zip](https://github.com/otya128/winevdm/files/6206940/trace.zip)

**Comment by cracyc** [comment]
The debugger assumes that the entry to loadlibrary and cvwdebug contains "push bp; mov bp,sp; push <word>" at the start and winevdm doesn't.
