### ISSUE TITLE
waiting for splwow64.exe 

### ISSUE THREAD

**Issue by destroyer667** [otya128/winevdm#908]
Unfortunately, a new problem has arisen.
From time to time when using search in the program otvdm simply stops.
In taskmanager it says under details queues analysis otvdm is waiting for splwow64.exe.
the error does not occur with version dev1999. only since dev2004.
also with dev2007 the error exists.

**Comment by cracyc** [comment]
I'd need a reproducible procedure that I can use and probably a trace to debug this.  splwow64 is the print spooler shim for 32bit windows programs on x86-64 so printing would likely be part of the issue.
