### ISSUE TITLE
Problem with comport

### ISSUE THREAD

**Issue by Leira2412** [otya128/winevdm#917]
Hello sir i have problem with old windows 3.1 application that is crashing when launched i with OTVDM and accessing serial port COM1, environement is windows 10 x64
You will find attached trace
[Trace.log](https://github.com/otya128/winevdm/files/6230969/Trace.log)
If you can help ?
thank you

**Comment by Leira2412** [comment]
Hello sir i understand, what you write , but i don't have the source code of the application and cannot modify it.
is anything can be fixed with otvdm ?

**Comment by cracyc** [comment]
Yes, the patch I made fixes the problem with buildcommdcb but there's another issue that unfortunately is not clear from the trace.  Since I don't have it to test directly, I couldn't have known that that didn't fix it fully.

**Comment by Leira2412** [comment]
Ok how is it possible to send it directly to you, i don't want to post it on internet ?
thank you

**Comment by Leira2412** [comment]
Hello sir you will on  google drive 2 files 

https://drive.google.com/drive/folders/12YaFrwgu229xRJocM5rQBxwyQNutTZaU?usp=sharing

 

Tei700-I7.7z you need on unpack on shortname dir (8.3)

And also tei700_psr.zip that does a record of step to reproduce the problem

 

The password asked when run the application is : Admin

After you click on Menu Configuration

Click on  SMX442 CODEUR

Click on Retour Menu Principal

And then Connexion

After it just crashed at about 25%

 

When this application is run on Windows 7 X32, it just runs until 75% and 

A popup comes “Non réponse de l’équipement «  

Because no equipment is connected.

 

If you can help It will be very nice

Thank You

 

 

De : cracyc ***@***.***> 
Envoyé : Thursday, April 1, 2021 2:08 AM
À : otya128/winevdm ***@***.***>
Cc : Leira2412 ***@***.***>; Author ***@***.***>
Objet : Re: [otya128/winevdm] Problem with comport (#917)

 

Yes, the patch I made fixes the problem with buildcommdcb but there's another issue that unfortunately is not clear from the trace. Since I don't have the program to test directly, I couldn't have known that that didn't fix it fully.

**Comment by cracyc** [comment]
Send it to bs666_1(at)hotmail(dot)com

**Comment by cracyc** [comment]
https://ci.appveyor.com/project/otya128/winevdm/builds/38520584 fixes the crash

**Comment by Leira2412** [comment]
Thank you we tested the application with equipemnt and everything is working
