### ISSUE TITLE
In Xerox Presents the MDI clients do not have maximize and minimize buttons, which complicates window management

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#921]
In Xerox Presents the MDI clients do not have maximize and minimize buttons, which complicates window management

**Comment by Anixx** [comment]
Well, "Maximize" it seems does not work in this case, but adding minimize and restore helps.

**Comment by Anixx** [comment]
The same is in Cadlogic Instinct 1.0

**Comment by cracyc** [comment]
It's the same in windows 2.0 so it's a problem in the program itself.
