### ISSUE TITLE
lack of labeling

### ISSUE THREAD

**Issue by destroyer667** [otya128/winevdm#928]
I have noticed in "Toffi" that for entries that are locked with the "F7" key, the "locked" flag is missing. 

picture 1 windows xP area marked green

![sperre da](https://user-images.githubusercontent.com/73582776/113707600-6d911f00-96e0-11eb-9df6-0cd9f274e287.png)

picture 2 windows 10 self entry

![sperre weg](https://user-images.githubusercontent.com/73582776/113707608-7124a600-96e0-11eb-8801-11d6134051db.png)

**Comment by cracyc** [comment]
Works for me.  I'd have to see a trace to have any hope of fixing it.
![Capture](https://user-images.githubusercontent.com/9255333/113756293-d4113f80-96d6-11eb-837e-8906fdabafc3.PNG)

**Comment by destroyer667** [comment]
I use the "whpxvm.dll" and HyperV, otherwise everything remained on default setting. I have tested it on 4 PCs always with the above described result.
I do not know how to pursue it further
here is a screenshot of the console:

![Konsole](https://user-images.githubusercontent.com/73582776/113819352-784bc280-9779-11eb-9c9c-ebe674dd30d2.png)

**Comment by cracyc** [comment]
See https://github.com/otya128/winevdm/issues/226#issuecomment-779702542 for detailed instructions on how to make a trace file.

**Comment by destroyer667** [comment]
thanks here is the trace file as zip
i hope it can be fixed with it

[trace.zip](https://github.com/otya128/winevdm/files/6276545/trace.zip)

**Comment by destroyer667** [comment]
I have for some time another problem on 2 of four computers the program now no longer runs at all it starts and after 2-3 times click the program freezes forever.
have made a trace to it:

[trace.zip](https://github.com/otya128/winevdm/files/6278673/trace.zip)

**Comment by cracyc** [comment]
the hang should be fixed by https://github.com/otya128/winevdm/pull/930

**Comment by cracyc** [comment]
Does the logo appear in this window on the computers where the "Sperre" is missing?
![Capture](https://user-images.githubusercontent.com/9255333/114117038-74b85880-98ab-11eb-88cf-8fae9e87ca64.PNG)

**Comment by destroyer667** [comment]
I have checked the logo is also missing

**Comment by cracyc** [comment]
This is a registry issue which was fixed but if the program was installed with an older version of winevdm it'll persist.  Try importing this reg file.
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Classes\Wow6432Node\CLSID\{00030007-0000-0000-C000-000000000046}\Ole1Class]
@="MSDraw"
```

**Comment by destroyer667** [comment]
its fixed thanks :)
the other error is now fixed on one of 2 computers. the sound output we eigendlich not output there are no speakers connected. can it be due to the sound card?
on the computer where it now freezes the trace does not work the program runs extremely slowly as soon as I have started it via the cmd and always freezes briefly so that I can not simulate the error.

**Comment by cracyc** [comment]
They might be different problems if the trace is from the one that works now.  I'd really need a trace if so.
