### ISSUE TITLE
Word 6.0a - Admin rights required to avoid SHARE.EXE problem

### ISSUE THREAD

**Issue by LegacyFreak** [otya128/winevdm#932]
Hello,
ist seems to be a well known behaviour of Word 6.0 that it tries to create a temp file on C:\ to check if share.exe ist loaded.
Because of this on Windows 10 it is necessary to start WineVDM with admin rights to run Word 6.0. It would be nicer if such a write access could be redirected in WineVDM. Is there a possibility to do so or are there any plans to implement that into otvdm?

![Screenshot](https://user-images.githubusercontent.com/68747203/114071434-66fdd580-98a1-11eb-847d-51cb2ea3184e.jpg)
[trace.zip](https://github.com/otya128/winevdm/files/6280441/trace.zip)

**Comment by cracyc** [comment]
```
1abc:Call KERNEL.97: GETTEMPFILENAME(00c3,195f836a "doc",0000,195f:824e) ret=1647:09b1 ds=195f
1abc:err:file:GetTempFileName16 1082: C:~doc7C86.TMP ERROR_ACCESS_DENIED
1abc:Ret  KERNEL.97: GETTEMPFILENAME() retval=00367c86 ret=1647:09b1 ds=195f
1abc:Call KERNEL.74: OPENFILE(195f824e "C:~doc7C86.TMP",195f82e0,1012) ret=1647:09d8 ds=195f
1abc:Ret  KERNEL.74: OPENFILE() retval=0000ffff ret=1647:09d8 ds=195f
1abc:Call USER.1: MESSAGEBOX(0000,195f837c "Sie müssen Windows verlassen und SHARE.EXE laden bevor Sie Word starten.",00000000 (null),1030) ret=1647:084f ds=195f
```

You need to have write permission to the current directory for it to work without admin privileges.  There's nothing winevdm can do to get around that.  You can set the start menu shortcut start directory to your documents folder and that should work.

**Comment by LegacyFreak** [comment]
Hallo,
thanks for the answer. But whatever I do Word insists to create a temp file on drive C:. Changeing the start folder for otvdm.exe does not give any success. 
Maybe it would be an option to modify the API function "GETTEMPFILENAME()" to avoid creating temp files on drive C:. I can't imagine that it would be useful for any win16 app to create temp files on drive C: in an Windows 10 environment.
Greetings fom germany.

**Comment by cracyc** [comment]
That is possible but it won't help here, in fact OpenFile already does that but it didn't work in this case because that passed path isn't fully qualified.  It's the winword.exe current directory that needs to be set, not otvdm.

**Comment by LegacyFreak** [comment]
Hello,
I have no further idea how to set the current directoy for winword. The latest thing I tried, was calling "otvdmw.exe word.lnk".
In the file word.lnk the working directory was set to m:\Winevdm\word6. Word furthermore insists on creating a temp file on C:
The only thing that works ist to run otvdmw.exe in compatbility mode, but that als means it gets admin rights.

**Comment by cracyc** [comment]
So it looks for the first fixed disk and puts the temp file in the current dir on that drive thus the working dir needs to be a directory you can write to that is on the first hdd (c:).

**Comment by otya128** [comment]
```cmd
Y:\>c:
C:\>cd users\user
C:\Users\user>Y:
Y:\>cd WINWORD
Y:\WINWORD>WINWORD.EXE
```
This can be avoided by changing the current directory of the C drive and then starting it.

temppath needs to be redirected in GetTempFileName16 and RedirectDriveRoot should redirect relative path.

**Comment by LegacyFreak** [comment]
Ok, works for me when otvdm is correctly installed in Windows 10.
