### ISSUE TITLE
Microsoft Access 2.0 - Error calling 32 bit ODBC driver

### ISSUE THREAD

**Issue by LegacyFreak** [otya128/winevdm#952]
Hello,
I tried to get Access 2.0 to work with 32 bit ODBC. These steps I have done so far.

1. Copied the files ds16gt.dll, ds32gt.dll, odbc16gt.dll and odbc32gt.dll from an existing Windows XP installation where Access 2.0 successfully runs with 32 bit ODBC into the Windows system directory in OTVDM.
2. Created two 32 bit ODBC datasources for Oracle and Access with the 32 bit ODBC Administrator
3. Installed Access 2.0 and ODBC 2.0 (16 bit) in OTVDM.
4. Copied the entries, which are related to my datasources, from ODBC.INI in Windows 10 into my ODBC.INI in OTVDM.

Now I can see the 32 bit data sources within the 16 bit ODBC Driver Manager in OTVDM.
When I select one of my 32 bit datasources in Access 2.0 to create a linked table, I get the follow error message. This is the same for the Oracle and the Access datasource (see screenshot and trace).
![grafik](https://user-images.githubusercontent.com/68747203/115434863-7833d400-a209-11eb-8abc-cbc85d0ca1ff.png)
[trace.zip](https://github.com/otya128/winevdm/files/6345286/trace.zip)

**Comment by cracyc** [comment]
Google translate gives me "Invalid window handle".  Since winevdm doesn't share hwnds with win32 the way ntvdm does, they have to be translated going in and out.  Usually CallProc32W is used for calling from win16 to win32 and there's some window handle translation in there already, this will probably need adding.

**Comment by LegacyFreak** [comment]
Hello, 
problem solved. Thanks for patch.
