### ISSUE TITLE
otvdm 2064 executables cannot be runned anymore

### ISSUE THREAD

**Issue by oxy9vm** [otya128/winevdm#954]
![otvdmregression0](https://user-images.githubusercontent.com/83113596/115952320-9e809a80-a4bb-11eb-9f37-c098198f7b5e.png)

It can be installed normally just clicking "install"  under **Windows 10 64bits 1909** but,
"**otvdmw.exe**" and "**otvdm.exe**" from  version 2064 cannot be runned, message says "**Windows does not have access to device, path or specified file. You may not have the appropriate permissions to access the item**. "  
 
dev2064 from here https://ci.appveyor.com/project/otya128/winevdm/build/job/gnslw41odfl54tcu/artifacts

Last well-working build I´ve tested was 2056, so it is a critical regression.

**Comment by MrPepka** [comment]
Maybe the antivirus classified winevdm as a virus? Check that the program's files do not appear as locked

**Comment by oxy9vm** [comment]
Yes, it is Avast antivirus system. Enabled as exception solves it.

**Comment by oxy9vm** [comment]
The  only tips now is that Firefox warns otvdm 2065 as warning, nothing that download anyways can solve. In Chrome does not happen.

![otvdm2065FirefoxTrolling0](https://user-images.githubusercontent.com/83113596/115977418-77bf7400-a54e-11eb-8a62-9c470e7cc29e.png)
![otvdm2065FirefoxTrolling1](https://user-images.githubusercontent.com/83113596/115977419-78580a80-a54e-11eb-88c0-2bbe9deb1540.png)
