### ISSUE TITLE
[Question] How To Get It

### ISSUE THREAD

**Issue by sudo-nautilus** [otya128/winevdm#957]
So, how to get this thing to my pc ?,
The things in the Readme.md are unclear. I tried Building with visual studio 2019 Enterprise and it ended up with an issue saying `..\wine\windows\wtypes.idl` was not found but it was there actually.

**Comment by otya128** [comment]
To guess, it's possible that widl is giving an error. I want a detailed error message.
You can get the latest build from https://ci.appveyor.com/project/otya128/winevdm. Environment: THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1->Artifacts->otvdm-*.zip

**Comment by sudo-nautilus** [comment]
wait a second lemme send detailed error logs

**Comment by sudo-nautilus** [comment]
# Setup Screen

![winevdm_screen](https://user-images.githubusercontent.com/78522210/116078885-cab33b80-a6b4-11eb-9c08-e78ed223ebac.jpg)

# How I Tries Builds

![winedvm_build](https://user-images.githubusercontent.com/78522210/116078989-ed455480-a6b4-11eb-9590-dbbb0379d6be.png)

# The Error In A Nutshell

![error_nutshell](https://user-images.githubusercontent.com/78522210/116079123-12d25e00-a6b5-11eb-95b0-78f9132c051a.png)

# Detailed ( Ig )

![error_detailed](https://user-images.githubusercontent.com/78522210/116079234-2c73a580-a6b5-11eb-97fa-2baa35eed5ce.png)
