### ISSUE TITLE
IQ Box doesn't work

### ISSUE THREAD

**Issue by MrPepka** [otya128/winevdm#964]
I came across another game not working with WineVDM. This game is IQ Box. The game starts, but I get a SEGV error when I try to start. After selecting "Continue", I only have a black screen with HUD items from the game. I am attaching the content of the console from the moment the error was displayed:
version: 2070
=====dump all modules=====
Module Flags Name Flag
 13c7   8021    WIN87EM     SINGLEDATA | BUILTIN | LIBMODULE
 137f   0302    PUSH_BOX_EDITOR             »*♠ňWÉ├D»*♠ăT       R§Đ├7MULTIPLEDATA | FRAMEBUF | CONSOLE | GUI
 121f   8301    MULTDLL     SINGLEDATA | FRAMEBUF | CONSOLE | GUI | LIBMODULE
 11af   0302    PUSH_BOX_MAIN             »*♠ňWÉ├D»*♠ăT R§Đ├7MULTIPLEDATA | FRAMEBUF | CONSOLE | GUI
 1197   8021    SOUND       SINGLEDATA | BUILTIN | LIBMODULE
 117f   8021    MMSYSTEM    SINGLEDATA | BUILTIN | LIBMODULE
 1167   8021    MOUSE       SINGLEDATA | BUILTIN | LIBMODULE
 114f   8021    KEYBOARD    SINGLEDATA | BUILTIN | LIBMODULE
 1137   8021    DISPLAY     SINGLEDATA | BUILTIN | LIBMODULE
 1117   8021    USER        SINGLEDATA | BUILTIN | LIBMODULE
 10f7   8021    GDI         SINGLEDATA | BUILTIN | LIBMODULE
 10cf   8021    TIMER       SINGLEDATA | BUILTIN | LIBMODULE
 10b7   8021    COMM        SINGLEDATA | BUILTIN | LIBMODULE
 109f   8021    SYSTEM      SINGLEDATA | BUILTIN | LIBMODULE
 1007   8021    KERNEL      SINGLEDATA | BUILTIN | LIBMODULE
=====dump all modules=====
00A50000-00A59000 otvdm.exe
77E00000-77FA3000 ntdll.dll
77BB0000-77CA0000 KERNEL32.DLL
76870000-76A84000 KERNELBASE.dll
75BB0000-75C4F000 apphelp.dll
75FF0000-7606A000 ADVAPI32.dll
77A90000-77B4F000 msvcrt.dll
77290000-77305000 sechost.dll
76C10000-76CD0000 RPCRT4.dll
75ED0000-75FF0000 ucrtbase.dll
70F30000-70F44000 VCRUNTIME140.dll
52160000-5219A000 libwine.dll
520D0000-52154000 krnl386.exe16
75CB0000-75E46000 USER32.dll
77690000-776A8000 win32u.dll
55D40000-55DBF000 DSOUND.dll
766D0000-766F3000 GDI32.dll
77750000-779D2000 combase.dll
77310000-773EC000 gdi32full.dll
77D70000-77DEB000 msvcp_win.dll
70930000-70974000 powrprof.dll
76CD0000-77283000 SHELL32.dll
59CE0000-59CFD000 winmmbase.dll
77570000-775B5000 SHLWAPI.dll
6E2B0000-6E31D000 WINSPOOL.DRV
70850000-7085D000 UMPDC.dll
773F0000-77415000 IMM32.DLL
71830000-71859000 ntmarta.dll
5AF00000-5AF08000 system.drv16
5AEF0000-5AEF8000 comm.drv16
5AEE0000-5AEE8000 timer.drv16
52040000-520C7000 vm86.dll
77A70000-77A89000 imagehlp.dll
52010000-52033000 gdi.exe16
51E60000-5200A000 user.exe16
6F970000-6F9E4000 UxTheme.dll
70EA0000-70EB9000 MPR.dll
75BA0000-75BA8000 VERSION.dll
76700000-767D3000 MSCTF.dll
776B0000-77746000 OLEAUT32.dll
77480000-77563000 ole32.dll
75A80000-75A8F000 kernel.appcore.dll
77420000-7747D000 bcryptPrimitives.dll
535C0000-535C9000 display.drv16
535B0000-535B8000 keyboard.drv16
51E50000-51E58000 mouse.drv16
74BC0000-751C9000 windows.storage.dll
74B90000-74BB4000 Wldp.dll
77CA0000-77D27000 shcore.dll
6F8A0000-6F963000 PROPSYS.dll
51E30000-51E4B000 mmsystem.dll16
70E50000-70E78000 WINMM.dll
51DB0000-51DB9000 sound.drv16
51DA0000-51DA8000 ctl3dv2.dll16
51D90000-51D98000 ctl3d.dll16
65F10000-66098000 dbghelp.dll
55CF0000-55D12000 MSVFW32.dll
6E000000-6E08D000 COMCTL32.dll
55D20000-55D3B000 AVIFIL32.DLL
59D00000-59D19000 MSACM32.dll
75E50000-75ECE000 clbcatq.dll
59AF0000-59B5B000 MMDevAPI.DLL
73750000-73774000 DEVOBJ.dll
77D30000-77D6B000 cfgmgr32.dll
7A8A0000-7A8DA000 wdmaud.drv
66760000-66767000 ksuser.dll
55570000-55578000 AVRT.dll
7A8E0000-7A91B000 VirtualMIDISynth.dll
7A920000-7A95C000 MIDIMapper.dll
76180000-765B5000 SETUPAPI.dll
77A40000-77A59000 bcrypt.dll
63650000-63709000 textinputframework.dll
635B0000-6364B000 CoreMessaging.dll
63330000-635AE000 CoreUIComponents.dll
77620000-77683000 WS2_32.dll
63250000-6332B000 wintypes.dll
535D0000-53706000 AUDIOSES.DLL
516A0000-516AA000 msacm32.drv
50000000-50008000 midimap.dll
59BE0000-59CD3000 Windows.UI.dll
5FC00000-5FCED000 InputHost.dll
59B60000-59BD3000 WindowManagementAPI.dll
64430000-645BF000 twinapi.appcore.dll
51D80000-51D88000 win87em.dll16
31: vm86.dll!load_x87function+0x7141 - 0x5208bb40 0x52092c81 (null):0
30: ntdll.dll!LdrSetDllManifestProber+0xf8 - 0x77e6cc80 0x77e6cd78 (null):0
29: ntdll.dll!RtlUnwind+0x1cb - 0x77e68e30 0x77e68ffb (null):0
28: ntdll.dll!KiUserExceptionDispatcher+0x26 - 0x77e74e70 0x77e74e96 (null):0

27: krnl386.exe16!RegFlushKey16+0x703 - 0x5210f330 0x5210fa33 (null):0
26: krnl386.exe16!vm_debug_get_entry_point+0x80c - 0x5210fa90 0x5211029c (null):0
25: vm86.dll!disassemble_debug+0x11b5 - 0x52093630 0x520947e5 (null):0
24: vm86.dll!wine_call_to_16_regs_vm86+0x53 - 0x52093300 0x52093353 (null):0
23: krnl386.exe16!K32WOWCallback16Ex+0x46c - 0x521259e0 0x52125e4c (null):0
22: user.exe16!call_native_wndproc_context+0x332 - 0x51e71060 0x51e71392 (null):0
21: user.exe16!call_native_wndproc_context+0x3c5a - 0x51e71060 0x51e74cba (null):0
20: user.exe16!_wine_call_wndproc+0x377b - 0x51e77490 0x51e7ac0b (null):0
19: USER32.dll!AddClipboardFormatListener+0x4b - 0x75ceee70 0x75ceeebb (null):0
18: USER32.dll!GetClassLongW+0x7aa - 0x75ce56d0 0x75ce5e7a (null):0
17: USER32.dll!GetClassLongW+0x3aa - 0x75ce56d0 0x75ce5a7a (null):0
16: USER32.dll!GetDC+0x89 - 0x75cecce0 0x75cecd69 (null):0
15: ntdll.dll!KiUserCallbackDispatcher+0x4d - 0x77e74e00 0x77e74e4d (null):0
14: USER32.dll!CreateWindowExW+0x167 - 0x75cdd500 0x75cdd667 (null):0
13: USER32.dll!CreateWindowExA+0x38 - 0x75cd6420 0x75cd6458 (null):0
12: user.exe16!_wine_call_wndproc+0x34a3 - 0x51e77490 0x51e7a933 (null):0
11: user.exe16!USER_ClassNext16+0x15f7 - 0x51e86bd0 0x51e881c7 (null):0
10: user.exe16!CreateIconFromResourceEx16+0x265b - 0x51e81870 0x51e83ecb (null):0
9: krnl386.exe16!RegFlushKey16+0x703 - 0x5210f330 0x5210fa33 (null):0
8: krnl386.exe16!vm_debug_get_entry_point+0x80c - 0x5210fa90 0x5211029c (null):0
7: vm86.dll!disassemble_debug+0x11b5 - 0x52093630 0x520947e5 (null):0
6: vm86.dll!wine_call_to_16_regs_vm86+0x53 - 0x52093300 0x52093353 (null):0
5: krnl386.exe16!K32WOWCallback16Ex+0x46c - 0x521259e0 0x52125e4c (null):0
4: krnl386.exe16!LoadModule16+0x7a5 - 0x52109b70 0x5210a315 (null):0
3: krnl386.exe16!RestoreThunkLock+0xecf - 0x52116560 0x5211742f (null):0
2: KERNEL32.DLL!BaseThreadInitThunk+0x19 - 0x77bcfa10 0x77bcfa29 (null):0
1: ntdll.dll!RtlGetAppContainerNamedObjectPath+0x11e - 0x77e67930 0x77e67a4e (null):0
0: ntdll.dll!RtlGetAppContainerNamedObjectPath+0xee - 0x77e67930 0x77e67a1e (null):0
cs:ip=111f:0abe bp=a5de                 args(13b7,01b8,0000,0000,002d,0000,3731,3300,0039,3735)
cs:ip=13b7:358a bp=a6a5(call 13b7:38b4) args(002d,13be,002d,0000,111f,0000,6b0c,51e6,524a,7870)
cs:ip=13b7:24d1 bp=a6dd(call 13b7:33c6) args(a6ec,13bf,0000,0001,002d,0000,0000,13be,0000,002a)
(callback)cs:ip=102f:0458 bp=a739
cs:ip=13b7:2432 bp=a75d(call 111f:4fac) args(13be,0003,00a4,2780,520e,a778,21a2,13b7,ffff,a9b4)
cs:ip=13b7:229a bp=a77b(call 13b7:23fa) args(0003,0080,139f,0000,13be,13bf,0001,00b4,13b7,0001)
cs:ip=13b7:00e7 bp=a78d(call 13b7:2270) args(0001,a798,a9b4,a800,0000,13bf,0000,0000,0458,102f)
cs:ip=13b7:00b4 bp=0001(call 13b7:00c4) args(a7d0,0000,8036,a7a0,a7a0,012c,0000,0001,0000,0000)
cs:ip=13b7:0000 bp=0000                 args(0005,a7d0,0000,8036,a7a0,a7a0,012c,0000,0001,0000)

address=51E7CB9E
access address=00000004
VM context
EAX:A5CC,ECX:01E0,EDX:0000,EBX:0000
ESP:A580,EBP:A5DE,ESI:0000,EDI:0000
ES:0000,CS:111F,SS:13BF,DS:13BF,FS:0000,GS:0000
IP:0ABE, address:02EDA546
EFLAGS:00003246

SEGV
<img width="1920" alt="2021-04-28 (1)" src="https://user-images.githubusercontent.com/38865931/116417327-7090b280-a83b-11eb-8116-c5cb519616c2.png">
Link to game - https://www.old-games.ru/game/download/10118.html

**Comment by cracyc** [comment]
This fixes the crash but the game window is still blank.  Might be a palette issue because the same happens in xp-ntvdm in 24bit color mode.

**Comment by MrPepka** [comment]
For me, the palette is OK
<img width="1920" alt="2021-04-28 (2)" src="https://user-images.githubusercontent.com/38865931/116434090-64602180-a84a-11eb-90a5-ac44b1157153.png">
