### ISSUE TITLE
SEGV error

### ISSUE THREAD

**Issue by luishdemetrio** [otya128/winevdm#977]
**Describe the bug**
A VB3 application is crashing for a specific UI for the emulator 2039. I am using Windows 10 64-bit.
The first trace: the app was launched, user puts the customer ID and before entering the next window it crashes. On the 2nd the next window arrives and when it goes to the fixed-term option, it closes there.

**Expected behavior**
The VB3 App is working on Windows 10 32-bit.

**Screenshots**
![image](https://user-images.githubusercontent.com/49683427/117079749-c7eac300-ad12-11eb-8761-f57816f196fb.png)

**Environment (please complete the following information):**
 - OS: Windows 10 64-bits 2004

[trace.zip](https://github.com/otya128/winevdm/files/6424330/trace.zip)

Thank you very much in advance.

**Comment by cracyc** [comment]
The trace shows it's crashing in IDispatch::Release but there's not enough information to know why.

**Comment by luishdemetrio** [comment]
Thank you @cracyc for helping us out. 👊 Do you know if there is a way to get more details?

**Comment by cracyc** [comment]
For starters, since it crashes in 32bit code, a backtrace with symbols in windbg would help.

**Comment by luishdemetrio** [comment]
Hi, I am trying to build a version with symbols to collect a dump.

But I am having some issues here to build it. :)

In this first step, I think that it worked:

![image](https://user-images.githubusercontent.com/49683427/118563122-5e23dd80-b744-11eb-913a-43e7dc8b0e35.png)

As I am using the CMAKE from VS2019, I am assuming that MAKE will not work and that I have to build using MSBUILD. 

First I tried with the sln available in the build folder, that was generated in the previous step:

msbuild winevdm.sln

It is on this step that it is returning erros:

![image](https://user-images.githubusercontent.com/49683427/118563653-57499a80-b745-11eb-9a09-68d0d504829b.png)

I also tried to build the msbuild otvdm.sln solution, but this time I got the following error:

![image](https://user-images.githubusercontent.com/49683427/118563725-79dbb380-b745-11eb-8ce7-61741c91774d.png)

Any idea?

**Comment by luishdemetrio** [comment]
I am closing this bug, as the issue was fixed after I've compiled the emulator with the latest version to get the symbols.
Thank you very much!!!! 👊

![PedroApprovesPedrorcGIF](https://user-images.githubusercontent.com/49683427/119037597-8f8ceb00-b988-11eb-9139-180ee8c4ea41.gif)
