### ISSUE TITLE
Error messages in Interactive Physics 2.5 causes a hang

### ISSUE THREAD

**Issue by Nukley** [otya128/winevdm#981]
When an error message appears inside of Interactive Physics 2.5, and you click the button on the error message to close it, it causes it to hang and task manager says it's not responding.

The program should be able to close the error message without a hang

Windows 10 2004
2089

One way to create an error message inside of the program is to create a physics block, and then attempt to copy it using Ctrl + C

Again, I much rather not attach any trace files to protect my privacy. But here is a link to the program, in case you lost it: https://cdn.discordapp.com/attachments/313351634635849730/835676737488551936/IntPhys.zip

**Comment by cracyc** [comment]
This is a bad one.  It's calling throw to a catch buf on the other side of a windowproc callback.  x64 documentation says this will not work so I'm at a loss of what to do.  It may not be fixable.
