### ISSUE TITLE
Elifoot 98 appears a eli.cod error file

### ISSUE THREAD

**Issue by HyperScorpio** [otya128/winevdm#984]
When i try to run Elifoot 98 appears a eli.cod file error in the game and the editor.
Both are .exe files.
The eli.cod file appears in otvdm-master-1056\WINDOWS folder. 
I try to remove it, but the error still persists. 

![1](https://user-images.githubusercontent.com/30736913/118996627-f2c64f80-b97f-11eb-8d7b-206259a693f5.png)
![2](https://user-images.githubusercontent.com/30736913/118996640-f4901300-b97f-11eb-8489-6451679bb6fd.png)
![3](https://user-images.githubusercontent.com/30736913/119001306-c44a7380-b983-11eb-8ccf-fe487f33b115.png)

 - OS: Windows 10 PRO
 - Version 20H2

You can test the game by downloading throw here: http://marmota.org/elifoot98/
Go to Downloads - Click in your left Elifoot 98 and Registrador - is the crack.
Pacote de equipes - is a package to put in the game to play 500 new soccer teams in the world.
Trapaceador - Is the Cheat O Matic to bypass your team with full of money to buy new players.
Please make this game running ok on the lastest windows is the best portuguese manager game ever!
As i can see the creator of this emulator is japanese and yes you can make your own J. League tournament too. :)
Thank you!

**Comment by zepedropaulos** [comment]
Issue persists in v0.8.1 and v0.9.0.
Tried W11-XP.
