### ISSUE TITLE
Castle of the Winds - title screen artifact.

### ISSUE THREAD

**Issue by SabinStargem** [otya128/winevdm#988]
When starting up Castle of the Winds, be it Part I or Part II, there is a graphical artifact.  It is towards the bottom left.  This bug affects WineDVM 0.7, and also Build 2098.  This doesn't seem to cause genuine issues, but that is only a guess.

![COTW Artifact](https://user-images.githubusercontent.com/38871546/119415481-8a8cac00-bca6-11eb-849e-71e08c334c50.png)

The game is freeware, and is available through the Internet Archive.

[Castle of the Winds, I & II](https://archive.org/details/castleofthewindswinecotwine0.7)

**Comment by cracyc** [comment]
The load saved game button is moved to a place where it's position is signed overflow which causes it to get drawn incorrectly.  #992 fixes it by forcing a recalc of the window size.
