### ISSUE TITLE
Incomplete installation of Futurewave SmartSketch 95

### ISSUE THREAD

**Issue by jimhabegger** [otya128/winevdm#993]
Someone suggested that I tell you about my experience trying to use the files from some installation floppies for Futurewave SmartSketch, after installing the latest otvdm recommended build yesterday, 2 June 2021. I was able to install it and to open some files that I created with it in 1998, but there were error messages during the installation, and the links didn’t work on some of the help pages. I've attached the installation files, lists of the files on each disk, screenshots of the error messages, and screenshots of two of the help pages where the links didn’t work.

I was able to install it inside Win31DOSBOX, and everything worked perfectly.

* lists of installation files on disks
[disk1.txt](https://github.com/otya128/winevdm/files/6588058/disk1.txt)
[disk2.txt](https://github.com/otya128/winevdm/files/6588059/disk2.txt)
[disk3.txt](https://github.com/otya128/winevdm/files/6588060/disk3.txt)
[disk4.txt](https://github.com/otya128/winevdm/files/6588061/disk4.txt)
[disk5.txt](https://github.com/otya128/winevdm/files/6588062/disk5.txt)

* installation files
[SmartSketch.zip](https://github.com/otya128/winevdm/files/6588106/SmartSketch.zip)

* screenshots
![install error 1](https://user-images.githubusercontent.com/85262330/120568592-c530da00-c446-11eb-9137-f2e6d7a0afdc.png)
![install error 2](https://user-images.githubusercontent.com/85262330/120568594-c6620700-c446-11eb-9976-09f1b6137cc3.png)
![link fail 1](https://user-images.githubusercontent.com/85262330/120568595-c6fa9d80-c446-11eb-9f85-75d050a245d0.png)
![link fail 2](https://user-images.githubusercontent.com/85262330/120568596-c7933400-c446-11eb-93f7-68f6c792e98c.png)

**Comment by jimhabegger** [comment]
Success!

It installs without errors now, and the warning about running a program works.

![SS install success](https://user-images.githubusercontent.com/85262330/120648675-7d459d80-c4ae-11eb-9f2b-cc43df27dc45.png)
![SS Menu EasyArt Finder](https://user-images.githubusercontent.com/85262330/120648708-8898c900-c4ae-11eb-80b4-3df7894926a2.png)
![SS EasyArt Finder](https://user-images.githubusercontent.com/85262330/120648731-8f274080-c4ae-11eb-8834-a39bab8efc97.png)
![SS warning](https://user-images.githubusercontent.com/85262330/120648784-9a7a6c00-c4ae-11eb-8ab0-e0dbf790a611.png)

There are still some links that don't work in the help menus, and links that don't function like they do in Win32DOSBOX. I'll post about those in another comment.

**Comment by jimhabegger** [comment]
It installs without errors now, and some of the links work in the help menus, but not all of them. Also, in some ways it doesn't run like it does in a Windows 3.1 environment. For example, sometimes instead of creating a new window in the app, it starts a new instance of the app.
![SS Menu EasyArt Finder](https://user-images.githubusercontent.com/85262330/120662175-7f622900-c4bb-11eb-8fc1-1e233cf337c5.png)
![SS warning](https://user-images.githubusercontent.com/85262330/120662246-8ee17200-c4bb-11eb-9393-6e3891ae1459.png)
![SS new instance a](https://user-images.githubusercontent.com/85262330/120662297-96a11680-c4bb-11eb-8b50-12087995a4cd.png)
![SS Quick Start](https://user-images.githubusercontent.com/85262330/120662915-1d55f380-c4bc-11eb-887f-de328ca1ec85.png)
![SS new instance b](https://user-images.githubusercontent.com/85262330/120662372-aa4c7d00-c4bb-11eb-925f-3f0245575391.jpg)

**Comment by jimhabegger** [comment]
There are some other problems with the menus, which I'll post tomorrow.

**Comment by cracyc** [comment]
> It installs without errors now, and some of the links work in the help menus, but not all of them. Also, in some ways it doesn't run like it does in a Windows 3.1 environment. For example, sometimes instead of creating a new window in the app, it starts a new instance of the app.

If you place a copy of win31 winhelp.exe in you winvdm windows dir then it behaves like win31.  It probably won't be possible to make this work the same with winhlp32.  Winevdm's winhlp32 can't be a full replacement for win16 winhelp for example it can't load win16 dlls although it works for 99% of win16 help files.

**Comment by jimhabegger** [comment]
> > It installs without errors now, and some of the links work in the help menus, but not all of them. Also, in some ways it doesn't run like it does in a Windows 3.1 environment. For example, sometimes instead of creating a new window in the app, it starts a new instance of the app.
> 
> If you place a copy of win31 winhelp.exe in you winevdm windows dir then it behaves like win31. It probably won't be possible to make this work the same with winhlp32. Winevdm's winhlp32 can't be a full replacement for win16 winhelp for example it can't load win16 dlls although it works for 99% of win16 help files.

Thank you.

I'm wondering now if I should post any more about the differences between how SmartSketch works in a Windows 3.1 box, and how it works with otvdm. I don't know if that would be of any use for developers or not.

**Comment by cracyc** [comment]
>I'm wondering now if I should post any more about the differences between how SmartSketch works in a Windows 3.1 box

This is useful info and worth posting even if it can't be fixed.  It's also useful to post differences with ntvdm if you can which since it runs on nt is going to be most like how winevdm should behave.

**Comment by jimhabegger** [comment]
Now I only see three trivial differences between the behavior of SmartSketch in Win31DOSBOX and its behavior with otvdm, and for one of them, the behavior with otvdm is actually better.
- In the box,, the help window is inside the app window. With otvdm, the help window is a separate window and can be seen and used outside of the app window.
- With otvdm, to be able to use the SmartSketch help files without opening the app, I had to manually associate them with winhelp.exe in the otvdm Windows folder. Otherwise, it took me to a Web page with an error message.
- With otvdm, if I exit the app using the menu, this window stays open:
![Screenshot (200)](https://user-images.githubusercontent.com/85262330/120738468-78223600-c522-11eb-84bd-d04904afb376.png)

If I exit the app by clicking on the X at the top right, that window closes also.

**Comment by jimhabegger** [comment]
Trying to use ntvdm on my 64-bit computer looks too risky to me. I'm wondering if I could use my Windows 10 license to install Windows 10 in a box, and install ntvdm on top of that.

**Comment by jimhabegger** [comment]
Too many hoops to jump through, for me, to try to use ntvdm on my computer.

**Comment by jimhabegger** [comment]
False alarm. I enabled virtualization technology in the bios, and easily installed VMWare Workstation Player with a Windows 10 x64 iso from the Microsoft website. Now I'm trying to install and run SmartSketch in that environment, and reporting the issues that come up on the ntvdm github page.

**Comment by otya128** [comment]
"ntvdm" is ntvdm on 32-bit version of Windows.
It is not necessary if you cannot build a 32-bit Windows environment.

**Comment by otya128** [comment]
Even if you use winhlp32.exe, setting SeparateWOWVDM=0 in otvdm.ini should prevent opening a new instance.

**Comment by jimhabegger** [comment]
> "ntvdm" is ntvdm on 32-bit version of Windows.
> It is not necessary if you cannot build a 32-bit Windows environment.

Oh. Sorry! I'm downloading a Windows 10 x86 iso now, from the Microsoft website.

**Comment by jimhabegger** [comment]
> It's also useful to post differences with ntvdm if you can which since it runs on nt is going to be most like how winevdm should behave.

> "ntvdm" is ntvdm on 32-bit version of Windows.

I got that confused with NTVDMx64 by Leecher1337. I'll start over now with ntvdm in 32-bit Windows 10 on VMWare, and the ntvdm github page.

**Comment by jimhabegger** [comment]
I installed 32-bit Windows 10 on VMWare, and copied the SmartSketch installation files into it. I double-clicked on _setup.exe, and a message came up saying that ntvdm needed to be installed. I agreed, and after that it installed and ran perfectly. so no issues to report on ntvdm.
