### ISSUE TITLE
Superbase classic error UDP not available unable to load winsock

### ISSUE THREAD

**Issue by darrylsmith526** [otya128/winevdm#995]
Trying to use winevdm to open a legacy 16bit application on windws 10 x64, but running into an error connecting to the server. 

When trying to connect, the following error appear. PPCS error, UDP not available - unable to load winsock. 

This normally connects ok when using on Windows 10 x86

Environment
 - OS: Windows 10 20H2 19042.685
 - Version: 2108

[trace.zip](https://github.com/otya128/winevdm/files/6647855/trace.zip)

**Comment by cracyc** [comment]
Try https://ci.appveyor.com/project/otya128/winevdm/builds/39592825/job/6hffvpf7sr68dnfp/artifacts

**Comment by darrylsmith526** [comment]
thanks for coming back, i get the same error, i've attached the trace, in case it helps.

[trace4.zip](https://github.com/otya128/winevdm/files/6649531/trace4.zip)

**Comment by cracyc** [comment]
I overlooked something, try https://ci.appveyor.com/project/otya128/winevdm/builds/39595856/job/lr82frrtrf9tny4t/artifacts

**Comment by darrylsmith526** [comment]
that's worked, thank you!
