### ISSUE TITLE
Application Crash with Superbase 

### ISSUE THREAD

**Issue by darrylsmith526** [otya128/winevdm#997]
**Describe the bug**
Application crashes when trying to open the code editor function

**Expected behavior**
The editor function opens as it does on a x86 machine

Screen shot attached

**Environment (please complete the following information):**
 - OS: Windows 10 20H2 OS Build 19042.685
 - Version 2111
[trace.txt](https://github.com/otya128/winevdm/files/6676242/trace.txt)
![Capture](https://user-images.githubusercontent.com/85876014/122543592-d7ed0680-d023-11eb-91a1-fc068e043680.PNG)

**Comment by cracyc** [comment]
The problem isn't obvious from the trace and superbase 95 works fine.  There used to be a demo version of superbase classic at their web site but it's been removed.  If you know where to get it, that would help.

**Comment by darrylsmith526** [comment]
thats fixed it. thank you

on a side note, its pretty slow, is there a version haxm to try? i looked at  the latest, but not sure its got the required dll.

**Comment by cracyc** [comment]
You can get haxm from https://github.com/intel/haxm or if you want to use whpx look at https://github.com/otya128/winevdm/issues/699#issuecomment-646020250
